### ISSUE TITLE
[feature request] - sitemap generator based on spider results

### ISSUE THREAD

**Issue by dogasantos** [Arachni/arachni#1023]
Hello,

I'd like to bring the need for generating complete sitemaps and exporting that to text and/or json files. 

Sometimes we need to inspect for known patterns that a vulnscan won't be able to catch .

Example:
Let's sat that the arachni crawler manages to find the following  script:

site.com/assets/js/jQuery-File-Upload/js/jquery.fileupload.js

It might not trigger any vulnerability on it, but if we can see that path (more than that, that third-party package), we can manually inspect for known or unknown vulnerabilities in there. This is obviously just a easy example, and we can also reach unknown vulnerabilities with this. I believe that this is a very good feature that don't require any additional computational work.

Thanks

**Comment by Zapotek** [comment]
The report already contains a sitemap and you can get it in multiple formats.
