### ISSUE TITLE
how fix

### ISSUE THREAD

**Issue by Kalimon12** [Arachni/arachni#1059]
```
root@kali-desktop:/home/kali/Desktop/arachni-1.6.0-0.6.0/bin# ./arachni http://testphp.vulnweb.com/
Arachni - Web Application Security Scanner Framework v1.6.0
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, nested_cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 4 browsers...
 [-] [browser#selenium:1122] Worker: Please ensure that chromedriver and Chrome are the same version and in your PATH.
 [-] [utilities#exception_jail:428] [Selenium::WebDriver::Error::UnknownError] unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
 [-] [utilities#exception_jail:428] #0 0x5650953167d3 <unknown>
 [-] [utilities#exception_jail:428] #1 0x565095072688 <unknown>
 [-] [utilities#exception_jail:428] #2 0x565095095b27 <unknown>
 [-] [utilities#exception_jail:428] #3 0x56509509168f <unknown>
```

**Comment by Zapotek** [comment]
Can you please try running it with a non-root user?

**Comment by Kalimon12** [comment]
kali@kali-desktop:~/Desktop/arachni-1.6.0-0.6.0/bin$ ./arachni http://testphp.vulnweb.com/
Arachni - Web Application Security Scanner Framework v1.6.0
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                
           (With the support of the community and the Arachni Team.)                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                
   Website:       http://arachni-scanner.com                                                                                                                                                                                                                                    
   Documentation: http://arachni-scanner.com/wiki                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
 [~] No checks were specified, loading all.                                                                                                                                                                                                                                     
 [~] No element audit options were specified, will audit links, forms, cookies, nested_cookies, UI inputs, UI forms, JSONs and XMLs.                                                                                                                                            
                                                                                                                                                                                                                                                                                
 [*] Initializing...                                                                                                                                                                                                                                                            
 [*] Preparing plugins...                                                                                                                                                                                                                                                       
 [*] ... done.                                                                                                                                                                                                                                                                  
 [*] BrowserCluster: Initializing 4 browsers...                                                                                                                                                                                                                                 
 [-] [utilities#exception_jail:428] [Timeout::Error] Request timed out: post http://127.0.0.1:9515/session                                                                                                                                                                      
{"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--allow-running-insecure-content","--disable-web-security","--reduce-security-for-testing","--ignore-certificate-errors","--disable-plugins","--user-data-dir=/tmp/Arachni_Chrome_54860/","--proxy-server=127.0.0.1:4901","--buid=46464646","--headless"],"mobileEmulation":{"userAgent":"Mozilla/5.0 (Gecko) Arachni/v1.6.0"}}}}}                                                                                                                                        
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/selenium/webdriver/remote/typhoeus.rb:48:in `request'                                                                                                    
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'                                                                                                 
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'                                                                                                  
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'                                                                                            
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:340:in `create_bridge'                                                                                            
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'                                                                                                
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `new'                                                                                                       
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `for'                                                                                                       
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'                                                                                                                     
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1100:in `selenium'                                                                                                                            
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1273:in `start_webdriver'                                                                                                                     
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:192:in `initialize'                                                                                                                           
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster/worker.rb:51:in `initialize'                                                                                                             
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:495:in `new'                                                                                                                          
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'                                                                                                  
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:494:in `times'                                                                                                                        
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:494:in `initialize_workers'                                                                                                           
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:112:in `initialize'                                                                                                                   
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:33:in `new'                                                                                                                   
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'                                                                                              
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'                                                                                                                                           
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'                                                                                                                                       
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'                                                                                                       
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/audit.rb:173:in `audit'                                                                                                                  
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `block in run'                                                                                                                       
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:425:in `exception_jail'                                                                                                                     
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `run'                                                                                                                                
 [-] [utilities#exception_jail:428] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'                                                                                                                             
 [-] [utilities#exception_jail:429]                                                                                                                                                                                                                                             
 [-] [utilities#exception_jail:430] Parent:                                                                                                                                                                                                                                     
 [-] [utilities#exception_jail:431] Arachni::Framework                                                                                                                                                                                                                          
 [-] [utilities#exception_jail:432]                                                                                                                                                                                                                                             
 [-] [utilities#exception_jail:433] Block:                                                                                                                                                                                                                                      
 [-] [utilities#exception_jail:434] #<Proc:0x000055e7cde7a080 /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117>                                                                                                              
 [-] [utilities#exception_jail:435]                                                                                                                                                                                                                                             
 [-] [utilities#exception_jail:436] Caller:                                                                                                                                                                                                                                     
 [-] [utilities#exception_jail:437] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:424:in `exception_jail'                                                                                                                     
 [-] [utilities#exception_jail:437] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `run'                                                                                                                                
 [-] [utilities#exception_jail:437] /home/kali/Desktop/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/ui/cli/framework.rb:80:in `block in run'                                                                                                                             
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------

**Comment by Zapotek** [comment]
I'll download Kali and see if I can reproduce.

**Comment by Kalimon12** [comment]
ok

**Comment by Zapotek** [comment]
Hello again,

The only problem I encountered with the latest Kali linux was a missing dependency.
The package depended on libffi7 which was removed from the repos in favor of libffi8.
I managed to solve it with:

```
wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
sudo dpkg -i libffi7_3.3-4_amd64.deb
```

Other than that Arachni is working fine, I couldn't reproduce your issue.

**Comment by Zapotek** [comment]
Regarding the libffi issue I encountered I released new packages to fix it.
As to your problem I still haven't been able to reproduce it, it works every time for me.

Can you try re-downloading and doing everything as a non-root user please?

**Comment by Kalimon12** [comment]
Thank you

**Comment by Zapotek** [comment]
Did that work?

**Comment by karfianto** [comment]
> Can you please try running it with a non-root user?

The error message is changed after switching to non-root user.

```
[2022-03-13 10:58:05 +0700] [Timeout::Error] Request timed out: post http://127.0.0.1:9515/session
{"capabilities":{"alwaysMatch":{"browserName":"chrome","goog:chromeOptions":{"args":["--allow-running-insecure-content","--disable-web-security","--reduce-security-for-testing","--ignore-certificate-errors","--disable-plugins","--user-data-dir=/tmp/Arachni_Chrome_52880/","--proxy-server=127.0.0.1:34133","--buid=46464646","--headless"],"mobileEmulation":{"userAgent":"Mozilla/5.0 (Gecko) Arachni/v1.6.0"}}}}}
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/selenium/webdriver/remote/typhoeus.rb:48:in `request'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:52:in `create_session'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:340:in `create_bridge'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:74:in `initialize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `new'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:47:in `for'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver.rb:88:in `for'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1100:in `selenium'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:1273:in `start_webdriver'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser.rb:192:in `initialize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster/worker.rb:51:in `initialize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:495:in `new'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:495:in `block in initialize_workers'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:494:in `times'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:494:in `initialize_workers'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/browser_cluster.rb:112:in `initialize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:33:in `new'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework/parts/audit.rb:173:in `audit'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `block in run'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:425:in `exception_jail'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `run'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/rpc/server/framework.rb:156:in `block in run'
[2022-03-13 10:58:05 +0700] 
[2022-03-13 10:58:05 +0700] Parent:
[2022-03-13 10:58:05 +0700] Arachni::RPC::Server::Framework
[2022-03-13 10:58:05 +0700] 
[2022-03-13 10:58:05 +0700] Block:
[2022-03-13 10:58:05 +0700] #<Proc:0x0000558241fa6fe0 /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117>
[2022-03-13 10:58:05 +0700] 
[2022-03-13 10:58:05 +0700] Caller:
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/utilities.rb:424:in `exception_jail'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/framework.rb:117:in `run'
[2022-03-13 10:58:05 +0700] /opt/arch/arachni-1.6.0-0.6.0/.system/gems/gems/arachni-1.6.0/lib/arachni/rpc/server/framework.rb:156:in `block in run'
```

**Comment by Zapotek** [comment]
I don't understand this, seems like there's an issue connecting to Chrome.
Do you use a clean Ubuntu system? Is it an underpowered VM?

**Comment by Kalimon12** [comment]
i fixed

**Comment by Kalimon12** [comment]
remove google chrome in "arachni-1.6.0-0.6.0/.system/opt/google/" and copy your chrome in /opt to  "arachni-1.6.0-0.6.0/.system/opt/" and --no-sandbox to google-chrome like "  exec -a "$0" "$HERE/chrome" "$@" --no-sandbox"
download  latest chromedriver mv to /usr/bin

**Comment by reddude21** [comment]
I am getting the same error for windows..what can i do?
