### ISSUE TITLE
[operation_timedout] Timeout was reached

### ISSUE THREAD

**Issue by era5mx** [Arachni/arachni#1061]
It is the first time that I use the tool but I got the following error message...

'This scan has the logged the following [errors](http://127.0.0.1:9292/scans/1/errors.txt) (if something looks like a bug feel free to [report](https://github.com/Arachni/arachni/issues) it):'

[operation_timedout] Timeout was reached

**Comment by Zapotek** [comment]
Hello, 

I shouldn't have logged these as errors, an HTTP request timed out, it's not an issue, my bad,
Thanks for the feedback though.
