### ISSUE TITLE
Nightly (10/03/22) : scheduled scan failed when started, normal scan running fine

### ISSUE THREAD

**Issue by Chridolc** [Arachni/arachni#1062]
Hello.
Just tried the Schedule : it seems  not working properly and stop immediatly when started.
On the web interface, the task have a "Finished" status with error

Type : N/A
Issue Count : 0
Started at : N/A
Finished at : N/A

next scan is still in queue.

Logs of this scheduled scan attached. 

thanks for your help
[arachni_web_schedule.txt](https://github.com/Arachni/arachni/files/8245026/arachni_web_schedule.txt)

**Comment by Zapotek** [comment]
Seems like a connectivity issue with the target, as the log says HTTP requests to reach it completely failed.

**Comment by Zapotek** [comment]
There's nothing special with scheduled scans.
There's a chance you got blocked.

**Comment by Chridolc** [comment]
yep. You're right.
Tested with a "monitored" website : scheduled scan running fine. I've found
that there was a wordpress "firewall (pfew..)" plugin on the previous one...
have a little problem : When i try to modify a schedule (start time) i've
had a "something get wrong" issue when updating... But i need to make more
tests to confirm.

Thanks again for your reply.

Cheers.

Le lun. 14 mars 2022 à 14:21, Tasos Laskos ***@***.***> a
écrit :

**Comment by Zapotek** [comment]
You can find the actual error in the logfile under `logs/webui/`.

**Comment by Chridolc** [comment]
i think it's here :

 Schedule Update (0.2ms)  UPDATE "schedules" SET "start_at" = ?,
"updated_at" = ? WHERE "schedules"."id" = ?  [["start_at", "2022-03-15
13:55:05"], ["updated_at", "2022-03-14 14:09:33.831500"], ["id", 14]]
   (7.8ms)  commit transaction
  Profile Load (0.5ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  Dispatcher Load (0.2ms)  SELECT "dispatchers".* FROM "dispatchers" WHERE
1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT", 11]]
Redirected to
  CACHE Profile Load (0.0ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  CACHE Dispatcher Load (0.0ms)  SELECT "dispatchers".* FROM "dispatchers"
WHERE 1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT",
11]]
Completed 500 Internal Server Error in 83ms (ActiveRecord: 10.0ms |
Allocations: 75540)
  CACHE Profile Load (0.0ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  CACHE Dispatcher Load (0.0ms)  SELECT "dispatchers".* FROM "dispatchers"
WHERE 1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT",
11]]

NoMethodError (undefined method `back_url' for
#<ScansController:0x000055fe0abe51a0>):

app/controllers/scans_controller.rb:238:in `block (2 levels) in update'
app/controllers/scans_controller.rb:234:in `update'
Started GET "/navigation" for XXX.XXX.XXX.XXX at 2022-03-14 15:09:33 +0100
Processing by HomeController#navigation as HTML


Just changed the start time of a scheduled scan.




Le lun. 14 mars 2022 à 14:57, Tasos Laskos ***@***.***> a
écrit :

**Comment by Zapotek** [comment]
Should be fixed now in the nightlies.

Thanks for the feedback.

**Comment by Chridolc** [comment]
tested again with an internal / sensible website - sure it's 100%
available.

=> created a new schedule
=> going back to this schedule
=> changing the start time
=> error

  (0.1ms)  begin transaction
  Schedule Update (0.2ms)  UPDATE "schedules" SET "start_at" = ?,
"updated_at" = ? WHERE "schedules"."id" = ?  [["start_at", "2022-03-14
16:30:00"], ["updated_at", "2022-03-14 15:00:50.020718"], ["id", 18]]
   (8.6ms)  commit transaction
  Profile Load (0.5ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  Dispatcher Load (0.2ms)  SELECT "dispatchers".* FROM "dispatchers" WHERE
1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT", 11]]
Redirected to
  CACHE Profile Load (0.0ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  CACHE Dispatcher Load (0.0ms)  SELECT "dispatchers".* FROM "dispatchers"
WHERE 1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT",
11]]
Completed 500 Internal Server Error in 86ms (ActiveRecord: 19.1ms |
Allocations: 76501)
  CACHE Profile Load (0.0ms)  SELECT "profiles".* FROM "profiles" WHERE
"profiles"."id" IN (?, ?, ?, ?, ?, ?, ?, ?, ?) LIMIT ?  [["id", 1], ["id",
2], ["id", 3], ["id", 4], ["id", 5], ["id", 1], ["id", 2], ["id", 3],
["id", 4], ["LIMIT", 11]]
  CACHE Dispatcher Load (0.0ms)  SELECT "dispatchers".* FROM "dispatchers"
WHERE 1=0 AND "dispatchers"."alive" = ? LIMIT ?  [["alive", 1], ["LIMIT",
11]]

NoMethodError (undefined method `back_url' for
#<ScansController:0x00007fb890243600>):

app/controllers/scans_controller.rb:238:in `block (2 levels) in update'
app/controllers/scans_controller.rb:234:in `update'
ScanManager#keep_schedule
  Schedule Load (0.3ms)  SELECT "schedules".* FROM "schedules" INNER JOIN
"scans" ON "scans"."schedule_id" = "schedules"."id" WHERE "scans"."status"
= ? AND (start_at <= '2022-03-14 15:00:52.309662')  [["status",
"scheduled"]]
ScanManager#refresh


Le lun. 14 mars 2022 à 14:12, Tasos Laskos ***@***.***> a
écrit :

**Comment by Chridolc** [comment]
i'll create another instance to check if i can reproduce it.

**Comment by Chridolc** [comment]
Hello.

I've installed a fresh nightly (14/03), empty database.
- created a new schedule with 'default" profile, then saved it.
- editing it again, changed the starting time
- still display "We're sorry, but something went wrong." when saving
- if i go back to the schedule, starting time is modified anyway. (good) :-)

**Comment by Zapotek** [comment]
Can I see the error this time please?

**Comment by Chridolc** [comment]
of course !
[arachni_web_schedule.txt](https://github.com/Arachni/arachni/files/8252332/arachni_web_schedule.txt)

**Comment by Zapotek** [comment]
My bad, from what I realised I had made the changes to the master branch (stable/release) by accident, not experimental (nightlies), that's why.

**Comment by Chridolc** [comment]
no problem :-).

maybe the same issue when i click on "mark as read" on the main page affter auth ?

**Comment by Zapotek** [comment]
Yep, it was a redirection issue, should be gone now in the nightlies.

**Comment by Chridolc** [comment]
I confirm.
schedule modification & "mark as read" button running fine.

Thanks.
