### ISSUE TITLE
Keeping Chromedriver up to date

### ISSUE THREAD

**Issue by ltickett** [Arachni/arachni#1068]
I am running the latest release on windows and scans were stopped working.

When I checked the logs I saw something about Chromedriver and Chrome version mismatch.

I remember I recently updated Chrome.

Simply downloading the correct version of chromedriver.exe and popping it in the chromedriver folder fixed the problem, but I wonder if we can/should:

- improve the documentation
- improve the error
- automatically handle it and download the correct version

Or do you think most users are savvy enough to figure it out for themselves?

**Comment by Zapotek** [comment]
The `TROUBLESHOOTING` file has such info.

**Comment by ltickett** [comment]
Where can I find that file? I can't find it in the repo or linked on the wiki?

**Comment by Zapotek** [comment]
In the package directory, it should be there.

**Comment by ltickett** [comment]
Ah got it in the installation directory. Is it in the repository somewhere too?

Thanks

**Comment by Zapotek** [comment]
Yes, it's a [template](https://github.com/Arachni/build-scripts-windows/blob/master/templates/TROUBLESHOOTING.txt) in the build scripts.

**Comment by ltickett** [comment]
Ah, that'll be why I couldn't find it, because it's in a different repo. Thanks a mill 💙
