### ISSUE TITLE
Segmentation fault - Ubuntu 20.04 (Minimal Version CLI) 

### ISSUE THREAD

**Issue by afonsofsgomes** [Arachni/arachni#1071]
Hi, 
After many trys of installing Arachni, I keep always getting the same segmentation fault error. 
It may be related with `/ffi lib` since the code error I obtain starts with: 
`/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401: [BUG] Illegal instruction at 0x00007f942cbae3c0`
I 'm running the _GLIBC_ lib in version 2.31 : `ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31`. 

I even installed Google Chrome, but it was worthless. 

Dump: 
`/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401: [BUG] Illegal instruction at 0x00007f942cbae3c0
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0053 p:---- s:0288 e:000287 CFUNC  :initialize
c:0052 p:---- s:0285 e:000284 CFUNC  :new
c:0051 p:0219 s:0278 e:000277 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401
c:0050 p:0167 s:0266 e:000265 CLASS  /root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:31
c:0049 p:0007 s:0262 e:000261 CLASS  /root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:6
c:0048 p:0013 s:0259 e:000258 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:5 [FINISH]
c:0047 p:---- s:0256 e:000255 CFUNC  :require_relative
c:0046 p:0019 s:0251 e:000250 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc.rb:31 [FINISH]
c:0045 p:---- s:0248 e:000247 CFUNC  :require
c:0044 p:0007 s:0243 e:000242 BLOCK  /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0043 p:0068 s:0240 e:000239 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291
c:0042 p:0010 s:0233 e:000232 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0041 p:0011 s:0227 e:000226 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5 [FINISH]
c:0040 p:---- s:0224 e:000223 CFUNC  :require
c:0039 p:0007 s:0219 e:000218 BLOCK  /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0038 p:0068 s:0216 e:000215 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291
c:0037 p:0010 s:0209 e:000208 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0036 p:0005 s:0203 e:000202 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/sass-rails-6.0.0/lib/sass-rails.rb:1 [FINISH]
c:0035 p:---- s:0200 e:000199 CFUNC  :require
c:0034 p:0007 s:0195 e:000194 BLOCK  /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0033 p:0068 s:0192 e:000191 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291
c:0032 p:0010 s:0185 e:000184 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325
c:0031 p:0047 s:0179 e:000178 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/bootstrap-sass-2.3.1.0/lib/bootstrap-sass.rb:14
c:0030 p:0019 s:0174 e:000173 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/bootstrap-sass-2.3.1.0/lib/bootstrap-sass.rb:45 [FINISH]
c:0029 p:---- s:0171 e:000170 CFUNC  :require
c:0028 p:0032 s:0166 e:000165 BLOCK  /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:60 [FINISH]
c:0027 p:---- s:0161 e:000160 CFUNC  :each
c:0026 p:0042 s:0157 e:000156 BLOCK  /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:55 [FINISH]
c:0025 p:---- s:0150 e:000149 CFUNC  :each
c:0024 p:0026 s:0146 e:000145 METHOD /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:44
c:0023 p:0013 s:0141 e:000140 METHOD /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler.rb:176
c:0022 p:0062 s:0136 e:000135 TOP    /root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/application.rb:15 [FINISH]
c:0021 p:---- s:0133 e:000132 CFUNC  :require
c:0020 p:0195 s:0128 e:000127 METHOD /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85
c:0019 p:0068 s:0111 e:000110 TOP    /root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/environment.rb:13 [FINISH]
c:0018 p:---- s:0108 e:000107 CFUNC  :require
c:0017 p:0195 s:0103 e:000102 METHOD /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85
c:0016 p:0021 s:0086 e:000085 EVAL   /root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config.ru:3 [FINISH]
c:0015 p:---- s:0083 e:000082 CFUNC  :eval
c:0014 p:0033 s:0076 e:000075 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:116
c:0013 p:0135 s:0068 e:000067 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:105
c:0012 p:0032 s:0059 e:000058 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:66
c:0011 p:0078 s:0052 e:000051 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:349
c:0010 p:0031 s:0046 e:000045 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:249
c:0009 p:0018 s:0042 e:000040 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:422
c:0008 p:0004 s:0037 e:000036 BLOCK  /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:312
c:0007 p:0092 s:0034 e:000033 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:379
c:0006 p:0131 s:0027 e:000026 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:311
c:0005 p:0010 s:0021 e:000020 METHOD /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:168
c:0004 p:0021 s:0016 e:000015 TOP    /root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/bin/rackup:5 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0124 s:0008 E:0018d0 EVAL   /root/arachni-1.6.1-0.6.1/bin/../.system/gems/bin/rackup:25 [FINISH]
c:0001 p:0000 s:0003 E:0012d0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/root/arachni-1.6.1-0.6.1/bin/../.system/gems/bin/rackup:25:in `<main>'
/root/arachni-1.6.1-0.6.1/bin/../.system/gems/bin/rackup:25:in `load'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
/root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config.ru:3:in `block in <main>'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/environment.rb:13:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/root/arachni-1.6.1-0.6.1/.system/arachni-ui-web/config/application.rb:15:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler.rb:176:in `require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:44:in `require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:44:in `each'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:55:in `block in require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:55:in `each'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:60:in `block (2 levels) in require'
/root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:60:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/bootstrap-sass-2.3.1.0/lib/bootstrap-sass.rb:45:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/bootstrap-sass-2.3.1.0/lib/bootstrap-sass.rb:14:in `load!'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sass-rails-6.0.0/lib/sass-rails.rb:1:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:291:in `load_dependency'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:5:in `<top (required)>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:6:in `<module:SassC>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/sassc-2.4.0/lib/sassc/native.rb:31:in `<module:Native>'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401:in `callback'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401:in `new'
/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401:in `initialize'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f942cbae3c0 RBP: 0x0000559efbf11540 RSP: 0x00007ffd7f94e248
 RAX: 0x0000000000000000 RBX: 0x0000559efc5d9280 RCX: 0x00007f942cbb8060
 RDX: 0x0000000000000002 RDI: 0x0000559efc5d92c8 RSI: 0x0000000000000002
  R8: 0x0000559efc0d3360  R9: 0x0000559efa563d80 R10: 0xfffffffffffff805
 R11: 0x00007f942cbae3b0 R12: 0x0000000000000002 R13: 0x0000559efc5ae9e8
 R14: 0x0000559efc5ae948 R15: 0x0000559efc798b38 EFL: 0x0000000000010293`

### This output comes out after running: ./bin/arachni_web or ./bin/arachni
****Complete dump on attached txt.**
[arachni_output.txt](https://github.com/Arachni/arachni/files/8597571/arachni_output.txt)

**Comment by afonsofsgomes** [comment]
### Running with debug option: 
`nil
Exception `NameError' at /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/site_ruby/2.7.0/bundler/rubygems_integration.rb:415 - method `gem' not defined in #<Class:Kernel>
Exception `NameError' at /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/2.7.0/psych/class_loader.rb:68 - uninitialized constant BigDecimal
Exception `NameError' at /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/2.7.0/psych/class_loader.rb:68 - uninitialized constant Date
Did you mean?  Data
Exception `NameError' at /root/arachni-1.6.1-0.6.1/.system/usr/lib/ruby/2.7.0/psych/class_loader.rb:68 - uninitialized constant DateTime
Did you mean?  DateAndTime
Using Ext extension for JSON.
Exception `LoadError' at /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325 - cannot load such file -- sqlite3/2.7/sqlite3_native
Exception `LoadError' at /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:295 - cannot load such file -- sqlite3/2.7/sqlite3_native
Exception `LoadError' at /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325 - cannot load such file -- 2.7/ffi_c
Exception `LoadError' at /root/arachni-1.6.1-0.6.1/.system/gems/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:295 - cannot load such file -- 2.7/ffi_c
/root/arachni-1.6.1-0.6.1/.system/gems/gems/ffi-1.15.5/lib/ffi/library.rb:401: [BUG] Illegal instruction at 0x00007f9e2b4193c0
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]`

**Comment by Zapotek** [comment]
I'm looking into this although I haven't been able to reproduce.
You shouldn't run Arachni as root though, it can cause [problems with Chrome](https://github.com/Arachni/arachni/issues/1063#issuecomment-1071146992).


I had updated the packages to check for this but GitHub must have not updated the release due to the packages having the same name as before.

**Comment by afonsofsgomes** [comment]
Hi! 
I was able to work around this issue by using Debian 11 with experimental Software Packages. 
I think it might be useful to mention experimental repos, if you use it, the GLIBC will upgrade to the latest version.
