### ISSUE TITLE
Recursive Dive into Pages

### ISSUE THREAD

**Issue by DevNerd** [Arachni/arachni#188]
Arachni is diving recursively into pages if a menu-url contains a redirect like /login.php?goto?=domain.tld/index.php
Its diving into the same link for over 300 times, creating a very very very long pile of nothing.

Is this a bug?

--G33K

**Comment by bardelch** [comment]
Why isn't this a separate issue on the list to be fixed rather putting the scanner on a loop?  It seems that with some light URL processing for de-duplication of the variables the URLs can be made to not go on this infinite loop.
