### ISSUE TITLE
Support for Web Services vulnerability scanning

### ISSUE THREAD

**Issue by ulissescastro** [Arachni/arachni#339]
Create WSDL/SOAP crawler to make possible throw security tests at entry points that common vulnerability assessment tools can't reach.

A good post about it and how it works:
http://www.acunetix.com/websitesecurity/web-services-wp/

**Comment by jahrek** [comment]
hello ;-)

What is the status of this task right now? :)

**Comment by Zapotek** [comment]
@jahrek My previous comment says it all, any updates will be posted here as they occur.

**Comment by Joeyn414** [comment]
This seems to be an old thread, but I have an interest in using this to scan my SOAP REST services. I wanted to first confirm that arachni cannot do this yet. And two, as mentioned by @eirikhm I would be interested in helping you write this if you told me where to insert it into the application.

**Comment by Zapotek** [comment]
Seeing as there's no standard way to crawl web services, your best bet is this: http://support.arachni-scanner.com/kb/general-use/service-scanning
