### ISSUE TITLE
Change --user-agent during the scan 

### ISSUE THREAD

**Issue by user021** [Arachni/arachni#345]
Change --user-agent during the scan manually or automatically every x seconds (this could come handy in order to avoid some defenses)

**Comment by Zapotek** [comment]
@user021 Don't really like the original idea of changing user-agents like that, makes the scan and the results unpredictable. It would be better to run scans with different UAs and compare the results at the end.

@treadie The current WebUI is dead in the water so I don't see this happening (the fact that this issues has been open for almost 2 years speaks to that too).

Sorry guys but I gotta close this.
