### ISSUE TITLE
Plug-n-Hack support

### ISSUE THREAD

**Issue by treadie** [Arachni/arachni#386]
Not sure if this is something you would want from Arachni as its more of a automated scanner rather than intercepting proxy, but it provides some pretty cool ideas.

See the following links:
http://blog.mozilla.org/security/2013/08/22/plug-n-hack/
https://github.com/mozmark/ringleader
https://github.com/mozmark/ringleader/blob/master/doc/main.md

Just a thought.

**Comment by Zapotek** [comment]
Hm, looks like development on this has stalled, no ringleader updates about supposedly upcoming functionality in a year, no updates to the MDN wiki pages about the spec in 2 years.

There doesn't seem to be much activity on this, closing the issue.
