### ISSUE TITLE
Autologin log the contents of the response to form submission

### ISSUE THREAD

**Issue by asieira** [Arachni/arachni#423]
I am getting this error here and am completely in the dark about what is going on:

```
[2014-01-31 09:49:57 -0800] AutoLogin: Form submitted but the response did not match the verifier.
```

However, the logs don't contain what the content was that AutoLogin received. I would suggest an option for the full HTTP response (status code, headers, body) to be logged so that situations like that can be better investigated.

**Comment by tfcporciuncula** [comment]
Is this fixed for the WebUI too? I'm using it but all I get is the error message (`Form submitted but the response did not match the verifier.`) Which is odd since I even tried `.*` as the check expression.

I wish I could see the response so I could understand what's hapenning, though.

**Comment by Zapotek** [comment]
No you won't be able to access debugging information via the WebUI, you'll need to use the CLI for that.
Btw, have you also configured the session options at the bottom? If there's a verifier there it'll override the one provided to the autologin plugin.

**Comment by tfcporciuncula** [comment]
That was fast hahah.

Yes, for the `.*` test I did, the issue was that I had another verifier over the session options. Thank you for that!

The WebUI is so cool that I've been avoiding the CLI so far. Seems I have no choice now :(

**Comment by Zapotek** [comment]
No problem, glad you got it working.

Cheers
