### ISSUE TITLE
Improve SSL, add SSL arguments

### ISSUE THREAD

**Issue by CoolerVoid** [Arachni/arachni#450]
A suggestion...
 
So you use Typhoeus -> he uses LibCurl...
https://github.com/Arachni/arachni/blob/master/lib/arachni/http.rb#L143
why not use sslversion opts etc... ?
https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb#L118

I think some arguments like "arachni --cacert-load key.pem  --ssl-version sslv3"

sslversion opts look here:
http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

cheers

**Comment by Zapotek** [comment]
All done. :)
