### ISSUE TITLE
Improvements to uncommon_headers plugin

### ISSUE THREAD

**Issue by treadie** [Arachni/arachni#451]
Would be nice if the user could configure which headers they want to ignore/catch.

**Comment by Zapotek** [comment]
Is this for a generic header collector thing or just to filter the default list of common headers used by the `uncommon_headers` plugin?

**Comment by treadie** [comment]
Essentially it would be great if the user could define what headers are ignored by the plugin rather than them being hard coded. I guess its more so the pentester can filter and choose what headers are collected that he/she may find interesting and relevant to that specific test.

**Comment by Zapotek** [comment]
This needs to be a different plugin then as we're no longer talking about uncommon headers but generic, user-scoped header collection.
