### ISSUE TITLE
not scan , start scan errors

### ISSUE THREAD

**Issue by securityigi** [Arachni/arachni#503]
2014-10-24 10:51:29 -0400 --------------------------------------------------------------------------------
## ENV:

XDG_SESSION_ID: '1'
GEM_HOME: "/root/jazireh/system/gems"
SHELL: "/bin/bash"
TERM: xterm
IRBRC: "/root/jazireh/bin/../system/usr/lib/ruby/.irbrc"
SSH_CLIENT: 192.95.47.198 43499 22
MY_RUBY_HOME: "/root/jazireh/bin/../system/usr/lib/ruby"
SSH_TTY: "/dev/pts/1"
USER: root
LD_LIBRARY_PATH: "/root/jazireh/bin/../system/usr/lib"
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:'
PATH: "/root/jazireh/system/gems/bin:/root/jazireh/bin/../system/../bin:/root/jazireh/bin/../system/usr/bin:/root/jazireh/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
MAIL: "/var/mail/root"
QT_QPA_PLATFORMTHEME: appmenu-qt5
PWD: "/root/jazireh/bin"
ARACHNI_WEBUI_LOGDIR: "/root/jazireh/bin/../system/logs/webui"
LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/root/jazireh/bin/../system/logs/framework"
HOME: "/root"
SHLVL: '1'
RAILS_ENV: production
DYLD_LIBRARY_PATH: "/root/jazireh/bin/../system/usr/lib:"
LOGNAME: root
GEM_PATH: "/root/jazireh/bin/../system/gems"
SSH_CONNECTION: 192.95.47.198 43499 192.99.133.160 22
LESSOPEN: "| /usr/bin/lesspipe %s"
XDG_RUNTIME_DIR: "/run/user/0"
RUBYLIB: "/root/jazireh/system/gems/gems/bundler-1.7.3/lib:/root/jazireh/bin/../system/usr/lib/ruby:/root/jazireh/bin/../system/usr/lib/ruby/site_ruby/2.1.0:/root/jazireh/bin/../system/usr/lib/ruby/2.1.0:/root/jazireh/bin/../system/usr/lib/ruby/2.1.0/x86_64-linux:/root/jazireh/bin/../system/usr/lib/ruby/site_ruby/2.1.0/x86_64-linux"
RUBY_VERSION: ruby-2.1.1
LESSCLOSE: "/usr/bin/lesspipe %s %s"
RACK_ENV: development
BUNDLE_GEMFILE: "/root/jazireh/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/root/jazireh/bin/../system/gems"
BUNDLE_BIN_PATH: "/root/jazireh/system/gems/gems/bundler-1.7.3/bin/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/root/jazireh/system/gems/gems/kramdown-1.4.1/man"
## OPTIONS:

scope:
  redundant_path_patterns: {}
  dom_depth_limit: 10
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
datastore:
  token: fe4cb7589e19b71140481d3fe7c99aad
browser_cluster:
  pool_size: 6
  job_timeout: 120
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
session: {}
audit:
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
input:
  values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  default_values:
    "(?i-mx:name)": arachni_name
    "(?i-mx:user)": arachni_user
    "(?i-mx:usr)": arachni_user
    "(?i-mx:pass)": 5543!%arachni_secret
    "(?i-mx:txt)": arachni_text
    "(?i-mx:num)": '132'
    "(?i-mx:amount)": '100'
    "(?i-mx:mail)": arachni@email.gr
    "(?i-mx:account)": '12'
    "(?i-mx:id)": '1'
  without_defaults: true
  force: false
http:
  user_agent: Arachni/v1.0.3
  request_timeout: 50000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 500
  request_headers: {}
  cookies: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_cookies
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- webdav
- xpath_injection
- xss
- xss_dom
- xss_dom_inputs
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
  platforms: []
  plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
  no_fingerprinting: false
  authorized_by: 
  url: http://sobheqazvin.ir/
  --------------------------------------------------------------------------------
  [2014-10-24 10:51:29 -0400] Giving up trying to audit: http://sobheqazvin.ir/
  [2014-10-24 10:51:29 -0400] Couldn't get a response after 5 tries.

**Comment by jjgh** [comment]
This worked for me, thanks. Is it possible to change the user agent using the web interface?

**Comment by Zapotek** [comment]
@jjgh Yep, look under the HTTP options in your scan profile.

**Comment by jjgh** [comment]
Ha, laziness :p. I'm sorry.
