### ISSUE TITLE
Check - Insecure cross domain policies

### ISSUE THREAD

**Issue by treadie** [Arachni/arachni#506]
It would be good to have a module that looked for wildcard entries in the cross domain policies for both Flash and Silverlight.

Flash - /Crossdomain.xml 
Silverlight - /Clientaccesspolicy.xml

reference: https://www.owasp.org/index.php/Test_RIA_cross_domain_policy_%28OTG-CONFIG-008%29

**Comment by Zapotek** [comment]
All done. :) You're on the hook for the info data though.
