### ISSUE TITLE
How can I make Arachni  test AJAX "unforms"?

### ISSUE THREAD

**Issue by sitsofe** [Arachni/arachni#517]
I've found that Arachni seems to skip over AJAX submitted (un)forms when doing a normal scan. Here's an example:
```php
<?
if ($_POST['choice'] == "XSS") {
        echo $_POST['XSS']; # XSS Time!
} else {
?>
<!DOCTYPE html>
<html>
<head>
<title>Arachni AJAX unform test</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<script type="text/javascript">
function submit() {
        var XHR = new XMLHttpRequest();
        var data = {choice:'XSS', XSS:document.getElementById("XSS").value};
        var FD  = new FormData();

        for(name in data) {
        FD.append(name, data[name]);
        }

        XHR.addEventListener('load', function(event) {
        document.getElementById("xhrresponse").innerHTML = XHR.responseText;
        });
        XHR.open('POST', 'unform.php');
        XHR.send(FD);
}
</script>
<input id="XSS" value="&lt;span style='color:red'&gt;XSS Time!&lt;/span&gt;">
<input type="submit" value="XSS" onclick="submit()">
<div id="xhrresponse"></div>
</body>
</html>
<?
}
?>
```

Is using Arachni's proxy the only way to get to such "unforms"?

**Comment by sitsofe** [comment]
Hi,

I've just tried rechecking this with a scan submitted from arachni_web1.3.1-0.5.8 and with

```
Audit forms
Audit UI forms
```

and all the XSS active checks on but this problem wasn't picked up. Is there something more I need to turn on in the web interface?

**Comment by Zapotek** [comment]
Turns out there was a regression causing issues with parsing `multipart/form-data`.
I'll release a bugfix version tomorrow, thanks for letting me know.

**Comment by Zapotek** [comment]
Turns out there was an issue with parsing form-data but the real regression was that UI Forms considered `<buttons>` and `<input type="button">` only, it missed `<input type="submit">`.

Adding specs for both cases to make sure this doesn't break again.

**Comment by Zapotek** [comment]
Referenced the wrong issue from the relevant [commit](https://github.com/Arachni/arachni/commit/0d44f52ee625adf3d689a22f2b4804863bb0d5fe).

Building packages for the release now, will let you know once it's ready.

**Comment by Zapotek** [comment]
Released: http://www.arachni-scanner.com/download/

**Comment by sitsofe** [comment]
The latest download definitely fixes this. Thanks!
