### ISSUE TITLE
URL Decode on Session Cookies 

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#521]
Hello,

Arachni is url decoding session cookies which is resulting in session cookies failing to work against the application.  Can the automatic URL decoding be removed?

**Comment by sbehrens** [comment]
Did this make it in the last release?  I'm having some issues with '=' being decoded in the cookies.

**Comment by Zapotek** [comment]
Yeah but the change only affected the handling of `&`, `=` is allowed in the cookie value and shouldn't be the cause of any issues.

**Comment by sbehrens** [comment]
Mysite=v%3D2%26mac%3DAQEAEAABABRHREDACTED; is the cookie I was trying to
send.

When I proxy and run it through Arachni I see parts of it URL Decoded and
the following is sent:

Mysite=v=2%26mac=AQEAEAABAABABRHREDACTED;.

By the time it hits the server, since the = signs are not encoded it must
be trying to parse that out because it is not accepting the cookie.

**Comment by Zapotek** [comment]
If that's indeed the cause, the server shouldn't be doing that, it should be splitting the cookie into name/value based only on the first `=`.

Are you comfortable adding `=` to the list of reserved characters (similarly to [my patch](https://github.com/Arachni/arachni/commit/d3e0e4002f5aa8c8b047b8a6df862289e8a8ef91#diff-7468386e8f63ab1fa3ed31c927410da4R469)) or would you like me to push a nightly? Because it's going to take a while to build and upload.

**Comment by sbehrens** [comment]
Yeah I've wondered if it was an issue with the server although it's a little confusing.  I'm looking at (http://tools.ietf.org/html/rfc6265)[RFC 6265 HTTP State Management Mechanism] on page 8 it states:

"To maximize compatibility with user agents, servers that wish to
   store arbitrary data in a cookie-value SHOULD encode that data, for
   example, using Base64 [RFC4648]."

Which makes me think all of the values in the cookie SHOULD be URL encoded (which would resolve this issue).

I would be totally fine adding it except we are actually in the process of doing a super large scale scan and were hoping to not have to maintain our own branch/version of Arachni as we will be deploying/pulling many instances of the app during the scan.

**Comment by Zapotek** [comment]
Lol of course not, I just wanted to you to check it out real quick so that we'll know if that the cause. If that fixes it then I'll push the fix immediately and start building nightlies.

**Comment by sbehrens** [comment]
Oh sure, give me a minute ill do another run!

**Comment by sbehrens** [comment]
Added the '=' (cookie.rb line 469) to reserved:

```code
reserved = "+;%\0\'\"&="
```
Server recognized the cookies.  That did indeed fix the issue.

**Comment by Zapotek** [comment]
Btw, are you running from source of using the packages?

**Comment by sbehrens** [comment]
I am using the packages.

**Comment by Zapotek** [comment]
Cool, nightlies are up. )
