### ISSUE TITLE
AutoLogin crash - [Selenium::WebDriver::Error::WebDriverError] unexpected response, code=0, content-type=""

### ISSUE THREAD

**Issue by TravellingGuy** [Arachni/arachni#525]
I'm attempting to have the AutoLogin plugin login to our web app, but it's failing after successfully logging in with the following error. I can see in our logs that arachni is successfully getting to the login page, and successfully POSTing the page, then successfully GETs the logged in dashboard page, then this error is thrown.
```
./arachni https://testingsite.com/ --plugin=autologin:url=https://testingsite.com/login,parameters='email=my@email.com&password=mypassword',check='logout' --scope-exclude-pattern=logout
Arachni - Web Application Security Scanner Framework v1.0.5
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms and cookies.

 [*] Initializing...
 [*] Waiting for plugins to settle...
 [~] AutoLogin: System paused.
 [-] [Selenium::WebDriver::Error::WebDriverError] unexpected response, code=0, content-type=""
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:66:in `create_response'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/selenium/webdriver/remote/http/typhoeus.rb:38:in `request'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:434:in `submitElement'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/element.rb:179:in `submit'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/watir-webdriver-0.6.9/lib/watir-webdriver/elements/form.rb:13:in `submit'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/browser.rb:625:in `block in fire_event'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/page/dom/transition.rb:151:in `call'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/page/dom/transition.rb:151:in `start'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/page/dom/transition.rb:106:in `initialize'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/browser.rb:617:in `new'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/browser.rb:617:in `fire_event'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/element/form/dom.rb:27:in `trigger'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/element/capabilities/auditable/dom.rb:90:in `block in submit'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/session.rb:242:in `call'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/session.rb:242:in `with_browser'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/element/capabilities/auditable/dom.rb:85:in `submit'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/session.rb:344:in `login_from_configuration'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/session.rb:230:in `login'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/components/plugins/autologin.rb:40:in `run'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/plugin/manager.rb:68:in `block (3 levels) in run'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/utilities.rb:395:in `call'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/utilities.rb:395:in `exception_jail'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/plugin/manager.rb:65:in `block (2 levels) in run'
 [-] 
 [-] Parent:
 [-] Arachni::Plugin::Manager
 [-] 
 [-] Block:
 [-] #<Proc:0x000000020445a0@/opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/plugin/manager.rb:65>
 [-] 
 [-] Caller:
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/utilities.rb:395:in `exception_jail'
 [-] /opt/arachni-1.0.5-0.5.6/system/gems/gems/arachni-1.0.5/lib/arachni/plugin/manager.rb:65:in `block (2 levels) in run'
 [-] --------------------------------------------------------------------------------
```

**Comment by TravellingGuy** [comment]
Hi Zapotek. Apologies for not replying back quickly on this. I got caught up in doing other things, and I actually missed the message about trying it with --debug=3!

I just downloaded arachni 1.0.6 and give it a try again and the error is still happening. I have a lot with --outout-debug=3. Is there a way I can send a private log to you, I believe I removed all the confidential bits, but I'd rather be cautious and not post the log in the public forum.

**Comment by Zapotek** [comment]
Sure thing: tasos.laskos@arachni-scanner.com

**Comment by Zapotek** [comment]
Thanks for the e-mail, I'm in the middle of debugging another issue right now but I get to this right after.

Cheers

**Comment by Zapotek** [comment]
I reviewed the log but unfortunately nothing's jumping out at me.
Is there any way that you can provide me with the settings you used in order to reproduce this?

**Comment by TravellingGuy** [comment]
Well, well, well. I have some exciting news.

So, I was running arachni on a base Ubuntu 14.04 install (on an m3.large EC2 instance) and that's what was throwing the error I reported. I don't know why I just decided to try this now, but I just tried running arachni from my local laptop (Debian unstable), hitting the same web app with the same command line and the error does not happen. arachni logs in fine and does finishes successfully.

So, it's repeatable for me on my EC2 instance, but I can't replicate the same behaviour on my laptop (using the same arachni download bundle, x86 64-bit). I think I may try to spin up a new EC2 instance and try it on there to see if it's reproducable there.

**Comment by TravellingGuy** [comment]
Hey Zapotek.

I just spun up another EC2 instance from the base Ubuntu 14.04 image provided by Canonical in the AWS console, downloaded arachni, ran it with the same command-line arguments against the same web app and was able to reproduce the error. It's happening on both an m3.large and an m3.medium instance types. I'm not sure if it's something specific to it being an EC2 instance or something in Ubuntu 14.04 that may be causing it.

**Comment by Zapotek** [comment]
Thanks for digging into this, one more thing I'd like to know is whether this happens for your webapp only or for every site.

Can you please try this example and let me know: http://support.arachni-scanner.com/kb/general-use/logging-in-and-maintaining-a-valid-session#autologin-plugin

Cheers

**Comment by TravellingGuy** [comment]
I tried the example (run from my arachni EC2 instance) and it works as expected. It logs in and starts running the test. I never let it finish the pen test (CTRL-c) to abort, but it does log in and get going.

One thing I noticed, when I run against the testfire.net test app, arachni logs in and starts the test very quickly (within 20 seconds). When I run against our app, it takes a looooonnnngggg time for it to login and start the test. The GET to the login page happens, but the POST doesn't happen until about 1.5 to 2 minutes later, then it's another 30+ seconds before it actually starts the test. This is true whether I run it on the EC2 instance or my laptop. Our app is not actually that slow. :-)
```
[22/Jan/2015:20:53:30 +0000] "GET /authentication/login HTTP/1.1" 200 3257 "-" "Arachni/v1.0.6"
... (GETs for css, js, etc.)
[22/Jan/2015:20:55:24 +0000] "POST /authentication/password/login HTTP/1.1" 302 227 "https://appsite.com/authenticate/login" "Arachni/v1.0.6"
[22/Jan/2015:20:55:27 +0000] "GET /dashboard HTTP/1.1" 200 8545 "https://appsite.com/authentication/login" "Arachni/v1.0.6"
... (GETs for css, js, etc.)
[22/Jan/2015:20:56:00 +0000] "GET /dashboard HTTP/1.1" 200 8474 "-" "Arachni/v1.0.6"
````

**Comment by Zapotek** [comment]
Is there a long JS `setTimeout` in your app? Arachni will wait for those to fire before proceeding.

**Comment by TravellingGuy** [comment]
Hey Zapotek. I'll try and do some debugging on this front. We don't have a setTimeout, but maybe there's something else causing it to delay for a long time, which in turn is causing the error to be thrown. However, I probably won't be back onto this project for months, so feel free to close this ticket if you wish.

**Comment by Zapotek** [comment]
Fair enough, closing the issue for now.
