### ISSUE TITLE
Unusual "Missing 'Strict-Transport-Security' header" result

### ISSUE THREAD

**Issue by pirxthepilot** [Arachni/arachni#532]
Hi,

We've recently added HSTS headers on our sites. Before this, Arachni detected "Missing 'Strict-Transport-Security' header" with  the affected URLs as the top level website names, as expected. For example:

https://site1.domain.com/
https://site2.domain.com/

But this time, after adding the HSTS header, Arachni still fires up "Missing 'Strict-Transport-Security' header", but only on the ff. patterns:

https://site1.domain.com/content/Css/css?v=g5_OBPLgjQ5__MI7jJvJtKH0VLAyXIMIeElSKO5GoaA1
https://site2.domain.com/bundles/jquery?v=CkVTG71m7lHB5jSCpyOSxbeKAWLIPag7u7NL4ykFenk1

For each website, either it's css or jquery, but never both. All websites contain both, however.

Checking on each affected link, I can see the HSTS header - to be expected as HSTS is configured at the top website level.

Could this behavior be explained?

Currently using version 1.0.5-0.5.6.

Thanks!

**Comment by pirxthepilot** [comment]
Hi Tasos, sorry for the very long delay in response. Looking at the report, the response headers are blank.. I have attached an image for reference.

![2015-01-20 14_26_58-clipboard](https://cloud.githubusercontent.com/assets/7690118/5812994/7d8a5cc8-a0b0-11e4-991a-8323c9556287.png)

**Comment by Zapotek** [comment]
OK that's just weird...Is this reproducible? And if so, may I please have the necessary info to rerun the same scan? If so, you can send me the info at tasos.laskos@arachni-scanner.com.

**Comment by Zapotek** [comment]
@pirxthepilot Hello again, would you like me to pursue this or shall I close the issue?

**Comment by pirxthepilot** [comment]
Hi Tasos, apologies for now following through. You may close this issue - I will be doing another Arachni scan on our sites soon (using the newest version), and will see if the problem still persists. I'll make sure to capture pertinent logs this time. Thank you!
