### ISSUE TITLE
How to scan pages that always reply with HTTP 200

### ISSUE THREAD

**Issue by pirxthepilot** [Arachni/arachni#533]
This is not really an issue, so forgive me if I posted in the wrong section.

I would like to know what is the best approach for web pages that replies with HTTP 200 no matter what you put in after it. Let's say we have a website with this page as the front page:

http://site/frontpage

If I visit any randomly-named URIs after it, e.g.

http://site/frontpage/random
http://site/frontpage/cmd.exe

it always shows the front page with HTTP 200. It does not redirect with a 302; it keeps the URI.

As you can see, this is an issue with web app scans as the scanner will incorrectly detect that backdoors/common directories/backup directories/etc are present in the site.

Thanks for the help.

**Comment by Zapotek** [comment]
Closing this issue, FP examples provided by other users and the fixes are in the v1.1 branch.

Cheers

**Comment by pirxthepilot** [comment]
Hi Tasos, sorry wasn't able to help you with this. Glad it's been fixed!

**Comment by Zapotek** [comment]
No worries.

There's still a bug in the v1.1 branch but I'll push the fix for that in a couple of days after some more testing.

Cheers
