### ISSUE TITLE
Support XXE (Xml eXternal Entity)

### ISSUE THREAD

**Issue by shitsecurity** [Arachni/arachni#537]
Add support for XXE (Xml External Entity) active checks.

**Comment by Zapotek** [comment]
Note to self (by @treadie) http://www.vsecurity.com/download/papers/XMLDTDEntityAttacks.pdf

**Comment by Zapotek** [comment]
I did a little digging into this and, if I understood the issue correctly, I don't think that it can be detected without an intermediary server.

Is that right?

**Comment by Zapotek** [comment]
Nevermind, I was educated on the subject by another user and I will start work on a check for reflected cases.
I'll keep you posted on my progress.

**Comment by Zapotek** [comment]
Unfortunately I haven't found a demo case I can test nor been able to create one via Ruby libs so as to include as a check test.

I'm removing this from v1.1, if anyone has a test case for me please let me know and I'll give it a shot then.

Cheers

**Comment by shitsecurity** [comment]
Simplest example possible: https://github.com/shitsecurity/ruby-xxe

XXE OOB (out of band) vectors require listeners. Worst case scenario they should include http(s), dns, ftp, ssh, gopher, telnet. That does NOT mean that an intermediary server is a necessity (if scanning is done from a vps for example).

The listeners could be used to detect OOB sql injections (postgres, oracle, etc) and SSRF, as well as blind XSS (say on backend support systems), although the latter isn't really a probable scenario, imho.

Please refence the SSRF bible (https://docs.google.com/document/d/1v1TkWZtrhzRLy0bYXBcdLUedXGb9njTNIJXa3u9akHM/edit?pli=1).

If scanning is done from behind a NAT, connections could reverse proxied (by external software) from some vps that has a white ip and is reachable from the target being scanned.

Let me know if you want to discuss possible vectors for detection. Thanks.

**Comment by Zapotek** [comment]
What an idiot, I was experimenting with something similar to your example but had the wrong options.
Now I can work on a check for reflected cases.

Any way you slice it though, the OOB case does indeed require an intermediary server. Maybe not in terms of a dedicated machine but from a networking point of view. Like you mentioned, there are more checks that could use that but I'm not prepared to implement it at the moment. I do plan to do this though at some point.

Thanks for the feedback, much appreciated.

**Comment by Zapotek** [comment]
@treadie If you could put this on your list for check descriptions that'd be great. :)

**Comment by treadie** [comment]
Sure thing.
