### ISSUE TITLE
How to auto login a website with verify code?

### ISSUE THREAD

**Issue by stujqye** [Arachni/arachni#539]
I wanna scan a website with verify code. How can I setup the autologin script? As the verify code changes every time, I can't set a static word in the script.
for example:
./arachni https://IP:Port --plugin=autologin:url=https://IP:Port/loginpage,parameters='userId=username&password=psw&check_code=1234',check='logout' --scope-exclude-pattern=logout

Thanks.

**Comment by Zapotek** [comment]
Hello,

Can you please ask this question a the [support](http://support.arachni-scanner.com) portal?
This tracker is for issues and feature requests.

Cheers

**Comment by Zapotek** [comment]
Nevermind, I see that you already did. :)
