### ISSUE TITLE
How can I see if login was sucessfull

### ISSUE THREAD

**Issue by laoneo** [Arachni/arachni#541]
When I want to do an authenticated scan (using the auto login plugin), how can I figure out if the login was successfully? In version 0.4 there was a message at the top of the output of the command. In version 1 I can't find any relevant information.

**Comment by Zapotek** [comment]
I'm not 100% sure but the message hasn't changed.
Also, in v1.x the scan will be aborted if the login isn't successful, so if it starts then you're OK.

Cheers
