### ISSUE TITLE
Rails Forms Backup Directory problem.

### ISSUE THREAD

**Issue by whithajess** [Arachni/arachni#545]
Running Arachni vs a basic rails website with a standard form gives large number of results for Backup directory issue. 

A standard rails app with a forms routes look like so:
```ruby
RAILS_ENV=production rake routes

       Prefix Verb   URI Pattern                   Controller#Action
         root GET    /                             testforms#index
    testforms GET    /testforms(.:format)          testforms#index
              POST   /testforms(.:format)          testforms#create
 new_testform GET    /testforms/new(.:format)      testforms#new
edit_testform GET    /testforms/:id/edit(.:format) testforms#edit
     testform GET    /testforms/:id(.:format)      testforms#show
              PATCH  /testforms/:id(.:format)      testforms#update
              PUT    /testforms/:id(.:format)      testforms#update
              DELETE /testforms/:id(.:format)      testforms#destroy


```

`new_testform GET    /testforms/new(.:format)      testforms#new` will respond to `/testforms/new.1` etc. and so Arachni just continues to postfix this url.

Im really unsure how long it will try to do this for but my current scan vs localhost (in production enviroment) is at 42 minutes and is still scanning that route. `Requests performed	165305` this seems pretty excessive for a test website with nothing but a single form.

**Comment by Zapotek** [comment]
This issue has been fixed in the [v1.1](https://github.com/Arachni/arachni/tree/v1.1) dev branch and will be released with v1.1, if you'd like to test it that'd be greatly helpful and allow me to release sooner. Setup instructions can be found at: https://github.com/Arachni/arachni/tree/v1.1#linux-and-osx

Cheers

**Comment by whithajess** [comment]
Cool thanks for this (fastest response ever)! Will check this out now.

**Comment by whithajess** [comment]
On testing of this with v1.1 it only displayed 21 Backup directory issues with `testforms/new`

**Comment by Zapotek** [comment]
Relevant issue at #547.
