### ISSUE TITLE
Instructions for building arachni with arachni-ui-web from source

### ISSUE THREAD

**Issue by whithajess** [Arachni/arachni#546]
So I was going through the [Installation Instructions](https://github.com/Arachni/arachni/wiki/Installation), and there does not appear to be any for building from source with arachni-ui-web. Just a caveat  "This is about installing the Arachni Framework only and does not include the WebUI."  would it be possible to have some instructions for doing this?

**Comment by Zapotek** [comment]
Here you go: https://github.com/Arachni/arachni-ui-web/tree/framework-v1.1#linux-and-osx

I'll put these in the Wiki once Framework v1.1 is released.

Cheers

**Comment by whithajess** [comment]
Thanks your a legend!
