### ISSUE TITLE
Backdoor false positive against OWA 2010

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#552]
Got a hit on /owa/auth/cmdasp.aspx backdoor against an OWA 2010 server during a recent scan with the latest nightly.  Manually inspecting the page revealed a custom 404 page.  

Here are the arachni requests and responses:

Req:
GET /owa/auth/cmdasp.aspx HTTP/1.1
Host: <ip>
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cookie: OutlookSession=daa25035a2c34a778b908c7d3ae1692d

Resp:
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
X-OWA-Version: 14.3.224.2
X-OWA-Error: System.Web.HttpException
X-Powered-By: ASP.NET
Date: Sun, 22 Feb 2015 19:21:41 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html dir="ltr">

<head>
	<meta http-equiv="Content-Type" content="text/html; CHARSET=utf-8">
	<title>Error</title>
	<link type="text/css" rel="stylesheet" href="/owa/14.3.224.2/themes/base/premium.css">
	<link type="text/css" rel="stylesheet" href="/owa/14.3.224.2/themes/resources/owafont.css">
	<style>
		
	</style>
	
	
</head>
<body id="errorAspx" class="err">

<table class="errDesc" style="margin-top:24px"> 
<tr>
	<td style="width:1%"><img src="/owa/14.3.224.2/themes/base/warn.png"></td>
	<td id="errMsg">An error occurred and your request couldn't be completed. If the problem continues, contact your helpdesk with this HTTP Status code: 404.</td>
</tr>

</table>
<hr class="line" size="2">

			<div class=act onclick="window.clipboardData.setData('Text', document.getElementById('divDtls').innerText)"><img src="/owa/14.3.224.2/themes/resources/copy.gif"> Copy error details to clipboard</div>
		

	<div class=act onclick="document.getElementById('divDtls').style.display='';this.style.display='none';"><img src="/owa/14.3.224.2/themes/resources/expnd.gif"> Show details</div>
	<br>
	<div id=divDtls style="display:none"><br><b>Request</b><br>Url: <span id=requestUrl>https://<ip>:443/owa/auth/cmdasp.aspx</span><br>OWA version: <span id=owaVersion>14.3.224.2</span><br><br><b>Exception</b><br>Exception type: <span id=exceptionType>System.Web.HttpException</span><br>Exception message: <span id=exceptionMessage>The file '/owa/auth/cmdasp.aspx' does not exist.</span><br><br><b>Call stack</b><br><div id=exceptionCallStack><div nowrap>System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath)
  </div><div nowrap>System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile)
  </div><div nowrap>System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile)
  </div><div nowrap>System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean noAssert)
  </div><div nowrap>System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp, Boolean noAssert)
  </div><div nowrap>System.Web.UI.PageHandlerFactory.GetHandlerHelper(HttpContext context, String requestType, VirtualPath virtualPath, String physicalPath)
  </div><div nowrap>System.Web.HttpApplication.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
  </div>System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)</div></div>

</body>
</html>

**Comment by Zapotek** [comment]
Would you mind giving the upcoming release a shot? It contains bugfixes in that area.
https://github.com/Arachni/arachni/tree/v1.1#linux-and-osx

**Comment by cclements** [comment]
Sorry, caught me on vacation.  Problem is fixed in 1.1.  Thanks!
