### ISSUE TITLE
Invalid "Integer" restriction on --authorized-by parameter

### ISSUE THREAD

**Issue by seekorswim** [Arachni/arachni#553]
The **arachni/system/gems/gems/arachni-1.0.6/ui/cli/framework/option_parser.rb** file seems to have a bug in its definition for the --authorized-by parameter. The "Integer" restriction causes passing a valid email address to fail. If you remove the "Integer" option, the --authorized-by works as expected.

```ruby
    def authorized_by
        on( '--authorized-by EMAIL_ADDRESS', Integer,
               'E-mail address of the person who authorized the scan.',
               "(It'll make it easier on the sys-admins during log reviews.)",
               "(Will be used as a value for the 'From' HTTP request header.)"
        ) do |email_address|
            options.authorized_by = email_address
        end
    end

```

**Comment by Zapotek** [comment]
You're right, that's my bad.
