### ISSUE TITLE
Url scope rewrites fails?

### ISSUE THREAD

**Issue by lcg79** [Arachni/arachni#555]
Hello! Great work with Arachni :)

One question: I'm not able to define the URL SCOPE REWRITES:

- Rewrites URLs based on the given rules.
- Rules take the format of pattern:substitution, input each rule in its own line.
- For example, to convert http://test.com/articles/some-stuff/23 to http://test.com/articles.php?id=23 use /articles\/[\w-]+\/(\d+)/:articles.php?id=\1.

When I define anything, no matter what, it NEVER get saved.

I look al the system/logs/webui/production.log  and there is no error. And I can see the rewrite rule I entered in the "scope_url_rewrites" element:  
- Parameters: {"utf8"=>"?", "authenticity_token"=>"SiagjVoXJ3PFT9eiWsWT4tO/SUCm/oT2/JuvZco9XAs=", "profile"=>{"name"=>"LEO 2015", "global"=>"0", "description"=>"Sensible, default settings.", (......) , "scope_url_rewrites"=>"(.*)/(.*)/(.*)/:index.
php?zone=\\1&family=\\2&product=\\3", "audit_forms"=>"1", (.......)

BUT, in the SQLITE file, I can not find this information:
- sqlite3 ./system/arachni-ui-web/db/production.sqlite3 .dump | grep scope_url_rewrites | wc -l 1  <- (the CREATE TABLE statement only)
- sqlite3 ./system/arachni-ui-web/db/production.sqlite3 .dump | grep family | wc -l 0

Other data can be changed, but the rewrites doesn't seem to work ¿?

Please: am I doing something wrong, or misundertanding something?

Without these rewrite rules working, I don't know how to use the application with new web applications with friendly URLs for SEO :-(

Thank you very much.
Leo

**Comment by Zapotek** [comment]
I appreciate the feedback but since this is a WebUI issue could I trouble you to post it at the relevant [tracker](https://github.com/Arachni/arachni-ui-web/issues) please?

Cheers

**Comment by Zapotek** [comment]
All done, the fix will be included in the next release.

Thanks for the feedback.

**Comment by lcg79** [comment]
great! thank you :^)
