### ISSUE TITLE
Inconsistent result using v1.0.6-0.5.6 & v1.0.6(+)

### ISSUE THREAD

**Issue by bstream** [Arachni/arachni#557]
I have been trying out different versions of arachni against WIVET v4 and I seem to get inconsistency between versions and I cannot figure out why. The inconsistency displays itself in the way arachni behaves for different versions (and different builds of the same version?) running the exact same command.

Steps to reproduce:
* Download [Linux x86 32bit](http://downloads.arachni-scanner.com/arachni-1.0.6-0.5.6-linux-i686.tar.gz) from arachni [downloads page](http://www.arachni-scanner.com/download/).
* Start a scan with 
```
./bin/arachni http://<redactedURL>/wivet/ --checks trainer --audit-links --audit-forms --scope-exclude-pattern=logout --scope-exclude-pattern=100\.php --scope-exclude-pattern=offscanpages --http-cookie-string="PHPSESSID=hums43b9hqftep444effgav547"
```
For me, this results in a scan that reaches 50% in 3 minutes and then continues running for 15-20 minutes with a result of **96%**. 
* clone arachni repo and build arachni as explained in the v1.1 branch.
* Again start a scan (from the "new" folder git-v1.1) with the same command as above (exchanging the PHPSESSID-cookie for a fresh run. This results in a scan that reaches 50% completion in ~20 seconds (note difference from above) but it stops there. It never reaches any higher than **50%**.
* *From here the problem seems to be with the v1.1 branch but trying both master and release/v1.0.6 I get the same results (50%)*.

I noticed that when running arachni from arachni-1.0.6-0.5.6 it spawns a browsercluster which none of the other versions seem to do. 

It looks as though the default parameters differ between the versions but that is only speculations since I have not found any proof for this. 

The system I used is Ubuntu 14.04.3 LTS 32-bit (with 2 GB RAM) running in a virtualbox on a Windows 7 host.

**Comment by Zapotek** [comment]
As the packages are self-contained they bundle a `phantomjs` browser, if you run Arachni some other way then PhantomJS 1.9.2 needs to be in your `$PATH`.

Also, my tests have been with the released version of WIVETv3: http://www.webguvenligi.org/software/wivet/wivet_v3.rar

**Comment by Zapotek** [comment]
That's mentioned in the Wiki, I forgot to mention it in the branch README though, that's by bad.

**Comment by bstream** [comment]
I see! I am getting phantomjs now and will test this again then!

**Comment by Zapotek** [comment]
I'm assuming you didn't use the build-script approach to setup your env right?

**Comment by bstream** [comment]
That is correct. I totally overlooked that part when following the README of branch v1.1.
To install v1.1 using the build-script approach I can run 
```bash
export ARACHNI_BUILD_BRANCH="framework-v1.1";
export ARACHNI_BUILD_ENV="development";
wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash;
```
Or am I missing something? (I am reconfiguring my virtual machine atm so cannot test just yet).

**Comment by Zapotek** [comment]
I was thinking that you could just pull the git repo and do this: https://github.com/Arachni/arachni/wiki/Development-environment

That way you get a stable env and you can just `git pull` to get updates instead of re-building each time.

**Comment by bstream** [comment]
Tried the procedure from scratch now. Running 
```bash
export ARACHNI_BUILD_ENV=development
wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash
```

resulted in this error during install (on step 5/6 Installing Arachni)
Included all linked logs here:
https://gist.github.com/bstream/abb590ab85e243820b6c

Looks like there is some dependency missing?
Im looking into it.

**Comment by Zapotek** [comment]
You just stumbled on my v1.1 blocker: https://github.com/sparklemotion/nokogiri/issues/1250

**Comment by bstream** [comment]
Oh, I see. Will try using RVM and installing phantomjs manually then :)

**Comment by Zapotek** [comment]
Not sure if that'll make a difference, the same dependency will need to be installed in the process. Do let me know how it goes though either way.

**Comment by bstream** [comment]
Actually, that seem to have done the trick, it succeeded with installing nokogiri. I will try to retrace the commands I used:
```bash
# I began with following the readme
sudo apt-get install build-essential curl libcurl3 libcurl4-openssl-dev
gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable --ruby
rvm use ruby

git clone git://github.com/Arachni/arachni.git
cd arachni
git checkout v1.1
bundle install --without prof docs # failed since bundler was not installed
sudo apt-get install bundler
bundle install --without prof docs # -> Your bundle is complete
```

**Comment by Zapotek** [comment]
Can you show me the output of `gem install nokogiri -v 1.6.6.2` please?

**Comment by bstream** [comment]
```bash 
gem install nokogiri -v 1.6.6.2 # You don't have permissions into the /var/lib/gems/1.9.1
sudo gem install nokogiri -v 1.6.6.2
```
```
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.6.2
1 gem installed
Installing ri documentation for nokogiri-1.6.6.2...
Installing RDoc documentation for nokogiri-1.6.6.2...
```

**Comment by Zapotek** [comment]
Erm, I edited my post to include the `-V` flag shortly after I posted it, could you retry please?

**Comment by bstream** [comment]
Oh, it appears that the auto-updating view here on GH does not update on edits... Of course, running it now.

**Comment by bstream** [comment]
Here you go https://gist.github.com/bstream/255dcf3b390f344ebdf7

**Comment by Zapotek** [comment]
So, it only fails when running from the build env, not sure if that's a good or a bad thing, looking into it again.
Thanks for the feedback man.

**Comment by bstream** [comment]
Yea seems so.. No problem at all! 

Closing this since the Browsercluster is back now when I have phantomjs in $PATH like you said, thanks :+1:

**Comment by Zapotek** [comment]
The build scripts work on my machine so I don't know what's going on, I better wait for the Nokogiri maintainers to look into this.
