### ISSUE TITLE
Permission Denied on Most Scans

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#562]
Hello,

I receive the following error (usually around 2 hours into an authenticated scan against one of y sites):

```
 [-] Client: [ArgumentError] Missing :url.
 [-] [Errno::EACCES] Permission denied @ rb_sysopen - /apps/arachni/bin/../system/logs/framework/error-28175.log
 [-] Timeout has been reached, shutting down.
 [-] [Errno::EACCES] Permission denied @ rb_sysopen - /apps/arachni/bin/../system/logs/framework/error-28175.log
/apps/arachni/system/gems/gems/arachni-1.0.6/ui/cli/output.rb:77:in `initialize': Permission denied @ rb_sysopen - /apps/arachni/bin/../system/logs/framework/error-28175.log (Errno::EACCES)
```

Any ideas on what the issue is?  This is running on Ubuntu 12.04 LTS.

**Comment by Zapotek** [comment]
It would appear that the user running the scan doesn't have write access to the logs dir, so when an error occurs (and thus has to be logged) you get that permission error.

So, you can either place the package to a dir to which you have write access or specify alternative paths at: `/apps/arachni/system/gems/gems/arachni-1.0.6/config/write_paths.yml`

If you intent to use the WebUI though you better place the package to a dir with write access as I can't really control all the locations Rails may need to write.

**Comment by Zapotek** [comment]
Also, don't worry about that error, it's somewhat common and caused by a malformed URLs, I can have a closer look at it though if you'd like, just to be safe.

**Comment by sbehrens** [comment]
The application does hang when it hits this error and the phantomjs drivers
stay open until I force kill the parent process.

**Comment by Zapotek** [comment]
By bad, I meant the `Missing :url` error. The permission error could indeed have crippling effects.

**Comment by sbehrens** [comment]
Got it, thanks!

**Comment by sbehrens** [comment]
I am looking in the gem file and I do not see write_paths.yml.   Is there
another file or location I should check?

**Comment by Zapotek** [comment]
What an idiot, I forgot to include that in the `gemspec`. You can specify an alternative logs path via an env var too: `ARACHNI_FRAMEWORK_LOGDIR`

**Comment by sbehrens** [comment]
I am still seeing the same error even when setting the env variable (and
it's still trying to write to the old log location even with the
environment variable):

stuff@stuff:/apps/arachni/system/logs$ ARACHNI_FRAMEWORK_LOGDIR=/logs
/apps/arachni/bin/arachni --report-save-path /tmp/
d6see1af12cb1ccb2c10ced55159615cd.ar --timeout 02:00:00
--http-request-redirect-limit https://www.site.com

Any other ideas?

**Comment by Zapotek** [comment]
Try changing it in `arachni/system/environment`, I forgot that the packages set their own log directories.
Final answer, this will work, I double-promise.
