### ISSUE TITLE
Can't create an html report from an afr with v1.1

### ISSUE THREAD

**Issue by glestel** [Arachni/arachni#563]
Hello

Using v1.1 I run a scan with arachni, I get an .afr file. When I use `arachni_reporter` to generate a html report, I get an error due to an encoding error of the a string containing a quote ' :

```
home/user/arachni/lib/arachni/component/manager.rb:376:in `load': /home/user/arachni/components/reporters/html.rb:35: invalid multibyte char (US-ASCII) (SyntaxError)
/home/user/arachni/components/reporters/html.rb:33: invalid multibyte char (US-ASCII)
/home/user/arachni/components/reporters/html.rb:33: syntax error, unexpected $end, expecting '}'
...ommand or query. The attacker’s hostile
...                               ^
	from /home/user/arachni/lib/arachni/component/manager.rb:376:in `load_from_path'
	from /home/user/arachni/lib/arachni/component/manager.rb:284:in `[]'
	from /home/user/arachni/lib/arachni/component/manager.rb:117:in `block in load'
	from /home/user/arachni/lib/arachni/component/manager.rb:117:in `each'
	from /home/user/arachni/lib/arachni/component/manager.rb:117:in `load'
	from /home/user/arachni/ui/cli/reporter/option_parser.rb:80:in `validate'
	from /home/user/arachni/ui/cli/option_parser.rb:69:in `parse'
	from /home/user/arachni/ui/cli/reporter.rb:34:in `run'
	from /home/user/arachni/ui/cli/reporter.rb:26:in `initialize'
	from bin/arachni_reporter:12:in `new'
	from bin/arachni_reporter:12:in `<main>'
```
The command used to generate the report was : `$ bin/arachni_reporter ~/tmp/testfire.net\ 2015-03-17\ 17_37_34\ +0100.afr --report=html:outfile=my_report.html`

If it can help, version of ruby is `ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

To run the scan I tried with arachni and arachni arachni_rpc. I believe that the issue comes from  arachni/components/reporters/html.rb

Regards

**Comment by Zapotek** [comment]
Hello there,

I'm inclined to think that Ruby 1.9.3 is the issue, as encoding handling has been improved in later versions.
Also, the gemspec for v1.1 has recently been updated to require at least 2.0.0 and the official packages will bundle Ruby 2.2.1.

Still, I'll go over the issue descriptions and the HTML report to ensure that strings are sanitized before being used.

Just for the sake of verifying my suspicion, could you try to generate the report with Ruby 2.2.1?

Cheers

**Comment by glestel** [comment]
After some intensive fight and hair loss, I managed to update my Ubuntu Trusty to Ruby 2.0 and html report generation works. Thanks

**Comment by Zapotek** [comment]
Not to piss you off, but why not use the official self-contained packages or RVM?

**Comment by glestel** [comment]
I'm not conformable with the Ruby ecosystem and when I tried the RVM it was overrided by ruby package in Ubuntu.
By the self-contained package, you mean the build scripts to set up a development environment? As my development use Arachni-RPC-Pure, I'm not sure it's compatible with an "isolation" of Arachni

**Comment by Zapotek** [comment]
Ah, fair enough then. :)
