### ISSUE TITLE
Broken links in HTML report

### ISSUE THREAD

**Issue by bstream** [Arachni/arachni#565]
Minor issue with broken links in the HTML reports. Some links are absolute when they should be relative. Here are the ones that I have found:
* [charts.erb#L32](https://github.com/Arachni/arachni/blob/experimental/components/reporters/html/default/summary/charts.erb#L32)
* [charts.erb#L55](https://github.com/Arachni/arachni/blob/experimental/components/reporters/html/default/summary/charts.erb#L55)
* [charts.erb#L56](https://github.com/Arachni/arachni/blob/experimental/components/reporters/html/default/summary/charts.erb#L56)

**Comment by Zapotek** [comment]
Thank you. :)
