### ISSUE TITLE
Arachni Unable to Scan Oracle ADF/JSF Application

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#566]
Hi Tasos,

I have a site which Arachni cannot seem to spider/scan.  This is an Application written in the Oracle ADF framework with Java Server Faces.  When proxing the scan to see what is going on, it seems to hit the root of the web application but it does not load the ADFLoopbackUtils JS function which seems to main function for URL rewriting for the application.   

I unfortunately can't provide you access to the web application but I could provide some example request/response pairs if that would be helpful in determining why It cannot crawl the app.

**Comment by Zapotek** [comment]
Could you try with the latest nightlies please?
I fixed a bug yesterday which may take care of this.

**Comment by sbehrens** [comment]
Sure i'll give it a shot, thanks!

**Comment by sbehrens** [comment]
Seems to now know how to spider the site, closing.
