### ISSUE TITLE
workload exhausted when scanning testfire.net

### ISSUE THREAD

**Issue by 0xd012** [Arachni/arachni#568]
Hi,

Launching `arachni http://testfire.net` with both v1.1 and experimental on a Linux box leads to "Workload exhausted..." and the scan seems to freeze.

Hope this helps!
Laurent.

**Comment by 0xd012** [comment]
Hi,

I am giving it another try today as the scan seems to freeze several minutes, then come back to life again and again.

Regards,
Laurent.

**Comment by Zapotek** [comment]
The default browser job time-out is 120 seconds, could you try decreasing it to 8 or so and retrying?
The option is `--browser-cluster-job-timeout`.

Cheers

**Comment by 0xd012** [comment]
Ok, launched it again.

**Comment by 0xd012** [comment]
That's fine now!

Thanks!
