### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by discostur** [Arachni/arachni#574]
Hi,

i try to scan a website with the CLI and i get the following error:

/arachni-1.0.6-0.5.6/system/gems/gems/arachni-1.0.6/lib/arachni/element/base.rb:138: stack level too deep (SystemStackError)

The error appears at the end of the scan and it doesn't write any report file. If i try to scan the website by the Web-GUI it never finishes (scans now for 1,5h).

I tried it multipel times and got everytime the same error.

Greets

**Comment by Zapotek** [comment]
Can you please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?
I believe that error has been fixed there.

Cheers

**Comment by discostur** [comment]
Hi Zapotek,

you are wright, the nightlies fixed the problem!

Thanks for your help
