### ISSUE TITLE
Plugin to collect metrics

### ISSUE THREAD

**Issue by treadie** [Arachni/arachni#575]
It would be awesome if there was a plugin that collected bulk metrics about the application / scan. Some metrics may include: 

1. Total time to crawl, audit
2. Response time min, average, max
3. No. of static resources
4. No. of dynamic resources
5. No. of parameters (vectors) + names in total
6. No. of parameters (vectors) + names unique
7. No. or redundant paths / links (capture those that exceed the default)
8. csrf tokens (true or false)
9. auth (true of false)
10. url rewriting (true or false)
11. dom objects (true or false)
12. http or https 
13. web services
14. binary objects
15. flash objects

I don't think this would be an exhaustive list, and would welcome others reading this to leave comments of other metrics that they think would be useful to collect.

**Comment by cschneider4711** [comment]
Great idea. Would also be useful when scanning only parts of an application... Eventually also like scan/spider duration for distinct parts and distinct attack checks would make up good stats!

**Comment by Zapotek** [comment]
Gathering metrics for specific parts would be really hard to configure. 
If you configure the scope of the scan to only cover a part of the webapp it's no problem, if you want to run a full scan but group metrics in webapp parts then things can get **really** complicated.

About the rest, luckily v1.1 allows for fine grained stats gathering so you can get data on a per check basis, operations, requests, avg response times per check, total webapp time per check, checked elements and many more.

**Comment by Zapotek** [comment]
How would you identify 3 vs 4?

**Comment by cschneider4711** [comment]
Good question. Either via name pattern heuristics or more precise via hash comparison of response (did it change?)... Looks like an performance overkill, or?

**Comment by Zapotek** [comment]
Name, extension and content-type can separate assets vs markup, but not static vs. dynamic content since assets can be dynamic too.
Performing multiple requests per resource in hopes of determining changes would be a huge overkill, and there's no way to know when the resource is going to change anyways.

**Comment by Zapotek** [comment]
Also, what might 11 be? Elements with associated event listeners?
Because, strictly speaking, all elements are DOM objects.

**Comment by cschneider4711** [comment]
Based on content-type/extension heuristics would just be a rough estimate - app owner eventually knows how good/bad this is depending on number of dynamically generated images etc. in app. So that would be up to the person interpreting the numbers then...

Regarding performance: I also expect the hash comparison to be overkill.

Regarding #11: Can't think of a definition either: eventually the creator of this issue has more details

**Comment by Zapotek** [comment]
@treadie I can't really tell if a website is using URL rewriting, unless the webapp is successfully fingerprinted as an MVC framework, in which case a better clarification would be `is_mvc` rather than `does_url_rewriting` or something.

**Comment by Zapotek** [comment]
@treadie Maybe instead of having a web services flag I can provide a count of element types? So if there are JSON and XML inputs you'd see that.

**Comment by Zapotek** [comment]
This is that I'm thinking so far:

```ruby
    runtime:                      0,
    http_response_time_min:       0,
    http_response_time_max:       0,
    http_response_time_average:   0,
    static_resource_count:        0,
    dynamic_resource_count:       0,
    link_input_count:             0,
    form_input_count:             0,
    cookie_input_count:           0,
    json_input_count:             0,
    xml_input_count:              0,
    input_vector_total_count:     0,
    input_vector_unique_count:    0,
    out_of_scope_resource_count:  0,
    has_csrf_tokens:              nil,
    has_authentication:           nil,
    is_mvc:                       nil,
    event_listener_count:         0,
    uses_http:                    nil,
    uses_https:                   nil,
    binary_resource_count:        0,
    swf_object_cont:              0

```

**Comment by treadie** [comment]
ok.. from the beginning >

3 & 4 - was thinking about this, static vs dynamic could be misleading. I guess the correct way to explain what I was meaning would be static pages/requests vs those that contain parameters. A potential gotcha with this is where there are several requests to the same resource where the parameters being used are different. in this case each unique request is counted individually as it will inevitably be treated independently by the scanner anyway right? happy to discuss if you feel different.

DOM Elements - Yeah as you mentioned.

Rewriting - fair point, MVC flag would be a good one anyway. would you feed this particular info back into the trainer? even know you don't know the exact rule, it could be worth scanning each path/folder/ whatever its called (just woke up, still haven't had my coffee)?

Elements - JSON/XML/GET/POST = cracking idea

Looks good otherwise. Something i just noticed, I think the total scan time should also be put into this plugin. although its used elsewhere, this is probably where you need it most :)

**Comment by Zapotek** [comment]
* The request thing sounds cool, will need another name though.
* OK about the DOM stuff as well.
* This is done by the fingerprinters so it's per resource and is used to avoid doing discovery checks that don't apply to webapps that do their own routing instead of loading from the FS.
* That's the `runtime`.

(Just having my coffee too fwiw.)

**Comment by Zapotek** [comment]
Turns out I can't count out of scope resources.

**Comment by Zapotek** [comment]
Demo run against http://testhtml5.vulnweb.com:

```ruby
{
                             :runtime => 379.433694167,
              :http_response_time_min => 0.007831,
              :http_response_time_max => 1.4731969999999999,
          :http_response_time_average => 0.13620721173613712,
    :resource_without_parameter_count => 10,
       :resource_with_parameter_count => 15,
                    :link_input_count => 376,
                    :form_input_count => 36,
                  :cookie_input_count => 0,
                    :json_input_count => 0,
                     :xml_input_count => 1,
       :input_vector_name_total_count => 608,
      :input_vector_name_unique_count => 12,
                    :has_nonce_tokens => false,
                  :has_authentication => true,
                              :is_mvc => false,
                :event_listener_count => 45,
                           :uses_http => true,
                          :uses_https => false,
               :binary_resource_count => 0,
                    :swf_object_count => 0
}
```

The `binary_resource_count` will vary depending on the browser cache.

The `event_listener_count` will take its toll on performance because each page has to be loaded by a browser, which is redundant, but the alternative would be storing that data into all pages which (depending on circumstance) would take a bigger toll by way of RAM consumption.

Looks OK?

**Comment by Zapotek** [comment]
Better yet:

```ruby
{
     :general => {
          :has_nonce_tokens => false,
        :has_authentication => true,
                 :uses_http => true,
                :uses_https => false
    },
        :scan => {
        :runtime => 26.763202812
    },
        :http => {
            :response_time_min => 0.00645,
            :response_time_max => 1.593092,
        :response_time_average => 0.1912037425011537
    },
    :resource => {
                   :binary_count => 0,
        :without_parameter_count => 3,
           :with_parameter_count => 9
    },
     :element => {
                     :link_count => 0,
                     :form_count => 1,
                   :cookie_count => 0,
                     :json_count => 0,
                      :xml_count => 0,
         :input_name_total_count => 3,
        :input_name_unique_count => 3
    },
    :platform => {
        :is_mvc => false
    },
         :dom => {
        :event_listener_count => 0,
            :swf_object_count => 0
    }
}
```

Maybe I should remove the `_count` prefixes too.

**Comment by Zapotek** [comment]
Update:

```ruby
{
     :general => {
            :egress_traffic => 8202085,
           :ingress_traffic => 61825479,
          :has_nonce_tokens => false,
        :has_authentication => false,
                 :uses_http => true,
                :uses_https => false
    },
        :scan => {
        :runtime => 385.897232193
    },
        :http => {
            :response_time_min => 0.008166,
            :response_time_max => 1.7324570000000001,
        :response_time_average => 0.13582370300206997
    },
    :resource => {
                   :binary => 3,
        :without_parameter => 9,
           :with_parameter => 15
    },
     :element => {
                     :links => 394,
                     :forms => 161,
                   :cookies => 0,
                     :jsons => 0,
                      :xmls => 0,
         :input_names_total => 634,
        :input_names_unique => 11
    },
    :platform => {
        :is_mvc => false
    },
         :dom => {
        :event_listeners => 41,
            :swf_objects => 0
    }
}
```

Traffic data are an approximation, compression and other factors may result in different actual values.

Any other ideas now that the iron's hot?

**Comment by treadie** [comment]
Seems I should sleep more often. Every time i do you churn out something new and great. My only additions (still pre coffee):  

1. a `total` count for resources just as a nice to have.
2. I guess you could also include unique injectable `headers` as an input count?
3. In platform could you add which platforms are detected. ie. `database',`framework`,`language` (essentially the headings that are used in the profile)

3 is a bit of a nice to have if I'm being honest.. but it would be pretty nice none the less

**Comment by treadie** [comment]
Data approximates are fine also.

**Comment by Zapotek** [comment]
1. Sitemap size?
2. That doesn't really apply. Arachni just audits some common request headers, that number will always be the same and not of much relevance.
3. This is easy enough.

**Comment by treadie** [comment]
yep, interesting, thanks

**Comment by Zapotek** [comment]
Need some clarifications:

1. The sitemap size won't be the same as the number of resources. URLs with parameters or fragments can point to the same resource but be reported multiple times in the sitemap. What constitutes a resource?
2. I'll update the system to include custom headers it sees via the proxy plugin or AJAX requests (as per your suggestion), so what I said previously doesn't apply.
3. You want the platforms themselves or just the types? Because the headings are the types (if I recall correctly) but it'd be much more useful to list the actual detected platforms.

**Comment by Zapotek** [comment]
Test run against: http://testfire.net

```ruby
{
      :general => {
            :egress_traffic => 6519781,
           :ingress_traffic => 65804331,
          :has_nonce_tokens => false,
        :has_authentication => false,
                 :uses_http => true,
                :uses_https => false
    },
         :scan => {
        :runtime => 379.632663782
    },
         :http => {
            :response_time_min => 0.001789,
            :response_time_max => 6.331365,
        :response_time_average => 0.34955091692667756
    },
     :resource => {
                   :binary => 3,
        :without_parameter => 19,
           :with_parameter => 17
    },
      :element => {
                     :links => 1757,
                     :forms => 90,
                   :cookies => 184,
                     :jsons => 0,
                      :xmls => 0,
                   :headers => 665,
         :input_names_total => 2721,
        :input_names_unique => 26
    },
          :dom => {
        :event_listeners => 0,
            :swf_objects => 0
    },
    :platforms => [
        [0] :windows,
        [1] :iis,
        [2] :asp,
        [3] :aspx,
        [4] :mssql
    ]
}
```

Platforms look OK? I kinda get the feeling I should categorize them by type.

**Comment by Zapotek** [comment]
Platforms ended up being categorized by type and the system now includes the actually used HTTP request headers in each page's auditable elements -- will catch custom request headers resulting from AJAX or the proxy plugin.

**Comment by treadie** [comment]
looks great, at this point in time I dont have anything else to add. guessing nobody else does either?

**Comment by Zapotek** [comment]
Cool, closing. Thanks for the feedback guys,

**Comment by treadie** [comment]
Mate, I'm a bit late with this one but it would have helped me out immensely in the last few days, can you add:

min_request_size
max_request_size
avg_request_size
min_response_size
max_response_size
avg_response_size

Cheers in advance :)

**Comment by Zapotek** [comment]
Just in time, I was preparing the v1.2 release. Nice additions btw.

**Comment by treadie** [comment]
Was there already one for total requests? (cant check for myself right at the moment)
________________________________

**Comment by Zapotek** [comment]
There is now.
