### ISSUE TITLE
`affected_input_name` always empty in the xml report

### ISSUE THREAD

**Issue by dylemma** [Arachni/arachni#577]
In the HTML report, arachni generates phrases like "In `form` with inputs `q` using `GET` at ....". I'm trying to get the `q` part from the XML report, and as far as I can tell, I should be looking at the `affected_input_name` element:

https://github.com/Arachni/arachni/blob/master/components/reporters/xml/schema.xsd#L382
```xml
<!--
    Vulnerable input name, its value can be found in
    "variationvector:inputs".
-->
<xs:element name="affected_input_name" type="xs:string"
            minOccurs="0"/>
```

I've looked through a few data sets that I could get my hands on, including http://downloads.arachni-scanner.com/dev/reports/report.xml and it's always empty: `<affected_input_name/>`

**Comment by Zapotek** [comment]
You're right that's a bug, I'll push a fix and some fresh nightlies tomorrow after I test it.

**Comment by Zapotek** [comment]
The issues is now fixed in the nightlies: http://downloads.arachni-scanner.com/nightlies/
