### ISSUE TITLE
False Negative on a POST-only Webseclab test (/xss/reflect/post1_splash)

### ISSUE THREAD

**Issue by dmitris** [Arachni/arachni#580]
Consider the Webseclab test for the POST-only XSS case - http://127.0.0.1:8080/xss/reflect/post1_splash with the action URL of http://127.0.0.1:8080/xss/reflect/post1  The idea is that the scanner should notice that there are form fields such as "in" among the form input fields, and send attack payloads to the action target fuzzing the values, for example:

$ curl -s -d in='"><script>alert(123)</script>' http://127.0.0.1:8080/xss/reflect/post1 | grep alert
<INPUT type="text" id="in" name="in" size="40" value=""><script>alert(123)</script>">

But I believe currently Arachni does not do it (yet) - I scanned both http://127.0.0.1:8080/xss/reflect/post1_splash and http://127.0.0.1:8080/xss/reflect/post1, and there are no XSS issues flagged:
```
$ ./arachni http://myloc:8088/xss/reflect/post1?in=foo  --checks xss | grep issues
[~] Report false positives at: http://github.com/Arachni/arachni/issues
[+] 0 issues were detected.
[+] No issues
[-] Has issues
[+] Without issues: 1
[-] With issues: 0 ( 0% )
```
(tried it both in master and experimental branches; similar results in the UI)

Would you consider that type of check in scope and possible to add?  We have encountered the need for it multiple times in practice - for example, when the website server code has a special case for handling POST requests, or only POST method is allowed for certain entrypoints.

![screen shot 2015-05-12 at 11 23 45](https://cloud.githubusercontent.com/assets/31205/7584236/4f13e2ee-f89c-11e4-8bd8-194475d65b7f.png)
)

**Comment by dmitris** [comment]
Rescanned with the Cross-Site Scripting profile, made sure that "Audit forms" in profile settings is checked - but still no issues flagged (tried both /xss/reflect/post1 and /xss/reflect/post1_splash).

I also tried http://webseclab:8088/xss/reflect/post1?in=foo - also no alerts.  An idea and suggestion - if the URL contains CGI parameters, would it be worth to attack them both with GET as well as with POST (doing an analogue of ```curl -d 'in="><script>alert(123)</script>' http://127.0.0.1:8088/xss/reflect/post1``` - which returns ```INPUT type="text" id="in" name="in" size="40" value=""><script>alert(123)</script>">```  Our internal scanner did that and we found it an effective approach since you can cover some POST entrypoints despite supplying just URLs.

**Comment by Zapotek** [comment]
This is the same hostname redirections to out-of-scope IP address issue as #582.

**Comment by Zapotek** [comment]
This works for example:

    ./bin/arachni http://127.0.0.2:8080/xss/reflect/post1_splash --checks xss*

Because when given an IP address it is preserved by webseclab and does not redirect to an out of scope address.

**Comment by dmitris** [comment]
Correct - thanks for setting this straight.  For some reason I'm unable to use 127.0.0.2 even when added to /etc/hosts...

**Comment by Zapotek** [comment]
Are you scanning from OSX?

**Comment by dmitris** [comment]
yes

**Comment by Zapotek** [comment]
sudo ifconfig lo0 alias 127.0.0.2 up

**Comment by dmitris** [comment]
Yay! live and learn :smile:   thanks
