### ISSUE TITLE
False Negative on the Webseclab double-encoded payload XSS test (/xss/reflect/doubq1?in=x)

### ISSUE THREAD

**Issue by dmitris** [Arachni/arachni#581]
Consider the Webseclab test /xss/reflect/doubq1?in=x for an injection of double-escaped tags, PoE:
http://127.0.0.1:8080/xss/reflect/doubq1?in=change_me2%2522%253E%253Cimg%2520src%253Dfoobar%2520onerror%253Dalert(13578)%253E&

with the following source in the response HTML:
```
The value of the cgi parameter &quot;in&quot; is: change_me2"><img src=foobar onerror=alert(13578)>
```

Arachni currently does not flag this an XSS issue:
$ ./arachni http://myloc:8088/xss/reflect/doubq1?in=x --check xss | grep issues
[~] Report false positives at: http://github.com/Arachni/arachni/issues
[+] 0 issues were detected.
[+] No issues
[-] Has issues
[+] Without issues: 1
[-] With issues: 0 ( 0% )

tried on master and experimental branches as well as with the Web GUI (screenshot below).

Would it be possible to add a double-escaped payload?  Thanks.

![screen shot 2015-05-12 at 13 04 47](https://cloud.githubusercontent.com/assets/31205/7585917/876bcd40-f8a7-11e4-89c3-75ed8d7ea586.png)

**Comment by dmitris** [comment]
rescanned it with the Cross-Site Scripting profile but still getting no issues flagged.

**Comment by dmitris** [comment]
Rescanned as a quad-pair IP target (Cross-Site Scripting profile), but still not getting an XSS finding.
Double-checked that http://192.168.178.74:8088/xss/reflect/doubq1?in=xin=%253Cscript%253Ealert%28%252FXSS%252F%29%253C%252Fscript%253E pops-up an alert

```
$ curl 'http://192.168.178.74:8088/xss/reflect/doubq1?in=xin=%253Cscript%253Ealert%28%252FXSS%252F%29%253C%252Fscript%253E'


<!DOCTYPE html>
<html><head><title>Double-Encoded tags injection (doubq.1)</title>

</head><body>


Hello!<BR>
The value of the cgi parameter &quot;in&quot; is: xin=<script>alert(/XSS/)</script>
<p>
This test echos unencoded version of double-encoded tags.


</body></html>
```

![screen shot 2015-05-12 at 10 05 50 pm](https://cloud.githubusercontent.com/assets/31205/7597335/19c365a4-f8f3-11e4-98c1-fcc884c5114d.png)

**Comment by Zapotek** [comment]
The XSS checks don't currently send double-encoded payloads, I'll look into this.
