### ISSUE TITLE
login_script plugin is not working properly

### ISSUE THREAD

**Issue by Gaurang033** [Arachni/arachni#585]
Hi Guys, 

I am trying to use arachni for doing security testing of my website, however the problem is my website requires authentication.

As our site, doesn't have any login form (uses extjs), I thought it would be good idea to write login script for that and so I wrote login script using waitr-webdriver as suggested. Login script is working fine. 

However when I provide this login script to arachni it fails at check pattern.  If i don't provide blank in check pattern then arachani performs the attack, however it's not able to visit the pages which requires Authentication. 

Following is the login script. 

```
require 'selenium-webdriver'
require 'watir-webdriver'
require 'arachni'

b = Watir::Browser.new
b.goto "https://10.10.10.10/webui/login"
b.text_field(:id => 'j_username-inputEl').send_keys 'admin'
b.element(:id => 'j_password-inputEl').send_keys 'symantec'
b.element(:xpath => "//*[text()='Sign In']").click
sleep(30)
Watir::Wait.until { b.text.include? 'System is Healthy' }
```

following is the command I am using 

    arachni https://10.10.10.10/webui/login --plugin=login_script:script=login.rb --session-check-pattern=/.*/ --session-check-url="http://110.10.10.10/webui/charts/getactivethreatschartdata"

and following is the output 

```
 [!] Session: Logging in via sequence: #<Proc:0x000000012647c8@/usr/local/rvm/gems/ruby-2.0.0-p643/gems/arachni-1.1/components/plugins/login_script.rb:30>
 [~] Login script: Running the script.
 [~] Login script: Execution completed.
 [!] Client: ------------
 [!] Client: Queued request.
 [!] Client: ID#: 0
 [!] Client: Performer: nil
 [!] Client: URL: http://10.10.10.10/webui/charts/getactivethreatschartdata
 [!] Client: Method: get
 [!] Client: Params: {}
 [!] Client: Body: 
 [!] Client: Headers: {"Accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent"=>"Arachni/v1.1"}
 [!] Client: Cookies: {}
 [!] Client: Train?: false
 [!] Client: ------------
 [!] Client: ------------
 [!] Client: Got response for request ID#: 0
 [!] Client: Performer: nil
 [!] Client: Status: 0
 [!] Client: Code: couldnt_connect
 [!] Client: Message: Couldn't connect to server
 [!] Client: URL: http://10.10.10.10/webui/charts/getactivethreatschartdata
 [!] Client: Headers:

 [!] Client: Parsed headers: {}
 [!] Client: Request timed-out! -- ID# 0
 [!] Client: ------------
 [+] Login script: Login was successful.
 [~] Login script: Cookies set to:
 [!] 
 [!] Waiting on 4 plugins to finish:
 [!] uniformity, timing_attacks, discovery, healthmap
 [!] 
```

**Comment by Zapotek** [comment]
Hello,

You're not supposed to instantiate nor require anything, you are already provided with a browser via the `browser` variable.

Your script should instead look like this:

```
browser.goto "https://10.10.10.10/webui/login"
browser.text_field(:id => 'j_username-inputEl').send_keys 'admin'
browser.element(:id => 'j_password-inputEl').send_keys 'symantec'
browser.element(:xpath => "//*[text()='Sign In']").click
sleep(30)
Watir::Wait.until { b.text.include? 'System is Healthy' }
```

Give that a try and let me know how it works.

Also, I believe I'm already talking with a colleague of yours (probably different dept) regarding another matter.
It has to do with a bug when dealing with event-based URLs (using `data-url` and empty hrefs), so if you come across any similar crawling issues please let me know.

Cheers

**Comment by Gaurang033** [comment]
Hi Zapotek, 

I really appreciate the prompt reply, I tried as you suggested, however getting error in executing script.

Log: 

*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [~] Login script: System paused.
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/platform.rb:139: warning: Insecure world writable dir /root in PATH, mode 040777
 [~] Login script: Running the script.
 [-] Session: [NoMethodError] undefined method `goto' for nil:NilClass
 [-] Session: /usr/local/rvm/gems/ruby-2.0.0-p643/gems/arachni-1.1/components/plugins/login_script.rb:23:in `eval'
 [-] Session: /usr/local/rvm/gems/ruby-2.0.0-p643/gems/arachni-1.1/components/plugins/login_script.rb:23:in `eval'
 [-] Session: /usr/local/rvm/gems/ruby-2.0.0-p643/gems/arachni-1.1/components/plugins/login_script.rb:23:in `block in prepare'

**Comment by Zapotek** [comment]
It's better to use the [official packages](http://www.arachni-scanner.com/download/) unless you're planning on some sort of scripted scan or integration **and** you're sure that your environment provides all necessary dependencies.
In this case, your system is missing the PhantomJS executable which is the browser Arachni uses for DOM operations.

If for some reason you can't use the packages you can place the [phantomjs](https://code.google.com/p/phantomjs/downloads/list) executable in your `PATH`.

I strongly recommend that you use the packages though, otherwise you may run into unforeseen issues which I may not be able to provide support for.

**Comment by Gaurang033** [comment]
Hi Tasos,

I am using ruby 2.0 and I am not sure what you mean by offical package
however I have install arachni using following command

gem install arachni

Let me know if I need to download the package from suggest site and install
it.

however, I installed the PhantomJS and seems like script is working but
stuck in another problem. It's not able to open the webpage.

I tried google, which it's able to open (verified after taking screenshot),
however when it tries to open my site it just shows white page.

I think it's due to the *certificate error*, my site is having. Is there
any way to pass an option to ignore the certificate verification ?


Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Here are the official packages: http://www.arachni-scanner.com/download/
They are self-contained and include all dependencies, you better use those instead.

Certificate errors are by default ignored, although from the original debugging output you posted it looks as if requests usually time-out. You can enable debugging again to see what's going on.

**Comment by Gaurang033** [comment]
Hi,

I did as you suggest, removed the arachni gem and then install from the
location you suggested. However it's still not able to open the website.

I also uninstall the phantomjs gem. Attached is the screenshot.

Modified Login script.

browser.goto "https://10.219.170.155/webui/login"
#browser.goto "https://google.com"
sleep(15)
browser.screenshot.save 'screenshot.png'
browser.text_field(:id => 'j_username-inputEl').send_keys 'admin'
browser.element(:id => 'j_password-inputEl').send_keys 'symantec'
browser.element(:xpath => "//*[text()='Sign In']").click
sleep(15)
Watir::Wait.until { browser.text.include? 'System' }


following is the log.

2015-05-14T00:45:18 [DEBUG]      2 arg: "--logLevel=INFO"
2015-05-14T00:45:18 [DEBUG] Phantom - execute: Starting Remote WebDriver
mode
PhantomJS is launching GhostDriver...
2015-05-14T00:45:18 [DEBUG] WebPage - setupFrame ""
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/modules/fs.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/modules/system.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/modules/webpage.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/modules/webserver.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open:
":/ghostdriver/./hub_register.js" QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/ghostdriver/./logger.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open:
":/ghostdriver/./third_party/console++.js" QMap(("mode", QVariant(QString,
"r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/ghostdriver/./config.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] FileSystem - _open:
":/ghostdriver/./third_party/parseuri.js" QMap(("mode", QVariant(QString,
"r") ) )
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: "session.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: "inputs.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/status_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] FileSystem - _open: ":/ghostdriver/./errors.js"
QMap(("mode", QVariant(QString, "r") ) )
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/shutdown_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/session_manager_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/session_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/webelement_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs:
"request_handlers/router_request_handler.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: "webelementlocator.js"
2015-05-14T00:45:18 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
[INFO  - 2015-05-14T07:45:18.371Z] GhostDriver - Main - running on port
55660

[!] Browser: PhantomJS is ready.
[!] Session: Logging in via sequence: #<Proc:0x00000003d90ac8@
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:30>
[-] Session: [Watir::Exception::UnknownObjectException] unable to locate
element, using {:id=>"j_username-inputEl", :tag_name=>"input or textarea",
:type=>"(any text type)"}
[-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`eval'
[-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/watir-webdriver-0.6.9/lib/watir-webdriver/elements/element.rb:319:in
`send_keys'
[-] Session: (eval):5:in `block in prepare'
[-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`eval'
[-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`block in prepare'
[-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:32:in
`call'


Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Can you please retry using debug level 3 as before? I need to see what's going on at the HTTP level.

**Comment by Gaurang033** [comment]
Hi Tasos,

Following is the logs I am getting after setting love level to 5.  it's not
able to find the user name editbox as it seems like it fails to load the
UI.

Is there any way I can change the browser to other than PhantomJS. Coz it
has worked in Firefox.

 [!] Client: Parsed headers: {"Server"=>"Apache-Coyote/1.1",
"Content-Length"=>"0", "Date"=>"Thu, 14 May 2015 10:17:02 GMT"}
 [!] Client: ------------
 [-] Session: [Watir::Exception::UnknownObjectException] unable to locate
element, using {:id=>"j_username-inputEl", :tag_name=>"input or textarea",
:type=>"(any text type)"}
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`eval'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/watir-webdriver-0.6.9/lib/watir-webdriver/elements/element.rb:319:in
`send_keys'
 [-] Session: (eval):8:in `block in prepare'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`eval'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:23:in
`block in prepare'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:32:in
`call'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:32:in
`block in run'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:296:in
`call'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:296:in
`login_from_sequence'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:232:in
`block in login'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:231:in
`login'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:37:in
`run'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/plugin/manager.rb:75:in
`block (3 levels) in run'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/plugin/manager.rb:67:in
`block (2 levels) in run'
 [-] Session:
 [-] Session: Parent:
 [-] Session: Arachni::Session
 [-] Session:
 [-] Session: Block:
 [-] Session: #<Proc:0x000000038ab008@
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:231>
 [-] Session:
 [-] Session: Caller:
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/session.rb:231:in
`login'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/plugins/login_script.rb:37:in
`run'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/plugin/manager.rb:75:in
`block (3 levels) in run'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
 [-] Session:
/data/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/plugin/manager.rb:67:in
`block (2 levels) in run'
 [-] Session:
--------------------------------------------------------------------------------
 [-] Login script: A runtime error was encountered while executing the
login script.


Attached is the full log file.

Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Can you please show me the entire output from the beginning? It's missing the HTTP stuff.

**Comment by Zapotek** [comment]
From what little I can make out in the output, the server returned an empty response, this isn't an Arachni nor browser issue.
Is there any chance there's a firewall or something interfering with the scan? Something that blocks Arachni based on its user-agent perhaps?

**Comment by Gaurang033** [comment]
Hi Tasos,

yes, I checked and realize it has nothing to do with Arachni, I create a
new file where I creating phantomjs object, it also gives me the same
result. Not able to render the page.

So I wanted to ask you, is any way where I can change the driver other than
phantomjs. as with Firefox driver this script is working perfectly fine.



Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
In your case it may have been the SSL thing but when operating from Arachni insecure connections are allowed, so that may be the reason.
It would be very weird for PhantomJS to fail to render the page.

So, unless you show me the full debug output I'm afraid I won't be able to be of further help.

As for your question, only PhantomJS is supported.

**Comment by Gaurang033** [comment]
Hi Tasos,

I understand that it's a phantomjs Issue and not Arachani, what I am asking
is, do login_script provides supports Firefox or chrome driver.

as this script works fine with those driver.

Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
No, as I said, only PhantomJS is supported and in order to identify the problem I will need the full debug output.
I don't think that PhantomJS has a problem either but unless you can provide me with the information I requested I'm afraid I'll have to close this issue.

**Comment by Gaurang033** [comment]
let me know how should i generate full debut output, I have generated logs
with log level 5 and sent you.

Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Like I mentioned before, those logs were **not** sent in their entirety. I need the **full** output in order to diagnose this issue.
Simply rerun Arachni with a debug level of at least 3 and send me everything it outputs.

**Comment by Gaurang033** [comment]
Hi Tasos,

I am new to Arachni, would you please let me know how to collect all the
logs. I used following command, however I doubt it dumps all the log to
file.

arachni https://10.10.10.10/webui/login
--plugin=login_script:script=login.rb --session-check-pattern=/.*/
--session-check-url="
http://110.10.10.10/webui/charts/getactivethreatschartdata" --output-debug
3 > log_3.log


Gaurang Shah
Blog: qtp-help.blogspot.com
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Can you please set an appropriate check pattern, run it and then upload the **entire** `log_3.log` file somewhere?

**Comment by bstream** [comment]
@Gaurang033 You should run:

```
arachni https://10.10.10.10/webui/login
--plugin=login_script:script=login.rb --session-check-pattern=/.*/
--session-check-url="
http://110.10.10.10/webui/charts/getactivethreatschartdata" --output-debug
3 > log_3.log 2>&1
```
*2>&1 will make sure to redirect both stderr and stdout to the log file (log_3.log)*

You may also want to specify some checks like @Zapotek suggested while you are at it!

**Comment by Gaurang033** [comment]
Hi Guys,

Thanks for all you replied, however the Login issue has been resolved.

I changed the resolution of my computer and re-run the script, Now I am
able to login to the site. I take the screenshot after login to verify and
also I have verification step within script.

I think, My application needed some minimum resolution, weird that never
happened with Firefox driver.

So, Please go ahead and close this issue.

However before you close this issue, I would like to know if arachni has
some active forum where I can ask question like this.

Right now script is running successfully, however when I check *HTML report*,
under *sitemap *section, it doesn't show any URL which are accessible by
authentication only. Which makes my doubt if script has at all crawled
pages behind Authentication.

However if you will see my *login script, session-check-pattern,
session-check-url, * It is provided such that, it will match only if
Authentication has been successful.

Gaurang Shah
Blog: AutomationTesting.co.in <http://automationtesting.co.in>
Mobile: +91 7387756556

On Thu, May 21, 2015 at 12:32 PM, Andreas Broström <notifications@github.com

**Comment by Zapotek** [comment]
You can set the browser's viewport size via the following options: 

* https://github.com/Arachni/arachni/wiki/Command-line-user-interface#browser-cluster-screen-width
* https://github.com/Arachni/arachni/wiki/Command-line-user-interface#browser-cluster-screen-height

For support you can use the [support portal](http://support.arachni-scanner.com).

As for the success of the login, the pattern you've set will match anything and from what I can tell you haven't [excluded](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#scope-exclude-pattern) any resources which might cause a logout.
(I'm not sure if you tried to attach any files to your reply, GitHub doesn't suppor tthat.)

**Comment by Gaurang033** [comment]
Hi,

Following is the command I am using
arachni https://10.219.170.155/webui/login
--plugin=login_script:script=login.rb --session-check-pattern=/.*Gaurang.*/
--session-check-url="
https://10.219.170.155/webui/generic/getcurrentuser?_dc=1431833114991"
--scope-https-only --scope-dom-depth-limit=20 --audit-links
--report-save-path=test1.afr --scope-extend-path=paths

And following is what I get in output.

 [+] Login was successful.
 [~] Cookies set to:
 [~]     * JSESSIONID = BCA3309C979781AC5B069090F50D810E

I have few URL added into the paths file as well, which requires
authentication. It appears in the logs however it doesn't appear in the
sitemap.


Gaurang Shah
Blog: AutomationTesting.co.in <http://automationtesting.co.in>
Mobile: +91 7387756556

**Comment by Gaurang033** [comment]
Sure, this would be good idea.

Gaurang Shah
Blog: AutomationTesting.co.in <http://automationtesting.co.in>
Mobile: +91 7387756556

**Comment by Zapotek** [comment]
Haha you replied to the wrong discussion: http://support.arachni-scanner.com/discussions/problems/3787-arachni-for-rest-based-websites
