### ISSUE TITLE
DOM rendering with browser_cluster - is it possible?

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#588]
By proxying the scanner I noticed that most requests never result in the DOM being rendered.  The site I am scanning is almost 100% Ajax, so each request returns a response that has a bunch of API calls that create the DOM.  The API's are never hit by the scanner and it seems as though the PhantomJS browsers never make any Ajax calls.  Is this by design or is there a special way to configure it to render the DOM?

**Comment by sbehrens** [comment]
The site also leverages React.js.

**Comment by Zapotek** [comment]
There's either a bug somewhere or something I haven't accounted for, care to send me the details over e-mail?

**Comment by sbehrens** [comment]
Sure, thanks.
