### ISSUE TITLE
Multi CPU support

### ISSUE THREAD

**Issue by myrinx** [Arachni/arachni#592]
Hi,

It seems in my Debian 7 64bit environment with 2 cores that Arachni limits itself to using only 1 of the available cores, and slows down a lot once it reaches the 100% cpu mark. 

Is this something i can fix myself or would it be possible to see what can be done to utlize all available resources on the system? Im' on the experimental branch.

THanks!

**Comment by Zapotek** [comment]
You could try using multiple processes for the scan via `arachni_multi`.
That feature hasn't received a lot of testing though since it's rarely enabled by users.

Occasional CPU spikes are normal though, what sort of utilizations are you seeing over time?

**Comment by myrinx** [comment]
i'm running the command line ./arachni right now.

It's a steady 100% CPU over 1 core for the last 10 hours straight ;)

**Comment by Zapotek** [comment]
Ok that's weird.
Could you please send me the URL via e-mail if possible? I'd like to take a closer look.

**Comment by myrinx** [comment]
sent

**Comment by Zapotek** [comment]
I was playing with the caches and just realized that what you mentioned could also happen if many thousands of very different and complex URLs were suddenly presented to the system.

Usually URI parsing and other aspects of the system are cached since it's the same data over and over.

**Comment by myrinx** [comment]
That is very likely indeed. Sounds like our scenario
Op 28 jun. 2015 20:57 schreef "Tasos Laskos" <notifications@github.com>:

**Comment by Zapotek** [comment]
OK, it so happens that I'm working on some optimizations on the subject.
I need to do some more testing but they'll probably be merged into the experimental branch in a few days, you'll then be able to try the nightlies and see if they help.

Still, caching can only get you so far, it's a few thousand entries for each operation and it only helps if the data are similar, we'll have to see how it goes.

**Comment by Zapotek** [comment]
@myrinx Could you send me some samples of the resource with the URLs we're talking about?

**Comment by Zapotek** [comment]
This conversation has been moved to e-mail.
