### ISSUE TITLE
Bug in Cookie parser

### ISSUE THREAD

**Issue by tunnelshade** [Arachni/arachni#593]
Application is returning the following cookie

```
Set-Cookie: rsession="06142010_0%3Ae275d357943e9a2de0a5ea87050da87596fcba0451aedb53905480545e7195968f82fec971b709f4bba6271404179fc97909c7fd23766b68eb7e70bce5f9b6bd";
```

But subsequent requests from Arachni are sent with the following cookie

```
Cookie: rsession=%2206142010_0:e275d357943e9a2de0a5ea87050da87596fcba0451aedb53905480545e7195968f82fec971b709f4bba6271404179fc97909c7fd23766b68eb7e70bce5f9b6bd%22
```

The quotes are getting url encoded and the encoding inside the cookie value is getting decoded.

Using the self sufficient package for Linux x86 from downloads page. The only plugin being used is login script.

**Comment by Zapotek** [comment]
Could you please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) real quick and see if the issues persists?

Cheers

**Comment by Zapotek** [comment]
Found the issue, this cookie was returned by the browser and even though it returns it as a parsed object, it doesn't go so far as to properly normalize the value, so the quotes remained.

Fixing it now.

**Comment by Zapotek** [comment]
Done, pushing a nightly for you to test.

**Comment by tunnelshade** [comment]
Awesome! That was a really quick fix. Thanks. I will test it

**Comment by Zapotek** [comment]
No worries, I'll let you know once it's up.

**Comment by tunnelshade** [comment]
You should consider an IRC channel. It will be active and useful

**Comment by Zapotek** [comment]
It'll probably just be people asking what the default credentials are for the WebUI.

Nightlies are up btw, give them a try: http://downloads.arachni-scanner.com/nightlies/

**Comment by tunnelshade** [comment]
I think it is still sending the cookies with urlencoded quotes. I just saw in an intercept proxy

![screen shot 2015-06-17 at 9 49 04 pm](https://cloud.githubusercontent.com/assets/2751016/8212701/bdee99ba-153a-11e5-9005-ea9593a271e4.png)

**Comment by tunnelshade** [comment]
Confirmed, this is still happening. Using login script.

```
rsession=%2205272004_0%3A945426b376361f853950b74ff6e2a4625f195f4019a50a5839845731220655a45bde211b04e4783d3f87a9385a4ec0c2a671e78dca1717aa%22
```

**Comment by Zapotek** [comment]
Hm, can you please set the debug output to 3?

**Comment by Zapotek** [comment]
Also, could you please show me your login script?

**Comment by tunnelshade** [comment]
Login Script

```
browser.goto 'https://something.com/login.do'

sleep(15)
form = browser.form( name: 'loginForm' )
form.text_field( name: 'loginName' ).set 'testbed'
form.submit

sleep(5)

form = browser.form( name: 'loginForm' )
form.text_field( name: 'answer').set '1'
form.submit

sleep(5)

form = browser.form( name: 'loginForm' )
form.text_field( id: 'password').set 'Arachni@123'
form.submit

sleep(5)


# You can also configure the session check from the script, dynamically,
# if you don't want to set static options via the user interface.
framework.options.session.check_url     = browser.url
framework.options.session.check_pattern = /Dashboard/
```

All the requests that are supposed to happen are happening correctly. The final response and the next redirect

```
HTTP/1.1 302 Moved Temporarily
X-Powered-By: Unknown
X-XSS-Protection: 1
Pragma: no-cache
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache
Cache-Control: no-store
SET-COOKIE: rsession="05272004_0%3Aa5537d0fb6e67a9b40e90ca2bec9a3edf226e1345d795529f4501d7b78c602b2e6cdda69a74c35f45e9c4c7d18cf7d9814ecdca3390af20b"; Version=1; Path=/; domain=.something.com;  Secure;  HttpOnly
Set-Cookie: Locale=en_US; Version=1; Domain=.something.com; Path=/; Secure
Set-Cookie: nodessionid=6339922ECCC94BACC57A8CEC1B00CF39; Version=1; Domain=.something.com; Path=/; Secure
Location: https://something.com/somelocation/home.somelocation.do?c=key%3AOevaEut9UHQdrWOT9sKKA3BAEuw%3D&l=u:s
Content-Language: en-US
Content-Length: 0
Date: Thu, 18 Jun 2015 02:22:22 GMT
Server: Unknown


 [!] Client: Parsed headers: {"X-Powered-By"=>"Unknown", "X-Xss-Protection"=>"1", "Pragma"=>"no-cache", "Expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "Cache-Control"=>["no-cache", "no-store"], "Set-Cookie"=>["rsession=\"05272004_0%3Aa5537d0fb6e67a9b40e90ca2bec9a3edf226e1345d795529f4501d7b78c602b2e6cdda69a74c35f45e9c4c7d18cf7d9814ecdca3390af20b\"; Version=1; Path=/; domain=.something.com;  Secure;  HttpOnly", ["Locale=en_US; Version=1; Domain=.something.com; Path=/; Secure", "nodessionid=6339922ECCC94BACC57A8CEC1B00CF39; Version=1; Domain=.something.com; Path=/; Secure"]], "Location"=>"https://something.com/somelocation/home.somelocation.do?c=key%3AOevaEut9UHQdrWOT9sKKA3BAEuw%3D&l=u:s", "Content-Language"=>"en-US", "Content-Length"=>"0", "Date"=>"Thu, 18 Jun 2015 02:22:22 GMT", "Server"=>"Unknown"}
 [!] Client: ------------
 [!] Client: ------------
 [!] Client: Queued request.
 [!] Client: ID#: 11
 [!] Client: Performer: #<Arachni::Browser pid=13014 last-url=nil transitions=0>
 [!] Client: URL: https://something.com/somelocation/home.somelocation.do?c=key:OevaEut9UHQdrWOT9sKKA3BAEuw=&l=u:s
 [!] Client: Method: get
 [!] Client: Params: {}
 [!] Client: Body:
 [!] Client: Headers: {"Cache-Control"=>"no-cache", "Pragma"=>"no-cache", "Origin"=>"https://something.com", "User-Agent"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10104) AppleWebKit/537.36 (KHTML like Gecko) Chrome/38.0.2125.122 Safari/537.36", "Accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Referer"=>"https://something.com/somelocation/mfaloginflow.somelocation.do", "Cookie"=>"JSESSIONID=6339922ECCC94BACC57A8CEC1B00CF39; jsdk=1.0.0; scriptable=1; rsession=\"05272004_0%3Aa5537d0fb6e67a9b40e90ca2bec9a3edf226e1345d795529f4501d7b78c602b2e6cdda69a74c35f45e9c4c7d18cf7d9814ecdca3390af20b\"; Locale=en_US; nodessionid=6339922ECCC94BACC57A8CEC1B00CF39", "Accept-Encoding"=>"gzip", "Accept-Language"=>"en-US,*", "Host"=>"something.com"}
 [!] Client: Cookies: {}
 [!] Client: Train?: false
 [!] Client: Fingerprint?: true
 [!] Client: ------------
 [!] Client: ------------
 [!] Client: Got response for request ID#: 11
 [!] Client: Performer: #<Arachni::Browser pid=13014 last-url=nil transitions=0>
 [!] Client: Status: 302
 [!] Client: Code: ok
 [!] Client: Message: No error
 [!] Client: URL: https://something.com/somelocation/home.somelocation.do?c=key:OevaEut9UHQdrWOT9sKKA3BAEuw=&l=u:s
 [!] Client: Headers:
HTTP/1.1 302 Moved Temporarily
X-Powered-By: Unknown
X-XSS-Protection: 1
SET-COOKIE: rsession="123321"; Version=1; Path=/; domain=.something.com;  Secure;  HttpOnly
Set-Cookie: Locale=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
Location: https://something.com/somelocation/somelocation.do?errorCode=invalidLogin
Content-Language: en-US
Content-Length: 0
Date: Thu, 18 Jun 2015 02:22:22 GMT
Server: Unknown
```

The third step of login succeeds and the application sends the rsession cookie and a redirect location. But arachni gets the redirect with the wrong value of the cookie (i.e url encoding the quotes)

**Comment by Zapotek** [comment]
You cut out the good part, can you show me the output up to the point the issue is visible?
Up to the request with the wrong cookie.

**Comment by tunnelshade** [comment]
The last request shown is the bad part. See the location header

```
Location: https://something.com/somelocation/somelocation.do?errorCode=invalidLogin
```

**Comment by Zapotek** [comment]
Hm, so even though the debugging output shows the cookies properly formatted, something changes between the time they're queued and performed.

Looking into it.

**Comment by tunnelshade** [comment]
Yes, somewhere in between the cookie is getting urlencoded

**Comment by Zapotek** [comment]
Trying to see if I can repro with a custom server, if not, I'll update the debugging output and push a nightly so that you can try it again and hopefully get some more info.

**Comment by Zapotek** [comment]
Btw, just to clarify something, the request cookies will always be URL encoded, unless the request is performed by the browser (which sometimes has to do its own internal handling).
Arachni in general will try to only send v0 cookies, since all servers should support those.

I did manage to reproduce the issue though, it only happens when using the `Watir` interface directly, instead of the `Arachni::Browser` or `Arachni::HTTP::Client`.

Not sure why yet, but I should be able to fix it now that I know how to reproduce it.

**Comment by tunnelshade** [comment]
Sure. Cookie value is urlencoded but the quotes wrapping the value?

**Comment by Zapotek** [comment]
The quotes are there so that you won't have to encode the value. I'm not sure why your cookie has both though.

**Comment by Zapotek** [comment]
I think I fixed it, pushing nightlies.

**Comment by tunnelshade** [comment]
Waiting for the linux ones, only darwin ones are up as of now

**Comment by Zapotek** [comment]
Still uploading. :)

**Comment by Zapotek** [comment]
Done.

**Comment by tunnelshade** [comment]
Done. This bug is fixed. I can confirm

**Comment by Zapotek** [comment]
Yay, good stuff. Thanks for all the feedback man. :)

Back to preparing the v1.2 release I go.
