### ISSUE TITLE
Cookies are not being returned as they are recieved

### ISSUE THREAD

**Issue by tunnelshade** [Arachni/arachni#595]
From previous issues, you might be having enough context of the application. Arachni recieves

```
SET-COOKIE: rsession="somethingsomethignurlencodingsomething"
```

In the subsequent requests, the cookie is being sent as 

```
Cookie: rsession=somethingsomethingurlencodingsomething
```

I understand that urlencoding is present so quotes are not required, but I think returning cookies just the way they are received will make more sense?

**Comment by Zapotek** [comment]
This will just add specialized handling and create complications, I'd rather use a cookie format that is understood by all server and not change behavior needlessly.
Unless it becomes a problem of course, then I'll reconsider.

Has it become a problem?

**Comment by tunnelshade** [comment]
How about sending the cookie just as it is received?

**Comment by Zapotek** [comment]
This is not an echo operation. Everything is parsed and normalized prior to being stored and then formatted prior to being submitted.

**Comment by tunnelshade** [comment]
Yes, I understand. I was just reporting what I thought was legible. Thanks

**Comment by Zapotek** [comment]
No I get it, it would certainly be more convenient sometimes from the user perspective. But this is protocol data, they don't have to legible my humans and I'd rather keep things as simple as possible code-wise.

Cheers

**Comment by tunnelshade** [comment]
Sure, I get the maintenance part. I too maintain a framework. Anyways great tool :)
