### ISSUE TITLE
Invalid license

### ISSUE THREAD

**Issue by joepie91** [Arachni/arachni#596]
The `LICENSE.md` file states the following:

> Cases that include commercialization of Arachni require a commercial, non-free license. Otherwise, the system can be used under the terms of Apache License v2.0, found at the bottom of this document.

However, this isn't possible. The Apache license is a *public license*, and *by definition* applies to anybody who wishes to use it. No further restrictions can be set, beyond the restrictions that exist within the license itself. The Apache license does not include a commercial use clause.

Furthermore, the site states the following:

> Arachni is an __Open Source__, feature-full, modular, high-performance Ruby framework aimed towards helping penetration testers and administrators evaluate the security of web applications.

This is also incorrect; to be considered "open-source", the license of software must comply with the [OSD](http://opensource.org/osd-annotated). The commercial use clause for Arachni, *even* if the Apache license were to be dropped in favour of a custom license, would violate point 6 of the OSD, and therefore make Arachni not open-source.

Please do note that right now, under the current dual licensing scheme, *anybody* can use Arachni under the Apache license, whether for commercial use or not. This is irrevocable, per Apache 2.0 license.

**Comment by Zapotek** [comment]
I'm closing this since this tracker is for system issues, but I'm actually working to resolve this matter.
I've heard different opinions on the subject, which is why it has taken me a while to sort this out, but a custom "public source" license is in the works and will resolve the situation.

Cheers
