### ISSUE TITLE
Error in Arachni::Checks::BackupFiles: Too many open files @ rb_sysopen

### ISSUE THREAD

**Issue by magnologan** [Arachni/arachni#601]
Hi,

I got this error message in Arachni yesterday. Not sure what it means. The command used was this one:

./arachni --scope-directory-depth-limit=2 --scope-page-limit=100  --scope-dom-depth-limit=1 --scope-auto-redundant=2 --scope-exclude-binaries --http-request-timeout=5000 --http-request-redirect-limit=1 --browser-cluster-pool-size=10 --checks=* --http-authentication-username=xxx --http-authentication-password=xxx http://www.website.com

 Error in Arachni::Checks::BackupFiles: Too many open files @ rb_sysopen - /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/components/checks/passive/backup_files//formats.txt
 [-] [Errno::EMFILE] Too many open files @ rb_sysopen - /Users/.../arachni-1.1-0.5.7/bin/../system/logs/framework/error-806.log
 [-] [Errno::EMFILE] Too many open files @ rb_sysopen - /Users/.../arachni-1.1-0.5.7/bin/../system/logs/framework/error-806.log
/Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:77:in `initialize': Too many open files @ rb_sysopen - /Users/.../arachni-1.1-0.5.7/bin/../system/logs/framework/error-806.log (Errno::EMFILE)
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:77:in `open'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:77:in `error_log_fd'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:147:in `log_error'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:95:in `print_error'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/output.rb:106:in `print_exception'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/framework.rb:111:in `rescue in run'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/framework.rb:59:in `run'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/ui/cli/framework.rb:49:in `initialize'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/bin/arachni:12:in `new'
	from /Users/.../arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/bin/arachni:12:in `<top (required)>'
	from /Users/.../arachni-1.1-0.5.7/bin/../system/arachni-ui-web/bin/arachni:16:in `load'
	from /Users/.../arachni-1.1-0.5.7/bin/../system/arachni-ui-web/bin/arachni:16:in `<main>'

**Comment by Zapotek** [comment]
Hello,

You'll need to increase your open file limit, the best way to go about this depends on your distro, a google search should point you to the right direction.

Cheers

**Comment by magnologan** [comment]
Sorry, my bad! Thank you! =)

Att / Best Regards,

Magno Rodrigues, Security+
CEO - Katana Security
www.katanasec.net
83 99127 5727
