### ISSUE TITLE
Auto-redundancy does not recognize timestamp parameters

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#602]
I have auto-redundancy set to 4.  There is a timestamp parameter on most pages, but the scanner keeps trying to crawl/test these pages even though just the timestamp is changing.  See screenshot below:

![](http://i.snag.gy/UtfSe.jpg)

**Comment by Zapotek** [comment]
Where are those entries from?

**Comment by sbehrens** [comment]
The path is also identical in every request only the timestamp parameter changes. That screenshot is from the sitemap link in the HTML report.

**Comment by sbehrens** [comment]
Here is a screenshot of the paths:

![](http://i.snag.gy/1dgLt.jpg)

**Comment by Zapotek** [comment]
I get the feeling these resources are requested by the browser, which is cool, but if the redundancy setting isn't enforced when the resources are pushed to the Framework that's a bug.
I'll have a look at it and keep you posted.

**Comment by sbehrens** [comment]
Got it, so it's possible that those endpoints weren't actually tested?
They are all for API (so definitely requested via resource loads/Ajax).

**Comment by sbehrens** [comment]
The API in particular returns information on content descriptions for movie
titles.

**Comment by Zapotek** [comment]
I'm not 100% sure yet, in order for them to be in the sitemap they must have passed through the part of the system that audits pages, but I can still see the redundant settings being enforced prior to that.
I'll need to do some more testing.

**Comment by Zapotek** [comment]
Are there any dynamic input names in there? That would explain it.

**Comment by sbehrens** [comment]
I don't believe so, there is just a timestamp that is appended.  NOt sure if this bug is related but, the sitemap is showing a bunch of requests to things I am explicitly listing as redundant_path_patterns.

As an example, here are a few rules I have created:

```
scope:
  redundant_path_patterns:
    "(?-mix:api/desktop/account)": '5'
    "(?-mix:api/desktop/notifications/load)": '5'
    "(?-mix:api/ecapi/account/myserviceinfo)": '5'
    "(?-mix:api/ecapi/account/v2/payment)": '5'
```

When Viewing scan results, here is what I see (few screenshots):

![](http://i.snag.gy/o4ffT.jpg) - showing > 30 calls to api/desktop/account

![](http://i.snag.gy/16ZZt.jpg) - showing > 300 calls to the api/desktop/notifications/load.story page

It seems as though auto-redundancy and redundant_path_patterns aren't being validated.

**Comment by Zapotek** [comment]
The rules seem to work fine in general and the regexps are matched just like any other, i.e. partial matches count.
Can you show me the entire paths please?

Thing is, the browsers will respect the redundancy rules but not decrease the counter to make sure that the functionality of the page remains intact.
However, when the pages are pushed to the Framework and the same scope check is applied, then the counters will be decreased.

This can explain the requests, but not why the scope rules aren't being reflected in the sitemap.

Let's start by showing me the full paths, preferably as pasted text, and we'll go from there.

**Comment by Zapotek** [comment]
Btw, I was wrong, the sitemap gets updated with requests the browser had performed, so it's a matter of who got there first, the framework audit or the browser operations.
(I've removed this to avoid confusion in the future., the sitemap got a big cleanup in general -- you won't see audit payloads in there either, at least not as many as before.)

Back to the issue at hand, I highly doubt that any of those pages were audited more times than the redundancy limits allowed.

So, closing this due to lack of feedback and because couldn't reproduce it.
Feel free to re-open it.
