### ISSUE TITLE
ERR_CERT_COMMON_NAME_INVALID in proxy

### ISSUE THREAD

**Issue by AmesCornish** [Arachni/arachni#604]
The proxy seems to work fine with https://google.com, but breaks with the site I'm testing, https://platform.dnanexus.com. After booting the proxy, hitting record, then navigating to the site, I get:

![screenshot from 2015-07-18 13 12 12](https://cloud.githubusercontent.com/assets/3673697/8763400/a027d60e-2d4e-11e5-87ab-340fa5603f1d.png)

I am using Chrome (Version 43.0.2357.134 (64-bit)) on Ubuntu 15.04.  I have added the arachni ssl-interceptor cert to Chrome as verifying web sites, and it seems to work fine with https://google.com.

**Comment by AmesCornish** [comment]
Here's the cert that is being rejected:

Subject: staging.dnanexus.com
Issuer: Arachni
Expires on: Jul 17, 2016
Current date: Jul 18, 2015
PEM encoded chain: -----BEGIN CERTIFICATE-----
MIIGtDCCBJygAwIBAgIDDp14MA0GCSqGSIb3DQEBBQUAMIGPMQswCQYDVQQGEwJH
UjEPMA0GA1UECAwGQXR0aWthMQ8wDQYDVQQHDAZBdGhlbnMxEDAOBgNVBAoMB0Fy
YWNobmkxDjAMBgNVBAsMBVByb3h5MRAwDgYDVQQDDAdBcmFjaG5pMSowKAYJKoZI
hvcNAQkBFhthcmFjaG5pQGFyYWNobmktc2Nhbm5lci5jb20wHhcNMTUwNzE4MjAw
ODU0WhcNMTYwNzE3MjAwODU0WjCBjzEdMBsGA1UEAwwUc3RhZ2luZy5kbmFuZXh1
cy5jb20xHTAbBgNVHREMFHN0YWdpbmcuZG5hbmV4dXMuY29tMRAwDgYDVQQKDAdB
cmFjaG5pMQ4wDAYDVQQLDAVQcm94eTEPMA0GA1UEBwwGQXRoZW5zMQ8wDQYDVQQI
DAZBdHRpa2ExCzAJBgNVBAYTAkdSMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAsHGDdEf3xI4yZyDte2t0gwz38JrhW8Q2QbNFReyasXR2YNI+sEDZpYka
m05IpNtWHDr3ehHsf7HO6EmFGtztOp/6P6vRx2PeG1tKHyM3mj30kLrU+2BWnYng
bIAzZdR32k6+j/Y/jxnam02F2Gug0pj+kDeWwrYfo907GUZJ6s/+hlYZ7c5NAfYx
4Fupi8hU59D9CGT1v1P3gtjKInsHHP9L+8mJD5Ue/k6eKo/Ny19IONpwM9ev3p0d
Z/G6qYzacJ0l+d8oNiAOUWNtMk7p05GQhNIIALcuL62XFYp/JzUw6lt4/vWQcf0j
/Bp4r1x0By9QlCcjAouadoL0uWBFbSc6zig9SFNMToS+UDsJIToaLi/klzmAUlo9
rU9Mn7gbphuXYCTxPJpowS+t9gXrOh/RKhZ1favQjL0baGOLd+9sz+rSBe7U5cav
NJ4wD9RglyVSmMlvp9uhk5kRf42iZx5DoTzdTlfbq8Uxzg4J/Lb32XsdGG8MDpzQ
55R6Q/UtxufvloUSSVkm39f1IDilRC6fc/MgNlLo1RN+q+nmbi9zsfuuCx6pjboq
m+r8xFvaKcPqpTfBZZqOn19P538Wll++JJfH/NkEtph8NBLSuPA6KkQyUIlYD/YJ
LnKoEfp/zubCLtdShHJzemEqPzIpECuQ61Tz+egZdIyaPvrcXc8CAwEAAaOCARUw
ggERMAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYE
FDjZ0+od72Wb46ZLyQ6MV42OClJDMIG8BgNVHSMEgbQwgbGAFG+ZHuAaoh9NAHQb
KDCAjbYrKvVsoYGVpIGSMIGPMQswCQYDVQQGEwJHUjEPMA0GA1UECAwGQXR0aWth
MQ8wDQYDVQQHDAZBdGhlbnMxEDAOBgNVBAoMB0FyYWNobmkxDjAMBgNVBAsMBVBy
b3h5MRAwDgYDVQQDDAdBcmFjaG5pMSowKAYJKoZIhvcNAQkBFhthcmFjaG5pQGFy
YWNobmktc2Nhbm5lci5jb22CAQAwDgYDVR0PAQH/BAQDAgTwMA0GCSqGSIb3DQEB
BQUAA4ICAQAqkcja03l0H5rQh0+NNkqIxHT8dOzxr7h8ceG1WeJ5l1btqGqkLtiT
xKT8CqLrGL4XvVim0VwlkPcRoQGljsI3ssQNwPBYYGy67Nu3lSrUaYgwQckF4vL4
Rdl0j9s22Ewe1UH13JZMJQ7X6VJqItm5h5W5lWmbARFBFgHZqMIYEWuiQsVRAXxt
AiQqJeiU1W7CU4bmY1Hs0r4dsR2gPX8jkFIO66XrHTxBokym8L7C05Y4ne6fPOoT
C3utfad3uBTNeBppvqWP4Ylj9l1hHlYXqiiT+5cnmTO0+l9mKa9TMR9Rcv6/I+Ur
HGGl0u1+X49NkyosH89LcIoi9KMES+ju7vbbM2LSm3VH1S3986gCbuBbIyTFo+0W
61gkea5KxT5sqAIu7lerlrB117nFlnM8DcJaB8sOeWiGFQ+J6zrq3lTOHCayzDay
WnsRfUohAoBrQCf/+Okgd4mrLf7n781xxawMLnF3p8C05HZOA5kUmsHb2nMTddni
TetbVO2v1sngq9La4mXqgCaEo7rJDPmxVpdw84qW9T2SPv4RKSaqccUvRFuarDpS
Yv3ikOUzz0PcFxCXyB0wTzzTuPYvdzqrUqbyknSJZq5EZxo+6EhsIgK7LznSEds6
H8MOiUmUrQfH16YMR9vFKymiisLvZWXwCyxwNCuEdpFK6uiPGEh2vA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIF6zCCA9OgAwIBAgIBADANBgkqhkiG9w0BAQUFADCBjzELMAkGA1UEBhMCR1Ix
DzANBgNVBAgMBkF0dGlrYTEPMA0GA1UEBwwGQXRoZW5zMRAwDgYDVQQKDAdBcmFj
aG5pMQ4wDAYDVQQLDAVQcm94eTEQMA4GA1UEAwwHQXJhY2huaTEqMCgGCSqGSIb3
DQEJARYbYXJhY2huaUBhcmFjaG5pLXNjYW5uZXIuY29tMB4XDTE1MDYxNDAyMDgz
MVoXDTI1MDYxMTAyMDgzMVowgY8xCzAJBgNVBAYTAkdSMQ8wDQYDVQQIDAZBdHRp
a2ExDzANBgNVBAcMBkF0aGVuczEQMA4GA1UECgwHQXJhY2huaTEOMAwGA1UECwwF
UHJveHkxEDAOBgNVBAMMB0FyYWNobmkxKjAoBgkqhkiG9w0BCQEWG2FyYWNobmlA
YXJhY2huaS1zY2FubmVyLmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
ggIBAKfH1iQiuG8zYS514F8zZLp8//00gPIML7+wcJn4cw2iN+yEix6RuZEIzqva
TfC4H6lZTyUhsoGZCeYAzzH9BMri/9uHJF+4worPfVKYIsm3TnMOVYoIC1kP1/Gj
Y1ih8KI/3baw0pddtJJeQ5/GjDaxx4+ynY4ZxrNcFmbTYXSrPcd62V/D4+edVnLi
uQsUezWYx7gNFiAuPRtlgJVBwzRoPV+Fh7Es2/SfmNSfGBCCYOpj4Fh0GOv7pSV0
9TeF1W/XqDoq/eZ7RzLXoFK0Rz70/22MnFWAIdEUHZqwh3ktndNEK2QHq9FRGUx8
cUlXVAJgYv8tTErYVBltKIi2qgbnkh0Rb+rT2OkgmSL9lg0PwpXChMeSo6o6riC7
5a8PQi6OmIseY742QYmBXApXDHtSzaY8onHUvqgxFrFpP0Bmca3AoF6kWQfXfRwS
ClMLwfBBDVeb+Tt97MO1G4m2VEW6c7o9H1t4td55LGslUzfJrmFe99vjAtdRTVqG
t3qDjbYi5VpE9kIyKcPHZkSKelMQ4VO1qB14CdaK/3ufqHTk7Ro2hKgstKDqnTCF
R7Qb9yXFsb1QyNtW8898T5mQm0HWQxdkaxcodizVjY5inHgqNwPa7A469EYFm5in
dLSOQtdPOV4q+y5lfhA2MkE3pRdSZPpnTqCEkSVVoKfdVlftAgMBAAGjUDBOMB0G
A1UdDgQWBBRvmR7gGqIfTQB0GygwgI22Kyr1bDAfBgNVHSMEGDAWgBRvmR7gGqIf
TQB0GygwgI22Kyr1bDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4ICAQAx
g+ZjxJZXW1dYkc9ItXwAZba7oQJapLPu1iWCFy5cU13gck2MwDqfaDApNdr+erHg
WN7N+smMO+x3+lZZptzTfc6g/hBthBBAnetj8CUehjnWCo3aBGgVLE/mIEyHyFym
JX6xgcNYpvEzHT2o3Kmu/dAHCqY/3P9NtGJMhf7fy/Zz72tGY+ZTlthFSGWOjIEV
KXTtYnRUKmIRBLMacZmrJKIZCp/qGVSnFh9yjxHTWPNXXngGMxF9ItsFbdakjefn
hi2sHqns6/YbMaD2wK42dRQH1wH66DCGbyDPQO2j8iGK1q4Ggps+mGNYNBzMSAO/
ybdGRLQNq8ag7RXr/tNp/jYHopS/Ga0+3bOnCKf6MXNOolknSZhsOo16BWKDRd+d
m9ZTlro9AQr9+jdychG41IQNHXySrC5F1jLtzpEE5CJZIXkEFNYRcO9HMByJ3qwG
759oYcMklwhU+NSC5qXpD2Z9KGf5rc0HmoO6OyD4T8hnQXkuAqoIN/NBg6YSNisN
H2C2gbl+taRLt0/RVCiacylo5pl3XSZuQxtGaQl55gRXQDPnlfB2CtIrV44gHZOJ
88s+Ld9h44aoT2rWbLld6dU5ElZXWEJOim+aYKJewxX7PwEHn4iCpvMLu+4jXH3j
OkDTHheVJkxyhTDQ43ebg3/qi4yFaQyAHk3bQItwCw==
-----END CERTIFICATE-----

**Comment by AmesCornish** [comment]
Under "advanced" on the error screen, I get the following with an odd comment about HSTS.  Maybe relevant?

=============
platform.dnanexus.com normally uses encryption to protect your information. When Chrome tried to connect to platform.dnanexus.com this time, the website sent back unusual and incorrect credentials. Either an attacker is trying to pretend to be platform.dnanexus.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit platform.dnanexus.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
==============

**Comment by Zapotek** [comment]
It should have worked after adding Arachni's cert, can you try with Firefox? It should work there.
I'm not sure if Chrome is too strict or if my cert contains invalid data but I'll look into it.

**Comment by AmesCornish** [comment]
Here's a similar error with Firefox.  It seems to have something to do with requests to multiple sites, and it's trying to use the cert for a previous site, which fails:

![screenshot from 2015-07-18 16 23 20](https://cloud.githubusercontent.com/assets/3673697/8763959/e569bfe4-2d6b-11e5-814e-b5ea75f03d97.png)

**Comment by Zapotek** [comment]
Hm, checking it out now, thanks for the feedback man.

**Comment by Zapotek** [comment]
If you expand the "I understand the risks" dialog and then confirm the exception does it not work?

**Comment by Zapotek** [comment]
This should do it. :)

I'll let you know once the fresh nightlies are up so you can test it.

**Comment by Zapotek** [comment]
Nightlies are up, they should work now: http://downloads.arachni-scanner.com/nightlies/

Let me know how it goes.

**Comment by AmesCornish** [comment]
Yes, that seems to have fixed the cert issue.  Thanks!

- Ames

--
Ames Cornish  ~  http://montebellopartners.com/
650-533-0835  ~  ames@montebellopartners.com
