### ISSUE TITLE
The full report for this scan could not be retrieved due to an unknown error.

### ISSUE THREAD

**Issue by alvinhsian** [Arachni/arachni#609]
After scanned the test site (http://testhtml5.vulnweb.com/), the charts can not show.

**Comment by Zapotek** [comment]
Can you please submit this issue to the [appropriate issue tracker](https://github.com/Arachni/arachni-ui-web/issues)? This is for the framework only.
Also, could you include any errors along with information about your system (OS, RAM, CPU, etc.)?

Thanks
