### ISSUE TITLE
Arachni hangs with Pending jobs: 1

### ISSUE THREAD

**Issue by zubinix** [Arachni/arachni#611]
My Arachni run did not complete last night. The last thing printed in the logs is:

```
[!] BrowserCluster Worker#28360340: Finished: #<Arachni::BrowserCluster::Jobs::BrowserProvider:70263633728560 callback=>
[!] BrowserCluster: Job done: #<Arachni::BrowserCluster::Jobs::BrowserProvider:70263633728560 callback=>
[~] BrowserCluster: Pending jobs: 1
```

The ruby process and phantomjs processes are still running:

```
ruby/home/ubuntu/TestArea/arachni/bin/../system/arachni-ui-web/bin/arachni--output-debug--output-verbose--report-save-path=staging-xxx-com.afr--checks=xss*,csrf*,trainer,*cookies*,*sql*--scope-exclude-pattern=logout--scope-include-pattern=staging.xxxx.com--plugin=vector_feed:yaml_file=arachni_staging_readonly_vectors.ymlhttps://staging.xxxx.com/workspace
```

```
/home/ubuntu/TestArea/arachni/bin/../system/usr/bin/phantomjs--webdriver=49348--proxy=http://127.0.0.1:56451/--ignore-ssl-errors=true--disk-cache=true--debug=true
```

I was running the following checks `xss*,csrf*,trainer,*cookies*,*sql*`.

With just `xss*,csrf*,trainer` no hang occurred.

Is this a known problem?

**Comment by Zapotek** [comment]
No it's not, jobs have a restricted time allowance to finish, they should never be able to hang.
Which version are you using?

Also, was the `css*` at the bottom of your post a typo?

**Comment by zubinix** [comment]
Yep sorry for the typo it should be `xss*`. I am running version 1.2.1.

**Comment by Zapotek** [comment]
Hm, any logged errors?
Also, can you stably reproduce this or was it an one off?

**Comment by zubinix** [comment]
No errors in the logs and this has happened a few times.

**Comment by zubinix** [comment]
I will run a few more tests with different combinations of checks to try and determine exactly which check is causing the hang.

**Comment by Zapotek** [comment]
If it's indeed browser related then the checks you didn't load shouldn't make any difference.
That's btw, I appreciate you taking the time to run some tests.

**Comment by zubinix** [comment]
`xss*,csrf*,trainer`    - did not cause a hang
`xss*,csrf*,trainer,*cookies*,*sql*` - did cause a hang

I will test:
`xss*,csrf*,trainer,*cookies*` 
`xss*,csrf*,trainer,*sql*`

The testing takes several hours to complete, I will post when finished.

**Comment by Zapotek** [comment]
It could be worth trying the [nightlies](http://downloads.arachni-scanner.com/nightlies/).
They're not that stable yet but the issue may have been resolved, and if not that's good to know too.

**Comment by zubinix** [comment]
From above:

`xss*,csrf*,trainer,*cookies*` - works fine
`xss*,csrf*,trainer,*sql*` - hangs

The last line in the log  is:
`[~] BrowserCluster: Pending jobs: 2`

phantomjs processes are still active (not running but in sleep state)

So it looks like the problem is with the **sql** tests.

**Comment by Zapotek** [comment]
That's weird, there's no connection between the browsers and the SQL injection checks.
Any chance I can run an identical scan against the same target?

**Comment by zubinix** [comment]
Will contact you shortly.

**Comment by Zapotek** [comment]
Discussion moved to e-mail, also, couldn't reproduce.

**Comment by marcvanduivenvoorde** [comment]
I have exactly the same issue. Where the scan hangs on the "[~] BrowserCluster: Pending jobs: 1" 

Has there been a solid solution found for this?

**Comment by Zapotek** [comment]
Can you please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?
