### ISSUE TITLE
EventMachine 1.0.3 fails to build with Ruby 2.2 (bundle install)

### ISSUE THREAD

**Issue by brandonprry** [Arachni/arachni#612]
Looks like EventMachine is set as 1.0.3 in Gemfile.lock, but this version fails to build with Ruby 2.2. 

Updating the Gemfile.lock to specify 1.0.4 resolved the issue for me.

See https://github.com/eventmachine/eventmachine/issues/509 for the eventmachine bug.

**Comment by Zapotek** [comment]
There's no EM in Arachni. Where's the `Gemfile.lock`?

**Comment by brandonprry** [comment]
bperry@bperry-dev-linux:~/Projects/arachni$ cat Gemfile.lock | grep event
    eventmachine (1.0.4)
      eventmachine
bperry@bperry-dev-linux:~/Projects/arachni$ git status
On branch experimental
Your branch is up-to-date with 'origin/experimental'.

nothing to commit, working directory clean
bperry@bperry-dev-linux:~/Projects/arachni$

**Comment by brandonprry** [comment]
Basically, bundle install failed until I updated the Gemfile.lock with EM 1.0.4

**Comment by Zapotek** [comment]
No idea what's going on, but I'm pretty sure there's on EM in Arachni:

```
$ cat Gemfile.lock | grep event
$ git status
On branch experimental
Your branch is up-to-date with 'origin/experimental'.

nothing to commit, working directory clean
```

**Comment by brandonprry** [comment]
Oh that's bizarre.

I can blow the directory away and reclone. I am actually not sure how old it is, but it should be up to date commit wise.

Let me blow away and reclone.

**Comment by Zapotek** [comment]
EM was removed aeons ago, it'd have to be pretty old.

**Comment by brandonprry** [comment]
Yep, you are right. For some reason, I just had an old Gemfile/Gemfile.lock. Blowing away then recloning removes the eventmachine dep.
