### ISSUE TITLE
Report tabs don't work

### ISSUE THREAD

**Issue by rgorski** [Arachni/arachni#613]
Running the nightly build from Sept. 05, 2015, after successful completion of a scan, the report tabs do not change the report details after click (viewing the scan details on the server). Have tested in Firefox 40.0.3, Chrome Version 45.0.2454.85 (64-bit), and Safari 8.0.8.

Originally, two issues showed in the "Pending verification" tab, but clicking it made no changes. I marked an item "Fixed", another as "Requires verification", and another as "False positive". The additional tabs became active, but clicking does nothing in the UI.

Clicking a tab appears to throw a "406 Not Acceptable" error.

**Comment by Zapotek** [comment]
Hello, can you please post this issue at the [WebUI issue tracker](https://github.com/Arachni/arachni-ui-web)?
This is for the Framework only.

Cheers
