### ISSUE TITLE
[ArgumentError] invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Karelkat** [Arachni/arachni#614]
Hello, I have found the following issue when generating the report in the YAML format:

 [*] YAML: Dumping audit results in moo.yaml.
 [-] [ArgumentError] invalid byte sequence in UTF-8
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `count'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `binary?'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:306:in `visit_String'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 ...

Doing the same export in XML format still gives the errors but it seems to generate the report anyway.

 [-] [ArgumentError] invalid byte sequence in UTF-8
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/components/fingerprinters/languages/aspx.rb:34:in `run'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/platform/manager.rb:262:in `block (3 levels) in fingerprint'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/utilities.rb:408:in `call'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/utilities.rb:408:in `exception_jail'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/platform/manager.rb:261:in `block (2 levels) in fingerprint'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/platform/manager.rb:260:in `each'
 [-] /home/moo/arachni/system/gems/gems/arachni-1.2/lib/arachni/platform/manager.rb:260:in `block in fingerprint'
 [-] /home/moo/arachni/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'

The issue only occurs on certain sites.
As mentioned before the XML still gets generated although the YAML it seems does not. This issue seems similar if not identical to a previous post here:

https://github.com/Arachni/arachni/issues/110

Regards,
Etienne

**Comment by Zapotek** [comment]
Hello,

Any chance of sending me the AFR report in private so that I may try to pinpoint the issue?

Cheers

**Comment by Zapotek** [comment]
This should do the trick, pushing fresh nightlies now, I'll let you know once they're up.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up, not sure if the fix will take effect for existing reports though.
Anyhow, give them a try.

**Comment by Zapotek** [comment]
Fresh nightlies are up again, they should take care of a loading order error.
Let me know how it works.

**Comment by Karelkat** [comment]
Ran a fresh scan today with nightlies (the last fixed worked), unfortunately the issue is still there. 

 [*] YAML: Dumping audit results in moo.yaml.
 [-] [ArgumentError] invalid byte sequence in UTF-8
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `count'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `binary?'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:306:in `visit_String'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `block in visit_Array'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `visit_Array'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:116:in `push'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych.rb:409:in `dump'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/core_ext.rb:14:in `psych_to_yaml'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:20:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:19:in `open'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:19:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:34:in `tap'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:34:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/utilities.rb:408:in `call'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/utilities.rb:408:in `exception_jail'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:33:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:43:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:25:in `initialize'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `new'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `<top (required)>'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-] 
 [-] Parent:
 [-] Arachni::Reporter::Manager
 [-] 
 [-] Block:
 [-] #<Proc:0x000000034ee168@/moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:33>
 [-] 
 [-] Caller:
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/utilities.rb:408:in `exception_jail'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:33:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:43:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:25:in `initialize'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `new'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `<top (required)>'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'
 [-] --------------------------------------------------------------------------------
 [-] [ArgumentError] invalid byte sequence in UTF-8
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `count'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:437:in `binary?'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:306:in `visit_String'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `block in visit_Array'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:397:in `visit_Array'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:377:in `block in visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:375:in `visit_Hash'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:152:in `accept'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb:116:in `push'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych.rb:409:in `dump'
 [-] /moo/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/psych/core_ext.rb:14:in `psych_to_yaml'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:20:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:19:in `open'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/components/reporters/yaml.rb:19:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:34:in `tap'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:34:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/utilities.rb:408:in `call'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/utilities.rb:408:in `exception_jail'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/lib/arachni/reporter/manager.rb:33:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:43:in `block in run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `each'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:42:in `run'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/ui/cli/reporter.rb:25:in `initialize'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `new'
 [-] /moo/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-2356d898c4f5/bin/arachni_reporter:12:in `<top (required)>'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `load'
 [-] /moo/arachni-2.0dev-1.0dev/bin/../system/arachni-ui-web/bin/arachni_reporter:16:in `<main>'

**Comment by Zapotek** [comment]
A string with broken encoding somehow slips by, can you send me the AFR report via e-mail please?

**Comment by Zapotek** [comment]
Is there any progress on this?
I'd like to get it sorted before releasing the next version.
