### ISSUE TITLE
Accept set-cookie

### ISSUE THREAD

**Issue by bararchy** [Arachni/arachni#617]
Is there a way to tell arachni to accept a set-cookie from the server when using cookie string ?

**Comment by Zapotek** [comment]
I'm not sure what you mean, but if you're asking if the `Set-Cookie` format is supported by the `--http-cookie-string` option then yeah, it should be.
Is it giving you trouble?

**Comment by bararchy** [comment]
Thanks for the fast response, let me try to rephrase 

I'm scanning a site that uses a login (user/pass), I'm authentication manually and passing the authenticated cookie string to arachni using --http-cookie-string 'asdasd;adsads;asd'.
One of the security mechanisms the site uses is a random token in the form of a cookie, as in 'asdasd;asdasda;random_token=123', now, every few connections the site will issue a Set-Cookie: random-token=345 header and will expect the client to change to cookie (the random_token value).

Now, when arachni is getting back a Set-Cookie header, will it know to change the cookie ?

**Comment by Zapotek** [comment]
Ah, yeah, it should act like any other user agent in that regard.
However, it's better to authenticate in a way that is replayable later one, in case of a logout, see:
http://support.arachni-scanner.com/kb/general-use/logging-in-and-maintaining-a-valid-session

That application sounds a bit strict though, so there may be a need to further configure Arachni to play nice with it (avoid auditing certain cookies for example), so let me know if you start noticing any weird or unexpected behavior and we'll go from there.

I'll leave this issue open until I get an OK from you, you can close it at any time.
Still, feel free to comment later on if you come across any issues.

Cheers

**Comment by Zapotek** [comment]
It's been a while so I'm assuming everything went fine, closing.
