### ISSUE TITLE
Custom profile scan pauses

### ISSUE THREAD

**Issue by PingLord** [Arachni/arachni#620]
Hey guys,

I created a custom profile in arachni_web and after around 30-70 requests the scan pauses itself and when i try to resume it pauses again in 2 seconds.
Any idea or hints ?

Version : 
Arachni v1.2.1 - WebUI v0.5.7.1

**Comment by Zapotek** [comment]
Have you enabled the `proxy` or `autologin` plugins?

**Comment by PingLord** [comment]
I enabled the autologin plugin.Known issues about it?

**Comment by Zapotek** [comment]
No, it just pauses the system while it logs in. Were there any errors with it?
Also, trying the same config via the CLI would probably be best for debugging this.

**Comment by PingLord** [comment]
hmm...it stayed paused for around 5 hours until i closed it.
used it on one of my websites which is on https and the login form parameters are basic.also the logs did not show anything even if phantomjs and ruby processes were making a litlle load.

**Comment by Zapotek** [comment]
There could have been an error or something, try using the CLI, it's much more verbose.
I'm preparing a new release right now, I may be able to squeeze in the fix if we spot the issue in time.

**Comment by PingLord** [comment]
Im out of the city today an now im writting from the phone but im gonna check the code an see im something pops up.
Im a beginner in ruby. using it for around 2 years but maybe i can spot anything if this is not a known issue.

**Comment by Zapotek** [comment]
Any updates on this?

**Comment by PingLord** [comment]
Hey,

Sorry for not updating anything on the ticket.I looked over the code and i've found no root cause for this. Im leaving for a conference in a few days so i think we can close this until i get more time to do another sweep of this issue.
Thank you for all your support on this.

**Comment by Zapotek** [comment]
No worries.
