### ISSUE TITLE
Please add URL fragment injection example

### ISSUE THREAD

**Issue by sitsofe** [Arachni/arachni#625]
If I have a page like this:

```php
?>
<!DOCTYPE html>
<html>
<head>
<title>Arachni parameters as path components test</title>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<?
$path = explode('/', getenv('REQUEST_URI'));
$script_name = "dirasparam";

$script_index = array_search($script_name, $path);
if ($script_index !== FALSE) {
        $parameter_index = $script_index + 1;
        while ($parameter_index < count($path)) {
                echo urldecode($path[$parameter_index]); # XSS time!
                $parameter_index++;
        }
}
?>
</body>
</html>
```

How do I go about teaching Arachni that it should pretend the last component of the URI path is a parameter so as to catch things like:

```
http://example.com/dirasparam/%3Cscript%3Ealert('XSS%20time!);%3Cscript%3E/
```

? I've got ```/.*\/(?<input1>[^\/]+)\/$/``` in Audit link templates but I'm unsure as to what to do next...

**Comment by Zapotek** [comment]
Can you try via the CLI please?

    ./bin/arachni http://127.0.0.2:4567/dirasparam/input1/ --checks xss --audit-link-template="/.*\/(?<input1>[^\/]+)\/$/"

It worked for me so maybe it's a WebUI issue that has to do with how it handles that option.

**Comment by Zapotek** [comment]
Btw, I didn't try your server, this is what I used:

```ruby
require 'sinatra'

get '/dirasparam/:xss/' do |xss|
    URI.decode( xss )
end
```

The result should be identical though.

**Comment by Zapotek** [comment]
Ah, I see the issue.
You don't need to enclose regexps with delimiters when passing them to Arachni (usually `/`) nor (necessarily) escape them.

In this case, the simplest pattern to get the result you want would look like: `.*/(?<input1>[^/]+)/$`

Let me know if that works for you.

**Comment by sitsofe** [comment]
Ah thank you - that resolved it. I think part of the problem is that the Audit link templates help says this:

For example, to extract the ```input1``` and ```input2``` inputs from
```http://test.com/input1/value1/input2/value2``` use
```/input1\/(?<input1>\w+)\/input2\/(?<input2>\w+)/``` .

which makes it look like you need to / enclose regexes and also escape them. I guess if the slash enclosing and escaping aren't needed could you update the help to reflect this?

**Comment by sitsofe** [comment]
(PS: It's far nicer to use example.com in examples - test.com exists ...)

**Comment by Zapotek** [comment]
Done and done, these changes will be included in the v1.3.2 bugfix release.

Thanks for the feedback.

**Comment by sitsofe** [comment]
Just out of interest, do the "no slash enclosing and escaping" rules apply to all Arachni regexes?

**Comment by sitsofe** [comment]
(Oh and thank you!)

**Comment by Zapotek** [comment]
No worries, and yeah it's a global thing.
If you find any occurrences where it doesn't that'll be a bug, so let me know.

**Comment by Zapotek** [comment]
Referenced the wrong issue from another [commit](https://github.com/Arachni/arachni/commit/0d44f52ee625adf3d689a22f2b4804863bb0d5fe).
