### ISSUE TITLE
 URI Encoding in attack payloads

### ISSUE THREAD

**Issue by tenscottc** [Arachni/arachni#626]
The current default encoding technique when sending the attack requests appears to be that the URI is url-encoded.  This feature request is to add support for an option to send payload without url-encoding as the default.

For instance, ideally there would be an command line option to specify with url-encoding, without, or sending the same payload with and then without to help give more control and ability to catch a few other cases of XSS that in some cases might not be flagged.  This was created in response to http://support.arachni-scanner.com/discussions/questions/12618-uri-encoding

Thank you!

**Comment by Zapotek** [comment]
I prepared a patch for [Ethon](https://github.com/typhoeus/ethon) to make encoding optional so I think the hard part is done.
I'll submit a PR after some more testing and then start work on the Arachni side of things.

**Comment by Zapotek** [comment]
Btw, the default would be following the RFC (i.e. encode by default) with an option to **also** send raw payloads, to be taken advantage by checks which can benefit from it.

**Comment by Zapotek** [comment]
Used the wrong issue ID in relevant commits:
* c07521cee0600e8bef2ad4807a0fe25b8cc74e9d
* ea4081b2bf838ac75fb1d34687b82138ab0f025c
* 93f773c954d4cc60c38b309678aca7d44e0d91f6

I'll be working on this in [arachni/optional-request-encoding](https://github.com/Arachni/arachni/tree/optional-request-encoding).

**Comment by Zapotek** [comment]
All done, although I have to wait for the Ethon [PR](https://github.com/typhoeus/ethon/pull/111) to be merged before I merge it into the experimental branch for it to be included in the nightlies.

I'll keep you posted.

**Comment by Zapotek** [comment]
You can find this feature in the [nightlies](http://downloads.arachni-scanner.com/nightlies/), enable it with `--audit-with-raw-payloads`, this will result in both encoded and raw payloads being injected.

Let me know how it works.

Cheers
