### ISSUE TITLE
login_script plugin - setting session cookie without set-cookie from server

### ISSUE THREAD

**Issue by lexmark-benmarks** [Arachni/arachni#627]
I'm trying to write a login_script script but the application I'm writing it for sends the session hash back as part of the body and then the client sets the cookie via code.  I cannot figure out how to "manually" set the session cookie in the login script (if it's even possible).

I tried creating a Cookie manually and then adding it to the session.cookies array but it seems that the Cookie constructor is private so I'm not sure how to create one or if session.cookies is even the right place for it.

Current login script:
```
response = http.get('http://webvulnserver:3000/login',
        parameters: {
                'username'      =>      'admin',
                'password'      =>      '1234'
        },
        mode:           :sync,
        update_cookies: true
)
puts "response body: " + response.body
#the above line prints: response body: {"session":"8724229702-3358607554-1699617389-5615569041","role":"admin"}

framework.options.session.check_url     = 'http://webvulnserver:3000/expense'
framework.options.session.check_pattern = /isApproved/
```

**Comment by Zapotek** [comment]
Here you go:

```ruby
HTTP::Client.update_cookies 'test' => '1'
```
