### ISSUE TITLE
unable to detect xss vulnerability

### ISSUE THREAD

**Issue by lexmark-benmarks** [Arachni/arachni#628]
We are working on a pilot of using Arachni to test our web client and I am unable to have it detect a basic xss vulnerability.  My page is publically available and will take any input from the text box and execute it.  You can test by entering <script>alert(1)</script>.

My test page: ``` http://52.91.72.127:8080/vulnerability/#vulnerabilitypackage/hax ```

My command line: ```$ ./arachni http://52.91.72.127:8080/vulnerability/#vulnerabilitypackage/hax --browser-cluster-wait-for-element='hax:#showText' --scope-page-limit=1 --checks=xss* ```

I've also tried adding: ``` --browser-cluster-wait-for-element='^((?!#).)*$:#showText' ``` but this does not seem to make any difference.

Am I doing something wrong here?

**Comment by Zapotek** [comment]
I remember settling this case, which Arachni version are you using?

**Comment by lexmark-benmarks** [comment]
We have tried with 1.3.2 and with the nightly 2.0.  Right now 1.3.2 misses the vulnerability and 2.0 actually throws an exception: [-] [utilities#exception_jail:428] [NoMethodError] undefined method `source' for "hax":String

**Comment by Zapotek** [comment]
Yeah I just saw that error, the false negative must be a regression, looking into it.

**Comment by Zapotek** [comment]
Fixed it, small deduplication issue while I was transitioning the handling of UI forms from the `xss_dom_inputs` check into auditable `UIForm` elements.

I'll add/do some more tests and have a working nightly for you tomorrow.

Thanks a lot for the feedback, much appreciated.

**Comment by lexmark-benmarks** [comment]
So just to be clear, should this vulnerability be found with 1.3.2 and xss* checks or is this something only nightly will pick up once fixed?

**Comment by Zapotek** [comment]
No there's no workaround for the current version, it'll be picked up once the fix is in the nightly.
Also, even if there was no bug, your config would still prevent it from being identified due to the scope restriction.

This would have worked:

    --browser-cluster-wait-for-element='^((?!#).)*$:#showText' --checks=xss*

Or, if you'd like to restrict the scope to a single state rather than the first seen page, you'd need to use:

    --plugin=restrict_to_dom_state:fragment=vulnerabilitypackage/hax --checks xss* --browser-cluster-wait-for-element='hax:#showText'

Or, since you know more or less what to expect, you could have used `xss_dom` rather than loading all XSS checks to speed things up.

To sum up, this is the optimal config for your case:

    --plugin=restrict_to_dom_state:fragment=vulnerabilitypackage/hax --checks xss --browser-cluster-wait-for-element='hax:#showText'

**Comment by lexmark-benmarks** [comment]
Excellent, thank you for your explanation.

**Comment by Zapotek** [comment]
Pushing nightlies, I'll let you know once they're up.

**Comment by Zapotek** [comment]
Nightlies are up, they should do the trick. :)

**Comment by Zapotek** [comment]
I forgot to mention, the nightlies have a substantial amount of new code, so if you come across any issues please let me know.
On the bright side, they're significantly faster and less resource intensive than the latest stable version.
