### ISSUE TITLE
NTLM Auth

### ISSUE THREAD

**Issue by bararchy** [Arachni/arachni#629]
Hi, I cannot find the right option, is there a way to do a NTLM auth with arachni ?

**Comment by Zapotek** [comment]
If you're talking about NTLMv2 then there's no support.

**Comment by bararchy** [comment]
@Zapotek Oh ... I have a application in Ruby that works with NTLM V.2 I'm using this gem: https://github.com/WinRb/rubyntlm Maybe you should check it out :) 
If I can help with implementation or something I would be glad to.

**Comment by Zapotek** [comment]
It's not that simple, it needs to be supported by `libcurl`.
I don't suppose Kerberos would work for your case, would it?

**Comment by Zapotek** [comment]
Anyhow, closing this since if libcurl doesn't support it then Arachni won't either.
I guess I could custom-handle this at Arachni's level but the solution would be way too ugly and I don't think it's worth it for such a low-demand feature.
