### ISSUE TITLE
missed stored xss vulnerability

### ISSUE THREAD

**Issue by lexmark-benmarks** [Arachni/arachni#630]
The latest nightly build as of 10/27/15 missed a stored XSS vulnerability in one of our test pages.  This vulnerability allows code to escape a textarea and execute instead of being displayed as text.  You can see this live at: `http://<see-email-for-public-IP>:3000/#expense/1772` by entering `</textarea><script>alert(1337)</script>` in the "Notes" field.

My command line is: 
```
arachni/bin/arachni \
http://10.16.0.151:3000/#expense/1915 \
--plugin=restrict_to_dom_state:fragment=expense/1915 \
--checks xss* \
--browser-cluster-wait-for-element='#expense/1118:.expense-edit' \
--plugin=login_script:script=login.rb \
--browser-cluster-pool-size=1
```

**Comment by Zapotek** [comment]
I'll also need the login script as it's likely to be a session issue.

**Comment by lexmark-benmarks** [comment]
Ah sorry, I should have included it the first time.
```
base_url = 'http://10.16.0.151:3000'

response = http.get(base_url + '/login',
        parameters: {
                'username'      =>      'admin',
                'password'      =>      '1234'
        },
        mode:           :sync,
        update_cookies: true
)
puts "response body: " + response.body
session = /\d{10}-\d{10}-\d{10}-\d{10}/.match(response.body)[0]

HTTP::Client.update_cookies 'session' => session

check_url = base_url + '/expense'
check_pattern = /isApproved/

#prove that the check url and pattern will work...
checkResponse = http.get(check_url,
        mode:   :sync,
        cookies: {
                'session' => session
        }
)
puts "check response body: " + checkResponse.body
puts "check_pattern is in body?: " + ((/isApproved/ =~ checkResponse.body) > 0).to_s

#set the check url and pattern
framework.options.session.check_url     = check_url
framework.options.session.check_pattern = check_pattern
```

**Comment by Zapotek** [comment]
Seems like the `restrict_to_state` plugin is running prior to the `login_script` one, so it basically restricts the scan to the login page.

**Comment by Zapotek** [comment]
Nighlties include the fix, there are some special considerations that need to be accommodated due to the quirks of your demo app but we'll continue that discussion over e-mail.

Cheers
