### ISSUE TITLE
False positive backup folders, not actually existing?

### ISSUE THREAD

**Issue by jjgh** [Arachni/arachni#634]
For every website I scan Arachni gives me many backup folders (and I think it spends the majority of time with those requests and their processing). They usually amount to one hundred or more, basically they are multiple of the "real" pages because for any of those there are many backup folders.

But if I try to open them the servers just say 404 not found.

Example, just for a index.php, I get these backup directories in report:

http://www.domain.com/index.php%20-%20Copy%20(2)/
http://www.domain.com/index.php%20-%20Copy/
http://www.domain.com/index.php%20(4th%20copy)/
http://www.domain.com/index.php%20(3rd%20copy)/
http://www.domain.com/index.php%20-%20Copy%20Copy/
http://www.domain.com/index.php%20(third%20copy)/
http://www.domain.com/index.php%20(another%20copy)/
http://www.domain.com/index.php%20(copy)/

Strangely enough I saw a similar issue with OWASP ZAP which constantly reports the presence of many backup folders which just don't exist.. (can't remember if they had same names right now...).

**Comment by Zapotek** [comment]
Can you send me the real URLs in private please?
Something must be throwing off the custom-404 identification.

I'm more worried about the "every website" remark though, I can see that happening for certain edge cases but if it happens every time there must be a regression somewhere.

**Comment by Zapotek** [comment]
Also, are those issues marked as trusted or untrussted?

**Comment by jjgh** [comment]
Sent answer by mail (please tell me if you received it).

**Comment by Zapotek** [comment]
Ok, good news these issues only exist in the experimental branch, which is OK, that's what it's for.
I was trying out an optimization that backfired, I'm reverting the change now.

**Comment by Zapotek** [comment]
Nightlies updated with the fix.

Thanks for the feedback.
