### ISSUE TITLE
Empty response from server triggers "Missing 'X-Frame-Options' header in Server"

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#636]
A request to a remote server that goes unanswered (empty response) will trigger this vulnerability

Inspecting the "findings" shows an empty "Response" box

**Comment by nrathaus** [comment]
Wanted to mention that manual inspection of the server shows that the X-Frame-Options is in fact there and returned for every response sent from the server.

The request in question also returns this Header.

If the response is shown as "Empty" because of some bug, but is actually it is "captured" - i.e. this is a GUI display issue and not a test issue then I don't quite see why the software would detect this vulnerability.

**Comment by Zapotek** [comment]
Pushing some nightlies with the fix now, will let you know once they're up.

Cheers

**Comment by Zapotek** [comment]
Nightlies are up, they should fix all the issues you reported.

Cheers
