### ISSUE TITLE
HttpOnly found in Response but Vulnerability still triggered

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#638]
The response contains the HttpOnly tag but the vulnerability still is marked as relevant

Response:

```
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
Set-Cookie: ASP.NET_SessionId=t; path=/; secure; HttpOnly
Set-Cookie: ASP.NET_SessionId=t; path=/; secure; HttpOnly
Set-Cookie: _culture=en-US; expires=Thu, 26-Nov-2015 13:56:21 GMT; path=/; secure; HttpOnly
Set-Cookie: __RequestVerificationToken_L=M; path=/; secure; HttpOnly
X-UA-Compatible: IE=edge
x-content-type-options: no sniff
X-Frame-Options: DENY
X-XSS-Protection: 0
Date: Thu, 26 Nov 2015 13:36:21 GMT
Content-Length: 4769

<script src="http://javascript.browser.arachni/taint_tracer.js"></script> <!-- Injected by Arachni::Browser::Javascript -->
<script src="http://javascript.browser.arachni/dom_monitor.js"></script> <!-- Injected by Arachni::Browser::Javascript -->
```

**Comment by Zapotek** [comment]
Hello, which version are you using/

**Comment by nrathaus** [comment]
1.3.0-0.5.9 on Ubuntu 15.04

**Comment by Zapotek** [comment]
Thanks, some of issues are caused by pages fed by to the system by the browser, hence lacking some context.
The issues should be simple to resolve though.

Thanks a lot for the feedback.

Cheers

**Comment by nrathaus** [comment]
No problem, glad to help

**Comment by Zapotek** [comment]
There have been some changes in that part of the system so could you please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) and check that the issue is still there?

Also, which of the cookies was logged? Or was it all of them?

**Comment by nrathaus** [comment]
Since this happened on one host from our test lab out of several, I will finish with test with the Nightlies when we finish the lab check

**Comment by nrathaus** [comment]
I will
