### ISSUE TITLE
URL having < or > inside it prevents exporting of report to XML form

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#639]
A server having a URL that has "<" (lower-than) or ">" (greater than) inside it would cause an exception (related to XML verification) when trying to export the results into a file in XML form - HTML format has no issue (other types of format were not tested)

**Comment by Zapotek** [comment]
That's weird, I generally let the parser handle encoding, any chance you can send me the AFR in private?
That'll greatly help with the other issues you mentioned as well.

You can do so in private: tasos.laskos@arachni-scanner.com

**Comment by nrathaus** [comment]
I am sorry, I wish I kept that scan around, I but I didn't - I will try to recreate this scenario in our lab again

The "workaround" I was able to do in the end to get an XML report was to enter using sqllite and modify the table's content, so that the URL in question with "<" would be replaced with &lt; and ">" with &gt;

I don't remember anymore which table it was as well, but I remember it was a BLOB having a list of URLs (not just one) - so it was maybe a traverse map of URLs (how we reached this point) or which URLs were tested, not sure.

**Comment by Zapotek** [comment]
Sounds like it was in the sitemap of the report but I when I tried to reproduce it I didn't get any errors.
Let me know if you manage to bring out that error again.

**Comment by nrathaus** [comment]
I guess we can close this ticket off until I have something more to provide - like an AFR file or some more information on the problem

**Comment by Zapotek** [comment]
Fair enough. :)
