### ISSUE TITLE
Support Scanning Sites Written with ReactJS

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#640]
Hi Tasos,

I wanted to circle back on scanning sites written with ReactJS (https://facebook.github.io/react/).  I noticed that most of my sitemaps for ReactJS apps are looking very incomplete, indicating that the crawler does not have the ability to click elements in the DOM or parse out links.  

This would be a great feature to add as many sites are now using react (Facebook, Netflix, etc.)

**Comment by Zapotek** [comment]
Hey Scott,

I generally don't need to add special support for libraries, there's probably a function in ReactOS that doesn't play nice with my taint tracer or some such bug.

Do you have a test case I can use to hunt down the bug?

Cheers

**Comment by Zapotek** [comment]
Also, does this issues happen with the nightlies?

**Comment by sbehrens** [comment]
Yes, the main issue I notice is with www.netflix.com/YourAccount.  Any of the links found on that page return pages that have a button to save, update, etc.  It doesn't seem to find any of those buttons which all make API calls.  It does find the links but it can't seem to identify the forms/buttons.

**Comment by Zapotek** [comment]
Does that problem happen with the nightlies too?
There was a resolved issue causing the same behavior.

**Comment by sbehrens** [comment]
I will try it out right now and let you know.

Scott

**Comment by sbehrens** [comment]
The nightlies are breaking our session cookies again similar to this issue i filed a while ago:

https://github.com/Arachni/arachni/issues/521

Can you fix the regression and then let me know so I can retest?

**Comment by sbehrens** [comment]
SecureBLAHBALHId=v%3D2%26mac%BLAHBLAH.%26dt%3DTIMESTAMP;

is what is returned after logging in however Arachni is decoding certain characters:

SecureBLAHBALHId=v=2&mac%BLAHBLAH.&dt=TIMESTAMP;

The our web server attempts to pull the key/value cookies BEFORE url decoding,
which is why it causes an error.

**Comment by Zapotek** [comment]
Are you getting this from the HTTP traffic or the autologin plugin's output?
I may have introduced a bug in the nightlies, but I don't think it's in encoding cookies.

**Comment by sbehrens** [comment]
I'm proxying the autologin plugin output and I can see it receiving the
cookies with the right encoding but then it url decodes them before sending
them.  Same behavior as the issue I linked.  I can send you some
screenshots if needed.

**Comment by Zapotek** [comment]
I'm sorry for the trouble, can you send over the login options or script please?

**Comment by sbehrens** [comment]
Sure, will forward offline.

**Comment by Zapotek** [comment]
Are you sure that `&` were sent decoded in the values?
From what I could see only `=` were sent decoded in the cookie value.

As soon as I enabled encoding for `=` it worked fine.

I could swear the HTTP cookie specification (one of them) mentioned `=` being OK in values since the name/value split only happens on the first `=`, but these things are a mess both spec and implementation wise.

This has become the bane of my existence so I'll eventually update cookies to just be dumb storage and unless a cookie has been mutated it'll be sent back to the webapp the same way it was set, encoded in whatever way the webapp thought was right.

**Comment by sbehrens** [comment]
Here is the response from the server:

[image: Inline image 1]

Here is what Arachni is sending (notice how NeflixId=v=2 instead of
NetflixId=v%3D2):

[image: Inline image 2]
The = signs are being decoded which is resulting in the web app being
unable to determine where the cookie starts/ends.  Basically what would
work is to disable url decoding of the = symbol and just passing through
the cookie value as returned from the web server.

**Comment by Zapotek** [comment]
Inline images don't really work here it seems, but we're saying the same thing.

**Comment by sbehrens** [comment]
Cool, is there a quick fix I could implement to check the react.js scanning stuff?  Do you want me to open up the cookie bug in a separate thread?  I sorta hijacked this issue for that one...

**Comment by Zapotek** [comment]
Hahaha bit too late for a different thread, kinda wish GH could split them though.

Anyhow, you can add `=` to [this list](https://github.com/Arachni/arachni/blob/experimental/lib/arachni/element/cookie.rb#L38) and remove it from [this one](https://github.com/Arachni/arachni/blob/experimental/lib/arachni/element/cookie.rb#L41).
I'm now running the test suite, make sure everything works as expected with the change.

**Comment by sbehrens** [comment]
Adding = into the list worked for me, i was able to auth now using the
scanner.  Will report back on react.js coverage.

**Comment by sbehrens** [comment]
Hi Tasos,

I have confirmed that the nightlies are finding some links but the crawler/scanner isn't clicking any buttons for Saving, updating, etc, which is resulting in a ton of API calls not being identified in the sitemap.

**Comment by Zapotek** [comment]
No worries, looking into it.

**Comment by Zapotek** [comment]
Considering that the Netflix interface has a huge number of possible pages and your configuration is setting a time limit, I'm not sure whether there's an issue causing those elements to not have any events triggered or if the scan just doesn't get to that page within the configured time constraints.

I'll try to narrow it down a little, make sure the scanner sees the relevant pages.

**Comment by sbehrens** [comment]
It definitely hits the pages with the buttons it just isn't clicking them,
a few example pages that it hits but doesn't click the save button:

https://www.netflix.com/DoNotTest
https://www.netflix.com/EmailPreferences
https://www.netflix.com/SubtitlePreferences
etc.

**Comment by Zapotek** [comment]
The operation isn't synchronous, depends on how many browser jobs are already in the queue when the system gets there.

**Comment by Zapotek** [comment]
The pages you mentioned don't have anything for the browsers, it looks like they've just got regular forms without any DOM events.
Their inputs will be audited by the checks just like any regular form's inputs.

Do you have a page that demonstrates the issue?

**Comment by sbehrens** [comment]
Ive run a large number of scans and none of the pages that are found under
www.netflix.com/YourAccount those pages buttons never get clicked (which
makes API calls I never see in the sitemap), example pages are:

https://www.netflix.com/SubtitlePreferences

It finds SubtitlePreferences bjt desn't click the save button which would
result in a POST request to:

https://www.netflix.com/api/shakti/17034415/account/subtitles

None of the sitemaps I've seen with Arachni have any API calls for these
endpoints.

Scott

**Comment by Zapotek** [comment]
Can't believe I missed this, I had NoScript enabled while I was checking out the page manually, my bad.
The JSON inputs in the AJAX request that occurs after clicking the button should have been extracted and audited.

**Comment by Zapotek** [comment]
I think this is caused by the same-origin policies set by Netflix.
They may be interfering with Arachni's JS env which is loaded via internal URLs like `http://javascript.browser.arachni/dom_monitor.js`.

**Comment by Zapotek** [comment]
I bypassed that restriction but still getting "Script error" at line 0.
Have you seen that before?

**Comment by Zapotek** [comment]
OK getting closer, PhantomJS can optionally disable web security stuff and I managed to get the real error:

```
    [0] [
        [0] "TypeError: 'undefined' is not a function (evaluating 's.createElement.bind(null,e)')",
        [1] "https://www2-ext-s.nflximg.net/pkg/4.2.8/web/6db00e6b/js/3/0203782b101112036d2ac2ad2a92aa00414314d13413218f19a11521c36636936812800c02601c29f38312712615a17214812329d29611f13014a1421551a219d01d14113b38b13913604019519619019319419f19119219b2b003937611d11c11e11200937d273/js/k",
        [2] 8
    ]
```

It seems to be happening only when Arachni's custom env is loaded, digging deeper.

**Comment by Zapotek** [comment]
Turns out PhantomJS 1.9.2 doesn't have `Function.prototype.bind`, after adding a polyfill it worked fine -- turns out even without Arachni's env things weren't working properly either.

For now I'll commit the polyfill and start looking into migrating to PhantomJS 2.0.x.

**Comment by Zapotek** [comment]
Try the nightlies, the `*_dom` checks should now submit these forms via the browsers during the audit.
You still won't be seeing those API calls in the sitemap though, browser requests are no longer displayed, caused confusion and got to be too hectic.

Only audited pages are listed in the sitemap since v1.3 or so.

**Comment by sbehrens** [comment]
Cool I will give this a shot, thanks again.
Scott

**Comment by sbehrens** [comment]
Hi Tasos,

I have let a scan run for a few hours on YourAccount and I haven't seen any calls to the Shakti api which would indicate button clicks.  I'm proxying traffic through BurpSuite and it's just hitting the top level links on www.netflix.com/YourAccount but never actioning any of the buttons.  

I'm going to let it run a few more hours but it still seems to be having an issue.

**Comment by Zapotek** [comment]
I'm not sure if it hit Shakti URLs but there was JSON posted by the `xss_dom` check when submitting one of the setting forms during the audit of a toggle input, don't recall the exact name.

I'll have another look and let you know.

**Comment by sbehrens** [comment]
Thanks and let me know what you find out.

**Comment by Zapotek** [comment]
Well, the elements and the events are seen and scheduled for submission but the elements appear to have dynamic attributes (`data-reactid`), so upon refreshing the page the CSS locator no longer finds the element.

There's a workaround (couple actually) I can try out, I'll keep you posted.

**Comment by Zapotek** [comment]
I've identified the issue, it has to do with delegated event handling.
I initially wanted to add custom handling for ReactJS but I figured out a more generic way to take care of the issue.

**Comment by Zapotek** [comment]
I'm removing it from the v1.4 miltestone because this change requires caution and the nightlies are pretty much ready to ship. I'm just waiting on some dependency updates to be released.

In the meantime, I'll be working on this separately.

**Comment by Zapotek** [comment]
I've created an issue that better describes the situation so let's move there: #652

**Comment by sbehrens** [comment]
I didn't really observe any difference with the nightly.  Pretty much every request to netflix.com fuzzes the following:

```
`raw_query, ac_category_type, ac_rel_posn, ac_abs_posn, v1, search_submit`
```

I'm not sure what these parameters are.  They aren't valid, and they don't result in any findings.  Most requests via our API happen via Ajax calls to JSON endpoints.  

Here are some findings to different pages with the same parameters that it fuzzes

```
 [+] 1 | Cross-Site Request Forgery at https://www.netflix.com/billingactivity in form with inputs `search-input-toggle`.
 [+] 2 | Cross-Site Request Forgery at https://www.netflix.com/activate in form with inputs `search-input-toggle`.
 [+] 3 | Cross-Site Request Forgery at http://www.netflix.com/Kids/search in form with inputs `raw_query, ac_category_type, ac_rel_posn, ac_abs_posn, v1, search_submit`.
```
It seems Arachni isn't scanning any of the Ajax/JSON and/or it's having some issue finding the parameters to fuzz. 

As an example, let's look at /activate using BurpSuite to see what we should be seeing.  A GET request to /activate returns a form expecting a device number.  When clicking submit an Ajax call is made to this system:

https://www.netflix.com/api/shakti/723370cb/account/devices

With the following POST body:

```
{"activationCode":"112345","authURL":"REDACTED+tj45taRZQ8iE="}
```

The parameters it is trying to fuzz for /activate, I can't even find so I'm not sure what those are and they aren't being used obviously (never found any bugs).  

When running Arachni through a proxy it seems none of the Ajax calls are being parsed or checked.
