### ISSUE TITLE
autologin with redirect and new cookie doesn't work

### ISSUE THREAD

**Issue by lukaszbudnik** [Arachni/arachni#642]
Hi,

I cannot get autologin to work with successful HTTP 303 See Other + Set-Cookie respone.

I'm running arachni with these parameters:

--plugin=autologin:url=https://XXXX/login,parameters="username=XXXX&password=XXX&",check=""

When running in debug set to 3 I see that the webapplication authentication works fine.

I start with url https:/XXX. Webapp detects that arachni is not authenticated, adds C1 cookie and redirects arachni to /login page.

Arachni submits C1 cookie together with the autologin POST request:

```
POST /login HTTP/1.1
...
Cookie: C1=XXXX
....
[!!!] Client: Status: 303
[!!!] Client: URL: XXX
[!!!] Client: Headers:
HTTP/1.1 303 See Other
Cache-Control: no-cache, no-store, must-revalidate
Date: Tue, 01 Dec 2015 13:37:02 GMT
Expires: 0
Location: /
Pragma: no-cache
Set-Cookie: C2=XXXX; Path=/; Secure; HTTPOnly
Set-Cookie: C3=XXXX; Path=/; Secure; HTTPOnly
Set-Cookie: C4=XXXX; Path=/; Secure; HTTPOnly
```

Webapp authenticated the POST, returns 303 and sets additional C2, C3, and C4 cookies.

In the console output I see that AutoLogin plugin set C1, but didn't include C2, C3, and C4 cookies:

```
 [~] AutoLogin: System paused.
 [+] AutoLogin: Form submitted successfully.
 [~] AutoLogin: Cookies set to:
 [~] AutoLogin:     * "C1" = "XXX"
```

And I think this is causing my issues. Arachni cannot crawl any more pages as C2, C3, and C4 cookies are not set.

Is this arachni limitation, is there a work around for it?

thanks,
Łukasz

**Comment by Zapotek** [comment]
Hello,

Since the response was seen the cookies should have been set, can you also try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) and let me know if the issue persists?
There have been a lot of changes in that area that will be part of the next release.

Cheers

**Comment by lukaszbudnik** [comment]
Hi Zapotek,

So there is a progress as the autologin now prints all cookies (C1, C2, C3, and C4) correctly.

However arachni is still not able to access other pages. Even when I specify all URLs using --scope-extend-paths=paths.txt the result is still the same all requests are redirected to my login page. 

How often do you update your code? I will be keeping my eye on the nightlies.

thanks,
Łukasz

**Comment by Zapotek** [comment]
Is the fact that cookies are being set all proof that the login was successful?
Are you setting a login check so that the system can verify its session's validity?

**Comment by lukaszbudnik** [comment]
Yes, I'm absolutely sure. I can see in webapp logs that authentication was successful. Our application for unsuccessful login attempts returns HTTP 400 Bad Request. Arachni also prints that in total it did [~] Processed 47/47 HTTP requests. (checks=xss for testing only). And after unsuccessful login attempt the autologin prints just 1 cookie (which is set always).

After successful login 3 additional cookies are set of which 2  contain user settings (available only when we have reference to the user). They are printed by Arachni autologin plugin to the console. I must use autologin with checks="" as what ever I set there ends with check error (due to redirect after login?). Also Arachni does a little bit more requests (so for sure Arachni is 1 step farther): [~] Processed 89/89 HTTP requests.

By looking at the debug logs I see that there is a ping pong between / and /login page. So it looks like the cookies (which in 2.0dev are now listed by autologin plugin OK) are still not attached correctly to newly spawned phantomjs processed. Is there some kind of loop? When someone is logged in and opens /login my applications detects it and redirect the user to /.

**Comment by Zapotek** [comment]
You can use the `--session-check-url` and `--session-check-pattern` (overrides the `check` option of the plugin) options to set an alternative URL for the login check.
It is essential to set a working login check.

And now that I mentioned that, are you excluding resources that can invalidate the session (like logout links)?

Also, it's possible that there's a bug in the nightlies, so if you are indeed excluding any log-out resources you can contact me in private with the configuration you're using in order to reproduce the issue and I can debug it for you.

**Comment by lukaszbudnik** [comment]
Hi,

I'm using these commands:

```
bin/arachni --report-save-path=output.afr --scope-dom-depth-limit=10 --plugin=autologin:url=https://XXX/login,parameters="username=aaaa%40aaaa.com&password=XXX",check="" --scope-exclude-pattern="assets|logout" --checks=xss https://XXX --output-debug=3 2> log.txt
```

when using session check params:

```
bin/arachni --report-save-path=output.afr --scope-dom-depth-limit=10 --plugin=autologin:url=https://XXX/login,parameters="username=aaaa%40aaaa.com&password=XXX",check="" --session-check-url=https://XXX/users --session-check-pattern="Users" --scope-exclude-pattern="assets|logout" --checks=xss https://XXX --output-debug=3 2> log.txt
```

I cannot login at all:
```
[~] Scheduled 303 redirection: https://XXX/ => /login
 [-] Session: The scanner has been logged out.
 [~] Session: Trying to re-login...
 [-] Session: Login attempt 1 failed, retrying after 5 seconds...
 [-] Session: Login attempt 2 failed, retrying after 5 seconds...

 [+] Form submitted but the response did not match the verifier.
```
but in log.txt I don't see any requests targetted at /users page so it doesn't look like arachni even made an attempt to call that url.

**Comment by Zapotek** [comment]
I'll have to reproduce this issue in order to see what's going on, could you send me the configuration in private please?
tasos.laskos@arachni-scanner.com

**Comment by Zapotek** [comment]
Any update on this?
If it's a bug in Arachni I'd really like to get it sorted.

Cheers

**Comment by lukaszbudnik** [comment]
hi Zapotek,

Sorry for delay. I added a lot of additional debug messages to my application. 

The cookies (all C1, C2, C3, and C4) are encrypted and base64'd. I added printing them after successful login (on the application side).

In the authentication filter I added printing all cookies which are sent by the user.

I saw that all cookies sent by Arachni have characters like '=' changed into '%3D' etc and the application is redirecting Arachni back to the login page.

Is there a way to tell Arachni to treat cookies as raw strings and not parse them. Just sent them as they are?

thanks,
Łukasz

**Comment by Zapotek** [comment]
Give the fresh nightlies a shot, I think this is a duplicate of an issue I've already fixed.

**Comment by lukaszbudnik** [comment]
I'm already running MacOS nighly from 18th of December (downloaded yesterday).

**Comment by Zapotek** [comment]
My bad, I misunderstood.
Nightlies now encode `=` in cookie values to fix another reported issue but I do plan on treating cookies as raw strings for v1.5 to take case of these types of issues once and for all.

There's a chance that I can squeeze this feature in for v1.4 because I'm waiting for some dependencies to be updated before releasing, in any case, I'll be keeping this issue updated with my progress.

Thanks for the feedback man.

**Comment by Zapotek** [comment]
Nighlties are up and should fix this issue, can you give them a try please and let me know?
Cheers

**Comment by lukaszbudnik** [comment]
I downloaded latest nightly from today. After googling for the error message I found that you had the same issue you wrote about here: https://github.com/ffi/ffi/issues/461 

```
/Users/lukasz/dve/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-856d674420fe/lib/ffi/library.rb:141:in `block in ffi_lib': Could not open library 'c': dlopen(c, 5): image not found. (LoadError)
Could not open library '/usr/lib/libc.dyliblibc.dylib': dlopen(/usr/lib/libc.dyliblibc.dylib, 5): image not found
	from /Users/lukasz/dev/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-856d674420fe/lib/ffi/library.rb:100:in `map'
	from /Users/lukasz/kainos/arachni-2.0dev-1.0dev/system/gems/bundler/gems/ffi-856d674420fe/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/lukasz/kainos/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.8.1/lib/ethon/libc.rb:8:in `<module:Libc>'
```

**Comment by Zapotek** [comment]
Any chance you can try from a Linux box until the OSX issue is fixed?

**Comment by lukaszbudnik** [comment]
Yes, I will try to do this tomorrow (I'm super busy this week if not tomorrow then Friday).

**Comment by Zapotek** [comment]
I'm assuming that my change fixed the issue, if not please let me know.
