### ISSUE TITLE
False positive for Path Traversal 

### ISSUE THREAD

**Issue by glestel** [Arachni/arachni#645]
Hi, I've been recently trying out the new release of Arachni (v1.3.2 from master) and I've noticed a false positive on testfire.net with the url http://testfire.net/default.aspx?content=whatever.mine it displays an error "Error! File must be of type TXT or HTM" but It answers with 200 Ok so it must confuse Arachni.
I think a basic workaround would be like "if positive, check another path traversal. If the result is exactly the same, it's a false positive"

**Comment by Zapotek** [comment]
Hey,

It's not an FP: http://testfire.net/default.aspx?content=/../../../../boot.ini%00.htm

Cheers

**Comment by glestel** [comment]
And I haven't thought of the most basic escaping. My bad

**Comment by Zapotek** [comment]
No worries, there should be a link provided in the reports just like the one I posted, did you miss it or it didn't work?

**Comment by glestel** [comment]
Special chars in the link got lost because of my output formatting though RPC calls. But the html report is comprehensive enough on the subject

**Comment by Zapotek** [comment]
The reports are generated from the same data, you'll find that link in the `url` of the `affected_page`.

**Comment by glestel** [comment]
The link is `GET /default.aspx?content=%2F..%2F..%2F..%2F..%2F..%2Fwindows%2Fwin.ini............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................%00.htm` but the `%00.htm` was dropped by my basic print of the rpc result in `issue['vector']['action'] `

**Comment by Zapotek** [comment]
`issue['vector']['action']` holds the location to which the input vector should be submitted, not necessarily the final vulnerable resource.
Checkout `issue['affected_page]['url']` or better yet `issue['affected_page]['dom']['url']`.

Btw, since you're integrating, have you checked out the license?

**Comment by glestel** [comment]
Thanks for the advice. However, I plan on rewriting my "wrapper" from RPC to REST API to avoid a layer of abstraction and call Arachni in Python. As I am maintaining a plugin to integrate Arachni with [Mozilla Minion](https://github.com/mozilla/minion) so I think it's OK with the licence.

**Comment by Zapotek** [comment]
Yep you should be cool.
