### ISSUE TITLE
false positive: credit card disclosure trigered for a style element

### ISSUE THREAD

**Issue by themr0c** [Arachni/arachni#647]
The sequence 5309136012499991 was detected as a credit card number, and reported as such.
But at it is part of the style of an HTML entity, i believe this is a false positive and should not be reported by the engine.

This is part of the body examined by the scanner:

```
<h1 style="opacity: 0.989381727975; -webkit-transform: translate(0%, -0.5309136012499991%) translate3d(0px, 0px, 0px); ">
```
NB: the body that is examined is quite different from the body seen from a browser: the style is not in the HTML, but in an external CSS file, with following content:

```
-webkit-transform:translateY(-50%);
```

**Comment by Zapotek** [comment]
Unfortunately there's nothing I can do about that.
That number passes the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) which is about the only think you can use to check the number's validity.

To make thing a little better, In the nightlies these issues are marked as untrusted by default.
