### ISSUE TITLE
Arachni WebUI in current and nightly builds binds to IPV6 by default

### ISSUE THREAD

**Issue by mdembree** [Arachni/arachni#649]
When I run the Arachni WebUI, both the current and nightly (2015-12-09) builds, it binds to IPV6 rather than IPV4.  This issue has occurred running the WebUI on both RHEL 7.1 and Windows 10. 

To get it to bind to IPV4 so I can access the WebUI from a browser on another host, I have added the following line to `arachni-ui-web/config.ru`, immediately after the comment at the top:

`#\ --host 0.0.0.0`

**Comment by Zapotek** [comment]
This isn't an issue, the WebUI binds to `localhost` by default, which is what is output in the terminal.
To specify alternative bind values you can use the options listed by `arachni_web -h`.

**Comment by mdembree** [comment]
In my experience, older versions of Arachni didn't behave this way on systems with both IPV4 and IPV6 stacks, it always bound to IPV4.  I first ran into the issue when trying a nightly build a few months ago.

Maybe it's a documentation issue then.  It might be good to document somewhere that `arachni_web --host 0.0.0.0` may be required to bind it to IPV4.

I don't recall seeing `arachni_web -h` documented and didn't realize `host` could be directly supplied as an option.

**Comment by Zapotek** [comment]
It did use to give preference to IPv4 but that's because you've got to bind to an IP address to listen on `localhost`, the actual IP address was left up to the underlying libraries.

If the system says its listening on `localhost:9292` and that works, then there's no bug.
