### ISSUE TITLE
False Positive for bootstrap-datepicker3.css

### ISSUE THREAD

**Issue by chrislp** [Arachni/arachni#651]
The following request is identified as *Backup file in Server*
```
GET /assets/bootstrap-datepicker/css/bootstrap-datepicker3.css HTTP/1.1
```
It clearly is not a backup file.

**Comment by Zapotek** [comment]
Hello,

Are you sure that's the URL that was logged?
I could understand there being a false positive, but that looks like the URL of the original resource, not one of the backup filename formats Arachni would generate and check for.

Cheers

**Comment by chrislp** [comment]
Hi,

I am sure ... but I also don't understand why it's logged:

![unbenannt](https://cloud.githubusercontent.com/assets/186817/11821839/ca922af0-a36b-11e5-9ed6-99e61be8d3d7.png)

Cheers,
Chris

**Comment by Zapotek** [comment]
Any chance you can export the AFR report and send it to me privately (tasos.laskos@arachni-scanner.com)?
Also, which version are you using?

**Comment by chrislp** [comment]
You've got mail :)

**Comment by Zapotek** [comment]
OK, on the positive side the scanner did mark this as `Untrusted` (i.e. possible FP).
Still, I'd rather it hadn't been logged at all.

**Comment by Zapotek** [comment]
Ah OK, this is interesting. :)

See, the original resource was http://uat1.nt.d-pim.com/assets/bootstrap-datepicker/css/bootstrap-datepicker.min.css, but Arachni manipulated the filename to the backup-file format of `bootstrap-datepicker3.min.css`, which of course actually exists: 

http://uat1.nt.d-pim.com/assets/bootstrap-datepicker/css/bootstrap-datepicker3.min.css

So this isn't an FP after all.

**Comment by chrislp** [comment]
Wow, I didn't see that! Thanks!


Chris

**Comment by Zapotek** [comment]
I feel really proud when I'm outsmarted by my own system, heh.
