### ISSUE TITLE
Special SSL configuration causes Nightly to fail to connect (stable works)

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#653]
Hi,

The following server SSL configuration:

    # ./sslscan/sslscan x.x.x.x
    Version: 1.11.0-rbsec-6-g662b704-static
    OpenSSL 1.0.2e-dev xx XXX xxxx
    
    Testing SSL server x.x.x.x on port 443
    
      TLS renegotiation:
    Session renegotiation not supported
    
      TLS Compression:
    Compression disabled
    
      Heartbleed:
    TLS 1.2 not vulnerable to heartbleed
    TLS 1.1 not vulnerable to heartbleed
    TLS 1.0 not vulnerable to heartbleed
    
      Supported Server Cipher(s):
        Preferred TLSv1.0  112 bits  DES-CBC3-SHA
    
      SSL Certificate:
        Signature Algorithm: sha256WithRSAEncryption
        RSA Key Strength:    2048
        
    Subject:  x.x.x.x
    Altnames: DNS:x.x.x.x
    Issuer:   Symantec Class 3 Secure Server CA - G4
    
    Not valid before: Dec 30 00:00:00 2014 GMT
    Not valid after:  Dec 31 23:59:59 2015 GMT

    # GET https://x.x.x.x
    Can't connect to x.x.x.x:443

    # lynx https://x.x.x.x
    
    (works)

Will provide crash log...

**Comment by nrathaus** [comment]
[crash.txt](https://github.com/Arachni/arachni/files/73926/crash.txt)

**Comment by Zapotek** [comment]
Hello,

Any chance you can send me the URL in private?
Also, does the latest release work?

Cheers

**Comment by nrathaus** [comment]
Hi,

The server is located inside our Amazon farm which is not accessible to the
outside

I tried it with the Stable version arachni-1.3.2-0.5.9 it works, with
this: arachni-2.0dev-1.0dev (2015-12-19) it doesn't.



On Wed, Jan 6, 2016 at 10:49 AM, Tasos Laskos <notifications@github.com>
wrote:

> Hello,
>
> Any chance you can send me the URL in private?
> Also, does the latest release work?
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-169269076>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

I think the problem is related to using the RPCD engine, which I need to
use it here because I cannot directly connect to this AWS instance


On Wed, Jan 6, 2016 at 11:29 AM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> The server is located inside our Amazon farm which is not accessible to
> the outside
>
> I tried it with the Stable version arachni-1.3.2-0.5.9 it works, with
> this: arachni-2.0dev-1.0dev (2015-12-19) it doesn't.
>
>
>
> On Wed, Jan 6, 2016 at 10:49 AM, Tasos Laskos <notifications@github.com>
> wrote:
>
>> Hello,
>>
>> Any chance you can send me the URL in private?
>> Also, does the latest release work?
>>
>> Cheers
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Arachni/arachni/issues/653#issuecomment-169269076>.
>>
>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
It's probably because the nightlies have an updated `libcurl` version.
Can you please show me the output of the following command for both stable and nightly?

    bin/arachni_shell -c 'curl -vvv https://host'

**Comment by nrathaus** [comment]
arachni-2.0dev-1.0dev-2015-12-19# bin/arachni_shell -c 'curl -vvv
https://10.9.8.1/'
*   Trying 10.9.8.1...
* Connected to 10.9.8.1 (10.9.8.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection:
ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

arachni-1.3.2-0.5.9# bin/arachni_shell -c 'curl -vvv https://10.9.8.1/'
*   Trying 10.9.8.1...
* Connected to 10.9.8.1 (10.9.8.1) port 443 (#0)
* error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none




On Wed, Jan 6, 2016 at 1:54 PM, Tasos Laskos <notifications@github.com>
wrote:

> It's probably because the nightlies have an updated libcurl version.
> Can you please show me the output of the following command for both stable
> and nightly?
>
> bin/arachni_shell -c 'curl -vvv https://host'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-169307539>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Did you get a response body back for both runs?

**Comment by nrathaus** [comment]
Hi,

No, I also tried secure.beyondsecurity.com and no response comes back, so I
thought that it was normal

Thanks,
Noam Rathaus
CTO
Beyond Security

**Comment by Zapotek** [comment]
Hm, can you please retry with the `-k` flag in both cases?

**Comment by nrathaus** [comment]
arachni-1.3.2-0.5.9# bin/arachni_shell -c 'curl -k -vvv https://10.9.8.1/'
*   Trying 10.9.8.1...
* Connected to 10.9.8.1 (10.9.8.1) port 443 (#0)
* error setting certificate verify locations, continuing anyway:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2, TLS handshake, Client hello (1):
* TLSv1.0, TLS handshake, Server hello (2):
* TLSv1.0, TLS handshake, CERT (11):
* TLSv1.0, TLS handshake, Server finished (14):
* TLSv1.0, TLS handshake, Client key exchange (16):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* TLSv1.0, TLS change cipher, Client hello (1):
* TLSv1.0, TLS handshake, Finished (20):
* SSL connection using TLSv1.0 / DES-CBC3-SHA
* Server certificate:
*        subject: C=US; ST=Virginia; L=McLean; O=Beyond Security; OU=IT;
CN=10.9.8.1
*        start date: 2015-06-22 00:00:00 GMT
*        expire date: 2016-06-15 23:59:59 GMT
> GET / HTTP/1.1
> User-Agent: curl/7.41.0
> Host: 10.9.8.1
> Accept: */*
>

arachni-2.0dev-1.0dev-2015-12-19# bin/arachni_shell -c 'curl -k -vvv
https://10.9.8.1/'
*   Trying 10.9.8.1...
* Connected to 10.9.8.1 (10.9.8.1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection:
ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations, continuing anyway:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to 10.9.8.1:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to 10.9.8.1:443


On Wed, Jan 6, 2016 at 2:14 PM, Tasos Laskos <notifications@github.com>
wrote:

> Hm, can you please retry with the -k flag in both cases?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-169310113>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
So it's either the libcurl upgrade or the openssl upgrade, should be fixable, will have a nightly up in a few hours.

Thanks for the feedback man.

**Comment by nrathaus** [comment]
Hi,

No problem.

I also noted, but I cannot confirm, that Arachni isn't adding
Accept-Language header field to requests, some servers will not respond
(mainly .NET servers) correctly if they see such a request come in, worth
checking.




On Wed, Jan 6, 2016 at 5:14 PM, Tasos Laskos <notifications@github.com>
wrote:

> So it's either the libcurl upgrade or the openssl upgrade, should be
> fixable, will have a nightly up in a few hours.
>
> Thanks for the feedback man.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-169350376>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Seriously? I've never seen that before, do you have a test case?

**Comment by nrathaus** [comment]
Hi,

Will send it off-record





On Wed, Jan 6, 2016 at 5:20 PM, Tasos Laskos <notifications@github.com>
wrote:

> Seriously? I've never seen that before, do you have a test case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-169353037>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
You don't happen to have a URL so that I can test the original issue do you?
It takes a while to upload and I may have to try out a couple of things.

**Comment by nrathaus** [comment]
Which URL are you referring to?

Thanks,
Noam Rathaus
CTO
Beyond Security

**Comment by Zapotek** [comment]
My bad, I forgot it was in Amazon's cloud.

**Comment by Zapotek** [comment]
Bad news, http://zlib.net/ seems down for the moment, I can't build fresh packages until it's up.

**Comment by Zapotek** [comment]
Site is up, building and pushing.

**Comment by Zapotek** [comment]
Nightlies are up.

**Comment by Zapotek** [comment]
Hello,

Did the nightlies solve your issue?

**Comment by nrathaus** [comment]
Hi,

I don't think so, I just tried it:
arachni-2.0dev-1.0dev-2016-01-12# bin/arachni_shell -c 'curl -k -vvv
https://10.9.8.1/'
*   Trying 10.9.8.1...
* Connected to 10.9.8.1 (10.9.8.1) port 443 (#0)
* error setting certificate verify locations, continuing anyway:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
* TLSv1.2, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to 10.9.8.1:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to 10.9.8.1:443

While on 1.3.2-0.5.9 it works


On Sat, Jan 16, 2016 at 4:46 PM, Tasos Laskos <notifications@github.com>
wrote:

> Hello,
>
> Did the nightlies solve your issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-172213095>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Must have been the OpenSSL upgrade then, I'm building new nightlies now using the same OpenSSL branch as the latest stable package.

**Comment by nrathaus** [comment]
Ok

Thanks,
Noam Rathaus
CTO
Beyond Security

**Comment by Zapotek** [comment]
OK, I used the 1.0.1 OpenSSL branch like before, although a more recent version of it.
It should work now.

**Comment by nrathaus** [comment]
Hi,

The nightly from the 18th works on this site as the stable version does

I think this is closed


On Sun, Jan 17, 2016 at 6:55 PM, Tasos Laskos <notifications@github.com>
wrote:

> OK, I used the 1.0.1 OpenSSL branch like before, although a more recent
> version of it.
> It should work now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-172351278>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Excellent.

I set `libcurl` to its newest version since the issue turned out to be with OpenSSL, but could you please verify this one more time with the latest nightlies just to be safe?

Cheers

**Comment by nrathaus** [comment]
I tried about 2 hrs ago, is the nightly newer than that?


On Tue, Jan 19, 2016 at 3:43 PM, Tasos Laskos <notifications@github.com>
wrote:

> Excellent.
>
> I set libcurl to its newest version since the issue turned out to be with
> OpenSSL, but could you please verify this one more time with the latest
> nightlies just to be safe?
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/653#issuecomment-172857862>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Yeah, just pushed it a min ago.
