### ISSUE TITLE
--scope-exclude-pattern seems to be case-sensitive, but docs are ambiguous

### ISSUE THREAD

**Issue by brandonprry** [Arachni/arachni#656]
Auditing a web application on a Windows server, so paths are case-insensitive. Specifying --scope-exclude-pattern login results in Login.aspx still being crawled.

This was tested on both master and experimental latest.

Command I was running:

```
./arachni --http-cookie-string "ASP.NET_SessionId=5eznch5dwjpwd4c12ogy5zbt;" --scope-exclude-pattern logout --scope-exclude-pattern login --scope-extend-paths paths 'http://192.168.0.24/Default.aspx'
```

But this yields:

 [*] OS command injection: Auditing form input 'txtUserName' pointing to: 'http://192.168.0.24/Login.aspx?ReturnUrl=_arachni_trainer_0995773374a3815d5f2363130c5d2d69'

As well as all the other usual checks. I have verified that 'paths' that is seeding the scanner does not include Login.aspx, so it shouldn't be overwriting anything internally either in regards to whether it should check that URL or not.

Thoughts?

**Comment by brandonprry** [comment]
It looks like specifying --scope-exclude-pattern Login does prevent Login.aspx from being crawled.

**Comment by Zapotek** [comment]
Looking at the code, it turns out that I was mistaken, it's not case insensitive by default.
Problem is that there's no way to make it so either, so I'd like some feedback on this, do you think switching to always case-insensitive would be preferable?

Sorry for the mix-up.

**Comment by brandonprry** [comment]
Hey, no worries at all.

I think it should be case-insensitive by default, with an option some way to specify patterns should be case insensitive.

Off the top of my head though, I am not sure how I would expect to specify that. Maybe something like --scope-pattern-insensitive true|false

**Comment by brandonprry** [comment]
Er, case-sensitive by default*

**Comment by brandonprry** [comment]
For full disclosure, I feel like case-sensitive by default is 'default restrictive', so the chance of unintended side effects are smaller.

**Comment by Zapotek** [comment]
Sounds good, until it turns out that a case-insensitive flag is necessary I'll refrain from implementing it.

Thanks for the feedback.

**Comment by Zapotek** [comment]
Forgot to ask, you don't happen to need it now, do you?

**Comment by brandonprry** [comment]
Nah, I'm good, and now that I know I can ensure in the future I cover my bases correctly. Thanks though.

**Comment by brandonprry** [comment]
Maybe docs could be updated to be explicit

**Comment by Zapotek** [comment]
Yeah will do that in: https://github.com/Arachni/arachni/wiki/Command-line-user-interface#scope
