### ISSUE TITLE
Error in Arachni::Checks::CodeInjectionPhpInputWrapper: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by arschlochnop** [Arachni/arachni#657]
when i csan like this url http://site/?search_button=&s=%E6%90%9C%E7%B4%A2%E4%B8%80%E4%B8%8B 
igot a error.
![this's pic](https://cloud.githubusercontent.com/assets/7948693/12356433/ad66814e-bbdd-11e5-8472-09b4818850a1.png)
I feel because there are Unicode characters in URL.
this's Chinese characters.
/?search_button=&s=搜索一下
Can u help me?

**Comment by Zapotek** [comment]
I'll look into it, thanks for the feedback.

**Comment by arschlochnop** [comment]
woooo.So quicklly.
I've added ‘#encoding: utf-8’ in source_code_disclosure.rb, but there's still a mistake.

**Comment by Zapotek** [comment]
Any chance you can send me the site's URL in private so that I can try and reproduce the issue?
Data are sanitized to UTF8 but in this case something other managed to go through.

Also, do you get the same issue if you use the [nightlies](http://downloads.arachni-scanner.com/nightlies/)?

**Comment by arschlochnop** [comment]
ok URL by base64 encoding  aHR0cDovL2Iubm9wLnB3Lw== ,you can test it.
I went to the test under the new version, there will be a result in the feedback. :)

**Comment by arschlochnop** [comment]
There is no problem with the use of the  arachni-2.0dev .

**Comment by Zapotek** [comment]
Great, closing.
