### ISSUE TITLE
Please add firing range output

### ISSUE THREAD

**Issue by sitsofe** [Arachni/arachni#659]
(This is only a feature-request) Google have a program called [firing-range](https://github.com/google/firing-range) to asses vulnerability scanners. It would be nice if Arachni's progress on it could be reported on http://www.arachni-scanner.com/features/framework/crawl-coverage-vulnerability-detection/ ...

**Comment by Zapotek** [comment]
I can't really do that for every benchmark out there, the only reason that the WAVSEP results have been published is because it has been independently performed and includes almost all available scanners for comparison.
