### ISSUE TITLE
dashboard lost jqplot.canvasAxisLabelRenderer.min.js

### ISSUE THREAD

**Issue by arschlochnop** [Arachni/arachni#660]
This problem exists in all versions.
error:
![1](https://cloud.githubusercontent.com/assets/7948693/12377123/d2f3596c-bd4c-11e5-9d9c-f18826e8d548.png)

**Comment by Zapotek** [comment]
WebUI issues should be reported at https://github.com/Arachni/arachni-ui-web, this error shouldn't cause any issues but I'll sort it out.

Thanks for the heads up.

**Comment by arschlochnop** [comment]
:) good job! 
Do you have the software to chat? like Skype.
some small problems can be directly on the Skype to communicate

**Comment by Zapotek** [comment]
I'd rather you use the issue trackers, makes it easier to keep track of them.

On January 17, 2016 1:15:06 PM GMT+02:00, nop <notifications@github.com> wrote:
>:) good job! 
>Do you have the software to chat? like Skype.
>some small problems can be directly on the Skype to communicate
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Arachni/arachni/issues/660#issuecomment-172314812

-- 
Sent from my phone, please excuse my brevity.

**Comment by arschlochnop** [comment]
Okay
