### ISSUE TITLE
The crawler has been crawling the same URL

### ISSUE THREAD

**Issue by arschlochnop** [Arachni/arachni#664]
like title.
![123](https://cloud.githubusercontent.com/assets/7948693/12519186/492c83cc-c178-11e5-9343-430cc5ee4b43.png)
![456](https://cloud.githubusercontent.com/assets/7948693/12519266/c8040328-c178-11e5-9a90-78ab615c1e33.png)

**Comment by arschlochnop** [comment]
command ‘./bin/arachni http://site --checks - --scope-include-subdomains --scope-exclude-binaries --scope-auto-redundant --scope-exclude-pattern js’

**Comment by Zapotek** [comment]
It's not really that simple, the page state has changed so it needs to be processed again.
If there's JS in the page that keeps changing it significantly then this would be the result.

You can set scope redundancy rules to limit processing for certain URLs or try the nightlies, there have been some changes that might bypass the issue.
Alternatively, I'd really like to see what's going on myself in case I can automate this for future versions.

Cheers

**Comment by arschlochnop** [comment]
I seem to have found the reason.
`arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-ed4d88aeb01d/lib/arachni/page.rb:42:in `block in from_url'
`
The default value is 2, the request will lead to the same link twice crawling, I can not think of his role, can help me explain

`opts[:precision] ||= 2
`

**Comment by Zapotek** [comment]
That's not it, that plays a completely different role.
It's probably what I mentioned in my last reply, you should set redundancy rules and if possible let me examine the situation myself.

Cheers
