### ISSUE TITLE
Following relative links with whitespace in <meta http-equiv="refresh"... >

### ISSUE THREAD

**Issue by slackish** [Arachni/arachni#666]
Loading the following webpage contents results in a false link for arachni.

``<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title></title><meta http-equiv="refresh" content="0;url= Home.html" /></head><body></body></html>``

At first I thought the site I'm checking on was just out of spec. The following link indicates that whitespace should be skipped after the "=" within the content field:  https://www.w3.org/TR/html5/document-metadata.html#attr-meta-http-equiv-refresh

The following shows up in the reports under the sitemap section when this happens.
> [-] http://some.site/
[-] http://some.site/%20Home.bak
[+] http://some.site/%20Home.html
[-] http://some.site/%20Home.html.bak
[-] http://some.site/%20Home.html.bak/
[-] http://some.site/%20Home.html.old
[-] http://some.site/%20Home.html.old/
[-] http://some.site/%20Home.html~
[-] http://some.site/%20Home.html~/
[-] http://some.site/%20Home.old
[-] http://some.site/robots.txt
[-] http://some.site/source/

**Comment by Zapotek** [comment]
Thanks for the heads up, pushing some nightlies for you to verify the fix.

Cheers

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up and should work fine now.

**Comment by slackish** [comment]
Works just fine.  Thanks for the quick fix.

Cheers
