### ISSUE TITLE
Config option: allow customization of "_arachni_trainer_" string

### ISSUE THREAD

**Issue by myrinx** [Arachni/arachni#667]
Hi,

We believe it would be nice to have the ability to customize the "_arachni_trainer_" string in the code. Would it be possible to place this on the roadmap?

Thanks!

**Comment by Zapotek** [comment]
Hello,

Is there a reason for this?
Arachni doesn't generally try to conceal itself because it's quite distinctive in its operation and easily identifiable.

Cheers

**Comment by Zapotek** [comment]
Closing this since I do need a valid justification for making changes and I don't see this feature as being in line with Arachni's objective.

Feel free to comment if you'd like to continue this discussion.

Cheers
