### ISSUE TITLE
Arachni Proxy Overlaps webpage

### ISSUE THREAD

**Issue by 1110532** [Arachni/arachni#668]
Good day,
It appears that arachni web proxy overlaps some elements of the webpage when a "/panel" is present (i.e.: "thissite.com/panel") resulting in some weird behavior.

Thanks for addressing this bug.

**Comment by Zapotek** [comment]
Can you give a quick try to the [nightlies](http://downloads.arachni-scanner.com/nightlies/) please and let me know if the issue has been resolved?

**Comment by 1110532** [comment]
Works like a charm ;)
Thank you.

**Comment by Zapotek** [comment]
No problem.
