### ISSUE TITLE
common_admin_interfaces issue

### ISSUE THREAD

**Issue by corelanc0d3r** [Arachni/arachni#673]
Hi,

The common_admin_interfaces check is missing the cases that involve a 302 redirect from the initial url to the actual admin login page.  In most cases, the redirect goes from `/<adminurl>` to `/<adminurl>/<something>`

thanks

**Comment by Zapotek** [comment]
Can you please try the nightlies and let me know if the issue has been fixed?

Cheers

**Comment by corelanc0d3r** [comment]
tested the nightlies, but the admin interface was not reported.    The login page itself was found though, marked as an unencrypted password form.

**Comment by Zapotek** [comment]
I'm pushing one more nightly and hopefully it'll do the trick, otherwise I'll have to mess with the custom-404 detection system, which I would very much like to avoid because it's really tricky.

I'll let you know once it's up.

**Comment by corelanc0d3r** [comment]
ok, I'll try.  Not sure if it matters, but there is no 404 involved in this one.  The redirect is a 302 (as explained in the initial issue description above)

**Comment by Zapotek** [comment]
Nighlties are up -- fingers crossed.

**Comment by corelanc0d3r** [comment]
something has changed for sure - scan has been running for 40 hours so far (versus 11 hours in the past).. it looks like it's looking for admin interfaces, trying all possible combinations.  I'll keep you posted

**Comment by Zapotek** [comment]
I was afraid of that, I introduced an infinite loop, I'll revert the change.
You can abort the scan.

**Comment by Zapotek** [comment]
Btw, can I get access to the webapp in question?
This process will go a lot faster if I don't have to push nightlies after each change.
You can send me the details via e-mail if you prefer.

Cheers

**Comment by corelanc0d3r** [comment]
you've got mail :)

**Comment by Zapotek** [comment]
I'm pushing some nightlies now with the fix.

**Comment by Zapotek** [comment]
Forgot to mention it, nightlies are up.
Give them a try and let me know how they do.

**Comment by corelanc0d3r** [comment]
confirmed, it now correctly finds the admin interface... but it does no longer report the fact that it contains a cleartext password form or anything like that.

**Comment by Zapotek** [comment]
Was the issue marked as untrusted by any chance?

**Comment by corelanc0d3r** [comment]
not that I recall, but as I can't see the issue (and I have deleted all previous scans against that website), is there any way to tell ?

**Comment by Zapotek** [comment]
I'll try to reproduce but since the page wasn't pushed back to the system it must have been marked as untrusted.

**Comment by Zapotek** [comment]
Nope, it was trusted, looking into it.
You hadn't set any scope limits, had you?

**Comment by Zapotek** [comment]
Nevermind, figured it out.
It's because only one issue of that type was logged, so if it was an FP the system wouldn't have enough data to determine it.
So it gets marked as `Trusted` because there's no evidence that it's not, but the system is not taking the risk of pushing the page to the Framework to avoid possible infinite loops in case custom 404-detection has failed.

Not sure if I need to change this, I've coded it this way for a good reason (i.e. no inf loops).

**Comment by Zapotek** [comment]
On the other hand, if custom-404 detection had indeed failed there probably wouldn't just be only one FP, there would be many.

Hm..
