### ISSUE TITLE
there is space character in afr filename

### ISSUE THREAD

**Issue by deltay** [Arachni/arachni#678]
The report file name like:
" 192.168.0.1 2016-02-24 15_49_50 +0700.afr"
Maybe we can replace " " with  "_" .

**Comment by Zapotek** [comment]
I could do that, is it just for convenience or is there a serious reason behind this?

**Comment by Zapotek** [comment]
I'm afraid I'll need some justification for keeping this issue open, could you please elaborate as to why you need this change?

Cheers
