### ISSUE TITLE
Supplying NTLM based credentials in the URL causes an error

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#684]
Providing a URL such as:
http://domain\username:password@192.168.1.1/login.aspx

Causes the following exception to get triggered:
```
[-] [ui/cli/framework#run:112] [URI::InvalidURIError] bad URI(is not URI?): http://domain\username:password@192.168.1.1/login.aspx
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/usr/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/usr/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/usr/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/usr/lib/ruby/2.2.0/uri/common.rb:713:in `URI'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/lib/arachni/report.rb:149:in `save'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/ui/cli/framework.rb:378:in `generate_reports'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/ui/cli/framework.rb:94:in `run'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/ui/cli/framework.rb:49:in `initialize'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/bin/arachni:12:in `new'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/system/gems/bundler/gems/arachni-14c314f80053/bin/arachni:12:in `<top (required)>'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/bin/../system/arachni-ui-web/bin/arachni:16:in `load'
 [-] [ui/cli/framework#run:112] /root/arachni-2.0dev-1.0dev-2016-02-18/bin/../system/arachni-ui-web/bin/arachni:16:in `<main>'

```
In addition, its not clear if the NTLM is being handled or not, but from the output coming back of:
`HTTP/1.1 401 Unauthorized`

It appears it is not

**Comment by Zapotek** [comment]
Hello,

Better use the [authentication options](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#http-authentication).
Let me know if that solves your problem.

Cheers

**Comment by nrathaus** [comment]
Hi,

I tried, while the report generation and scan appear to complete without error, I don't believe authentication is being preformed

I see that the GET response is being sent without the NTLM authentication and the responses are still showing 401 Unauthorized

Is there some verbose "way" to see if it is even trying to NTLM authenticate?

**Comment by Zapotek** [comment]
I could update the system to print out that data, currently the debugging output doesn't include raw HTTP traffic.
HTTP authentication by default is set to auto and handled by `libcurl` so it should have worked.

Btw, is it NTLM or NTLMv2?

**Comment by Zapotek** [comment]
Try running the following as:

    ./bin/arachni_script ntlm.rb

```ruby
URL      = 'http://192.168.1.1/'
USERNAME = 'domain\username'
PASSWORD = 'password'

response = Typhoeus.get(
    URL,
    userpwd: "#{USERNAME}:#{PASSWORD}",
    httpauth: :ntlm,
    verbose: true
)

ap response.code
ap response.headers
puts response.body
ap response.debug_info

ap '-' * 100

response = Typhoeus.get(
    URL,
    userpwd:  "#{USERNAME}:#{PASSWORD}",
    httpauth: :auto,
    verbose: true
)

ap response.code
ap response.headers
puts response.body
ap response.debug_info
```

**Comment by nrathaus** [comment]
Hi,

Using:
 curl --verbose --ntlm -u domain\\username:password
http://192.168.1.1/login.aspx

Works, however, not specifying --ntlm, fails.

I see in the curl trace, that Basic authentication was attempted.

Adding --anyauth also fails, with curl complaining that its not able to
find a protocol to negotiate authentication - which is strange as the
response includes "WWW-Authenticate: NTLM".

So appears to be that only if I will pass NTLM, curl will properly work.

Maybe Arachni should allow users to pick what Auth Mechanism to use?


On Tue, Mar 1, 2016 at 4:16 PM, Tasos Laskos <notifications@github.com>
wrote:

> I could update the system to print out that data, currently the debugging
> output doesn't include raw HTTP traffic.
> HTTP authentication by default is set to auto and handled by libcurl so
> it should have worked.
>
> Btw, is it NTLM or NTLMv2?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/684#issuecomment-190737485>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

Using ntlm.rb it works

See my notes about curl not auto-detecting NTLM


On Tue, Mar 1, 2016 at 4:24 PM, Tasos Laskos <notifications@github.com>
wrote:

> Try running the following as:
>
> ./bin/arachni_script ntlm.rb
>
> URL      = 'http://192.168.1.1/'USERNAME = 'domain\username'PASSWORD = 'password'
>
> response = Typhoeus.get(
>     URL,
>     userpwd: "#{USERNAME}:#{PASSWORD}",
>     httpauth: :ntlm,
>     verbose: true
> )
>
> ap response.code
> ap response.headers
> puts response.body
> ap response.debug_info
>
> ap '-' * 100
>
> response = Typhoeus.get(
>     URL,
>     userpwd:  "#{USERNAME}:#{PASSWORD}",
>     httpauth: :auto,
>     verbose: true
> )
>
> ap response.code
> ap response.headers
> puts response.body
> ap response.debug_info
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/684#issuecomment-190740124>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
The script performs 2 requests in different ways, do both succeed or just the first one?

**Comment by nrathaus** [comment]
Hi,

Both are showing the same outcome, though the @messages array isn't the same

```
302
{
                "Cache-Control" => "private",
               "Content-Length" => "139",
                 "Content-Type" => "text/html; charset=utf-8",
                     "Location" => "/default.aspx",
                       "Server" => "Microsoft-IIS/7.5",
             "X-AspNet-Version" => "4.0.30319",
                       "REQ_ID" => "2948411f-842c-4975-ab12-e318105d6f11",
              "X-UA-Compatible" => "IE=8;IE=9;IE=10",
                   "Set-Cookie" => "ReqClientId=27a8be39-81ee-4b6b-a44a-2c1d7072990b; expires=Mon, 01-Mar-2066 14:38:49 GMT; path=/; HttpOnly",
              "Persistent-Auth" => "true",
                 "X-Powered-By" => "ASP.NET",
    "Strict-Transport-Security" => "max-age=31536000",
                         "Date" => "Tue, 01 Mar 2016 14:38:48 GMT"
}
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/default.aspx">here</a>.</h2>
</body></html>
#<Ethon::Easy::DebugInfo:0x04f7cea8
    @messages = [
        [0] #<Ethon::Easy::DebugInfo::Message:0x04f9ff70
            attr_reader :message = "GET / HTTP/1.1\r\nHost: 192.168.1.1\r\nAuthorization: NTLM ...=\r\nAccept: */*\r\nUser-Agent: Typhoeus - https://github.cotyphoeus/typhoeus\r\n\r\n",
            attr_reader :type = :header_out
        >,
        [1] #<Ethon::Easy::DebugInfo::Message:0x04f9f7f0
            attr_reader :message = "GET / HTTP/1.1\r\nHost: 192.168.1.1\r\nAuthorization: NTLM ...+...+.../...+.../...==\r\nAccept: */*\r\nUser-Agent: Typhoeus - https://github.cotyphoeus/typhoeus\r\n\r\n",
            attr_reader :type = :header_out
        >
    ]
>
"----------------------------------------------------------------------------------------------------"
302
{
                "Cache-Control" => "private",
               "Content-Length" => "139",
                 "Content-Type" => "text/html; charset=utf-8",
                     "Location" => "/default.aspx",
                       "Server" => "Microsoft-IIS/7.5",
             "X-AspNet-Version" => "4.0.30319",
                       "REQ_ID" => "2c5862a6-ad28-498e-84c5-b465b6718057",
              "X-UA-Compatible" => "IE=8;IE=9;IE=10",
                   "Set-Cookie" => "ReqClientId=7bdc8ade-cd2c-4af8-bb72-75a90e9512c2; expires=Mon, 01-Mar-2066 14:38:49 GMT; path=/; HttpOnly",
              "Persistent-Auth" => "true",
                 "X-Powered-By" => "ASP.NET",
    "Strict-Transport-Security" => "max-age=31536000",
                         "Date" => "Tue, 01 Mar 2016 14:38:48 GMT"
}
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/default.aspx">here</a>.</h2>
</body></html>
#<Ethon::Easy::DebugInfo:0x04f9e418
    @messages = [
        [0] #<Ethon::Easy::DebugInfo::Message:0x04fbc5a8
            attr_reader :message = "GET / HTTP/1.1\r\nHost: 192.168.1.1\r\nAccept: */*\r\nUser-Agent: Typhoeus - https://github.cotyphoeus/typhoeus\r\n\r\n",
            attr_reader :type = :header_out
        >
    ]
>

```

**Comment by Zapotek** [comment]
Arg, I'm guessing libcurl remembers the auth from the previous request, my bad.

What does this show?

```ruby
response = Typhoeus.get(
    URL,
    userpwd:  "#{USERNAME}:#{PASSWORD}",
    httpauth: :auto,
    verbose: true
)

ap response.code
ap response.headers
puts response.body
ap response.debug_info
```

**Comment by nrathaus** [comment]
Fails to authenticate

Thanks,
Noam Rathaus
CTO
Beyond Security

**Comment by Zapotek** [comment]
It's settled then, I'll expose an auth type option.

Thanks for the feedback,

**Comment by nrathaus** [comment]
No problem


On Tue, Mar 1, 2016 at 5:13 PM, Tasos Laskos <notifications@github.com>
wrote:

> It's settled then, I'll expose an auth type option.
>
> Thanks for the feedback,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Arachni/arachni/issues/684#issuecomment-190763551>.
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

I found a "1" line change that "solves" the bug, probably breaks HTTP basic
(probably others)
inside system/gems/gems/arachni-1.4/lib/arachni/http/request.rb:
options[:httpauth] = :auto

to
options[:httpauth] = :ntlm



On Tue, Mar 1, 2016 at 5:17 PM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> No problem
>
>
> On Tue, Mar 1, 2016 at 5:13 PM, Tasos Laskos <notifications@github.com>
> wrote:
>
>> It's settled then, I'll expose an auth type option.
>>
>> Thanks for the feedback,
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Arachni/arachni/issues/684#issuecomment-190763551>.
>>
>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by Zapotek** [comment]
Yeah that'd break all others, that's where the option's value will go though.

**Comment by Zapotek** [comment]
Nightlies are up, FYI the change is not in the WebUI yet.
