### ISSUE TITLE
Accessing /profiles/new (New Profile) returns "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by nrathaus** [Arachni/arachni#685]
Hi,

I just tried it on the dev version from 2016-02-18, stable appears to not have this issue

The web interface is not very informative just states:
`10.9.8.1 - - [01/Mar/2016:14:34:18 +0000] "GET /500 HTTP/1.1" 500 643 0.0548`

**Comment by Zapotek** [comment]
The details will be in `system/logs/webui/production.log`.
This tracker is for the Framework though, WebUI issues should be reported at: https://github.com/Arachni/arachni-ui-web/issues
