### ISSUE TITLE
CPLUS_INCLUDE_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/include"

### ISSUE THREAD

**Issue by techanonhacker** [Arachni/arachni#686]
the error text is:- (i have removed the scanned website , and url.com is added as a replacement for it)

2016-03-01 20:50:11 -0500 --------------------------------------------------------------------------------
ENV:
---
CPLUS_INCLUDE_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/include"
XDG_VTNR: '2'
XDG_SESSION_ID: '1'
SSH_AGENT_PID: '1206'
GEM_HOME: "/root/Templates/arachni-1.4-0.5.10/system/gems"
VTE_VERSION: '4204'
XDG_MENU_PREFIX: gnome-
SHELL: "/bin/bash"
TERM: xterm-256color
IRBRC: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/.irbrc"
LIBRARY_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_LINUX_ACCESSIBILITY_ALWAYS_ON: '1'
GJS_DEBUG_OUTPUT: stderr
WINDOWID: '16777222'
MY_RUBY_HOME: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby"
GJS_DEBUG_TOPICS: JS ERROR;JS LOG
GTK_MODULES: gail:atk-bridge
USER: root
LD_LIBRARY_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
QT_ACCESSIBILITY: '1'
LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
SSH_AUTH_SOCK: "/run/user/0/keyring/ssh"
USERNAME: root
SESSION_MANAGER: local/user:@/tmp/.ICE-unix/1149,unix/user:/tmp/.ICE-unix/1149
DESKTOP_SESSION: default
PATH: "/root/Templates/arachni-1.4-0.5.10/system/gems/bin:/root/Templates/arachni-1.4-0.5.10/bin/../system/../bin:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/bin:/root/Templates/arachni-1.4-0.5.10/bin/../system/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
C_INCLUDE_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/include"
PWD: "/root/Templates/arachni-1.4-0.5.10/bin"
XDG_SESSION_TYPE: x11
ARACHNI_WEBUI_LOGDIR: "/root/Templates/arachni-1.4-0.5.10/bin/../system/logs/webui"
LANG: en_US.UTF-8
GDM_LANG: en_US.UTF-8
ARACHNI_FRAMEWORK_LOGDIR: "/root/Templates/arachni-1.4-0.5.10/bin/../system/logs/framework"
GDMSESSION: default
HOME: "/root/Templates/arachni-1.4-0.5.10/bin/../system/home/arachni"
XDG_SEAT: seat0
SHLVL: '1'
RAILS_ENV: production
GNOME_DESKTOP_SESSION_ID: this-is-deprecated
DYLD_LIBRARY_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib:/usr/lib:/usr/local/lib"
LOGNAME: root
XDG_SESSION_DESKTOP: default
GEM_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/gems"
DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/0/bus
XDG_DATA_DIRS: "/usr/share/gnome:/usr/local/share/:/usr/share/"
WINDOWPATH: '2'
DISPLAY: ":0"
XDG_RUNTIME_DIR: "/run/user/0"
XDG_CURRENT_DESKTOP: GNOME
RUBYLIB: "/root/Templates/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/lib:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/2.2.0/x86_64-linux:/root/Templates/arachni-1.4-0.5.10/bin/../system/usr/lib/ruby/site_ruby/2.2.0/x86_64-linux"
RUBY_VERSION: ruby-2.2.3
XAUTHORITY: "/run/user/0/gdm/Xauthority"
RACK_ENV: development
BUNDLE_GEMFILE: "/root/Templates/arachni-1.4-0.5.10/system/arachni-ui-web/Gemfile"
_ORIGINAL_GEM_PATH: "/root/Templates/arachni-1.4-0.5.10/bin/../system/gems"
BUNDLE_BIN_PATH: "/root/Templates/arachni-1.4-0.5.10/system/gems/gems/bundler-1.11.2/exe/bundle"
RUBYOPT: "-rbundler/setup"
MANPATH: "/root/Templates/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
BUNDLE_ORIG_MANPATH: "/root/Templates/arachni-1.4-0.5.10/system/gems/gems/kramdown-1.4.1/man"
--------------------------------------------------------------------------------
OPTIONS:
---
session: {}
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
datastore:
  token: a1c2333591b7c88737295fcc2f087fd0
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url.com
--------------------------------------------------------------------------------
[2016-03-01 20:50:11 -0500] [HTTP: 0] http://www.url..com/site/scripts/google_results.php?q=Search
[2016-03-01 20:50:11 -0500] [operation_timedout] Timeout was reached

**Comment by Zapotek** [comment]
It was just a timed out request not a bug, nothing to worry about.

Cheers
