### ISSUE TITLE
[Windows] Connection closed 

### ISSUE THREAD

**Issue by nliplace** [Arachni/arachni#687]
```
`Connection closed [A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied. - SSL_connect]
--------------------------------------------------------------------------------
E:/arachni-1.4-0.5.10-windows-x86_64/system/arachni-ui-web/app/models/scan.rb:528:in `block in refresh'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/proxy.rb:58:in `call'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/proxy.rb:58:in `block (2 levels) in translate'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/client/handler.rb:100:in `call'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-rpc-0.2.1.3/lib/arachni/rpc/client/handler.rb:100:in `on_close'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection.rb:179:in `close'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:93:in `rescue in _connect'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor/connection/tls.rb:79:in `_connect'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:564:in `block in process_connections'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:563:in `each'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:563:in `process_connections'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:316:in `block in run'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `loop'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:307:in `run'
E:/arachni-1.4-0.5.10-windows-x86_64/system/ruby/lib/ruby/gems/2.2.0/gems/arachni-reactor-0.1.1/lib/arachni/reactor.rb:349:in `block in run_in_thread'
********************************************************************************
`
```

Any ideea why I am getting this on a specific website?

**Comment by Zapotek** [comment]
That error doesn't really have to do anything with the website, nor the scan at all to be honest.
This is just for the RPC connections used to control the scanner and get progress data.

It's conceivable that a particular website could require a large amount of sockets in general that are being used by multiple subsystems and when it comes time for a progress update there are no available sockets due to a limit being reached, although that would probably trigger a different error and I don't know whether MS Windows behaves that way in the first place.

Alternatively, the system is designed to retry on these failures, but, if MS Windows raises a different exception type from the ones I've seen before that would cause the system to just propagate the error instead of just retrying, resulting in the behaviour you're seeing.

Also, are you sure that this is happening for that specific website and it's nor generally intermittent?

Also, can you provide some information about your OS and system resources?

Cheers

**Comment by Zapotek** [comment]
Also, pushing some nightlies now that will include the exception type in the error messages, that should help me narrow down the issue.
I'll let you know once they're up so that you can retry.

Cheers

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up, give them a try and let me know what the error message says this time.

Cheers

**Comment by nliplace** [comment]
Thank you @Zapotek!  

System resources: 
Windows 10 Pro. x64 + SSD + 8 Gb Ram + i7-4510U

> Also, are you sure that this is happening for that specific website and it's nor generally intermittent?

As weird as it may sound ... yes (10 tests ok 1 bad)

And I will provide the info regarding nightlies soon.

**Comment by Zapotek** [comment]
Btw, could you check with the process manager while the scan is running and also after you get that error and see if any processes die?
The situation may be as simple as the website making the scanner crash for some reason -- unlikely but could happen, again, the error would have been different, but I'd like to make sure.

Also, you can find error logs under `system\logs\framework\`, these can contain helpful info.

Cheers

**Comment by nliplace** [comment]
I have 3 error logs on that day and for security purpeses I can provide you only the Options and the last 2 lines (+ blackout).

**#1**
--------------------------------------------------------------------------------
OPTIONS:
---
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  token: 2ae4346ebbcd3ad7653158a1ebe39c5e
  master_priv_token: b8f6cc3b57e96f2464cafe821f2a226d
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  page_limit: 0
session: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  healthmap: {}
  timing_attacks: {}
no_fingerprinting: false
authorized_by: 
url: https://xxxxxxxxxxxx.xxx
--------------------------------------------------------------------------------
[2016-03-09 11:33:34 +0200] [HTTP: 200] https://xxxxxxxxxxxxx/xxx/xxx.pdf
[2016-03-09 11:33:34 +0200] [filesize_exceeded] Maximum file size exceeded

**#2**

--------------------------------------------------------------------------------
OPTIONS:
---
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: false
  forms: false
  cookies: false
  jsons: false
  xmls: false
  ui_forms: false
  ui_inputs: false
  headers: false
  with_both_http_methods: false
  cookies_extensively: false
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  token: 153ebcb4e6ea226dce0f1b312a1410e8
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
input:
  values: {}
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
  include_subdomains: false
  exclude_binaries: false
  https_only: false
session: {}
checks:
- os_cmd_injection
- os_cmd_injection_timing
- source_code_disclosure
- captcha
- emails
- htaccess_limit
- private_ip
- unencrypted_password_forms
platforms: []
plugins: {}
no_fingerprinting: false
authorized_by: 
url: https://xxxxxxxxxxxx.xxx
--------------------------------------------------------------------------------
[2016-03-09 11:29:54 +0200] [HTTP: 200] https://xxxxxxxxxxxxxxxxxxxxx.xxx/xxxxx.pdf
[2016-03-09 11:29:54 +0200] [filesize_exceeded] Maximum file size exceeded

**#3**

--------------------------------------------------------------------------------
OPTIONS:
---
audit:
  parameter_values: true
  exclude_vector_patterns: []
  include_vector_patterns: []
  link_templates: []
  links: true
  forms: true
  cookies: true
  jsons: true
  xmls: true
  ui_forms: true
  ui_inputs: true
browser_cluster:
  local_storage: {}
  wait_for_elements: {}
  pool_size: 6
  job_timeout: 25
  worker_time_to_live: 100
  ignore_images: false
  screen_width: 1600
  screen_height: 1200
datastore:
  token: fd6b5f45ac7e4919d9704dcad4f3201e
http:
  user_agent: Arachni/v1.4
  request_timeout: 10000
  request_redirect_limit: 5
  request_concurrency: 20
  request_queue_size: 100
  request_headers: {}
  response_max_size: 500000
  cookies: {}
input:
  values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  default_values:
    name: arachni_name
    user: arachni_user
    usr: arachni_user
    pass: 5543!%arachni_secret
    txt: arachni_text
    num: '132'
    amount: '100'
    mail: arachni@email.gr
    account: '12'
    id: '1'
  without_defaults: true
  force: false
scope:
  redundant_path_patterns: {}
  dom_depth_limit: 5
  exclude_file_extensions: []
  exclude_path_patterns: []
  exclude_content_patterns: []
  include_path_patterns: []
  restrict_paths: []
  extend_paths: []
  url_rewrites: {}
session: {}
checks:
- allowed_methods
- backdoors
- backup_directories
- backup_files
- captcha
- code_injection
- code_injection_php_input_wrapper
- code_injection_timing
- common_admin_interfaces
- common_directories
- common_files
- cookie_set_for_parent_domain
- credit_card
- csrf
- cvs_svn_users
- directory_listing
- emails
- file_inclusion
- form_upload
- hsts
- htaccess_limit
- html_objects
- http_only_cookies
- http_put
- insecure_client_access_policy
- insecure_cookies
- insecure_cors_policy
- insecure_cross_domain_policy_access
- insecure_cross_domain_policy_headers
- interesting_responses
- ldap_injection
- localstart_asp
- mixed_resource
- no_sql_injection
- no_sql_injection_differential
- origin_spoof_access_restriction_bypass
- os_cmd_injection
- os_cmd_injection_timing
- password_autocomplete
- path_traversal
- private_ip
- response_splitting
- rfi
- session_fixation
- source_code_disclosure
- sql_injection
- sql_injection_differential
- sql_injection_timing
- ssn
- trainer
- unencrypted_password_forms
- unvalidated_redirect
- unvalidated_redirect_dom
- webdav
- x_frame_options
- xpath_injection
- xss
- xss_dom
- xss_dom_script_context
- xss_event
- xss_path
- xss_script_context
- xss_tag
- xst
- xxe
platforms: []
plugins:
  autothrottle: {}
  discovery: {}
  healthmap: {}
  timing_attacks: {}
  uniformity: {}
no_fingerprinting: false
authorized_by: 
url: https://xxxxxxxx.xxx
--------------------------------------------------------------------------------
[2016-03-09 13:26:08 +0200] [HTTP: 0] https://xxxxxxxxxxxxxxxxxxx.xxx/xxxxxxxx.jspx?errorCode=_arachni_trainer_8cd8086a26278bd1e2f74aff17c95d09&_afrLoop=4313022994923656&_afrWindowMode=0&_afrWindowId=null
[2016-03-09 13:26:08 +0200] [operation_timedout] Timeout was reached


I did not forget you with the Nightlies I just need a few more days ;)

**Comment by Zapotek** [comment]
These are normal, let me know once you try the nightlies.

**Comment by Zapotek** [comment]
Any news on this?

**Comment by Zapotek** [comment]
Couldn't reproduce so closing due to lack of feedback.
