### ISSUE TITLE
prompt error of `load': undefined class/module Set (ArgumentError) when upgrade to arachni 1.4

### ISSUE THREAD

**Issue by dleyanlin** [Arachni/arachni#692]
[!!] [http/proxy_server#start_async:50] ProxyServer: Starting
 [!!] [http/proxy_server#start_async:63] ProxyServer: Started
 [!] [browser#spawn_phantomjs:1277] BrowserCluster Worker#70161493795760: Spawning PhantomJS...
 [!] [browser#spawn_phantomjs:1290] BrowserCluster Worker#70161493795760: Attempt #0, chose port number 61968
 [!] [browser#spawn_phantomjs:1294] BrowserCluster Worker#70161493795760: Spawning process: /Users/psoqa/.rvm/bin/phantomjs
 [!] [browser#spawn_phantomjs:1315] BrowserCluster Worker#70161493795760: Process spawned, waiting for it to boot-up...
 [!] [browser#spawn_phantomjs:1333] BrowserCluster Worker#70161493795760: Spawn timed-out.
 [!] [browser#spawn_phantomjs:1337] BrowserCluster Worker#70161493795760: /.rvm/gems/ruby-2.2.1/gems/arachni-1.4/lib/arachni/processes/executables/base.rb:3:in `load': undefined class/module Set (ArgumentError)
	from /.rvm/gems/ruby-2.2.1/gems/arachni-1.4/lib/arachni/processes/executables/base.rb:3:in `<main>'

**Comment by Zapotek** [comment]
Hello,

Can you please try the [official packages](http://www.arachni-scanner.com/download/)?
They are pretty much guaranteed to bypass environmental issues like these.

Cheers

**Comment by dleyanlin** [comment]
why use 1.3.2 is ok in the same environment?
i use arachni framework

**Comment by Zapotek** [comment]
So long as you use the packages you can use multiple versions without conflict.

**Comment by dleyanlin** [comment]
i uninstall arachni 1.4 version and install arachni 1.3.2 is ok 

when i debug i find may be the following code is causing the problem:

when implement Marshal.load( Base64.strict_decode64(ARGV.pop ) ) in base.rb
     
 for example:
      when u run Marshal.load("\004\010c\010Set") under irb

will prompt error ArgumentError: undefined class/module Set

**Comment by Zapotek** [comment]
Can you show me the configuration please?
