### ISSUE TITLE
Please ignore combine directories

### ISSUE THREAD

**Issue by ecoitsolutions** [Arachni/arachni#694]
The combine directories are often used to compress and minify web applications especially created using frameworks such laravel, codeigniter and so on. Arachni has seen that my /combine/ directory is made of backup files but there is no backup in there (neither .bck or similar files) only hash filenames conataining js and css minified.

**Comment by Zapotek** [comment]
Hello,

Can you please show me an example of the logged issues?

**Comment by ecoitsolutions** [comment]
Hi there,
 Of course. please see example below, severity is thrown as medium. Thank
you!




A common practice when administering web applications is to create a
copy/backup of a particular directory prior to making any modification.
Another common practice is to add an extension or change the name of the
original directory to signify that it is a backup (examples include .bak,
.orig, .backup, etc.).

During the initial recon stages of an attack, cyber-criminals will attempt
to locate backup directories by adding common extensions onto directories
already discovered on the webserver. By analysing the response headers from
the server they are able to determine if a backup directory exists. These
backup directories can then assist in the compromise of the web application.

By utilising the same method, Arachni was able to discover a possible
backup directory.
Vector typeHTTP methodAction
<#!/issues/untrusted/severity/medium/backup_directories/82839950> server GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511~/
<#!/issues/untrusted/severity/medium/backup_directories/2427866500> server
GET
https://www.ecoit.ro/combine/old_Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/1209648487> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20(another%20copy)/
<#!/issues/untrusted/severity/medium/backup_directories/1917179782> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20(3rd%20copy)/
<#!/issues/untrusted/severity/medium/backup_directories/3132518337> server
GET
https://www.ecoit.ro/combine/Copy%20(2)%20of%20Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/4099151044> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20(4th%20copy)/
<#!/issues/untrusted/severity/medium/backup_directories/1816740444> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/347895100> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20(third%20copy)/
<#!/issues/untrusted/severity/medium/backup_directories/2037875213> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20(copy)/
<#!/issues/untrusted/severity/medium/backup_directories/1745817714> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20-%20Copy%20(2)/
<#!/issues/untrusted/severity/medium/backup_directories/1714523880> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/2027735642> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20-%20Copy/
<#!/issues/untrusted/severity/medium/backup_directories/2679747354> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511%20-%20Copy%20Copy/
<#!/issues/untrusted/severity/medium/backup_directories/4105001470> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511_old/
<#!/issues/untrusted/severity/medium/backup_directories/2906426359> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511old/
<#!/issues/untrusted/severity/medium/backup_directories/3491159222> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511bak/
<#!/issues/untrusted/severity/medium/backup_directories/785264900> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511_backup/
<#!/issues/untrusted/severity/medium/backup_directories/2634237067> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511_inc/
<#!/issues/untrusted/severity/medium/backup_directories/2307329727> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511_bak/
<#!/issues/untrusted/severity/medium/backup_directories/353963677> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511backup/
<#!/issues/untrusted/severity/medium/backup_directories/3297941122> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511inc/
<#!/issues/untrusted/severity/medium/backup_directories/195621600> server
GET
https://www.ecoit.ro/combine/bak_Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/1587484666> server
GET
https://www.ecoit.ro/combine/backup_Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-1458115511/
<#!/issues/untrusted/severity/medium/backup_directories/1930517060> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-14581155111/
<#!/issues/untrusted/severity/medium/backup_directories/1480329607> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-14581155112/
<#!/issues/untrusted/severity/medium/backup_directories/1093089478> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-14581155113/
<#!/issues/untrusted/severity/medium/backup_directories/241610241> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-14581155114/
<#!/issues/untrusted/severity/medium/backup_directories/394108736> server
GET
https://www.ecoit.ro/combine/Copy%20of%20Copy%20of%20b4af33e104c848a5eb92025d14ecbbe0-14581155115/



-- 
Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Tel:           +40/371783679
Web:         https://www.ecoit.ro

**Comment by Zapotek** [comment]
Hm, I see.
Were these issues marked as "Untrusted"?

**Comment by ecoitsolutions** [comment]
Hi there, not all of them only half.
Thanks!

-- 
Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Tel:           +40/371783679
Web:         https://www.ecoit.ro

**Comment by Zapotek** [comment]
Ok, unless there's a bug somewhere, I just need to update the training scenarios of the custom-404 identification system for your case, which should be quite simple.

May I please run the same checks against that website in order to reproduce the issue and verify the fix?

**Comment by ecoitsolutions** [comment]
Of course, i have left the firewall in permissive mode for this purpose.
Thanks!

-- 
Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Tel:           +40/371783679
Web:         https://www.ecoit.ro

**Comment by Zapotek** [comment]
Excellent thank you, I'll keep you posted on my progress.

Cheers

**Comment by ecoitsolutions** [comment]
Thanks!
Cheers

-- 
Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Tel:           +40/371783679
Web:         https://www.ecoit.ro

**Comment by Zapotek** [comment]
In the meantime, you can set the following option to get around the issue: `--scope-exclude-pattern=combine`

**Comment by ecoitsolutions** [comment]
Thank you, will try that later today!
Have a nice day

Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Web:         https://www.ecoit.ro

On 06 Apr 2016, at 22:46, Tasos Laskos <notifications@github.com> wrote:

In the meantime, you can set the following option to get around the issue:
--scope-exclude-pattern=combine

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Arachni/arachni/issues/694#issuecomment-206558990>

**Comment by Zapotek** [comment]
I managed to sort it out, I'll do some more testing and then push the fix and some nightlies for you to test.
I'll let you know once I have a package for you.

**Comment by ecoitsolutions** [comment]
Thank you,
I will wait and test as soon as you push me the updates.
Thank you!

**Comment by Zapotek** [comment]
Nightlies are up, give them a shot.

**Comment by ecoitsolutions** [comment]
Thank you I will and let you know on Monday. Thanks!

Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Web:         https://www.ecoit.ro

On 08 Apr 2016, at 14:40, Tasos Laskos <notifications@github.com> wrote:

Nightlies are up, give them a shot.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Arachni/arachni/issues/694#issuecomment-207417086>

**Comment by Zapotek** [comment]
Damn, forgot to push the commit, my bad, ignore the nightlies for now.
I'll have this sorted by Monday though.

Cheers

**Comment by ecoitsolutions** [comment]
No worries, I will wait for your input then!
Thanks and have a nice weekend!

Lucian Lazar
EcoIT Solutions Srl
E-Mail:      lucian.lazar@ecoit.ro
Web:         https://www.ecoit.ro

On 08 Apr 2016, at 17:53, Tasos Laskos <notifications@github.com> wrote:

Damn, forgot to push the commit, my bad, ignore the nightlies for now.
I'll have this sorted by Monday though.

Cheers

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Arachni/arachni/issues/694#issuecomment-207490433>

**Comment by Zapotek** [comment]
Now they are up for real. :)
