### ISSUE TITLE
Monitor system resources during runtime and automatically adjust settings

### ISSUE THREAD

**Issue by Zapotek** [Arachni/arachni#695]
- [ ] Add `Arachni::Supervisor` (or something) to take system readings every few time intervals, or intervals based on system actions (like page audit, browser-cluster completed job etc.).
  - Should accept conditions (based on `Proc` objects probably) which will be evaluated at those intervals to gauge whether or not action needs to be taken.
- [ ] Conditions should be added by component-specific supervisors, for example `Framework::Supervisor`, `BrowserCluster::Supervisor`, etc.

The general idea is to monitor RAM utilization during scans and perform the following actions when resources start to run low:
- [ ] Adjust HTTP request queue size.
- [ ] Adjust buffer sizes to dump more entries to disk.
- [ ] Adjust cache sizes.
- [ ] Adjust the amount of browser workers.
- [ ] ...and pretty much anything else that can affect resource utilization.

The inverse should also be true, i.e. increasing lowered buffers to their default size once system health has been restored -- let's not ignore outside influences, Arachni will not be the only process on the machine.

**Comment by Zapotek** [comment]
FYI: This can be tricky due to kernel caching, true available RAM may be more than advertised.

**Comment by jeffwdg** [comment]
@Zapotek 
Just want to confirm if this has to be done under profiler class, is that correct?

**Comment by Zapotek** [comment]
No the profiler class is just a debugging tool, this will require quite the rewrite/redesign.

**Comment by samantha-cruz** [comment]
Is there a threshold of RAM consumption before we start adjusting the values? like a percentage of available/total RAM in mind? or would this be a trial and error process?

**Comment by Zapotek** [comment]
Actually, there's not much use bothering with this feature because I didn't take into account something critical, the fact that the Ruby VM doesn't release memory back to the OS.
You can make all the relevant adjustments during runtime, after RAM consumption gets high, but it wouldn't make any difference since the memory wouldn't get freed.
