### ISSUE TITLE
how to run against localhost

### ISSUE THREAD

**Issue by Moradnejad** [Arachni/arachni#699]
I wanted to run arachni_web against a benchmark running on localhost. it is on different port but arachni can't start. Is there anyway to run or can I run cli arachni on localhost?
thanks in advance

**Comment by Zapotek** [comment]
Try `127.0.0.2`

**Comment by Moradnejad** [comment]
my other server is on http://localhost:8443 and i can't access it from 127.0.0.2

**Comment by Moradnejad** [comment]
can't we change arachni host.

**Comment by Zapotek** [comment]
Unfortunately not, `127.0.0.1` and `localhost` are reserved and cannot be scanned.
You'll need to bind the benchmark application to a different address.

**Comment by Moradnejad** [comment]
thanks for the response. do you have any plans maybe just to reserve a few ports of localhost?

**Comment by Zapotek** [comment]
It's the localhost/120.0.0.1 address in general that's the problem, the browser workers bypass their configured proxies and this creates a problem.
