### ISSUE TITLE
The scanner has been logged out in between scan and trying to re-perform login.

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#702]
I am new to Arachni and performing an authenticated scan using below command:

arachni https://example.com --plugin=autologin:url=https://example.com/login,parameters="xyz=login&username=prospectstage1%40gmail.com&password=test123",check="Logout" --scope-exclude-pattern=Logout

After scanning for a while I am getting message in CLI as "The scanner has been logged out" and arachin tried to perform login attempts 5 times.

Would like to know why?

**Comment by Zapotek** [comment]
It depends on the web application, maybe a logout link was followed, you need to exclude resources that can invalidate the session.
Does the logout URL actually have the substring "Logout" in it?
Or, it could be some other functionality of the webapp or a bug in it.

Cheers

**Comment by theinfosecguyPankaj** [comment]
As per arachni document, I searched for keywords like logout in the response to confirm the successful login and to avoid the logout hyperlink link click I again used the text property of logout link.

I am surprised by the behavior of arachni after logout. It first performs a few unsuccessful login attempt and then all of sudden it gets login to the application and resumes the scan.

Not sure why? Your say.

**Comment by theinfosecguyPankaj** [comment]
![1](https://cloud.githubusercontent.com/assets/18594797/14708430/82abc106-07e8-11e6-8582-43342a307588.png)
![2](https://cloud.githubusercontent.com/assets/18594797/14708433/82d6c900-07e8-11e6-8749-21014df853a9.png)

Please refer the screens for your reference

**Comment by Zapotek** [comment]
I was referring to the logout resource that should be matched by the `--scope-exclude-pattern`, is the string "Logout" actually capitalized?
As for the retries I'll see if there's a bug in Arachni.

**Comment by theinfosecguyPankaj** [comment]
![1](https://cloud.githubusercontent.com/assets/18594797/14708451/b087ecc6-07e8-11e6-9040-a93f49014d77.png)
![2](https://cloud.githubusercontent.com/assets/18594797/14708452/b0b3521c-07e8-11e6-94ea-acd01a08fadf.png)

Please refer the screesn for your reference.

**Comment by Zapotek** [comment]
The Windows nightly that includes the fix has been upload.
*nix and OSX nightlies are still uploading.
