### ISSUE TITLE
Add some buttons at the top of the readme

### ISSUE THREAD

**Issue by OlegKi** [Arachni/arachni#703]
Hi!

I see that you work very good with issues and pull requests posted to GitHub. I suggest you to add on top of the [README.md](https://github.com/free-jqgrid/jqGrid) the links like 
```html
[![GitHub pulls](http://issuestats.com/github/Arachni/arachni/badge/pr?style=flat-square)](https://github.com/Arachni/arachni/pulls)
[![GitHub issues](http://issuestats.com/github/Arachni/arachni/badge/issue?style=flat-square)](https://github.com/Arachni/arachni/issues)
&nbsp;
[![GitHub watchers](https://img.shields.io/github/watchers/Arachni/arachni.svg)](https://github.com/Arachni/arachni/watchers)
[![GitHub forks](https://img.shields.io/github/forks/Arachni/arachni.svg)](https://github.com/Arachni/arachni/network)
[![GitHub stars](https://img.shields.io/github/stars/Arachni/arachni.svg)](https://github.com/Arachni/arachni/stargazers)
```

To see the results like

[![GitHub pulls](http://issuestats.com/github/Arachni/arachni/badge/pr?style=flat-square)](https://github.com/Arachni/arachni/pulls)[![GitHub issues](http://issuestats.com/github/Arachni/arachni/badge/issue?style=flat-square)](https://github.com/Arachni/arachni/issues)&nbsp;[![GitHub watchers](https://img.shields.io/github/watchers/Arachni/arachni.svg)](https://github.com/Arachni/arachni/watchers)[![GitHub forks](https://img.shields.io/github/forks/Arachni/arachni.svg)](https://github.com/Arachni/arachni/network)[![GitHub stars](https://img.shields.io/github/stars/Arachni/arachni.svg)](https://github.com/Arachni/arachni/stargazers)

I think, such icons could be good for the visitors.

Best regards
Oleg

**Comment by Zapotek** [comment]
Didn't even know about these, thank you.

**Comment by OlegKi** [comment]
I use such icons myself not so long time too, but I personally find there practical. Some buttons, which uses statistic value, needed be cached first. Thus you could have timeout at opening at the beginning. You can read more on http://issuestats.com/ and http://issuestats.com/analysis. You can examine http://issuestats.com/github/Arachni/arachni or examples from some other well-known repositories. It's important that the links from issuestats.com have HTTP prefix instead of HTTPS and GitGub automatically will wrap the links inside of https://camo.githubusercontent.com/ which is proxy caching via HTTPS picture resources provided only via HTTP. It takes additional time (also at the beginning only).

**Comment by Zapotek** [comment]
Cheers, will have a look at the site.
