### ISSUE TITLE
failed to start phantomjs

### ISSUE THREAD

**Issue by kyodule** [Arachni/arachni#707]
OS: ubuntu 16.04 TLS
Arachni: latest release 1.4
issue: 

```
[!] [browser#spawn_phantomjs:1345] BrowserCluster Worker#30495520: Killing process.
 [!] [browser#spawn_phantomjs:1290] BrowserCluster Worker#30495520: Attempt #1, chose port number 18255
 [!] [browser#spawn_phantomjs:1294] BrowserCluster Worker#30495520: Spawning process: /opt/woobuntu/arachni/bin/../system/usr/bin/phantomjs
 [!] [browser#spawn_phantomjs:1315] BrowserCluster Worker#30495520: Process spawned, waiting for it to boot-up...
 [!] [browser#spawn_phantomjs:1333] BrowserCluster Worker#30495520: Spawn timed-out.
```

```
lorin@lorin-virtual-machine:/opt/woobuntu/arachni/bin$ ./arachni_shell -c 'phantomjs --webdriver=18255'
Fontconfig error: Cannot load default config file
```

after very long time(more than 60s), it will launch success,
```
lorin@lorin-virtual-machine:/opt/woobuntu/arachni/bin$ ./arachni_shell -c 'phantomjs --webdriver=18255'
Fontconfig error: Cannot load default config file
PhantomJS is launching GhostDriver...
[INFO  - 2016-04-22T03:27:43.164Z] GhostDriver - Main - running on port 18255
```

**Comment by Zapotek** [comment]
That's way too long to start a process, what resources does the machine have available?

**Comment by hoopesj** [comment]
Part of the issue may be due to the fact that phantomjs requires some sort of X server to be running in order to work properly:

`$ phantomjs 
QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted (core dumped)
`

I was able to get phantomjs to start working again by installing xvfb and creating the following script in /etc/profile.d/aliases.sh to ensure the alias takes effect system-wide:

`
#!/bin/bash
alias phantomjs="xvfb-run phantomjs"
`

Kind of clunky but at least phantomjs appears to work again:

`
$ source /etc/profile && phantomjs
phantomjs>
`

Hope that helps :)

**Comment by Zapotek** [comment]
Actually, PhantomJS exists so that you don't need an X server running.
People have been using it and Arachni on headless servers without issue.

In your case that should have no effect on Arachni as it bundles its own executables in the package.
What's your setup and PhantomJS version?

**Comment by hoopesj** [comment]
Under normal circumstances, yes you're right phantomjs shouldn't need an X server to work.  Apparently the phantomjs package that comes w/ Ubuntu 16.04 is built to require a running X server and will crash w/o one.

As far as my Arachni setup, it's somewhat unique...I actually prefer to build from source vs use the package to take advantage of the latest security checks.  Currently running:

- Ubuntu 16.04 on EC2
- Built-in Ubuntu package of phantomjs (2.1.1+dfsg-1 amd64)
- Using the Arachni git repo (master branch) leveraging RVM, & ruby 2.3.0.  To avoid gem conflicts, I also created an independent, "ruby-2.3.0@arachni" gemset.  I want to continuously pull in updates via automation as new functionality is merged into the master branch.

**Comment by Zapotek** [comment]
Arachni is meant to work with PhantomJS 1.9.2, anything other than that has not been stable.

**Comment by hoopesj** [comment]
Ah, very good to know...thank you!

**Comment by Zapotek** [comment]
It's interesting that you didn't notice any other issues with PhantomJS v2.1.1, maybe the newest versions will work, I'll have a look at it again.

**Comment by hoopesj** [comment]
I can't say for certain - I've been on 16.04 for a couple days and haven't been able to get Arachni working due to the exact same error described by kyodule.  It worked fine from source on ubuntu 15.10 but I can't recall what version of PhantomJS was installed while running 15.10.

**Comment by hoopesj** [comment]
One more FYI, the same error occurs w/in Arachni as described above, however, it's because Arachni is referencing the absolute path of phantomjs when instantiating Browsers:

```bash
$ alias phantomjs='xvfb-run phantomjs'
$ phantomjs 
phantomjs> ^D
$ /usr/bin/phantomjs
/usr/bin/phantomjs 
QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted (core dumped)
```

```bash
[!] [browser#spawn_phantomjs:1277] BrowserCluster Worker#36307080: Spawning PhantomJS...
[!] [browser#spawn_phantomjs:1290] BrowserCluster Worker#36307080: Attempt #0, chose port number 46445
[!] [browser#spawn_phantomjs:1294] BrowserCluster Worker#36307080: Spawning process: **/usr/bin/phantomjs**
[!] [browser#spawn_phantomjs:1315] BrowserCluster Worker#36307080: Process spawned, waiting for it to boot-up...
[!] [browser#spawn_phantomjs:1333] BrowserCluster Worker#36307080: Spawn timed-out.
[!] [browser#spawn_phantomjs:1337] BrowserCluster Worker#36307080: 18576: Started
PID: 18579
18576: Working
18576: Working
18576: Working
18576: Working
18576: Working
18576: Working
18576: Working
18576: EOF
18576: Exiting
```


So afaict the real issue is how the native package of phantomjs is built for Ubuntu 16.04 that's causing the issue described by kyodule.

Hope that helps!

**Comment by Zapotek** [comment]
Not to sound dismissive, but I only care about the official Arachni packages, as long as they work I'm happy. Anything else is not my concern.

Btw, you can still get updated on experimental and still have a tested env: https://github.com/Arachni/build-scripts#bootstrapsh

And there's also the nightlies: http://downloads.arachni-scanner.com/nightlies/

**Comment by hoopesj** [comment]
Very cool, will take a look...that will likely prove much more useful - thanks Zapotek :)

**Comment by Zapotek** [comment]
The [nightlies](http://downloads.arachni-scanner.com/nightlies/) have been updated to use a larger timeout which should resolve the original issue.
