### ISSUE TITLE
How does Arachni performs Crawling? Does it use any third party plugin/application? If yes, Which one?

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#708]

**Comment by theinfosecguyPankaj** [comment]
I read somewhere that Arachni uses skipfish for crawling, please correct me if this statement is not true.

**Comment by Zapotek** [comment]
Except for PhantomJS which is used to provide the DOM and JS Arachni is self-contained, it doesn't use any other external applications.
