### ISSUE TITLE
Multiple false positives causes unusable web UI

### ISSUE THREAD

**Issue by thomja** [Arachni/arachni#709]
Hello

So I have a scan that has about 1600 false positives all about the same thing. Backup html pages in the form of /something/id.bak etc

All of these causes the web UI to be so slow that it is no longer usable in firefox. Chrome will not open the page due to no SSL certificate I believe.

Thanks

**Comment by Zapotek** [comment]
Hello,

Can you please tell me which version you're using?
Also, if you could run the scan via the CLI and send me the AFR report that would be immensely helpful.

Cheers

**Comment by thomja** [comment]
Sure

Where would you like me to send them? I will rerun the scan later on today.

Thanks

**Comment by Zapotek** [comment]
tasos[dot]laskos[at]arachni-scanner.com

Thanks a lot. :)

**Comment by thomja** [comment]
The results were sent and I have recieved a reply saying that this will be fixed.

Great support! :)

**Comment by Zapotek** [comment]
The fix has been pushed to a new branch which includes general optimizations.
It will take a while for it to make it to the nightlies though i.e. until the `memory-optimizations` branch is merged with `experimental`.

Cheers
