### ISSUE TITLE
webhook_notify plugin error when run rest server against  http://demo.testfire.net/

### ISSUE THREAD

**Issue by deltay** [Arachni/arachni#711]
When I test webhook_notify plugin with daily snapshot, there is an error.

The scan status output segment is:

       "url: http://demo.testfire.net/",
        "--------------------------------------------------------------------------------",
        "[2016-05-06 18:12:37 +0800] [ArgumentError] comparison of Arachni::Issue with Arachni::Issue failed",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/components/plugins/webhook_notify.rb:50:in `sort'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/components/plugins/webhook_notify.rb:50:in `interpolate_variables'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/components/plugins/webhook_notify.rb:23:in `run'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/plugin/manager.rb:75:in `block (3 levels) in run'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/utilities.rb:425:in `call'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/utilities.rb:425:in `exception_jail'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/plugin/manager.rb:73:in `block (2 levels) in run'",
        "[2016-05-06 18:12:37 +0800] ",
        "[2016-05-06 18:12:37 +0800] Parent:",
        "[2016-05-06 18:12:37 +0800] Arachni::RPC::Server::Plugin::Manager",
        "[2016-05-06 18:12:37 +0800] ",
        "[2016-05-06 18:12:37 +0800] Block:",
        "[2016-05-06 18:12:37 +0800] #<Proc:0x00000005702470@/home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/plugin/manager.rb:73>",
        "[2016-05-06 18:12:37 +0800] ",
        "[2016-05-06 18:12:37 +0800] Caller:",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/utilities.rb:425:in `exception_jail'",
        "[2016-05-06 18:12:37 +0800] /home/deltay/system/gems/bundler/gems/arachni-e8983a1d29a2/lib/arachni/plugin/manager.rb:73:in `block (2 levels) in run'",
        "[2016-05-06 18:12:37 +0800] --------------------------------------------------------------------------------"

**Comment by Zapotek** [comment]
Nightlies are up and include the fix, let me know if you still experience the issue.

Cheers
