### ISSUE TITLE
Plus-signs in query of Location header are incorrectly URL-encoded when following a redirect.

### ISSUE THREAD

**Issue by ordinaehs** [Arachni/arachni#712]
I was having trouble getting the login_script plugin to log me into a private site. The login form uses multiple 302 redirects, and the very last one of these fails. The 302 sends a Location-header back with a query-part, containing plus signs (indicating spaces). However, the URL that Arachni then visits next has %2B's (plus sign URL encoded) instead. The server obviously fails the request, and the login fails.

I found a (very bad, don't use in production!) workaround:

Add lib/arachni/http/client.rb, line 520:
`request.url = request.url.gsub('+', ' ')`

This corrects the issue; the redirect then gets followed correctly, and the login_script plugin succeeds. So somewhere along the way, the Location-header gets URL-encoded without being decoded first, causing the plus-signs in the query-part of the URI to be corrupted.

**Comment by Zapotek** [comment]
Thanks for the heads up, I'll look into it.

**Comment by Zapotek** [comment]
May I see the login script please?

**Comment by ordinaehs** [comment]
(Link sent through email.)

**Comment by Zapotek** [comment]
Nightlies are up, let me know how they do.

**Comment by ordinaehs** [comment]
Confirmed fixed! Thanks for the quick response and fix!
