### ISSUE TITLE
Scan fails to start with error: JSON::Ext::Generator is not a module

### ISSUE THREAD

**Issue by cclements** [Arachni/arachni#713]
With today's nightlies:
https://gist.github.com/cclements/d20109ad07c24d004b910ca3ef59d02d

**Comment by Zapotek** [comment]
Looks like a Ruby 2.3.1 issue, I'll go back to 2.2.1 and see if it works.

Thanks for the heads up,

**Comment by Zapotek** [comment]
Pushing nightlies, I'll let you know once they're up.

**Comment by Zapotek** [comment]
I have verified that it was an issue with the new Ruby version, the new packages seem to work fine.
They'll take a 1-1.5 hours to upload so give them a try then.

Cheers
