### ISSUE TITLE
scope option to control  depth first or breadth first when crawling

### ISSUE THREAD

**Issue by deltay** [Arachni/arachni#718]
It would be convenient to add a scope option  which specify depth first or breadth first when crawling

**Comment by Zapotek** [comment]
Why?

**Comment by deltay** [comment]
Yesterday I did a test scan against a simple site which is built with php symfony  framework.
It take a very long time(3 hours) for arachni to go very deep in the symfony library directories, and 
I got nothing valuable because all of the files are CSS,JS and image files.
I know we can set directory deep limit and some exclude pattern parameter to make arachni more efficent, but  I think it's a good idea that crawler can choose to do breadth first  when crawling, especialy for security scan.
 If I'm not wrong, some other scanners provide such parameter to control crawler's behaviour.

**Comment by Zapotek** [comment]
That won't make any difference, even with those options you'd get the full depth, you can just adjust whether it'll happen sooner or later.
What you're describing is a perfect use-case for the exclusion options.

And to make things even more efficient Arachi doesn't have a crawler as such, the workload is exhausted as soon as it becomes available with the effective crawl resulting from a feedback loop between the audit and the browser analysis.

**Comment by deltay** [comment]
I agree with you that for a complete scan, there is no difference.
But for a time limited scan, the result  is different, especially for large web applications.
And yes, time limited scan  is  one case  only.
This issue can be closed if no plan to add such option, :)

**Comment by Zapotek** [comment]
I don't see a difference again, if you abort the scan, regardless of breadth or depth first configuration, you still end up with limited coverage that you don't have much control over.

In your case you're encountering a very specific issue which can be better resolved with the scope exclude option.
Or you can also use the depth-limit option if you don't want to go in too deep and that will give you some real control regarding the coverage.

I don't know whether or not I can force the system to behave in a way to enforce those options, but there doesn't seem to be a need for these features yet.
So closing this for now but if someone has a use-case that requires that sort of behavior I'll of course reconsider.

Cheers
