### ISSUE TITLE
add a query parameter  in  get scan status API  which control whether return detail scan task status info

### ISSUE THREAD

**Issue by deltay** [Arachni/arachni#721]
When I want to return scan task status  using /scans/XXXXXXXXX,
it return very detail info which result in a large http response .
It would be better if there is a query parameter which control whether return detail scan.
Fox example, 
If GET /scans/XXXXXXXXX?detail=yes  or GET /scans/XXXXXXXXX  then return all message as before.
If GET /scans/XXXXXXXXX?detail=no then  do not return seen_errors,seen_sitemap and seen_issues

**Comment by Zapotek** [comment]
Pushing nightlies, will let you know once they're up.

Cheers

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up.
