### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#724]
I've noticed some irregularities while trying out the recent build of Arachni from 20160522.

The scan results are not consistent in at least two ways:

- The number of requests varies from one scan to another 
- The number of issues varies from one scan to another

In a long running scan this could be explained be network latency, server timeouts, etc. but I've reproduced the problem on very short and simple scans with less that 100 requests and only one check enabled.

This is the command I've been running:
`$ arachni [target]  --output-verbose  --scope-restrict-paths=pages.txt  --checks=common_files`

The pages.txt has two paths: the domain root (referring page) and /robots.txt (affected page) 

Sometimes I get one Issue and sometimes zero, I've tried this more than 20 times today to have a good sample size.

I can send you the reports directly if you like and I'm more than happy to help in any way possible.

**Comment by Zapotek** [comment]
Since you're using the `common_files` check results can vary if a request times out because this relies heavily on establishing a server baseline for custom-404 pages.
If a baseline cannot be reliably established the check will bail out.

To be on the safe side, I'd really like to check out the reports: tasos.laskos@gmail.com

**Comment by Zapotek** [comment]
I relaxed the corruption check for the baselines (and mistyped it as "Replaced" in the commit message).
Pushing nightlies now and will let you know once they're up.

Cheers

**Comment by Zapotek** [comment]
Nightlies are up.
