### ISSUE TITLE
Arachni 2 scans in parallel

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#726]
Dear Zapotek,

I tried couple of scans in parallel in same machine in 2 different command prompt. By doing that I observed that scan which I initiated later is going very very slow. 

Is there any way to increase the performance of second scan also?

**Comment by Zapotek** [comment]
Hello,

This has do to more with system resources than Arachni but try this guide: http://support.arachni-scanner.com/kb/general-use/optimizing-for-faster-scans

Cheers

**Comment by theinfosecguyPankaj** [comment]
Dear Laskos,

Sorry for troubling you quite frequently.

I have an observation with me.

I was scanning one application and it was going fine for a few hours. In
between scan it got logged out several times re-logged in (I suspect).
After around 10 hours, it got stuck and when I killed the process and
re-ran the same execution command, it gave me error "no connection could be
made because the target machine actively refused it 127.0.0.1 port 3***7".
But the application was accessible over browsers like chrome.

This morning, when I am running the same scan it is stuck in  [*]
AutoLogin: Logging in, please wait. Not sure why. Its not moving forward.
Would like to have your input.

I would like to have some tips from you to avoid frequent logout between
the scans. I have used below command:

arachni https://xyz.com/login --plugin=exec:during="python
D:\WebAutomation\3rdPartyTools.py" --plugin=autologin:url=
https://xyz.com/login,parameters="username=test123&password=abc567,check="Logout"
--scope-exclude-pattern="logout"

Kindly provide your suggestion.

Thanks in advance.

Regards,
Pankaj
