### ISSUE TITLE
proxy doesn't work for wss. Auto login doesn't work

### ISSUE THREAD

**Issue by marcusx2** [Arachni/arachni#729]
It doesn't work for wss. I get the message "Firefox can't establish a connection to the server at wss://xx.xxx.xxxxx/tel." I tried other browsers as well. OWASP ZAP proxy works fine. Why am I trying to use Arachni then? Because everything is so much better, if only I could log in. I tried the auto login as well. How can I validate a JSON response? Everytime I try it says the check was not found. It seems I can only validate html fields like anchor and stuff, but the problem is all the static files can be accessed even if not authenticated lol(I know that has to be fixed). I just need to check for one of the values of the JSON response when it logs in...how do I do that? I mean there's a POST request with login and password...the response is a JSON. If I put on the check field for example "field:value" it doesn't work...again OWASP ZAP works fine for this...I can crawl the app just fine. But I want to make arachni work because it has a much better UI, generates reports, can schedule and all that.

**Comment by Zapotek** [comment]
Hello,

Is there a chance I can get access to the webapp to see what's going on?

Cheers

**Comment by marcusx2** [comment]
@Zapotek I don't have permission to do that, unfortunately. If it helps, the web application uses Angular. I could almost make the auto plugin work, but it doesn't because all the static files are accessible even if you're not logged in. So it says it logged successfully when it didn't. Is there no way to check for the JSON response when I log in? That would solve the problem. The proxy plugin I think it's more complicated. The app also uses SIP protocol with web socket secure(wss), maybe it has something to do with that. OWASP Zap's proxy works perfectly though, so maybe you could take a look at its [source code](https://github.com/zaproxy/zaproxy)? I'm 99% sure this is a bug, but I don't have enough knowledge to be more specific about it.

**Comment by marcusx2** [comment]
Here's the error I get:

`Firefox can't establish a connection to the server at wss://xxx.xxx.xxx/tel. sip.js:8272:16
Wed Jun 08 2016 15:21:31 GMT-0300 (BRT) | sip.transport | WebSocket connection error: {"isTrusted":true} sip.js:2892:3
Wed Jun 08 2016 15:21:31 GMT-0300 (BRT) | sip.transport | WebSocket disconnected (code: 1006) sip.js:2892:3
Wed Jun 08 2016 15:21:31 GMT-0300 (BRT) | sip.transport | WebSocket abrupt disconnection sip.js:2892:3
"Wed Jun 08 2016 15:21:31 GMT-0300 (BRT) | sip.ua | transport wss://xxx.xxx.xxx/tel failed | connection state set to 2" sip.js:2892:3
disconnected sipjs-service.js:313:9
Wed Jun 08 2016 15:21:31 GMT-0300 (BRT) | sip.ua | next connection attempt in 2 seconds sip.js:2892:3
SIP register failed:  Object { error: Object, msg: "disconnected" } login-service.js:31:13
doLogin/<() login-service.js:31
processQueue() angular.js:14678
scheduleProcessQueue/<() angular.js:14694
$RootScopeProvider/this.$get</Scope.prototype.$eval() angular.js:15922
$RootScopeProvider/this.$get</Scope.prototype.$digest() angular.js:15733
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<() angular.js:15961
completeOutstandingRequest()`

**Comment by Zapotek** [comment]
It could be a proxy issue, I'll have a look at how it handled WebSocket connections.
As for the autologin plugin, you need a check separate from the login response because it needs to be performed periodically to check the session.
Is there no other request that you can make besides grabbing the static files?

Also, in the future please create separate discussions for different issues.

**Comment by marcusx2** [comment]
> It could be a proxy issue, I'll have a look at how it handled WebSocket connections.

> 

Thanks man.

> As for the autologin plugin, you need a check separate from the login response because it needs to be performed periodically to check the session.
Is there no other request that you can make besides grabbing the static files?

> 

I can, but all the responses are JSON. I can't seem to make the autologin work to check for JSON response. There are many requests that only return certain responses if you're logged in, but the responses are all JSON, how do I check that?

> Also, in the future please create separate discussions for different issues.

> 

Sure, sorry about that

**Comment by Zapotek** [comment]
Try setting the [session options](https://github.com/Arachni/arachni/wiki/Command-line-user-interface#session), these will take precedence over the check of the autologin plugin.
You can use them to grab any resource and check if the response includes an identifier signifying the session's validity.

**Comment by marcusx2** [comment]
@Zapotek Like I said, JSON response. Or maybe I'm missing something here. I could do something like this "GET url", and then the response could be something like "{hey:apple}". How do I check for this response? I couldn't check for any JSON responses, only when the response was an html(static) file I could check for a string between a tag, say an anchor tag. But I can't do that. I need to be able to check for JSON responses, not static file responses. I tried using --session-check-pattern but it doesn't work for JSON, just like the autologin. Or maybe I'm not understanding something, in which case could you clarify? Thank you.

**Comment by Zapotek** [comment]
Why wouldn't it work?
You don't need to parse the JSON, just searching for a substring you know to be there if the session is valid would be enough -- you can do that with the check pattern, which is a regexp.

**Comment by marcusx2** [comment]
@Zapotek Ok, so taking the example response  "{hey:apple}", what would be the check pattern? I tried "{hey:apple}", "hey", "apple", nothing works. I mean surely the first option should work, it's the whole response. I don't know why it doesn't...thanks for trying to help.

**Comment by Zapotek** [comment]
They all should have worked, the response must be different.
Try enabling the `--output-debug` flag, that'll show you the response that is being returned.

**Comment by marcusx2** [comment]
@Zapotek So you are right. I get a 401 Unauthorized. I probably need to set the session cookie and use it for the request. I mean when I log in a session cookie is created. When I do requests using postman or curl I need to use the cookie for it to work. So is there a way to use the cookie created when logged in and then do the request right after?

**Comment by Zapotek** [comment]
Cookies are updated automatically, are you sure you are filling in the form properly?
It's hard to help you with that without access to the application.

**Comment by marcusx2** [comment]
@Zapotek Yes I am absolutely sure. Like I said, if I check for a pattern on a html file it "works". If it helps the type of cookie is a bearer token. It the same error I get when I try to curl without providing the token

**Comment by marcusx2** [comment]
@Zapotek I checked the requests on the browser against the request on arachni, arachni doesn't set the Authorization header or the Cookie header, both of which are set by the browser. That is why I get the response {"statusCode":401,"error":"Unauthorized","message":"Missing authentication"}. Bug, maybe?

**Comment by marcusx2** [comment]
@Zapotek I discovered the problem. The cookies are definitely not being set. How can I edit the following login script to set the cookie? I'm already able to get the bearer token, I just don't know how to set it:

response = http.post( 'https://xxx.xxx.xxx/xxx/login',
    parameters:     {
        'email'   => 'xxx-xxx@xxx.com',
        'password' => 'xxx'
    },
    mode:           :sync,
    update_cookies: true
)


bearer = /[a-z0-9]{32}/.match(response.body)[0]


framework.options.session.check_url     = "https://xxx.xxx.xxx/xxx/xxx/xxx"
framework.options.session.check_pattern = /presence/

**Comment by Zapotek** [comment]
`HTTP::Client.update_cookies( name => value )` should do the trick.

**Comment by Zapotek** [comment]
Btw, the `Authorization` header has nothing to do with the form login, it is only set when HTTP level auth is present.

**Comment by marcusx2** [comment]
So I wrote
```
bearer = 'Bearer ' + /[a-z0-9]{32}/.match(response.body)[0]
HTTP::Client.update_cookies( 'Authorization' => bearer)
```

and the request is still
```
GET /xxx/xxx/xxx HTTP/1.1
Host: xxx.xxx.xxx
Accept-Encoding: gzip, deflate
User-Agent: Arachni/v1.4
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,he;q=0.6
```

What am I doing wrong? Thank you.

**Comment by marcusx2** [comment]
Ok so after investigating HTTP::Client, I found that "header" does exactly what I want, it's logging in perfectly now. Now I just wonder if it's actually crawling. If I discover it's not I'll open another issue. The command that worked for me is:

`HTTP::Client.headers['Authorization'] = bearer`

**Comment by Zapotek** [comment]
Good to know, I'll find a place to mention these in the article.

Cheers

**Comment by marcusx2** [comment]
You shouldn't close it though. There is definitely a bug on the proxy, because it doesn't work but OWASP ZAP's proxy does.

**Comment by Zapotek** [comment]
My bad.

**Comment by Zapotek** [comment]
Any chance of checking out the relevant WSS?
You can send me the info [in private](mailto:tasos.laskos@arachni-scanner.com) if you wish.

**Comment by Zapotek** [comment]
Nevermind, found an echo server.

**Comment by Zapotek** [comment]
Pushing nightlies with the fix, will let you know once they're up.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up.
