### ISSUE TITLE
Crawler treats a mailto URI as a relative path

### ISSUE THREAD

**Issue by jkallay1** [Arachni/arachni#730]
I'm getting a false-positive "Missing 'X-Frame-Options' header" issue from a url composed of a mailto URI appended to another url (i.e. http://foo.com/mailto:someone@bar.org). That invalid url results in a 400 response from the target server containing no X-Frame-Options header.

It seems that the crawler isn't parsing the scheme in the URI.

**Comment by Zapotek** [comment]
That's not a false positive, there really was no `X-Frame-Options` on that 400 page, regardless of HTTP code or address.
As for the `mailto:`, that's fair enough, it shouldn't have been followed, I'll work on it and keep you updated.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up and they include the fix.
