### ISSUE TITLE
REST API Monitor Scan Progress with Error

### ISSUE THREAD

**Issue by mvinii94** [Arachni/arachni#731]
When I try to get a Monitor Scan Progress using:

 GET http:/localhost:7331/scans/:id

The output comes the report of the scan, instead of the scan progress.

**Comment by Zapotek** [comment]
It's not the report, it gives you all the progress of the scan since the last time you checked for it, including identified issues, sitemap entries, erorrs etc..

Also, I don't understand why you changed the issue title, are you getting an error?
