### ISSUE TITLE
Fail at start

### ISSUE THREAD

**Issue by umbrella-yuri-komarov** [Arachni/arachni#737]
```
ubuntu@ubuntu-VirtualBox:~/arachni-1.4-0.5.10/bin$ sudo ./arachni http://jc-com.nichost.ru
[sudo] password for ubuntu: 
Arachni - Web Application Security Scanner Framework v1.4
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No checks were specified, loading all.
 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 6 browsers...
 [-] [utilities#exception_jail:428] [Arachni::Browser::Error::Spawn] Could not start the browser process.
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1268:in `spawn_browser'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:1164:in `selenium'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser.rb:197:in `initialize'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `new'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:477:in `block in initialize_workers'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `times'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:476:in `initialize_workers'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/browser_cluster.rb:119:in `initialize'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `new'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework/parts/audit.rb:173:in `audit'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `call'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x000000038822e8@/home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] /home/ubuntu/arachni-1.4-0.5.10/system/gems/gems/arachni-1.4/ui/cli/framework.rb:63:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------


================================================================================


 [+] Web Application Security Report - Arachni Framework

 [~] Report generated on: 2016-06-16 12:22:01 -0400
 [~] Report false positives at: http://github.com/Arachni/arachni/issues

 [+] System settings:
 [~] ---------------
 [~] Version:           1.4
 [~] Audit started on:  2016-06-16 12:20:21 -0400
 [~] Audit finished on: 2016-06-16 12:22:01 -0400
 [~] Runtime:           00:01:40

 [~] URL:        http://jc-com.nichost.ru/
 [~] User agent: Arachni/v1.4

 [*] Audited elements: 
 [~] * Links
 [~] * Forms
 [~] * Cookies
 [~] * XMLs
 [~] * JSONs
 [~] * UI inputs
 [~] * UI forms

 [*] Checks: xss_tag, no_sql_injection, path_traversal, xss_script_context, xss_dom, code_injection_timing, os_cmd_injection_timing, csrf, xss_event, unvalidated_redirect, code_injection_php_input_wrapper, sql_injection, os_cmd_injection, xss_dom_script_context, unvalidated_redirect_dom, file_inclusion, xss_path, sql_injection_timing, xxe, code_injection, ldap_injection, response_splitting, trainer, rfi, sql_injection_differential, session_fixation, source_code_disclosure, no_sql_injection_differential, xss, xpath_injection, localstart_asp, backup_files, backup_directories, allowed_methods, captcha, private_ip, form_upload, hsts, x_frame_options, ssn, password_autocomplete, html_objects, emails, http_only_cookies, credit_card, cvs_svn_users, insecure_cors_policy, cookie_set_for_parent_domain, unencrypted_password_forms, mixed_resource, insecure_cookies, webdav, interesting_responses, insecure_cross_domain_policy_access, origin_spoof_access_restriction_bypass, htaccess_limit, common_admin_interfaces, common_directories, insecure_client_access_policy, backdoors, common_files, http_put, insecure_cross_domain_policy_headers, xst, directory_listing

 [~] ===========================

 [+] 0 issues were detected.


 [~] Report saved at: /home/ubuntu/arachni-1.4-0.5.10/bin/jc-com.nichost.ru 2016-06-16 12_22_01 -0400.afr [0.0MB]
 [~] The scan has logged errors: /home/ubuntu/arachni-1.4-0.5.10/bin/../system/logs/framework/error-2587.log

 [~] Audited 0 pages.

 [~] Duration: 00:01:40
 [~] Processed 0/0 HTTP requests.
 [~] -- 0.0 requests/second.
 [~] Processed 0/0 browser jobs.
 [~] -- 0.0 second/job.

 [~] Burst response time sum     0.0 seconds
 [~] Burst response count        0
 [~] Burst average response time 0.0 seconds
 [~] Burst average               0.0 requests/second
 [~] Timed-out requests          0
 [~] Original max concurrency    20
 [~] Throttled max concurrency   20
```

**Comment by umbrella-yuri-komarov** [comment]
On Mac everything works good

**Comment by Zapotek** [comment]
Can you give the [nightlies](http://downloads.arachni-scanner.com/nightlies/) a shot and see if they make a difference?

**Comment by if412030** [comment]
I've the same problem, how to fix it?

**Comment by if412030** [comment]
I've the same problem, how to fix it?

I've try using nightlies, this is the result :

Arachni - Web Application Security Scanner Framework v2.0dev
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


[~] No checks were specified, loading all.
[~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

[*] Initializing...
[*] Preparing plugins...
[*] ... done.
[*] BrowserCluster: Initializing 6 browsers...
[*] BrowserCluster: Spawned #1 with PID 4116 [lifeline at PID 4113].
[*] BrowserCluster: Spawned #2 with PID 4155 [lifeline at PID 4152].

[-] [utilities#exception_jail:428] [Arachni::Browser::Error::Spawn] Could not start the browser process.
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser.rb:1209:in `spawn_browser'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser.rb:1105:in `selenium'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser.rb:196:in `initialize'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster/worker.rb:52:in `initialize'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster.rb:503:in `new'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster.rb:503:in `block in initialize_workers'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster.rb:502:in `times'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster.rb:502:in `initialize_workers'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/browser_cluster.rb:120:in `initialize'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework/parts/browser.rb:33:in `new'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework/parts/browser.rb:33:in `block in browser_cluster'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework/parts/browser.rb:28:in `browser_cluster'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework/parts/audit.rb:173:in `audit'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework.rb:117:in `block in run'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/utilities.rb:425:in `call'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/utilities.rb:425:in `exception_jail'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework.rb:117:in `run'
[-] [utilities#exception_jail:428] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/ui/cli/framework.rb:63:in `block in run'
[-] [utilities#exception_jail:429] 
[-] [utilities#exception_jail:430] Parent:
[-] [utilities#exception_jail:431] Arachni::Framework
[-] [utilities#exception_jail:432] 
[-] [utilities#exception_jail:433] Block:
[-] [utilities#exception_jail:434] #<Proc:0x0000000394b738@/home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework.rb:117>
[-] [utilities#exception_jail:435] 
[-] [utilities#exception_jail:436] Caller:
[-] [utilities#exception_jail:437] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/utilities.rb:425:in `exception_jail'
[-] [utilities#exception_jail:437] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/lib/arachni/framework.rb:117:in `run'
[-] [utilities#exception_jail:437] /home/if412030/Documents/internship/arachni/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-19e6bc8dca16/ui/cli/framework.rb:63:in `block in run'
[-] [utilities#exception_jail:438] --------------------------------------------------------------------------------
[2J

================================================================================

**Comment by Zapotek** [comment]
@if412030 What are your machine's specs?

**Comment by if412030** [comment]
@Zapotek this is my machine's specs :

Processor	4x Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
Memory	3952MB
Operating System	Ubuntu 16.04 LTS

**Comment by hackstrip** [comment]
Maybe not related.... Did you just run an x64 version on a i386 platform or viceversa?
This solved it for me
My symptoms: 
 - no browser threads starting (htop sees 6 x same PID process)
 - no url visit to any page, scan complete in one minute
Suggestion for future builds (to be checked)
- Create a check to see of system holds correct libs such as /lib/x86_64-linux-gnu/libpthread.so.0

Sidenote:
- Partedmagic live cd 64-bit does not run arachni 64 version (ruby not found? not resolved)
- Clean ubuntu 14.04 LTS install starts arachni just fine.

**Comment by Zapotek** [comment]
@if412030 Are you still having the issue with the latest nightlies? If so, can you please enable `--output-debug` and provide the output?

@hackstrip I'll look into `libpthread`, thanks. If you have any concerns about that please open a different issue.

**Comment by Zapotek** [comment]
I'm closing this since it's an environmental issue, but feel free to comment if you have more feedback.

Thanks
