### ISSUE TITLE
there is a problem running arachni on Kali GNU/Linux Rolling 

### ISSUE THREAD

**Issue by c0d39** [Arachni/arachni#739]
./arachni_web
./arachni_web: line 10: /root/tools/arachni-2.0dev-1.0dev/bin/../system/usr/bin/ruby: cannot execute binary file: Exec format error
./arachni_web: line 10: /root/tools/arachni-2.0dev-1.0dev/bin/../system/usr/bin/ruby: Success
i edited all bash files ( /../system to /system) and put them in root folder of arachni.it solved.but when i run ./arachni-web my localhost:9292 says there is somthing wrong

**Comment by c0d39** [comment]
although it works perfectly on backbox
i can't understand why on kali arachni web has issue...

**Comment by Zapotek** [comment]
Did you download Arachni from Kali's repo?
I'm not really familiar with Kali and it's not unusual for them to provide broken Arachni packages.

**Comment by 3rawkz** [comment]
@c0d39 Confirming your error report... Mine was working fine, had to reinstall kali, so my replication is based on more than likely not your same envio, Im probly missing a lot of deps ... god, I need a new Pc... or construct my own mirror and cron that bad boy daily. Personally, the web ui is the only reason I use arachni though I find it to be the most thourough sit&scan so If I must get used to the terminal to run it so be it ..  
*before I replicate your bin edit mod, going to wait for a repose from the main devs or find the solution... if so will
@Zapotek Correct me  if im wrong OP, But although arachni is Kalis current Rollning repo, to be able to use Arachni you must git'it or get it from their site... I have found for some reason cloneing it from GH, the web ui is missing, So I always DL from their site....

**Comment by Zapotek** [comment]
The Arachni repo doesn't include the WebUI, that lives in its own report.
In general, you should always download the official packages for you architecture rather than trust 3rd parties.

**Comment by 3rawkz** [comment]
well yea kinda noticed that, the web ui exits in the DL from the official site, any other method oif istaled that if tried does include arachni_web

**Comment by Zapotek** [comment]
@3rawkz  If you're having problems with the WebUI you can open up a bug report at: https://github.com/Arachni/arachni-ui-web/issues
