### ISSUE TITLE
Arachni Error: Workload exhausted, waiting for new pages from the browser-cluster...

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#740]
Dear Zapotek,

I am getting below error while running Arachni... 

[*] Workload exhausted, waiting for new pages from the browser-cluster...
[~] BrowserCluster: Pending jobs: 3
[~] BrowserCluster: Pending jobs: 2
[~] BrowserCluster: Pending jobs: 4
[~] BrowserCluster: Pending jobs: 3
[~] BrowserCluster: Pending jobs: 2
[~] BrowserCluster Worker#65372760: Could not trigger 'onclick' on: <a href="#" onclick="cl();return false;">
[~] BrowserCluster Worker#65372760: Could not trigger 'onclick' on: <a href="#" onclick="go(sDst);return false;">
[~] BrowserCluster: Pending jobs: 1

**Comment by Zapotek** [comment]
Hello, which version are you using/

**Comment by theinfosecguyPankaj** [comment]
getting the same in 1.4 and 2.0 nightlie.

**Comment by Zapotek** [comment]
OK, this isn't actually an error, this usually occurs when the element can no longer be found, it can happen when the page changes and the element can no longer be located.
It's part of normal operation, unless you have reason to suspect otherwise.

**Comment by bethbuhawe** [comment]
I've got the same issue using v1.4-0.5.10 and it's been running for an hour non-stop. Is this normal?

**Comment by Zapotek** [comment]
@bethbuhawe Can you try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) please and see if they fix the issue?

**Comment by bethbuhawe** [comment]
alright.. I'll let you know once done. Thanks.. 

Btw, very quick reponse. Good job :)

**Comment by bethbuhawe** [comment]
Can i ran arachni during jenkins build? From the thread that i've read, normally it is added in Jenkins as a post build action and we're using URL's for the application where the scan should be performed. How about doing a scan on a set of raw codes on jenkins workspace before it gets packaged into a war file. Is this possible?

**Comment by bethbuhawe** [comment]
where can i get the official arachni installer. First one I got was from the site and the 2nd one was using the nightlies that you're referring to. Which specific release can i use which is really official and stable so that we can integrate it in our production.

**Comment by Zapotek** [comment]
@bethbuhawe There's no installer, just the packages. The stable release ones are at the [download](http://www.arachni-scanner.com/download/) page (although at the moment these include known bugs) and the experimental ones are the nightlies (considered unstable but currently contain a lot of fixes).

If you need something stable you'll probably need to wait for the next release (no due date known), or just use the nightlies since these will become the next release and I could use some feedback on them.
