### ISSUE TITLE
Scans are stalling 

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#741]
Hi Tasos

I've been trying the latest nightly build (20160607) out on one of my sites, but unlike older versions of Arachni with the old crawler, the new one stalls during a scan.
It is always happening during this task:
`Response Splitting: Analyzing response #4378 for form input '1467114197282' pointing to: [domain]`
I've tried to leave it for a few hours, but it does not move on from that point.
I can stop the scan with kill signal 2, which will give me a report of the issues found up until that point.

Arachni runs with no parameters: `$ arachni [domain]`
The older version of arachni completes the scan in a few minutes (it's a small site).

**Comment by Zapotek** [comment]
I think I've identified the issue, working to fix it now.

**Comment by dnyrop** [comment]
Awesome :)

**Comment by Zapotek** [comment]
Pushing nightlies,will let you know once they're up.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) are up.
