### ISSUE TITLE
Browser Headers

### ISSUE THREAD

**Issue by robin-williams** [Arachni/arachni#742]
Is there a file I should be looking at to change the headers Arachni is using to make requests? Or can an option be implemented that allows a user to change/add their own browser headers?

**Comment by Zapotek** [comment]
I think that this is the option you're looking for: https://github.com/Arachni/arachni/wiki/Command-line-user-interface#http-user-agent

**Comment by robin-williams** [comment]
Thanks but I was more looking for the Arachni default header it uses.

**Comment by Zapotek** [comment]
These are the defaults which you can override with the option I mentioned earlier:

```
Accept-Encoding: gzip, deflate
User-Agent: Arachni/v2.0dev
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,he;q=0.6
```

**Comment by robin-williams** [comment]
Yes, I got that aspect of it. Where can I find this in the actual code though?

**Comment by Zapotek** [comment]
Ah OK, check out these locations:
* https://github.com/Arachni/arachni/blob/experimental/lib/arachni/http/client.rb#L133
* https://github.com/Arachni/arachni/blob/experimental/lib/arachni/http/request.rb#L794
