### ISSUE TITLE
autologin with JSF application and custom login form is missing a parameter

### ISSUE THREAD

**Issue by rennhard** [Arachni/arachni#743]
I'm using Arachni to analyse a JSF-based Java EE web application. I'm using a custom login form (not the standard Java EE login mechanism with j_security_check). The login form looks as follows in the generated HTML page:

```
<form id="j_idt9" name="j_idt9" method="post" action="/application/faces/view/public/secure/login.xhtml" enctype="application/x-www-form-urlencoded">
<input type="hidden" name="j_idt9" value="j_idt9" />
<table>
<tbody>
<tr>
<td><label>Username:</label></td>
<td><input type="text" name="j_idt9:j_idt12" value="" /></td>
</tr>
<tr>
<td><label>Password:</label></td>
<td><input type="password" name="j_idt9:j_idt14" value="" /></td>
</tr>
<tr>
<td></td>
<td><table>
<tbody>
<tr>
<td><input type="submit" name="j_idt9:j_idt17" value="Login" /></td>
<td><input type="button" onclick="window.location.href='/application/faces/view/public/search.xhtml'; return false;" value="Cancel" /></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<input type="hidden" name="javax.faces.ViewState" id="j_id1:javax.faces.ViewState:0" value="22429881288181446%3A1977379891975889790" autocomplete="off" />
</form>
```

I'm using the autologin option as follows:

```
--plugin=autologin:url=https://192.168.57.130:8181/application/faces/view/admin/admin.xhtml,parameters="j_idt9:j_idt12=USERNAME&j_idt9:j_idt14=PASSWORD",check="Admin Area"
```

Analyzing the login procedure with burp shows the following POST parameters:

```
j_idt9=j_idt9&j_idt9%3Aj_idt12=USERNAME&j_idt9%3Aj_idt14=PASSWORD&javax.faces.ViewState=22429881288181446%3A1977379891975889790
```

That's nearly correct and it would work if Arachni included the additional parameter `j_idt9%3Aj_idt17=Login` that corresponds to `<input type="submit" name="j_idt9:j_idt17" value="Login" />` in the form above:

```
j_idt9=j_idt9&j_idt9%3Aj_idt12=USERNAME&j_idt9%3Aj_idt14=PASSWORD&j_idt9%3Aj_idt17=Login&javax.faces.ViewState=22429881288181446%3A1977379891975889790
```

In fact, if I'm adding that parameter manually in Burp, autologin works.

I guess that's a bug - or am I missing something?

Thanks,
Marc

**Comment by Zapotek** [comment]
The `autologin` plugin will trigger a submit event on the form rather than click the submit button by default.
Can you try also specifying `j_idt9:j_idt17=Login` in the parameters to let the system know to click that button?

**Comment by rennhard** [comment]
Using 

```
--plugin=autologin:url=https://192.168.57.130:8181/Marketplace_v15-web/faces/view/admin/admin.xhtml,parameters="j_idt9:j_idt12=USERNAME&j_idt9:j_idt14=PASSWORD&j_idt9:j_idt17=Login",check="Admin Area"
```

results in the same request: Arachni still does not include `j_idt9:j_idt17=Login` as a POST parameter.

**Comment by Zapotek** [comment]
Could you try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) please?

**Comment by rennhard** [comment]
With the nightly version, it works - thanks!

One issue remains: I'm using `check="Admin Area"` since the HTML page the client gets after successful login includes the following:

```
</head><body>
        <div id="header">
            <h1>Admin Area</h1>
        </div>
```

Nevertheless, Arachni reports `AutoLogin: The response did not match the verifier.` Adapting this to `check="."` works (of course) and Arachni uses the correct session ID of the authenticated session.

Do I understand something wrong with the `check` parameter?

**Comment by Zapotek** [comment]
You may need to explicitly set a check URL in case there's a redirect or something, check out the `--session-check-url` and `--session-check-pattern` options.
`--session-check-pattern` will override the `check` option of the `autologin` plugin.

**Comment by rennhard** [comment]
Thanks for the hint, and indeed it works when using `--session-check-url=https://192.168.57.130:8181/application/faces/view/admin/admin.xhtml --session-check-pattern="Admin Area"`.

It's still strange the `check` option of `autologin` does not work because there's no redirection involved.

**Comment by Zapotek** [comment]
Glad to hear it.
You can enable `--output-debug` to see what's going on if you're curious.

Cheers
