### ISSUE TITLE
issue: scan started through REST API trapped in cleanup state

### ISSUE THREAD

**Issue by xunrui** [Arachni/arachni#744]
Scan settings:
1. The target url is set to one that cannot be resolved.
2. With plugins: health-map and waf-detector

version 1.4-0.5.10

Observed:
1. Attached is the json file returned by REST API: GET /scans/:id 
[getScans.json.txt](https://github.com/Arachni/arachni/files/351934/getScans.json.txt)

2. webui server is started by the scan, the production.log (in system/logs/webui) is appended with the following 3 lines about every 5 sec:
ScanManager#keep_schedule
ScanManager#refresh
DispatcherManager#refresh

**Comment by Zapotek** [comment]
`status` can be the last active status, you should be checking the `busy` key to check if the scan is done.
When `busy` is `false` it means that the scan is done.

**Comment by xunrui** [comment]
Thanks for your reply!
I will do that check to workaround, but is it expected that the webui server is started? I am worrying this might relate to some bug.

**Comment by Zapotek** [comment]
The WebUI doesn't have anything to do with the REST API so I don't see how it would get started.
