### ISSUE TITLE
Include runtime stats in report 

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#747]
Would it be possible to include the runtime stats in the reports ? 
```
 [~] Audited x page snapshots.
 [~] Audit limited to a max of x pages.

 [~] Duration: xx:xx:xx
 [~] Processed xxx/xxx HTTP requests.
 [~] -- xx.xxx requests/second.
 [~] Processed xx/xx browser jobs.
 [~] -- xx.xxx second/job.

 [~] Burst response time sum     x.xxx seconds
 [~] Burst response count        xxx
 [~] Burst average response time x.xx seconds
 [~] Burst average               xx.xx requests/second
 [~] Timed-out requests          xx
 [~] Original max concurrency    xx
 [~] Throttled max concurrency   xx
```
This is very useful information, but unfortunately only available in the terminal output at the moment.
It seems like a good idea to include this in the metrics module.

**Comment by Zapotek** [comment]
Added:

- HTTP
    - Request time-outs
    - Responses per second
- Browser cluster
    - Seconds per job
    - Total job time

**Comment by dnyrop** [comment]
Awesome :)
Would it be possible to add timed-out browser jobs as well ?

**Comment by Zapotek** [comment]
Done.

**Comment by Zapotek** [comment]
You can find this in the nightlies.

Cheers
