### ISSUE TITLE
Gem installation fails with dependency error 

### ISSUE THREAD

**Issue by bogdanRada** [Arachni/arachni#748]
Running this command 
```
gem install arachni
```
gives following error:
```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - nokogiri (>= 1.5.9) (requested by loofah-2.0.3)
```

I am using rubygems 2.6.4 

Could this be fixed? Thank you very much

**Comment by Zapotek** [comment]
There's an issue with the current Gem, you better use one of the [self-contained packages](http://www.arachni-scanner.com/download/).

**Comment by bogdanRada** [comment]
thanks
