### ISSUE TITLE
Web Interface - Download AFR report from crashed scans

### ISSUE THREAD

**Issue by taesiri** [Arachni/arachni#751]
Hello,

I have few crashed scans in my web console. the Download Report  button is not visible for these scans. Is there any way to generate AFR files for these scans?

![2](https://cloud.githubusercontent.com/assets/588431/17269594/0af54556-5662-11e6-9714-beef21c2de7e.png)

Regards,
Taesiri

**Comment by Zapotek** [comment]
Hello,

Unfortunately not.
It's interesting that the scan crashed though, this doesn't happen very often and is usually due to low resources (like not enough RAM).
Can you rerun the scan via the CLI and let me know of any error messages or strange output?
Also what are the specs of the machine?

Cheers

**Comment by taesiri** [comment]
Well, I've been tasked to check Arachni's performance and scan capabilities. I have a list of ~40 websites to run Arachni against them, most of my scans are crashing. for some of them, the problem is RAM and machine resource.

I have  6 virtual machines, 3 windows server 2008 and 3 ubuntu 14.04, each of them has 16 GB of ram and the CPU is Intel Xeon X5560 (It's OLD).

I think I should mention that my web console is unresponsive/hanging after this scan. even the browser itself  crashes (both firefox and chrome)  when i try to browse scan results.


![3](https://cloud.githubusercontent.com/assets/588431/17270990/c91786e4-5684-11e6-994e-fb4bafda86c4.png)



I'll run the scan once again via the CLI and will update this issue.

Regards

**Comment by Zapotek** [comment]
The [nightlies](http://downloads.arachni-scanner.com/nightlies/) should be faster and less resource intensive so give them a try.
I should warn you thought that they aren't considered stable so if you come across an issue please let me know.
And better stick with the CLI for now.

Cheers

**Comment by taesiri** [comment]
thanks for quick response. I'm already using the latest nightly build.

Regards

**Comment by taesiri** [comment]
The result of my first try was:

![4](https://cloud.githubusercontent.com/assets/588431/17278616/555a9b2c-5776-11e6-88f6-0b5f2cac70ac.png)

I've re-downloaded latest Arachni's build (nightlies) and re-ran the scan. It's been 24 hours and the scan hasn't finished yet. the Command Prompt showing tons of " BrowserCluster Worker#<ID>: Job timed-out after 25 seconds" messages.  Not sure what is wrong.

**Comment by Zapotek** [comment]
My guess is that either the server or the scanner machine are very stressed.
Are you running multiple scans in parallel?

**Comment by Zapotek** [comment]
Based on the screenshot I see that you've been running multiple scans as the same time, which can explain the degraded performance and the job time-outs, if the system doesn't have enough resources to accommodate the workload.

I'm closing this for now but feel free to comment/re-open if you'd like to provide more feedback.

Cheers
