### ISSUE TITLE
Invalid links for rubydoc 

### ISSUE THREAD

**Issue by vshl-ptl** [Arachni/arachni#759]
Rubydoc links for Arachni core is not valid. The link: http://www.rubydoc.info/github/Arachni/arachni says no docs are generated .

**Comment by Zapotek** [comment]
For some reason the doc generation errors out, looking into it.

Thanks for the heads up.

**Comment by Zapotek** [comment]
Fixed, although I can't update the online docs as they're generated automatically with every release.
