### ISSUE TITLE
Custom headers with Proxy plugin.

### ISSUE THREAD

**Issue by taesiri** [Arachni/arachni#763]
Hello,

It seems `--http-request-header` not working with Proxy plugin. Is there any way to specify a custom request header for the proxy plugin?

Regards,
Taesiri

**Comment by Zapotek** [comment]
Hello,

The purpose of the proxy plugin is to passively listen and not interfere.
Can you describe your use case please?

Cheers

**Comment by taesiri** [comment]
I'm using 'Host' header in my request for auditing Virtual Hosts on a server. I can manually add this header to my requests, but I think it would be much easier if Proxy plugin could do this header.

**Comment by Zapotek** [comment]
I'm afraid you'll need to do it a different way, sorry.
