### ISSUE TITLE
Upgrade PhantomJS

### ISSUE THREAD

**Issue by Zapotek** [Arachni/arachni#764]
Upgrade to a more recent version of PhantomJS to provide support for newer JS APIs and resolve a number of pending issues.

Known issues:

* Recent AngularJS webapps

**Comment by m6a-UdS** [comment]
+1
I think I have [this bug](http://stackoverflow.com/questions/26583409/watir-webdriver-phantomjs-and-urls-that-redirect-to-https) which would be resolved if PhantomJS was upgraded; Any easy work-around is welcome :-)

**Comment by Zapotek** [comment]
@m6a-UdS I don't think this is your issue, PhantomJS doesn't communicate with the target website (origin) directly, it goes through an internal proxy and the origin request is performed by Arachni's internal HTTP client.

**Comment by m6a-UdS** [comment]
OK thank you, I will open a separate issue about this :-)

**Comment by Zapotek** [comment]
I'm almost done with the upgrade.
Running the test suite and some more tests now to make sure everything is OK and I'll push nightlies soon.

**Comment by Zapotek** [comment]
[Nightlies](http://downloads.arachni-scanner.com/nightlies/) with PhanomJS 2.1.1 are up.
