### ISSUE TITLE
Unable to scan with latest nightly

### ISSUE THREAD

**Issue by Barsomisco** [Arachni/arachni#769]
I installed the linux x86_64 nightly and got this error:

/arachni-2.0dev-1.0dev/system/usr/lib/ruby/2.3.0/json/ext.rb:15:in `require': JSON::Ext::Generator is not a module (Class) (TypeError)

**Comment by Zapotek** [comment]
That's my bad, I didn't catch it in time, the current nighties should work -- except for OSX, something went wrong during the build process but I'm pushing fresh nightlies now.
