### ISSUE TITLE
Unable to scan, hostname reserved

### ISSUE THREAD

**Issue by Barsomisco** [Arachni/arachni#770]
First of all, thank you for fixing issue #769 earlier!
But now I get another error:
.../lib/arachni/options.rb:223:in `url=': '127.0.0.2' is reserved, please use a different IP address or hostname. (Arachni::Options::Error::ReservedHostname)

I have tried different addresses such as 127.0.0.3 (and so on) but still get the error

**Comment by Zapotek** [comment]
I should update the message, the upgraded PhntomJS version doesn't like any loopback interfaces.
You can use the machine's hostname or an address of a different interface.

**Comment by Barsomisco** [comment]
Does this mean that I have to change the default address of localhost?

**Comment by Zapotek** [comment]
No, it means that you need to specify something other than `localhost` or `127.x.x.x`.
You can pass the hostname of the machine (as printed by the `hostname` command) or the IP address of a different networking interface (`eth0` perhaps).

Depending on your webserver configuration, you may also need to alter its config to bind to the same interface as the one you passed to Arachni.

**Comment by georgiamilton** [comment]
how can i do this ? @Zapotek

**Comment by georgiamilton** [comment]
Arachni::RPC::Exceptions::RemoteException] Loopback interfaces (like 127.0.0.1) are not supported, please use a different IP address or hostname.

I am wanting to scan demo wesbites such as which are on the localhost.
