### ISSUE TITLE
Could not spawn browser process

### ISSUE THREAD

**Issue by axd** [Arachni/arachni#772]
I've start a new scan to a specific domain, everything was ok, but the scan finished with the following errors:

```
[2016-09-07 10:11:45 -0600] Could not spawn browser process.
[2016-09-07 10:11:45 -0600] 7465: Started
...
[2016-09-07 10:11:45 -0600] [Arachni::Browser::Error::Spawn] Could not start the browser process.
```

I don't know what exactly is going on.

Any suggestion is appreciated.

Thanks.

**Comment by Zapotek** [comment]
Which version were you using?

**Comment by axd** [comment]
The current version: v1.4-0.5.10

**Comment by Zapotek** [comment]
It's not a big issue, this can happen if the machine is under a lot of stress.
To prevent this altogether the [nightlies](http://downloads.arachni-scanner.com/nightlies/) have been updated to allow more time for the browsers to spawn.
Can you give them a try and let me know if they solve the issue?

**Comment by axd** [comment]
Sure thing. I'll test the nightlies and I'll let you know. Thanks.

**Comment by axd** [comment]
@Zapotek You were right, the nightlies is working. Thank you.

**Comment by Zapotek** [comment]
Glad to hear that. :)
