### ISSUE TITLE
Leaking phantomjs processes

### ISSUE THREAD

**Issue by mossharris** [Arachni/arachni#774]
description:
OS： Ubuntu 16.04.1 LTS 64 bit
Configuration: 8 nuclear 16 G

You're using 3.35g memory, created 5 tasks by web-UI interface (./bin/arachni_rpcd) and waiting for the ends of scaning.
the current system memory is 4.86G and more processes at the same time（arachni/lib/arachni/processes/executables/base.rb）

**Comment by Zapotek** [comment]
I'm not sure what you're trying to say but give the [nightlies](http://downloads.arachni-scanner.com/nightlies/) a shot and see if the problem persists.

**Comment by mossharris** [comment]
**OS: Ubuntu 16.04.1 LTS 64 bit, 8 nuclear 16 G**

**run Arachni v1.4 - WebUI v0.5.10**
![1](https://cloud.githubusercontent.com/assets/7722345/18624573/6a097832-7e7b-11e6-982d-18317fbf0791.png)

**run arachni_rpcd**
```
download http://downloads.arachni-scanner.com/nightlies/arachni-2.0dev-1.0dev-linux-x86_64.tar.gz
cd arachni-2.0dev-1.0dev
./bin/arachni_rpcd --address=10.236.70.39 --nickname=Jumbo-1
```

![2](https://cloud.githubusercontent.com/assets/7722345/18624625/bf03cb1c-7e7b-11e6-83b0-f598453e6c38.png)

![3](https://cloud.githubusercontent.com/assets/7722345/18624629/c3c8ef60-7e7b-11e6-9c69-32352de4e0ef.png)

Till now everything is alright.
And I start the scanning process.

![4](https://cloud.githubusercontent.com/assets/7722345/18624647/d9795e58-7e7b-11e6-83ec-ed1b15a58a9e.png)

![5](https://cloud.githubusercontent.com/assets/7722345/18624655/ddb875c6-7e7b-11e6-96fe-de90f585ed9c.png)

Waiting for the end of the scan

![6](https://cloud.githubusercontent.com/assets/7722345/18624667/e7a4f6f4-7e7b-11e6-99fe-ddcd5306eb7d.png)

Check the current RAM
![7](https://cloud.githubusercontent.com/assets/7722345/18624673/f259dd08-7e7b-11e6-9ace-c2617a5932ce.png)


OMG..

Jesus

I can’t get it  

After all these scanning, the RAM is 3.93G

Thanks for your reply.

**Comment by Zapotek** [comment]
You've started 5 scans, it's normal that they'd use a few GB of memory, isn't it?
If only one scans was using that much then you'd have a problem.

**Comment by mossharris** [comment]
At the beginning of the scanning it already took few RAM

Also at the end it still took a lot RAM

**Comment by Zapotek** [comment]
I'm not seeing a memory leak, you're running a lot of scans at the same time so the system is using a lot of RAM.
Also, the RAM usage in your screenshot shows total usage (OS and other programs) not just Arachni.

Still, you can decrease resource utilization by following this article: http://support.arachni-scanner.com/kb/general-use/optimizing-for-faster-scans

**Comment by mossharris** [comment]
I want to express is that after the end of the scan task it is still 3.9G memory.
If I scan more tasks, the memory will be full.

**Comment by Zapotek** [comment]
Are you trying to say that this is a WebUI rather than a scanner one?
Do you have a screenshot showing RAM usage per process?

**Comment by mossharris** [comment]
My WEB-UI are currently no task

![a](https://cloud.githubusercontent.com/assets/7722345/18662874/b7d3399e-7f4e-11e6-8e0f-442217949b9a.png)

**Comment by Zapotek** [comment]
I'm not seeing the problem, all processes are using a reasonable amount of RAM.
The only issue I'm seeing is the existence of `phantomjs` processes, if there are no scans there shouldn't be any of them around -- feel free to kill them.

**Comment by mossharris** [comment]
Web-UI doesnt run any tasks
So i was wonder 
Does `phantomjs` are the key problem which occur memory leaks

```
ps aux|grep phantomjs |wc -l
85
```
`root     23700  0.0  0.2 2293452 43528 pts/10  Sl   16:35   0:00 /home/moss/arachni-build-dir/arachni/system/usr/bin/phantomjs --webdriver=37456 --proxy=http://127.0.0.1:50212 --ignore-ssl-errors=true --ssl-protocol=any --disk-cache=true
`

**Comment by Zapotek** [comment]
That's *a lot*, these processes should be killed at the end of each scan.
Please kill them all and re-try your tests with the [nightlies](http://downloads.arachni-scanner.com/nightlies/).

**Comment by mossharris** [comment]
i had tested nightlies.

But this problem haven't worked out

**Comment by Zapotek** [comment]
You need to start fresh.
Kill all ruby and PhantomJS processes and they retest with just the nightlies.

**Comment by mossharris** [comment]
Test again with your way, but ruby and `PhantomJS` process still takes a lot

**Test process**

`PhantomJS 2.1.1`
`ruby 2.2.3p173`
`arachni-ui-web master`
`arachni-2.0dev-1.0dev-linux-x86_64` (sha1: f606e74928f95c5c6c11bf799c0617f7b0170bfc)

Start arachni-ui-web then `ruby` Prcess is 1, `PhantomJS` 0。

Start arachni-rpcd then  `ruby` Process increased to 13, `PhantomJS` 0
```
./bin/arachni_rpcd --address=10.236.70.39 --nickname=Jumbo-1
./bin/arachni_rpcd --address=10.236.70.39 --port 3772 --nickname=Jumbo-2 --neighbour=10.236.70.39:7331
```

I start to create a new task from WebUI (distribution: grid) and waiting for the end of scan

After scanning, I use ps commands to see `ruby` process, it had been increased to 20 and `PhantomJS ` process had been increased to 6

Then I start the second task and waiting for the end of scan

After scanning, `ruby` process had been increased to 27 ,while `PhantomJS` process had been increased to 12

**Comment by Zapotek** [comment]
I haven't been able to reproduce this, I tried the exact same configuration and there were no leaking processes.

**Comment by Zapotek** [comment]
Judging by the video you provided (thanks for that), you neglected to mention that right after the scan starts, you get an error that says that communication with the scanner was severed.
This explains everything as the scan never gets a chance to clean-up.

I'm not sure why that happens but can you try setting the `--external-address` to the same value as `--address` for `arachni_rpcd`?

Also, before you retry, please remove all files from `system/logs/framework/` and then send me the new logfiles (if any) after the test.

**Comment by mossharris** [comment]
./bin/arachni_rpcd --external-address=10.236.70.39 --address=10.236.70.39 --nickname=Jumbo-1
./bin/arachni_rpcd --external-address=10.236.70.39 --address=10.236.70.39 --port 3772 --nickname=Jumbo-2 --neighbour=10.236.70.39:7331


cat Dispatcher - 14797-7331.log

[Fri Sep 23 15:45:15 2016] [status]  Starting the RPC Server...
[Fri Sep 23 15:45:15 2016] [status]  Populating the pool with 5  Instances.
[Fri Sep 23 15:45:15 2016] [status]  Instance added to pool -- PID: 14812 - Port: 64357 - Owner: dispatcher
[Fri Sep 23 15:45:15 2016] [status]  Instance added to pool -- PID: 14816 - Port: 64005 - Owner: dispatcher
[Fri Sep 23 15:45:15 2016] [status]  Instance added to pool -- PID: 14820 - Port: 46910 - Owner: dispatcher
[Fri Sep 23 15:45:15 2016] [status]  Instance added to pool -- PID: 14824 - Port: 42929 - Owner: dispatcher
[Fri Sep 23 15:45:15 2016] [status]  Instance added to pool -- PID: 14827 - Port: 59511 - Owner: dispatcher
[Fri Sep 23 15:45:15 2016] [status]  Waiting for Instances to come on-line.
[Fri Sep 23 15:45:17 2016] [status]  Instances are on-line.
[Fri Sep 23 15:45:17 2016] [status]  Initializing grid node...
[Fri Sep 23 15:45:17 2016] [status]  Node ready.
[Fri Sep 23 15:45:17 2016] [info]  Updated neighbours:
[Fri Sep 23 15:45:17 2016] [info]  <empty>
[Fri Sep 23 15:45:17 2016] [status]  Ready
[Fri Sep 23 15:47:00 2016] [status]  Adding neighbour: 10.236.70.39:3772
[Fri Sep 23 15:47:00 2016] [info]  Updated neighbours:
[Fri Sep 23 15:47:00 2016] [info]  ---- 10.236.70.39:3772
[Fri Sep 23 15:47:00 2016] [status]  Advertising: 10.236.70.39:3772


cat Dispatcher - 14938-3772.log
[Fri Sep 23 15:46:57 2016] [status]  Starting the RPC Server...
[Fri Sep 23 15:46:57 2016] [status]  Populating the pool with 5  Instances.
[Fri Sep 23 15:46:57 2016] [status]  Instance added to pool -- PID: 14953 - Port: 13821 - Owner: dispatcher
[Fri Sep 23 15:46:57 2016] [status]  Instance added to pool -- PID: 14957 - Port: 56238 - Owner: dispatcher
[Fri Sep 23 15:46:57 2016] [status]  Instance added to pool -- PID: 14961 - Port: 22098 - Owner: dispatcher
[Fri Sep 23 15:46:57 2016] [status]  Instance added to pool -- PID: 14965 - Port: 11698 - Owner: dispatcher
[Fri Sep 23 15:46:57 2016] [status]  Instance added to pool -- PID: 14969 - Port: 3937 - Owner: dispatcher
[Fri Sep 23 15:46:57 2016] [status]  Waiting for Instances to come on-line.
[Fri Sep 23 15:46:59 2016] [status]  Instances are on-line.
[Fri Sep 23 15:46:59 2016] [status]  Initializing grid node...
[Fri Sep 23 15:46:59 2016] [status]  Node ready.
[Fri Sep 23 15:46:59 2016] [info]  Updated neighbours:
[Fri Sep 23 15:46:59 2016] [info]  <empty>
[Fri Sep 23 15:46:59 2016] [status]  Ready
[Fri Sep 23 15:47:00 2016] [status]  Adding neighbour: 10.236.70.39:7331
[Fri Sep 23 15:47:00 2016] [info]  Updated neighbours:
[Fri Sep 23 15:47:00 2016] [info]  ---- 10.236.70.39:7331
[Fri Sep 23 15:47:00 2016] [status]  Advertising: 10.236.70.39:7331
[Fri Sep 23 15:48:22 2016] [status]  Instance dispatched -- PID: 14965 - Port: 11698 - Owner: WebUI v0.5.10
[Fri Sep 23 15:48:22 2016] [status]  Instance added to pool -- PID: 15100 - Port: 32869 - Owner: dispatcher

**Comment by Zapotek** [comment]
Hm, and what about `system/logs/webui/`?
Better upload it to a [gist](http://gist.github.com/) this time.

**Comment by mossharris** [comment]
Is system/logs/framework/ Log

**Comment by Zapotek** [comment]
Please upload `system/logs/webui/production.log`  as a gist.

**Comment by mossharris** [comment]
https://gist.github.com/mossharris/cc18f3c76f3b1eb7759248d7255fecc1

**Comment by Zapotek** [comment]
That can't be the right one, weren't you using the WebUI from the package?

**Comment by mossharris** [comment]
Yes, I use the github pull down webui Code.

The problem has been resolved.

thank you very much.  :+1:

**Comment by Zapotek** [comment]
Glad to hear it.
