### ISSUE TITLE
Link to core api documentation is broken in wiki

### ISSUE THREAD

**Issue by shanteadam** [Arachni/arachni#781]
https://github.com/Arachni/arachni/wiki/Developer-guide

The automated code documentation does not seem to be working.

![core_api_doc_error](https://cloud.githubusercontent.com/assets/16108932/19024830/c1a0edb4-88c1-11e6-82f5-5dea2f4e141c.PNG)

**Comment by Zapotek** [comment]
There was an issue with the doc-comments in the code in the master branch,, the issue has been fixed in the experimental branch.
The fix won't be visible until the next version is released though.

**Comment by shanteadam** [comment]
I'd recommend leaving this open so that others can see your explanation until the next version is released. Is there an expected date for that release?

**Comment by Zapotek** [comment]
Fair enough, this is already a duplicate.
About the release date, I'm not sure yet.

**Comment by Zapotek** [comment]
Fixed.
