### ISSUE TITLE
How to scan a POST request with specific parameters

### ISSUE THREAD

**Issue by blinking-yan** [Arachni/arachni#782]
Hi, i want to scan a POST request with specific parameters. 

For example, an API of APP (Android or IOS ):

```
url: http://example.com/apply

method: POST

request_body:  {"birthday":"2000-06-06","phone":"1134556111"}
```

There is no page, just an API.  I want Arachni to scan the post parameters `birthday` and `phone`.

I had looked up [Command-line-user-interface](https://github.com/Arachni/arachni/wiki/Command-line-user-interface) for a while, but could not figure out how to do it.

Any helps? Thanks!

**Comment by blinking-yan** [comment]
Figure it out! 

I will post my configuration here later.

**Comment by blinking-yan** [comment]
@Zapotek 

If the POST request content-type is `multipart/form-data`,  how to set the `inputs` element?

**Comment by Zapotek** [comment]
Same way, I don't think it'll be a problem server side, did you try it/

**Comment by blinking-yan** [comment]
I had not tried it. 

`multipart/form-data` request body is something like this:

```
------WebKitFormBoundaryguUjqGpfXBnsvfXD
Content-Disposition: form-data; name="uploadId"

1476080835135
------WebKitFormBoundaryguUjqGpfXBnsvfXD
Content-Disposition: form-data; name="file"; filename="IMG_4996.JPG"
Content-Type: image/jpeg

ï¿½ï¿½ï¿½ï¿½
```

What i think `yaml_string` like this:

```
type: form
method: post
action: http://example.com/upload
inputs:
    uploadId: 1476080835135
    file: ï¿½ï¿½ï¿½ï¿½
```

So i worry, will the left  info of upload file like `filename="IMG_4996.JPG"` , `Content-Type: image/jpeg` go missing?

**Comment by Zapotek** [comment]
The content type will not be included and there won't be an upload, but the `file` input will still be audited as usual.

**Comment by blinking-yan** [comment]
That means it just like content-type `application/x-www-form-urlencoded`.

I think the server may send different response if there is not an upload.  

I will try it later and get the result. Thank you.
