### ISSUE TITLE
Problem with Content-Length request header

### ISSUE THREAD

**Issue by b1ngz** [Arachni/arachni#785]
Hi, I found scanning with `Content-Length` request header may cause some abnormal behaviors.  

When i tested my intranet service, i got a lot of timeout responses, almost all.

After removing the `Content-Length` header,  all requests get 200 OK.

Because some request infos are sensitive, i can not paste here.

I tested it with [DVWA](http://54.153.86.200:18888/).  Scanning without `Content-Length` can find the `os_cmd_injection ` vulnerability, while found nothing with `Content-Length`.

Here are my scan config:

```
{
  "url": "http://54.153.86.200:18888/vulnerabilities/exec/",
  "checks": [
    "os_cmd_injection"
  ],
  "audit": {
    "links": true,
    "forms": true,
    "cookies": false,
    "headers": false,
    "jsons": true,
    "xmls": true,
    "ui_inputs": true,
    "ui_forms": true
  },
  "input": {
    "without_defaults": true
  },
  "scope": {
    "page_limit": 0
  },
  "http": {
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "cookie_string": "security=low; path=/, PHPSESSID=jgh22v84424anailkka5ef8o64; path=/",
    "request_headers": {
      "Content-Length": 21
    }
  },
  "plugins": {
      "vector_feed": {
        "yaml_string": "method: POST\naction: 'http://54.153.86.200:18888/vulnerabilities/exec/'\ninputs:\n    ip: test\n    submit: submit\ntype: form\n"
      }
  }
}
```

You can test by removing the `Content-Length`.

I guess  Arachni may not calculate the correct `content-length` and set it when scanning.

**Comment by Zapotek** [comment]
Hello, 

Can you show me an example request please?
`libcurl` generally sets the `Content-Length`, not Arachni.

**Comment by b1ngz** [comment]
I am using latest [nightlies](http://downloads.arachni-scanner.com/nightlies/).

You can use my config pasted before directly. the url is `http://54.153.86.200:18888/vulnerabilities/exec/`

I mean if i set the `Content-Length` manually, it will cause some problem, like got timeout or can not find the vuls.

**Comment by Zapotek** [comment]
My bad, I misunderstood.

This isn't a bug, you're mis-configuring the system, time-outs are expected to occur with this configuration.

Why did you set this option?

**Comment by b1ngz** [comment]
Do you know the passive scan?  Something like:

My workmate collected the access logs from the QA testers(by setting the proxy) and save to database (Mysql).

I parse the access log  and create the scan task.

The `Content-Length` is included in request headers, so i set it as well as the other request headers like `Content-Type`.

![image](https://cloud.githubusercontent.com/assets/17590163/19436722/7557ed42-94a4-11e6-96df-01faa8554033.png)

**Comment by Zapotek** [comment]
The necessary headers will be set by the system during the scan, you don't need to configure the HTTP client to use them for **all**requests.
That option serves a different purpose.

**Comment by Zapotek** [comment]
I think there was a miscommunication, I just came across an issue that may have been what you were talking about.
The fix is in the nightlies.

**Comment by b1ngz** [comment]
Maybe i did not complain the problem clearly , anyhow it's fixed.  That's good.
