### ISSUE TITLE
Crawling broken in latest nightly

### ISSUE THREAD

**Issue by Logima** [Arachni/arachni#786]
Crawler doesn't follow any links in latest nightly (cf72a65). Here is a minimal example:

Create file index.html with content
`<a href="otherpage.html">other page</a>`
and otherpage.html with content
`<h1>Other page</h1>`.

Run `python -m SimpleHTTPServer` to serve these files.

`./bin/arachni --checks - http://hostname:8000/`

```
...
[*] BrowserCluster: Initialization completed with 6 browsers in the pool.

[*] [HTTP: 200] http://hostname:8000/
[~] Identified as: python
[~] Analysis resulted in 0 usable paths.
[~] DOM depth: 0 (Limit: 5)


================================================================================
...
```

After reverting the element.rb part of 2613729e8727f2cad67695f856c5076c347d2be2 the crawler seems to work again:

```
...
[*] BrowserCluster: Initialization completed with 6 browsers in the pool.

[*] [HTTP: 200] http://hostname:8000/
[~] Identified as: python
[~] Analysis resulted in 1 usable paths.
[~] DOM depth: 0 (Limit: 5)

[*] [HTTP: 200] http://hostname:8000/otherpage.html
[~] Identified as: python
[~] Analysis resulted in 0 usable paths.
[~] DOM depth: 0 (Limit: 5)


================================================================================
...
```

**Comment by Zapotek** [comment]
This one slipped through the cracks, reverted for pushing nightlies now.

Thanks a lot for the heads up.

**Comment by Zapotek** [comment]
Nightlies are up.
