### ISSUE TITLE
PhantomJS executable missing?

### ISSUE THREAD

**Issue by brandonprry** [Arachni/arachni#788]
Using the latest experimental branch at HEAD, I am getting an error regarding PhantomJS that I don't remember dealing with in the past.

```
$ ./arachni --http-cookie-string "lang=en_US; searchHide=1; PHPSESSID=mn8i2jq7l0ktonajshqhqf8de5" --scope-exclude-pattern logout --checks sql* http://172.18.20.68/admin/config.php
Arachni - Web Application Security Scanner Framework v2.0dev
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki


 [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.

 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [-] [utilities#exception_jail:428] [Selenium::WebDriver::Error::WebDriverError] Unable to find phantomjs executable.
 [-] [utilities#exception_jail:428] /Users/bperry/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-3.0.0/lib/selenium/webdriver/phantomjs.rb:38:in `path'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/browser.rb:148:in `executable'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/browser.rb:142:in `has_executable?'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework/parts/audit.rb:173:in `audit'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework.rb:117:in `block in run'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:428] /Users/bperry/Projects/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:429] 
 [-] [utilities#exception_jail:430] Parent:
 [-] [utilities#exception_jail:431] Arachni::Framework
 [-] [utilities#exception_jail:432] 
 [-] [utilities#exception_jail:433] Block:
 [-] [utilities#exception_jail:434] #<Proc:0x007fb9eec79e58@/Users/bperry/Projects/arachni/lib/arachni/framework.rb:117>
 [-] [utilities#exception_jail:435] 
 [-] [utilities#exception_jail:436] Caller:
 [-] [utilities#exception_jail:437] /Users/bperry/Projects/arachni/lib/arachni/utilities.rb:425:in `exception_jail'
 [-] [utilities#exception_jail:437] /Users/bperry/Projects/arachni/lib/arachni/framework.rb:117:in `run'
 [-] [utilities#exception_jail:437] /Users/bperry/Projects/arachni/ui/cli/framework.rb:80:in `block in run'
 [-] [utilities#exception_jail:438] --------------------------------------------------------------------------------

```

I don't remember needing to install phantomjs separately in the past. I believe this was taken care of by bundler.

Any thoughts on what I might be missing?

**Comment by Zapotek** [comment]
You always had to have PhantomJS on your system, it's only bundled via the packages.
You need version 2.1.1.

Why not use the nightlies btw?

**Comment by brandonprry** [comment]
Ah, I must have missed that then. I did recently need to reinstall OS X.

IRT nightlies, almost everything I run is out of git. Just a personal preference. sqlmap, metasploit, arachni, etc. Makes it easier to manage and update all at once with a quick shell script.

**Comment by arachni-user** [comment]
Hello can anybody help me out?
I got this error using gauntlt arachni
     
 expected "Arachni - Web Application Security Scanner Framework v1.5.1\n   Author: Tasos \"Zapotek\" Laskos <ta...ramework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/ui/cli/framework.rb:80:in `block in run'\n" to include "0 issues were detected."
      Diff:
      @@ -1,2 +1,29 @@
      -0 issues were detected.
      +Arachni - Web Application Security Scanner Framework v1.5.1
      +   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>
      +
      +           (With the support of the community and the Arachni Team.)
      +
      +   Website:       http://arachni-scanner.com
      +   Documentation: http://arachni-scanner.com/wiki
      +
      +
      +[~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.
      +
      +[*] Initializing...
      +[*] Preparing plugins...
      +[*] ... done.
      +[-] [ui/cli/framework#run:129] [LoadError] cannot load such file -- selenium/webdriver/phantomjs
      +[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
      +[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
      +[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/browser.rb:148:in `executable'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/browser.rb:142:in `has_executable?'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:173:in `audit'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in `block in run'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:in `exception_jail'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in `run'
      +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/ui/cli/framework.rb:80:in `block in run'
       (RSpec::Expectations::ExpectationNotMetError)
      arachni-xss.attack:10:in `Then the output should contain "0 issues were detected."'

Failing Scenarios:
cucumber arachni-xss.attack:4 # Scenario: Using the arachni, look for cross site scripting and verify no issues are found

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m1.953s

------

checked my arachni version
1.15.1

---------
Gemfile content:

PATH
  remote: .
  specs:
    gauntlt (1.0.12)
      aruba (= 0.5.4)
      cucumber (= 1.3.20)
      nokogiri (~> 1.6.5)
      trollop (~> 2.1.2)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.3.6)
    arachni (1.4)
      addressable (= 2.3.6)
      arachni-rpc (= 0.2.1.3)
      awesome_print
      bundler
      childprocess (= 0.5.3)
      coderay (= 1.1.0)
      concurrent-ruby (= 1.0.0)
      concurrent-ruby-ext (= 1.0.0)
      http_parser.rb
      kramdown (= 1.4.1)
      loofah (~> 2.0.0)
      msgpack (= 0.7.0)
      nokogiri (= 1.6.8rc2)
      oj (~> 2.14.3)
      oj_mimic_json
      pony (= 1.8)
      puma (= 2.14.0)
      rack
      rb-readline (= 0.5.1)
      rubyzip (= 1.1.6)
      sinatra (= 1.4.6)
      sinatra-contrib (= 1.4.6)
      terminal-table (= 1.4.5)
      typhoeus (= 1.0.1)
      watir-webdriver (= 0.8.0)
    arachni-reactor (0.1.1)
    arachni-rpc (0.2.1.3)
      arachni-reactor (= 0.1.1)
    aruba (0.5.4)
      childprocess (>= 0.3.6)
      cucumber (>= 1.1.1)
      rspec-expectations (>= 2.7.0)
    awesome_print (1.8.0)
    background_process (1.3)
    backports (3.10.3)
    builder (3.2.3)
    childprocess (0.5.3)
      ffi (~> 1.0, >= 1.0.11)
    coderay (1.1.0)
    concurrent-ruby (1.0.0)
    concurrent-ruby-ext (1.0.0)
      concurrent-ruby (~> 1.0.0)
    cucumber (1.3.20)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.12)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    diff-lcs (1.3)
    ethon (0.11.0)
      ffi (>= 1.3.0)
    ffi (1.9.18)
    gherkin (2.12.2)
      multi_json (~> 1.3)
    http_parser.rb (0.6.0)
    kramdown (1.4.1)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    mini_mime (1.0.0)
    mini_portile2 (2.1.0)
    msgpack (0.7.0)
    multi_json (1.12.2)
    multi_test (0.1.2)
    nokogiri (1.6.8.rc2)
      mini_portile2 (~> 2.1.0)
    oj (2.14.6)
    oj_mimic_json (1.0.1)
    pony (1.8)
      mail (>= 2.0)
    puma (2.14.0)
    rack (1.6.8)
    rack-protection (1.5.3)
      rack
    rack-test (0.8.2)
      rack (>= 1.0, < 3)
    rake (11.0.1)
    rb-readline (0.5.1)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)
    rubyzip (1.1.6)
    selenium-webdriver (3.8.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    service_manager (0.6.4)
      background_process (>= 1.2)
      tcpsocket-wait
    sinatra (1.4.6)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    sinatra-contrib (1.4.6)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (>= 1.3, < 3)
    tcpsocket-wait (1.0.0)
    terminal-table (1.4.5)
    tilt (2.0.8)
    trollop (2.1.2)
    typhoeus (1.0.1)
      ethon (>= 0.8.0)
    watir-webdriver (0.8.0)
      selenium-webdriver (>= 2.46.2)

PLATFORMS
  ruby

DEPENDENCIES
  arachni (= 1.4)
  gauntlt!
  rake (~> 11.0.1)
  service_manager

BUNDLED WITH
   1.15.1

**Comment by sampathmende** [comment]
I am getting same error phantomjs load error 
pls find the log


[LoadError] cannot load such file -- selenium/webdriver/phantomjs
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in `require'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in `executable'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:126:in `has_executable?'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:167:in `audit'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/ui/cli/framework.rb:62:in `block in run'
[-] [Errno::EINVAL] Invalid argument @ rb_io_seek - /tmp/arachni20180218-669-1up3449afr
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in `seek'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in `block in load'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:in `open'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:in `load'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:40:in `run'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:25:in `initialize'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:in `new'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:in `<top (required)>'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/bin/arachni_reporter:23:in `load'
[-] /home/sampath/.rvm/gems/ruby-2.3.0/bin/arachni_reporter:23:in `<main>'
[2018-02-18 11:41:04 +0530] Running tasks in stage: live
