### ISSUE TITLE
Arachni converted *.xml file cannot be uploaded to threadfix

### ISSUE THREAD

**Issue by bethbuhawe** [Arachni/arachni#795]
Hi,

After arachni has been executed via jenkins, generated *.afr has been converted to *.xml using --reporter=xml:outfile . However, by the time the generated *.xml file has been uploaded to threadfix, it doesn't identify it as a valid file. Could this be an arachni issue or a threadfix issue?

**Comment by Zapotek** [comment]
This is a Threadfix issue, they probably haven't updated to work with the nightlie.
