### ISSUE TITLE
xss_path False positive

### ISSUE THREAD

**Issue by mossharris** [Arachni/arachni#800]
scanner prompt : Cross-Site Scripting (XSS) in path (Trusted), I think it is False positive.

![xss_path](https://cloud.githubusercontent.com/assets/7722345/20424459/ec962cf0-adb0-11e6-9d48-32fe8ff42436.png)

![xss_path_2](https://cloud.githubusercontent.com/assets/7722345/20424461/f52204ac-adb0-11e6-9589-d0a484878969.png)

**Comment by Zapotek** [comment]
Can you show me the response headers please?

**Comment by mossharris** [comment]
```
HTTP/1.1 200 OK
Date: Sun, 20 Nov 2016 06:14:59 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 254
Connection: keep-alive
Content-Encoding: gzip
Vary: Accept-Encoding
Server: TornadoServer/4.0.2
Cache-Control: private,max-age=0,stale-while-revalidate=0
```

**Comment by mossharris** [comment]
If i use browser(watir-webdriver) to check <tag> ,will the results come out more exactly

**Comment by Zapotek** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by mossharris** [comment]
If i use browser to check <tag> ,will the results come out more exactly

**Comment by mossharris** [comment]
I was thinking how can i make the results more exactly
If i use watir-webdriver(it's a browser) to check `<tag>` does it make the difference

**Comment by mossharris** [comment]
**test**

link A exists xss_path vunlnerability
`http://www.a.com/xxx/xxx/xxx/xxx/xxx/?%3Cmy_tag_61dc7b94c73de77b6ef5bcbeac593e58/%3E=`

https://gist.github.com/mossharris/40662f8cd4279ef88237798edacb30ab


link B does not exists xss_path vunlnerability
`http://www.b.com/xxx/xxx/xxx/%3Cmy_tag_61dc7b94c73de77b6ef5bcbeac593e58/%3E`

https://gist.github.com/mossharris/11c6fa5cbb78349001cd30067619c0bb

**demo code**
```
require 'watir'

browser = Watir::Browser.new :phantomjs

#link A
browser.goto 'www.a.com/xxx/xxx/xxx/xxx/xxx/?%3Cmy_tag_61dc7b94c73de77b6ef5bcbeac593e58/%3E='

#link B
#browser.goto 'www.b.com/xxx/xxx/xxx/%3Cmy_tag_61dc7b94c73de77b6ef5bcbeac593e58/%3E'

puts browser.element(:tag_name, 'my_tag_61dc7b94c73de77b6ef5bcbeac593e58').exists?

browser.close
```


**result**
```
A link: true 
B link: false
```

**Comment by Zapotek** [comment]
Pushing nightlies now with the fix, I'll let you know once they're up.

**Comment by Zapotek** [comment]
Nightlies are up, give them a try.

Cheers
