### ISSUE TITLE
Arachni dont audit all.. missing something

### ISSUE THREAD

**Issue by moku23** [Arachni/arachni#803]
Hello,
i've seen arachni dont audits all links in webpage
this is my commandline:

>  ./arachni_multi --http-user-agent "Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36" --audit-cookies-extensively --audit-headers --audit-jsons --audit-parameter-names --audit-with-both-methods --audit-ui-forms --audit-links --audit-forms --audit-xmls --audit-ui-inputs --audit-cookies --audit-with-extra-parameter --http-request-concurrency=15 --http-response-max-size=9800000 --http-request-timeout=2300 --checks sql_injection* "http://...www.....com"

**Comment by Zapotek** [comment]
Does the issue occur when using the simple `arachni` executable instead of `arachni_multi`?

**Comment by moku23** [comment]
both :(

**Comment by Zapotek** [comment]
I'm going to need more information, is there any chance I can be given access to the webapp?
Also, please try the [nightlies](http://downloads.arachni-scanner.com/nightlies/) and see if they make any difference using the `arachni` executable.

**Comment by moku23** [comment]
im tring with nightly, but there are a problem when start ./arachni

./arachni: line 11: /home/ubuntu/arachni-2.0dev-1.0dev/bin/../system/usr/bin/ruby: No such file or directory

but `ruby` are present

**Comment by Zapotek** [comment]
I lost you, did the nightlies work but had the same problem or did they not work at all?

**Comment by moku23** [comment]
i've tried windows version and it work, but the results are the same.

**Comment by Zapotek** [comment]
Are you sure you downloaded the right package for your architecture before?
The packages work for me.

As for the problem, I don't think I can fix it without direct access to the webapp.
Can you at least page the HTML code of the page along with some example of things that were missed?

**Comment by moku23** [comment]
write you on email

**Comment by Zapotek** [comment]
From your e-mail I see that the webpage is mainly built with Flash, which is not supported.

**Comment by moku23** [comment]
Thanks for support. 
Have a nice day. 
grants for your project.
