### ISSUE TITLE
Arachni and JS UI kits

### ISSUE THREAD

**Issue by m6a-UdS** [Arachni/arachni#804]
Hello, I am having the same problem as this gentleman: http://support.arachni-scanner.com/discussions/questions/13045-how-to-configure-arachni-to-be-able-to-scan-pages-which-contains-navigation-based-on-tab-paths

It seems that the crawler does not extend pages which imply a fragment in the URL. My app consists has basically all the same base_url, followed by `#some_fct`. It's mostly an angular1.5-based app, using Babel, Autoprefixer, Sass, modernizr, hammerjs, momentjs, underscore.

Did you find any solution then?
The conversation ends with `Discussion moved to e-mail.`

Thanks!

**Comment by Zapotek** [comment]
Did you try the nightlies?
Other than that suggestion there's nothing I can do without access to the webapp.
This is either a bug or a configuration issue, either way I can't tell what's going on without access, or without a simple reproducible case if you can find some time to set that up.

**Comment by m6a-UdS** [comment]
OK thanks, I will try to set you something up ;-)
