### ISSUE TITLE
Unable to proceed with Scan

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#807]
Dear Tasos,

I am scanning http://demo.testfire.net/bank/login.aspx using Arachni and getting this error message in run time console and not moving further.

    Could not trigger 'onclick' on '<a href="#" onclick="call();return false;">' because the page has changed, capturing a new snapshot.

Please suggest.

**Comment by Zapotek** [comment]
Hello,

Which version are you using?

**Comment by theinfosecguyPankaj** [comment]
arachni-1.4-0.5.10-windows-x86_64

**Comment by Zapotek** [comment]
Can you try the nightlies please?

**Comment by theinfosecguyPankaj** [comment]
Nightlie build uploaded on 28th Dec 2016 is not identifying even single URL
to scan... Its saying URLs Scanned as 0.

Note: I am running in Windows

**Comment by Zapotek** [comment]
I just tried it on Linux and Windows and it's working fine for me.
