### ISSUE TITLE
Can't install Arachni using build script (Amazon EC2 instance, Ubuntu 16.04)

### ISSUE THREAD

**Issue by samantha-cruz** [Arachni/arachni#810]
Hi, I ran the build script for Arachni and my installation stops at 

```
# (4/6) Preparing the Ruby environment
-------------------------------------------
  * Generating environment configuration (/home/ubuntu/arachni-build-dir/arachni/system/environment)
  * Updating Rubygems
```

With this error:
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```
Is there a workaround to this. Clean instance, no other applications except for the dependencies.

I tried the git method and I keep getting this error.

```
sudo rake install
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000000d41d90>
/var/lib/gems/2.3.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:143:in `initialize'
/home/ubuntu/arachni/Rakefile:20:in `new'
/home/ubuntu/arachni/Rakefile:20:in `block in <top (required)>'
/home/ubuntu/arachni/Rakefile:17:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by Zapotek** [comment]
Why are you not using the self-contained packages?

**Comment by Zapotek** [comment]
About the `rake` error, I just came across it myself, something broke in the current version so I've had to [lock it](https://github.com/Arachni/arachni/commit/9857b1507574d612ee22c1762303f684a3b4fd95) to the last known working one.

**Comment by Zapotek** [comment]
I found the reason for the other error, your machine must be missing some SSL certs so I'm closing this since it's an env issue.
Again, I highly recommend using the provided packages rather than trying to create your own.

In addition, this is the wrong issue tracker for the issue, the build scripts have [their own](https://github.com/Arachni/build-scripts/issues).

Cheers
