### ISSUE TITLE
Arachni REST

### ISSUE THREAD

**Issue by nnvnaveen** [Arachni/arachni#816]
Hi ,

I am using REST way calling with scan options as below

```
{
	"url": "https://my-site/login",
	"scope": {
		"directory_depth_limit": 0,
		"dom_depth_limit": 10,
		"page_limit": 2
	},
	"checks": [
		"xss*"
	],
	"plugins": {
		"login_script": {
			"script": "Login_script_1.rb"
		}
	},
	"session": {
		"check_pattern": "Your profile",
		"check_url": "https://my-site/home"
	}
}
```

this is working without plugins well, but when i put plugin it is showing
[2016-12-29 16:45:15 -0500] Session: [Watir::Exception::UnknownObjectException] unable to locate element, using {:id=>"loginSecureLoginForm", :tag_name=>"form"} seems not able to find the element..

But when i tested using command prompt, it is working verywell,, and my login scipt has "no_proxy" , "127.0.0.1"
>
arachni https://my-site/login --plugin=login_script:script="Login_script_1.rb" --input-values-file=CWS-VALUES.afp --session-check-url=https://my-site/home --report-save-path=out.afr  --scope-auto-redundant=1 --scope-directory-depth-limit=0 --scope-dom-depth-limit=3 --scope-page-limit=2

**Comment by Zapotek** [comment]
May I see the script please?

**Comment by nnvnaveen** [comment]
# Specify the driver path

ENV['no_proxy'] = "127.0.0.1"
 
browser.goto("https://my-site/login")
browser.screenshot.save("screenshot.png")

script:
form = browser.form(id: 'loginForm')
form.text_field(name: 'username').set 'user'
form.text_field(name: 'password').set 'password'
browser.button(:id => 'loginButton').click

framework.options.session.check_url     =  'https://my-site/home'
framework.options.session.check_pattern = /Sign Off|MY ACCOUNT|logout|Log Out/


And this i placed under  C:\Naveen\softwares\arachni\arachni-2.0dev-1.0dev-windows-x86_64\bin
and my above post calling i am running from outside of arachni folder

My client is a java client which i am running. Calling from a java client is running good without loginscript but when i run login plugin has errors

String url = "http://localhost:7331/scans";
			
			String finalRequest = FileUtils.readFileToString(new File("C:\\Naveen\\arachni_request.json"));  -- above post request json..

			HttpClient client = new DefaultHttpClient();
			HttpPost post = new HttpPost(url);
			StringEntity params = new StringEntity(finalRequest);
			post.addHeader("Content-Type", "application/json");
			post.setEntity(params);
			HttpResponse response = client.execute(post);
			BufferedReader rd = new BufferedReader(new InputStreamReader(response.getEntity().getContent()));
			StringBuffer result = new StringBuffer();
			String line = "";
			while ((line = rd.readLine()) != null) {
				result.append(line);
			}

**Comment by Zapotek** [comment]
Is that the entire login script? Also, why are you specifying `no_proxy`?
In addition, `localhost` and `127.0.0.1` won't work as targets for Arachni so you can't use the in the login script either.

**Comment by nnvnaveen** [comment]
Hi ,
I've removed this line ENV['no_proxy'] = "127.0.0.1" from the script and tried. 

I gave "puts browser.url" in  my script and it was giving right url but it is not showing the right content when i printed html body . but same script is working as i said from arahcni bin path when i execute from command line as I said

**Comment by Zapotek** [comment]
There should be no difference between the CLI and REST, are you sure everything else is identical?
Same machine, same network, same target etc.?

**Comment by nnvnaveen** [comment]
Hi  Tasos,
Yes both are identical and no difference.  Can you confirm path of my java client..? Does it needs to be in archani software path?

**Comment by Zapotek** [comment]
The client's path doesn't make any difference but please try specifying the full path to the login script instead of a relative one.

**Comment by Zapotek** [comment]
I just noticed that the error doesn't match the login script, any chance you've got 2 login scripts with the same name at different places?

**Comment by nnvnaveen** [comment]
Hi Tasos,

I have my login script at only one place [C:\Naveen\softwares\arachni\arachni-2.0dev-1.0dev-windows-x86_64\bin] 

Sorry for the   form id fields  mismatch in error trace as I edited error manually to post in this forum due to my security reasons
2016-12-29 16:45:15 -0500] Session: [Watir::Exception::UnknownObjectException] unable to locate element, using {:id=>"**loginForm**", :tag_name=>"form"} seems not able to find the element..

**Comment by Zapotek** [comment]
Is there some other info that you've edited out?

**Comment by nnvnaveen** [comment]
No Tasos,
I did not edit any thing beyond form names ..

**Comment by Zapotek** [comment]
I'm sorry I don't know how to help you and I don't know of anyone having similar issues.
Any chance I can be given access to the webapp and try this for myself/

**Comment by Zapotek** [comment]
Couldn't reproduce so closing due to lack of feedback, feel free to comment if you've got something for me.
