### ISSUE TITLE
Crawler Option Only

### ISSUE THREAD

**Issue by urand0m** [Arachni/arachni#817]
Hello,

Is it possible to just have a crawler type switch which will just spider the site and print the links?
If this feature is already in, please could you share how to?

Thanks a lot

**Comment by Zapotek** [comment]
You can use `--checks=-` to not load any checks, or `--checks=trainer` to only load the trainer which helps with the crawl.

Cheers

**Comment by urand0m** [comment]
Fantastic, and this would print the list of crawled url or should i save as report?

**Comment by Zapotek** [comment]
You'll need to generate a report and extract the sitemap, it's pretty simple. JSON would be the easiest way.
