### ISSUE TITLE
Errors Reported During Scan

### ISSUE THREAD

**Issue by JGoLabs** [Arachni/arachni#821]
The following errors were received while running under Arachni under Kali Linux.  I suspect it ran out of resources, but hope the error log helps you improve the product.  If you need any further details, let me know.

[errors.txt](https://github.com/Arachni/arachni/files/692841/errors.txt)

**Comment by Zapotek** [comment]
Looks like you need to increase your open files limit; out of curiosity, can you please show me the current limits by pasting the output of `ulimit -a`?
