### ISSUE TITLE
XML Report - Body tag

### ISSUE THREAD

**Issue by myrinx** [Arachni/arachni#823]
Hi Tasos,

A request from my end. When processing the XML output in python with BeautifulSoup's LXML parser, the <body> tag is being removed, which causes a break in the XML file. It can be fixed by adding an additional step and replacing all <body> tags by something else.

The request is if it would be possible to change the XML output to something like <body_r> to prevent XML-parsers from breaking.

Thanks

**Comment by Zapotek** [comment]
I'm not sure I understand, which body tag and where?

**Comment by Zapotek** [comment]
Ah, you must mean `issues/page/body`, although I don't see why that would break XML parsers; `body` doesn't have special meaning.

**Comment by Zapotek** [comment]
You must be looking for this: http://stackoverflow.com/a/15914890/1889337
