### ISSUE TITLE
Arachni Scan Issue

### ISSUE THREAD

**Issue by leeroyc** [Arachni/arachni#825]
Hi, I had not used Arachni for some time and since upgarding to MacOS Sierra I wondered if I had a related issue to the update. I updated to teh latest version just now (downloaded from site) and also applied this fix to the environment: https://gist.github.com/Zapotek/26b1150c4c52eaeb4984ab60e2d4ce1d

The reason I applied this fix was becuase I had a libcurl issue reported by another user and this solved it for them and also for me.

Now once I run a scan, it comes back clean, but I do get errors, so I thought I should report incase anyone else has similar issues, or it is just me.

Any ideas? Happy to provide more info if needed.
[arachni_error.txt](https://github.com/Arachni/arachni/files/700014/arachni_error.txt)

**Comment by Zapotek** [comment]
Both issues have been fixed in the [nightlies](http://downloads.arachni-scanner.com/nightlies/), they'll be released as stable any time now.

Cheers
