### ISSUE TITLE
Could not find a form suiting the provided parameters.

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#830]
Dear Tasos,

I am providing username and parameters as two parameters to a login url for successful authentication using autologin plugin. For some of the application it is working fine, however for some of the applications it is saying "Could not find a form suiting the provided parameters." May I know the reason? I checked in the request and confirmed that the parameter names i supplied are correct.

Also, for same autologin syntax, sometimes during execution Arachni shows message as:

[!] [session#login_from_configuration:383] Session: Form submitted.
[!] [session#logged_in?:285] Session: Performing login check.
[!] [session#logged_in?:291] Session: Login check done: True
[!] [session#logged_in?:294] Session: 

and performs authenticated scan.

and for same syntax sometimes it gives the value of Login check done: false.

and it starts non-authenticated scan.

Please help me on the same.

Regards,
Pankaj

**Comment by Zapotek** [comment]
That would greatly depend on the webapp, I'll need access in order to be of more assistance.

Cheers

**Comment by theinfosecguyPankaj** [comment]
Sure Tasos. 

Let me know your convenient time and how can I share my screen with you? How about skype?

**Comment by Zapotek** [comment]
That's not very convenient, can you send me the URL and configuration over e-mail please?

**Comment by theinfosecguyPankaj** [comment]
Configuration I can tell you bt URL is confidential. Will not be able to
share. Let me know other best possible options. Apologies for inconvenience.

**Comment by Zapotek** [comment]
The autologin plugin has its limitations and may not work for every webapp, my advice would be switching to the login script plugin for the cases where autologin doesn't work.
