### ISSUE TITLE
Possible security risk

### ISSUE THREAD

**Issue by dnyrop** [Arachni/arachni#832]
I noticed that phantomJS is available on the network interface of the machine running arachni.
I can actually get a response from phantomJS by calling `[IP of my machine running arachni]:[a phantomjs port]` 

This command shows the ports that phantomjs opens: `netstat --listen -e -p` on linux.

Would it be possible to reject packages that doesn't originate from the scan ? 
Or simply not to have phantomJS available from the outside at all ?

**Comment by Zapotek** [comment]
I've forwarded the bug upstream: https://github.com/ariya/phantomjs/issues/14786

**Comment by Zapotek** [comment]
Closing this since it's a bug in PhantomJS.
