### ISSUE TITLE
Error installing puma-2.14.0

### ISSUE THREAD

**Issue by B4ckP0r7** [Arachni/arachni#833]
I downloaded Arachni from github, and when i try "bundler install", it gives me that error!

bundler install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 11.3.0
Using addressable 2.3.6
Using arachni-reactor 0.1.2
Using awesome_print 1.6.1
Using bundler 1.13.6
Using ffi 1.9.17
Using coderay 1.1.0
Using concurrent-ruby 1.0.2
Using http_parser.rb 0.6.0
Using kramdown 1.4.1
Using nokogiri 1.6.8.1
Using msgpack 0.7.0
Using oj 2.15.0
Using oj_mimic_json 1.0.1
Using ox 2.4.9
Using mime-types-data 3.2016.0521
Installing puma 2.14.0 with native extensions
Using rack 1.6.4
Using rb-readline 0.5.1
Using rubyzip 1.1.6
Using websocket 1.2.4
Using tilt 2.0.6
Using backports 3.6.8
Using multi_json 1.12.1
Using terminal-table 1.4.5
Using benchmark-ips 2.7.2
Using diff-lcs 1.3
Using docile 1.1.5
Using i18n 0.8.0
Using json 2.0.3
Using memory_profiler 0.9.7
Using method_source 0.8.2
Using slop 3.6.0
Using redcarpet 3.4.0
Using rspec-core 2.99.2
Using rspec-mocks 2.99.4
Using ruby-mass 0.1.3
Using simplecov-html 0.10.0
Using stackprof 0.2.10
Using sys-proctable 1.1.3
Using yard 0.9.8
Using arachni-rpc 0.2.1.4
Using childprocess 0.5.3
Using ethon 0.10.1
Using concurrent-ruby-ext 1.0.2
Using loofah 2.0.3
Using mime-types 3.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170201-9914-relrbfpuma-2.14.0/gems/puma-2.14.0/ext/puma_http11
/usr/bin/ruby2.3 -r ./siteconf20170201-9914-125rsy4.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20170201-9914-relrbfpuma-2.14.0/extensions/x86-linux/2.3.0/puma-2.14.0/mkmf.log

current directory: /tmp/bundler20170201-9914-relrbfpuma-2.14.0/gems/puma-2.14.0/ext/puma_http11
make "DESTDIR=" clean

current directory: /tmp/bundler20170201-9914-relrbfpuma-2.14.0/gems/puma-2.14.0/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
compiling mini_ssl.c
In file included from mini_ssl.c:4:0:
/usr/include/ruby-2.3.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
 #warning use "ruby/io.h" instead of "rubyio.h"
  ^~~~~~~
mini_ssl.c: In function ‘get_dh1024’:
mini_ssl.c:80:5: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
   dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
     ^~
mini_ssl.c: In function ‘engine_init_client’:
mini_ssl.c:182:3: warning: ‘DTLSv1_method’ is deprecated [-Wdeprecated-declarations]
   conn->ctx = SSL_CTX_new(DTLSv1_method());
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from mini_ssl.c:9:
/usr/include/openssl/ssl.h:1614:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
Makefile:239: set di istruzioni per l'obiettivo "mini_ssl.o" non riuscito
make: *** [mini_ssl.o] Errore 1

make failed, exit code 2

Gem files will remain installed in /tmp/bundler20170201-9914-relrbfpuma-2.14.0/gems/puma-2.14.0 for inspection.
Results logged to /tmp/bundler20170201-9914-relrbfpuma-2.14.0/extensions/x86-linux/2.3.0/puma-2.14.0/gem_make.out

An error occurred while installing puma (2.14.0), and Bundler cannot continue.
Make sure that `gem install puma -v '2.14.0'` succeeds before bundling.

and i tried online too with installing again openssl and more.
I'm on Parrot Security OS Latest.

**Comment by Zapotek** [comment]
Like you said, the error is with Puma and also with what looks like an issue with your system's build utilities, so I'm not sure how I can help.
My question though is: why aren't you using the provided packages?

**Comment by B4ckP0r7** [comment]
i installed it from repositories with "sudo apt-get install arachni*" same error, then downloaded the .tgz file, unpacked and tried "bundler install" but again this error.
The problem is that it won't download this specific version, because "gem install puma" works, but arachni need that specified version.
Searched on google and github about it, found that is an openssl problem. Tried everything, reinstall openssl, install all missing packages, but nothing worked!

**Comment by Zapotek** [comment]
The proper way to use Arachni is to download the official packages: http://www.arachni-scanner.com/download/
