### ISSUE TITLE
ruby.exe not compatible in windows 7 32bit

### ISSUE THREAD

**Issue by putuoka** [Arachni/arachni#835]
i got this error when running arachni.bat inside /bin folder

This version of C:\Users\Toshiba\Downloads\arachni-1.5-0.5.11-windows-x86_64\system\ruby\bin\ruby.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

**Comment by Zapotek** [comment]
Sorry, only a 64bit version is provided for MS Windows, I don't plan on releasing a 32bit MS Windows version.
