### ISSUE TITLE
Import targets from file + scan queue

### ISSUE THREAD

**Issue by MrScrudg** [Arachni/arachni#837]
Hello, my little future request
 Add:
 1. Option to load list of websites from file (txt/csv | http(s)://example.com/)
 2. Plugin for managing scan queue (max=n, if running<n, then start x scans so running=n)
Hope to see such update :)

**Comment by Zapotek** [comment]
Sorry, that's outside the scope of the project and can be better performed by a simple shell script or a script using Arachni's REST or RPC APIs.

**Comment by MrScrudg** [comment]
sorry, i forgot to write that i mean such option for WEBUI, not for comand-line interface. Is there a chance to see a little button "load targets from file" in next updates of WEBUI?

**Comment by Zapotek** [comment]
The WebUI issue tracker is located at: https://github.com/Arachni/arachni-ui-web/issues

However, the WebUI has stopped receiving new features as it's going to be replaced by a new web interface. This feature is going to be present in the new one.

**Comment by MrScrudg** [comment]
ok, thanks for response. Will be waiting for update, hope it will be soon :) P.S do i need to move this feature request to WEBUI issue tracker ?

**Comment by Zapotek** [comment]
No it's OK.
