### ISSUE TITLE
issue on sending multiple cookies via http-cookie-string

### ISSUE THREAD

**Issue by jeremychoi** [Arachni/arachni#839]
Testing with 1.5-0.5.11(linux i686), I hit an issue that only the first cookie is sent although I set multiple cookies. With DVWA set as a target, the CLI command I ran is:

$ bin/arachni http://192.168.56.102/dvwa/vulnerabilities/fi/ --checks=file* --scope-page-limit=1 --browser-cluster-pool-size=1 --audit-links --http-cookie-string="security=low; PHPSESSID=6ub86cj06iitiofo186auo2983" --http-proxy=127.0.0.1:8080

In the proxy, I saw like:

GET /dvwa/vulnerabilities/fi/ HTTP/1.1
Host: 192.168.56.102
Accept-Encoding: gzip, deflate
User-Agent: Arachni/v1.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,he;q=0.6
X-Arachni-Scan-Seed: 0af69642727f4641148b119b815bb824
Cookie: security=low
Connection: close

Note that the Cookie header only includes the first cookie.

The previous version(1.4) had no issue.

**Comment by Zapotek** [comment]
The format of that option has changes to only support `Set-Cookie` style cookies, see: https://github.com/Arachni/arachni/wiki/Command-line-user-interface#cookie-string---http-cookie-string
