### ISSUE TITLE
Arachni is so slow...

### ISSUE THREAD

**Issue by elmondogri** [Arachni/arachni#843]
Hello, I am running arachni on a windows 2008 r2 server (24gb of ram, octocore i7 3.33ghz, nothing else than arachni running, and a 1gb/s connexion), with thoses stats I exptected arachni to be light fast but no.

When it takes about 15 mins to scan a small site for acunetix, i left arachni for more than 1 day before stopping it, and it didn t even found the sqli that acunetix found in about 5 mins..
I ve tried with differents websites, it takes a lot of time, I never finished even one scan on 5 differents sites since 2 days.

Arachni seems to be a great project and I can see many people are pleased with it, but why isn t it working the same for me? I don t understand.

Thank you.

PS: Btw I'd like to add that i ve already read the doc @ http://support.arachni-scanner.com/kb/general-use/optimizing-for-faster-scans

**Comment by Zapotek** [comment]
Any chance I can be given access to that site to see what's going on?

**Comment by elmondogri** [comment]
Yes but it s not one particular site, i ve tested many site and always have the same problem, if there is any provate chatting method i ll let you check.

**Comment by Zapotek** [comment]
You can send me an e-mail at: tasos.laskos@arachni-scaner.com

**Comment by elmondogri** [comment]
email sent, btw the mail is @arachni-scanner.com I guess cause @arachni-scaner was rejected.

**Comment by Zapotek** [comment]
Yep, my bad, still drinking my coffee.

**Comment by Zapotek** [comment]
Closing this since I couldn't find an issue with Arachni, for the record the gist of it was:

* One site had a large archive of large document files (.doc, .pdf, .ppt, etc.) that Arachni had to download.
* All of the reported sites responded slowly, so Arachni had to throttle itself down in order to maintain stability and not kill the servers.
