### ISSUE TITLE
nearly 10000 files created on /tmp

### ISSUE THREAD

**Issue by gittygoo** [Arachni/arachni#850]
With names such as "Arachni_Support_Database_Queue_" how can i make sure that these are within a reasonable limit? This ended up filling all my /tmp drive (nearly 6gb).

**Comment by Zapotek** [comment]
Sadly, you can't. That data needs to be stored somewhere.

**Comment by gittygoo** [comment]
Any way I can move it to another place or somehow limit the amount of space it takes ?

**Comment by Zapotek** [comment]
You can't limit the space but you can check for ways to change the tmp directory for the process.
I don't know how to be honest and a few things I tried (changing env variables) didn't work.

**Comment by gittygoo** [comment]
@Zapotek I am in need of a "hack" even if it is temporary... looking through the code i found https://github.com/Arachni/arachni/blob/5e89af5d238b5342bb609d000f2aba32a56231f3/lib/arachni/support/database/base.rb

`def generate_filename
        # Should be unique enough...
        "#{Arachni.tmpdir}/#{self.class.name}_#{Process.pid}_#{object_id}_#{@filename_counter}".gsub( '::', '_' )
    ensure`

and changed to 

`def generate_filename
        # Should be unique enough...
        "/mydrive/tmp/#{self.class.name}_#{Process.pid}_#{object_id}_#{@filename_counter}".gsub( '::', '_' )
    ensure`


would that be enough ? I am currently running an arachni scan and files are being correctly placed on /mydrive/tmp, i was just wondering if i need to change this somewhere else on the code?

**Comment by Zapotek** [comment]
Should be enough yes, but be careful when modifying the source.

**Comment by gittygoo** [comment]
Hi @Zapotek first of all thank you for the quick replies. So that seems to work correctly, the files are now placed on /mydrive/tmp/ .

What exactly is the content of these files? I have tried to look at contents but it all just seems gibberish to me. I would like to know this to try and understand how i can somehow limit their creation.

I do not mind SOME files being created but nearly 10.000 makes me think something is not correct.

As i understand there is no parameter/option on arachni that i can set to limit their creation?

Can you  explain how this queue works a bit better/in short?
