### ISSUE TITLE
Plugin:Proxy problem

### ISSUE THREAD

**Issue by ztencmcp** [Arachni/arachni#852]
Hello, 

I would like to pass username,password and captcha through Proxy plugin, but i tried to use firefox and chrome, firefox showed error like "SEC_ERROR_UNKNOWN_ISSUER" and Chrome responsed with "NET::ERR_CERT_AUTHORITY_INVALID" . I also tried to add it into exception, but can't help. how can i do ? Thanks.

**Comment by Zapotek** [comment]
Did you import Arachni's CA certificate into your browser?
Its location is printed to the console when starting the proxy.

**Comment by ztencmcp** [comment]
yes, but it can't import into browser, also showed error when import it into browser.

**Comment by Zapotek** [comment]
It works for me on Firefox, did you import it as an Authority certificate and check the relevant boxes?

**Comment by ztencmcp** [comment]
How to import as Authority certificate ?

**Comment by ztencmcp** [comment]
okay, let me try it again.

**Comment by ztencmcp** [comment]
it works now, thank you !
