### ISSUE TITLE
Plugin-Proxy and Scan

### ISSUE THREAD

**Issue by ztencmcp** [Arachni/arachni#854]
Hello,

I have to say arachni is great tool, and i have a problem when i use proxy plugin to manually crawl inner resources that protected by app, that is arachni will scan all resources that it crawled after i complete crawling all resources or scan resoures while crawl resources? another question, if i launch arachni proxy plugin without --check and --audit xxx, it will check and audit all, right ?

**Comment by Zapotek** [comment]
I'm not quite sure what you want to do, do you want the system to only scan pages identified by using the proxy plugin and nothing else (i.e. not perform a crawl)?

**Comment by ztencmcp** [comment]
I just want to know when I use proxy plugin, it will scan everything that I manually crawl at same time, right ? or scan crawled things after I complete crawling?

**Comment by Zapotek** [comment]
No, it will scan after the proxy has been shut down.

**Comment by ztencmcp** [comment]
how to shutdown the proxy?

**Comment by Zapotek** [comment]
That information is printed out in the terminal when the proxy is enabled.

**Comment by ztencmcp** [comment]
okay, thank you!
