### ISSUE TITLE
[Mac OS X] How to resolve SHA-1 mismatch?

### ISSUE THREAD

**Issue by bryongloden** [Arachni/arachni#855]
🐛 label: #crypto

Greetings,

File [arachni-1.5-0.5.11-darwin-x86_64.tar.gz](https://github.com/Arachni/arachni/releases/download/v1.5/arachni-1.5-0.5.11-darwin-x86_64.tar.gz) has a SHA-1 digest of: `758f0f4e9d24e84bbd582a65a9b9e5b272be15fd`

The message digest of file [arachni-1.5-0.5.11-darwin-x86_64.tar.gz.sha1](https://github.com/Arachni/arachni/releases/download/v1.5/arachni-1.5-0.5.11-darwin-x86_64.tar.gz.sha1) is: `413aa7f636f88195fce34ce2ef71fdfcc98ce4c8`

```
Last login: Sat Mar 18 15:14:00 on ttys001
$ openssl sha1 arachni-1.5-0.5.11-darwin-x86_64.tar
SHA1(arachni-1.5-0.5.11-darwin-x86_64.tar)= 758f0f4e9d24e84bbd582a65a9b9e5b272be15fd
$ cat arachni-1.5-0.5.11-darwin-x86_64.tar.gz.sha1
413aa7f636f88195fce34ce2ef71fdfcc98ce4c8
```

These digest should never be different, i.e., SHA-1 digest verification should never fail.

Signed-off-by: Bryon Gloden, CISSP® <cissp@bryongloden.com>

**Comment by Zapotek** [comment]
I'm getting the right hash, are you sure you downloaded the package in its entirety?

**Comment by bryongloden** [comment]
100% sure.

**Comment by Zapotek** [comment]
Can the archive be extracted without issue?

**Comment by bryongloden** [comment]
Yes.

**Comment by Zapotek** [comment]
I re-downloaded the package just to make sure and the SHA1 hashes match for me again.
Can you try re-downloading and rechecking as well?

Also, could I trouble you to upload that package with the mismatch somewhere so that I can take a closer look?

**Comment by Zapotek** [comment]
Btw, my filesize is 177878030 bytes, what's yours?

**Comment by bryongloden** [comment]
```
$ ls -la *.tar
-rw-r--r--@ 1 bryongloden  staff  664985600 Mar 19 10:45 arachni-1.5-0.5.11-darwin-x86_64.tar
$ 
```

**Comment by Zapotek** [comment]
What's your location?
I'd like to forward this issue to the GH staff and knowing which mirror served you will be helpful.

**Comment by bryongloden** [comment]
I'd prefer to email you my location. What's your PGP public key?

**Comment by Zapotek** [comment]
Ping me at tasos.laskos@arachni-scanner.com

Also, can you please download the package a few times and post filesizes and SHA1 hashes?

**Comment by Zapotek** [comment]
I responded with my PGP key attached (from a different address though) some time ago, did you receive it?

**Comment by bryongloden** [comment]
Yes. Thank you, Tasos. Safari is dumb, and we are running the verification against the tar, not the gz. If we hold the ⌥ alt button while clicking on [arachni-1.5-0.5.11-darwin-x86_64.tar.gz](https://github.com/Arachni/arachni/releases/download/v1.5/arachni-1.5-0.5.11-darwin-x86_64.tar.gz), it prevents Safari from unzipping after download. Disabling 'Open "safe" files after downloading' also prevents Safari from automatically unzipping files.

```
Last login: Sun Mar 19 12:45:00 on ttys001
$ openssl sha1 arachni-1.5-0.5.11-darwin-x86_64.tar.gz
SHA1(arachni-1.5-0.5.11-darwin-x86_64.tar.gz)= 413aa7f636f88195fce34ce2ef71fdfcc98ce4c8
$ cat arachni-1.5-0.5.11-darwin-x86_64.tar.gz.sha1
413aa7f636f88195fce34ce2ef71fdfcc98ce4c8
```

**Comment by Zapotek** [comment]
Oh man, I didn't even notice the extension from your terminal output.
Anyhow, all's well that ends well.
