### ISSUE TITLE
Arachni log files filling up hard drive/PhantomJS Memory issues

### ISSUE THREAD

**Issue by sbehrens** [Arachni/arachni#858]
Hi Tasos,

I'm seeing a lot of log files with one of the most recenlty nightlies, some of which are filling up gigs of hard drive space:

![image](https://cloud.githubusercontent.com/assets/688589/24107678/a3bbb6f6-0d48-11e7-9f56-4a4a77b284ae.png)

Memory also seems high on Ruby/PhantomJS?  

![image](https://cloud.githubusercontent.com/assets/688589/24107741/cddb069e-0d48-11e7-8d17-507a6dd4be95.png)

Are you aware of any issues with the recent nightlies?  Do I need to upgrade?

**Comment by Zapotek** [comment]
There's no change between the stable version and the nightlies that could cause a difference.

These aren't logfiles btw, but excess scan workload which is offloaded to disk to keep memory usage down.
As the name suggests, the files are queue items which will be deleted once processed.

As for PhantomJS, it's the same version as stable.

About RAM usage (I'm assuming that RES is in KB because I doubt that `top` is using 1GB), it doesn't seem that high.

**Comment by sbehrens** [comment]
It's filling up around 4-6 gigs of data on disk and killing our instances.

**Comment by Zapotek** [comment]
I don't really consider that a bug in Arachni though, a few GB (or even 10+) of temporary storage being available during the runtime of the program is a fair requirement; almost everyone has that to spare.

However, I see 10 browser workers in the cluster pool, I'd suggest using the default value of 6 or even lowering it if you want the system to use less resources. Right now they generate too much workload that the system can't get to in time and it's just piling up.

I'm closing this for now, but if disk usage becomes uncontrollable in some way then I would consider that a bug so please reopen[1].
Also, let me know of how the system does when configured to use less browser workers.

[1] This is the second time I've gotten this complain, but never with or prior to v1.4, so I could have made a change in v1.5 (current stable) that altered behavior. I'll keep an eye out for a bug in this area but so far the behavior of the system is acceptable.

**Comment by sbehrens** [comment]
Is there anyway to change where these files are logged?  Since uploading the nightlies a couple weeks ago we've been seeing all of our boxes hitting disk issues.

**Comment by Zapotek** [comment]
I've made the tmpdir configurable, now running the specs and will let you know once a nightly is up.

**Comment by sbehrens** [comment]
Awesome, thanks Tasos!

**Comment by Zapotek** [comment]
Bo problem, nightlies are up.
