### ISSUE TITLE
[Mac OS X] SHA-1 File Verification

### ISSUE THREAD

**Issue by bryongloden** [Arachni/arachni#859]
:bug: label: #crypto

Greetings,

This issue is the file verification process of Arachni self-contained packages. SHA-1 was officially deprecated by NIST in 2011 due to fundamental security weaknesses demonstrated in various analyses and theoretical attacks. Despite the high complexity and computational cost of finding a collision, on February 23, 2017, CWI Amsterdam and Google announced the SHAttered attack, in which they generated two different PDF files with the same SHA-1 hash [0]. Therefore, we recommend updating Arachni self-contained package digest from SHA-1 to SHA-256. Valid alternatives could be SHA-384 or SHA-512.

[0] https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html

Signed-off-by: Bryon Gloden, CISSP® <cissp@bryongloden.com>

**Comment by Zapotek** [comment]
Point taken, subsequent builds will use SHA521.

Ref: https://github.com/Arachni/build-scripts/commit/0c5333c991b5dbb669dcb107a70aeacaa8e97391
