### ISSUE TITLE
Exclude pattern in rest server

### ISSUE THREAD

**Issue by dadabhaijan** [Arachni/arachni#861]
I want to know that how I can exclude files using `scope-exclude-pattern` for  REST server

**Comment by dadabhaijan** [comment]
Where I can find the available options list for REST server?

**Comment by Zapotek** [comment]
Did you check out the [API doc](https://github.com/Arachni/arachni/wiki/REST-API)?

**Comment by dadabhaijan** [comment]
Yes! I have checked but can not find `scope-exclude-pattern` scope option. When i use `"exclude_pattern":["*.css"],` it gives the error 
``
 undefined method `exclude_pattern='
``

**Comment by Zapotek** [comment]
The option you need is mentioned in the API, search for `exclude_path_patterns` in the Wiki page and you'll find it.
