### ISSUE TITLE
How to restrict Scan scope to a directory.

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#863]
As part of my project I am scanning a fellow student's web application. He is serving it on his laptop using Xampp on Windows 10

I am accessing it as http://192.168.2.20/template/ . Arachni seems to be scanning the whole Xampp  server. Is there a scope restriction I have missed?

I notice that on the web ui for the scan, template is displayed in lower case. Perhaps Arachni is disregarding it and just scanning the base url? Is it possible to do some sort of exclusion what restricts Arachni to the Template directory  and stops it stepping back?

**Comment by bgerardw** [comment]
In case this issue is useful to others. I am now running a scan with
 --scope-include-pattern=192.168.2.20/template/ .

**Comment by Zapotek** [comment]
Yep, that'll do it.
