### ISSUE TITLE
Scan just returns a 301

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#867]
HI,

I decided to scan http://www.riotgames.com/ (League of Legends fan). The can just hit one page and returned a 301. What have I missed, Arachni handles redirects I believe?

**Comment by Zapotek** [comment]
It works fine for me, the only issue I see is with the `https` version of the site which returns a `503`.
I don't get a redirect when visiting via Firefox either.

Shall I assume that you didn't try to scan http://www.riotgames.com/ but http://riotgames.com/ without enabling the `--scope-include-subdomains` option?

**Comment by bgerardw** [comment]
That is correct, enabled it now. Thanks.
