### ISSUE TITLE
Unable to scan the --audit-json of xss

### ISSUE THREAD

**Issue by dingmandmq** [Arachni/arachni#868]
Hi,Zapotek
When I tried to test the --audit-json,use vector_feed plugin,I have a trouble:
First,my environment
```
os: centos 6.8
arachni:1.5.1
phantomjs:2.1.1
ruby:2.3.3
```

I made a xss on my server:
```
[root@security bin]# curl -H "Content-Type: application/json" -X POST -d '{ "id": "111111" }' http://10.0.80.80:8000/index.php/home/test/test
111111
```
and  I wanted to use arachni to scan the xss issue.

when I ran this command , arachni seems stoped unexpectedly and no issues were detected

`arachni http://10.0.80.80:8000/index.php/home/test/test  --checks=xss* --plugin=vector_feed:yaml_file=/tmp/10.0.80.80:8000_f134fe7bdc970fa2fbd2c67b9f9aa750.yml --scope-page-limit=0`

> 
> Arachni - Web Application Security Scanner Framework v1.5.1
>    Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>
> 
>            (With the support of the community and the Arachni Team.)
> 
>    Website:       http://arachni-scanner.com
>    Documentation: http://arachni-scanner.com/wiki
> 
> 
>  [~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs.
> 
>  [*] Initializing...
>  [*] Preparing plugins...
>  [*] Vector feed: Imported 1 vectors.
>  [*] Vector feed: Pushing the vectors to the audit queue...
>  [*] Vector feed: Done!
>  [*] ... done.
>  [*] BrowserCluster: Initializing 6 browsers...
>  [*] BrowserCluster: Spawned #1 with PID 31636 [lifeline at PID 28934].
>  [*] BrowserCluster: Spawned #2 with PID 3823 [lifeline at PID 1251].
>  [*] BrowserCluster: Spawned #3 with PID 8674 [lifeline at PID 5922].
>  [*] BrowserCluster: Spawned #4 with PID 13178 [lifeline at PID 10601].
>  [*] BrowserCluster: Spawned #5 with PID 17848 [lifeline at PID 15273].
>  [*] BrowserCluster: Spawned #6 with PID 22408 [lifeline at PID 19874].
>  [*] BrowserCluster: Initialization completed with 6 browsers in the pool.
> 
>  [*] [HTTP: 200] http://10.0.80.80:8000/index.php/home/test/test
>  [~] Identified as: php
>  [~] DOM depth: 0 (Limit: 5)
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/<my_tag_7f36b9d253f97d00edf1b9fdac38f33e/>
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/>"'><my_tag_7f36b9d253f97d00edf1b9fdac38f33e/>
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/
>  [*] XSS in path: Checking for: http://10.0.80.80:8000/index.php/home/test/test/
>  [*] Harvesting HTTP responses...
>  [~] Depending on server responsiveness and network conditions this may take a while.

the content of yml file:
```
action: http://10.0.80.80:8000/index.php/home/test/test
inputs:
  id: "1"
method: post
type: json
```

**Comment by Zapotek** [comment]
There's no XSS checks on JSON inputs alone, because that response would be useless unless it was incorporated into the DOM somehow.

If you had a form that had an input that triggers an XSS vuln, and that form when submitted sent a JSON request whose response was then placed into the page, then Arachni would identify it.
