### ISSUE TITLE
Issue with exec plugin to execute third party tools

### ISSUE THREAD

**Issue by theinfosecguyPankaj** [Arachni/arachni#870]
Dear Tasos,

I have designed a python script which is acting as a third party tool for Arachni framework. I am using below command to execute the script:

Arachni --plugin=exec:during="Python D:\security_automation\ThirdPartyTools.py 12.23.345.735" http://demo.testfire.net/bank/login.aspx

Arachni is continuously giving me error:

No such file or directory - python D:\security_automation\ThirdPartyTools.py 12.23.345.735

Please suggest.

-Pankaj

**Comment by Zapotek** [comment]
The system is expecting an executable file, you're giving it a shell command.
