### ISSUE TITLE
rake spec build fails on Kali 2016.2

### ISSUE THREAD

**Issue by manasmbellani** [Arachni/arachni#874]
I am trying to install arachni on Kali 2016.2, but I get the following error - I tried to search this error on the net, but I am unable to determine what the exact issue is and how to remediate this. 

I tried to install msgpack via 'gem install msgpack', but this did not fix the issue. Any directions on how to remediate this are really appreciated.

$ rake spec
(in /opt/arachni)                                                        
rake aborted!                                                            
LoadError: /var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack/msgpack.so:
 undefined symbol: rb_num2int - /var/lib/gems/2.3.0/gems/msgpack-0.7.0/li
b/msgpack/msgpack.so                                                     
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:11:in `require'    
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:11:in `rescue in <t
op (required)>'                                                          
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:8:in `<top (require
d)>'                                                                     
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `require'                
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `<top (required)>'       
/opt/arachni/lib/arachni/report.rb:9:in `require_relative'               
/opt/arachni/lib/arachni/report.rb:9:in `<top (required)>'               
/opt/arachni/lib/arachni/framework.rb:35:in `require'                    
/opt/arachni/lib/arachni/framework.rb:35:in `<module:Arachni>'           
/opt/arachni/lib/arachni/framework.rb:17:in `<top (required)>'           
/opt/arachni/lib/arachni.rb:97:in `require_relative'                     
/opt/arachni/lib/arachni.rb:97:in `<top (required)>'                     
/opt/arachni/Rakefile:11:in `<top (required)>'                           
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'   
LoadError: cannot load such file -- msgpack/2.3/msgpack                  
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:9:in `require'     
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:9:in `<top (require
d)>'                                                                     
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `require'                
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `<top (required)>'       
/opt/arachni/lib/arachni/report.rb:9:in `require_relative'
/opt/arachni/lib/arachni/report.rb:9:in `<top (required)>'               
/opt/arachni/lib/arachni/framework.rb:35:in `require'                    
/opt/arachni/lib/arachni/framework.rb:35:in `<module:Arachni>'           
/opt/arachni/lib/arachni/framework.rb:17:in `<top (required)>'           
/opt/arachni/lib/arachni.rb:97:in `require_relative'                     
/opt/arachni/lib/arachni.rb:97:in `<top (required)>'                     
/opt/arachni/Rakefile:11:in `<top (required)>'                           
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'   
LoadError: cannot load such file -- msgpack/2.3/msgpack                  
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:9:in `require'     
/var/lib/gems/2.3.0/gems/msgpack-0.7.0/lib/msgpack.rb:9:in `<top (require
d)>'                                                                     
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `require'                
/opt/arachni/lib/arachni/rpc/serializer.rb:9:in `<top (required)>'       
/opt/arachni/lib/arachni/report.rb:9:in `require_relative'               
/opt/arachni/lib/arachni/report.rb:9:in `<top (required)>'               
/opt/arachni/lib/arachni/framework.rb:35:in `require'                    
/opt/arachni/lib/arachni/framework.rb:35:in `<module:Arachni>'           
/opt/arachni/lib/arachni/framework.rb:17:in `<top (required)>'           
/opt/arachni/lib/arachni.rb:97:in `require_relative'                     
/opt/arachni/lib/arachni.rb:97:in `<top (required)>'                     
/opt/arachni/Rakefile:11:in `<top (required)>'                           
/var/lib/gems/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'

**Comment by Zapotek** [comment]
Please use the [official packages](http://www.arachni-scanner.com/download/), they're there to avoid these issues.
