### ISSUE TITLE
Centos7 arachni_rest_server timeout when perform a new scan

### ISSUE THREAD

**Issue by nobleXu** [Arachni/arachni#875]
I use arachni in Centos7. I install it by download the releases directly.
However, when I perform a new scan on arachni_rest_server, I always get a "timeout" error. But sometimes, I can perform a scan. Moreover, I can list all scans, get report , delete scan with no problem. I'm confused by this problem , waiting for your reply!

In addition, I use it on my Mac successfully .

With regards！

**Comment by Zapotek** [comment]
Have you tried increasing the request timeout of your HTTP client?

**Comment by nobleXu** [comment]
Thank you for reply! 
Yes, I set timeout to 30 and the problem has been solved! Thanks
