### ISSUE TITLE
Anti-csrf token not recognized

### ISSUE THREAD

**Issue by rukavina** [Arachni/arachni#877]
We get an issue for a form which has csrf token...here's example:
`<input type="hidden" name="csrf" ng-model="vm.formData.csrf" value="ZmQyYWY0M2UyODExMjU2NjcxOTlkZDc1MTFmZTdiMzgtNzI5OTRhZThjMzQ4YTA5MDExY2Q5ZGIxODMwMTFhNTk=">`

Is there any reason the scanner does not recognize this? The value is updated on each load. Form is submitted via ajax (angular) but even source contains all fields and the scanner still complains about possible csrf

Thanks

**Comment by Zapotek** [comment]
May I have access to that page please?

**Comment by rukavina** [comment]
Unfortunately not, but we're using zend framework anti-csrf token: https://framework.zend.com/manual/2.4/en/modules/zend.form.element.csrf.html

I found a few things which might be confusing scanner with this token:

* not base64
* using md5
* in the same session list of tokens are valid: they track in session token id => token value

I changed all of this and does not help.

Then I'm not sure if ajax is causing problems. Form is submitted, and response is application/json and even on invalid pass response is 200 ... but not sure if response code has anything to do with csrf detection

**Comment by Zapotek** [comment]
Can you give the [nightlies](http://downloads.arachni-scanner.com/nightlies/) a shot please?

**Comment by Zapotek** [comment]
Assuming that the issue went away, feel free to re-open if that's not the case.
