### ISSUE TITLE
memory consumption and pending jobs

### ISSUE THREAD

**Issue by bgerardw** [Arachni/arachni#878]
I was running a scan from my local machine on developer.riot.com. I noticed ram on my machine was nearly fully consumed.

As  I monitored the out put I noticed this
`BrowserCluster: Pending jobs: 238830  BrowserCluster: Pending jobs: 238830  `

Is this a lot of jobs and id that what is eating my ram?

Config was:

`Version
2.0dev
Seed
4cbd4913b0889b22c46b921add62778e
Audit started on
2017-04-26 11:10:30 +0100
Audit finished on
2017-04-28 09:46:11 +0100
Runtime
46:35:41
General

URL
https://developer.riotgames.com/

Checks
sql_injection, sql_injection_differential, sql_injection_timing, xss, xss_dom, xss_dom_script_context, xss_event, xss_path, xss_script_context, xss_tag
Plugins
autothrottle
discovery
healthmap
rate_limiter
{"requests_per_second"=>"10"}
timing_attacks
uniformity

Audit
"parameter_values"	true
"exclude_vector_patterns"	[]
"include_vector_patterns"	[]
"link_templates"	[]
"links"	true
"forms"	true
"cookies"	true
"headers"	false
"with_both_http_methods"	false
"cookies_extensively"	false
"jsons"	true
"xmls"	true
"ui_forms"	true
"ui_inputs"	true

Datastore
"report_path"	nil
Input
"values"	
"(?i-mx:name)"	"arachni_name"
"(?i-mx:user)"	"arachni_user"
"(?i-mx:usr)"	"arachni_user"
"(?i-mx:pass)"	"5543!%arachni_secret"
"(?i-mx:txt)"	"arachni_text"
"(?i-mx:num)"	"132"
"(?i-mx:amount)"	"100"
"(?i-mx:mail)"	"arachni@email.gr"
"(?i-mx:account)"	"12"
"(?i-mx:id)"	"1"
"default_values"	
"name"	"arachni_name"
"user"	"arachni_user"
"usr"	"arachni_user"
"pass"	"5543!%arachni_secret"
"txt"	"arachni_text"
"num"	"132"
"amount"	"100"
"mail"	"arachni@email.gr"
"account"	"12"
"id"	"1"
"without_defaults"	true
"force"	false

Http
"user_agent"	"Arachni/v2.0dev"
"request_timeout"	10000
"request_redirect_limit"	5
"request_concurrency"	20
"request_queue_size"	50
"request_headers"	{}
"response_max_size"	500000
"cookies"	{}
"authentication_type"	"auto"

Scope
"redundant_path_patterns"	{}
"dom_depth_limit"	5
"exclude_file_extensions"	["[]"]
"exclude_path_patterns"	[]
"exclude_content_patterns"	[]
"include_path_patterns"	["https://developer.riotgames.com"]
"restrict_paths"	[]
"extend_paths"	[]
"url_rewrites"	{}
"include_subdomains"	false
"exclude_binaries"	false
"https_only"	false
Browser cluster
"local_storage"	{}
"wait_for_elements"	{}
"pool_size"	6
"job_timeout"	10
"worker_time_to_live"	100
"ignore_images"	false
"screen_width"	1600
"screen_height"	1200`

Browser cluster
"local_storage"	{}
"wait_for_elements"	{}
"pool_size"	6
"job_timeout"	10
"worker_time_to_live"	100
"ignore_images"	false
"screen_width"	1600
"screen_height"	1200

**Comment by Zapotek** [comment]
This is a duplicate of: https://github.com/Arachni/arachni/issues/862

I have an idea of how to fix it but I'm still thinking about it, it's a tricky problem.
