### ISSUE TITLE
Skip some pages during the scan.

### ISSUE THREAD

**Issue by dec0dOS** [Arachni/arachni#879]
Hello! Is it possible to skip some pages during the scan in Web UI? Sometimes arachni could scan one page for too long. And it would be really useful to have the ability to skip static/self-checked pages.

**Comment by m6a-UdS** [comment]
You can use `--scope-exclude-pattern=` in order to exclude page; If I am not mistaken, I think you can use it multiple times.

**Comment by dec0dOS** [comment]
With this parameter I can't exclude pages during the scan in Web UI.

**Comment by Zapotek** [comment]
You can find that option under the Scope section of the scan profile you're using.
