### ISSUE TITLE
Enhancing crawling phase

### ISSUE THREAD

**Issue by Tochirou** [Arachni/arachni#881]
Hello,

In some heavy AngularJS websites, the user has to select and/or click on several elements on the page in order to get on the next one. Or in other cases, he just has to wait, when a loading page shows up.
In such cases I am not able to tell arachni scanner what to do in order for it to properly crawl additional pages of the website.

As a matter of fact, do you think it would be possible to include something like a selenium script to help the arachni's crawler ? I have noticed that there is the "browser-cluster-wait-for-element" parameter but in some cases we might need to wait for another element to be poped up by AngularJS depending on the page we land on or on the action that the user does.

If I didn't make myself clear enough, I would be happy to provide further explanation.

**Comment by Zapotek** [comment]
`--browser-cluster-wait-for-element` rules are set per page so you can set different rules for different pages.
As for the selenium script, that won't work for Arachni but there's [something else](https://github.com/Arachni/arachni/issues/812) in the pipeline.
