### ISSUE TITLE
about arachni_rest_server

### ISSUE THREAD

**Issue by 3lackrush** [Arachni/arachni#885]
i was attempt to play scan modules using python, i post the json data to the url and it return me a 401 unauthorized error. i looked into your ruby code. is that you use the specific cookie so that you can solve the login problem? How much time will the cookie last ? forever or something ?

**Comment by 3lackrush** [comment]
i would be appreciate it if you reply me!

**Comment by Zapotek** [comment]
I'm not sure I understand, did you configure the server to require HTTP auth?

**Comment by 3lackrush** [comment]
I start the rest server with this command "./arachni_rest_server --authentication-username admin@admin.admin ----authentication-password administrator". Is that right?

**Comment by 3lackrush** [comment]
oops,i type it wrong in issues. You mean i should include the username and password when posting task to the server.

i done that in this way before you tell me
`def addTask(request):
        url_task = "http://127.0.0.1:7331/scans"
        url = "http://demo.aisec.cn/demo/aisec/"
        payload = {
          "url" : url,
          "http" : {
            "user_agent" : "Arachni/v2.0dev",
            "request_timeout" : 10000,
            "request_redirect_limit" : 5,
            "request_concurrency" : 20,
            "request_queue_size" : 100,
            "request_headers" : {},
            "response_max_size" : 500000,
            "cookies" : {}
          },
          "audit" : {
            "parameter_values" : "true",
            "exclude_vector_patterns" : [],
            "include_vector_patterns" : [],
            "link_templates" : []
          },
          "input" : {
            "values" : {},
            "default_values" : {
              "(?i-mx:name)" : "arachni_name",
              "(?i-mx:user)" : "arachni_user",
              "(?i-mx:usr)" : "arachni_user",
              "(?i-mx:pass)" : "5543!%arachni_secret",
              "(?i-mx:txt)" : "arachni_text",
              "(?i-mx:num)" : "132",
              "(?i-mx:amount)" : "100",
              "(?i-mx:mail)" : "arachni@email.gr",
              "(?i-mx:account)" : "12",
              "(?i-mx:id)" : "1"
            },
            "without_defaults" : "false",
            "force" : "false"
          },
          "browser_cluster" : {
            "wait_for_elements" : {},
            "pool_size" : 6,
            "job_timeout" : 25,
            "worker_time_to_live" : 100,
            "ignore_images" : "false",
            "screen_width" : 1600,
            "screen_height" : 1200
          },
          "scope" : {
            "redundant_path_patterns" : {},
            "dom_depth_limit" : 5,
            "exclude_path_patterns" : [],
            "exclude_content_patterns" : [],
            "include_path_patterns" : [],
            "restrict_paths" : [],
            "extend_paths" : [],
            "url_rewrites" : {}
          },
          "session" : {},
          "checks" : [],
          "platforms" : [],
          "plugins" : {},
          "no_fingerprinting" : "false",
          "authorized_by" : "null"
        }
        r = requests.post(url_task, data=payload)
        print r.content
        print r.status_code
        return HttpResponse("add task complete!")`

Are the keyword "(?i-mx:name)" , "(?i-mx:user)","(?i-mx:usr)" ,"(?i-mx:pass)" which  in json data 'admin@admin.admin' and administrator?

**Comment by Zapotek** [comment]
No, you need to specify the credentials in the HTTP client you're using, this has nothing to do with the scan configuration.
