### ISSUE TITLE
Blind SQL Injection (differential analysis) Error report

### ISSUE THREAD

**Issue by chushuai** [Arachni/arachni#890]
when dynamic web page, Error report

**Comment by Zapotek** [comment]
I'm not sure what you mean, can you show some more details?
Maybe tell me how to reproduce it by performing an identical scan?

**Comment by Zapotek** [comment]
Closing due to lack of feedback.

**Comment by star-tw** [comment]
The page data is random. Blind SQL Injection (differential analysis) always report High Issure.
e.g. A random ajax hot news module. no get or put any parameter, and never read cookie. Blind SQL Injection (differential analysis) still report High Issure.
