### ISSUE TITLE
The full report for this scan could not be retrieved due to an unknown error. 

### ISSUE THREAD

**Issue by ggtd** [Arachni/arachni#893]
After scanning with nightly "**v2.0dev - WebUI v1.0dev**", I can't see report.
The error is "**The full report for this scan could not be retrieved due to an unknown error.**"

let me know, if I can do more to resolve this.
THX.

**Comment by Zapotek** [comment]
You won't be able to get the report but you could prevent this from happening again.
Is there any chance that the OS killed the scanner due to low RAM?

**Comment by ggtd** [comment]
unfortunately I can't confirm or exclude any OS/host problems. (8GB RAM). I Will check that and debug more.    

Thanks a lot
Closing.
