### ISSUE TITLE
Arachni http-request-header doesn't understand Basic64 values

### ISSUE THREAD

**Issue by bewell** [Arachni/arachni#898]
Hello,

I'm using OSX version of Arachni and stumbled upon really interesting issue. When defining the authentication header I'm using the Base64 value like this:
`./arachni https://site.com --http-request-header="Basic: dXNlcjpwYXNzd29yZA=="`
Now the thing is, Arachni doesn't understand fully the two symbols of `=` at the end of a value. I see it can't login to the app and found out that in the reports it is shown as this:
![image](https://user-images.githubusercontent.com/6248536/27793566-4884d562-6007-11e7-8751-b5ce61460494.png)
This makes we wonder where is the problem --- either showing in the reports page, or actually parsing the value from the variable?

Thanks

**Comment by Zapotek** [comment]
```
      --http-request-header NAME=VALUE
```
