### ISSUE TITLE
False positive on FreePBX 

### ISSUE THREAD

**Issue by janpapas** [Arachni/arachni#901]
Arachni on FreePBX 13.0.192.9 gives an high issue  "Access restriction bypass via origin spoof"

The proof is HTTP/1.1 200 OK

But trying the request:

GET /index.php HTTP/1.1
Host: myhost:81
Accept-Encoding: gzip, deflate
User-Agent: Arachni/v1.5.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.8,he;q=0.6
X-Arachni-Scan-Seed: 4a194056b6a9f5891315e9d231de45ae
X-Forwarded-For: 127.0.0.1
X-Originating-Ip: 127.0.0.1
X-Remote-Ip: 127.0.0.1
X-Remote-Addr: 127.0.0.1
Cookie: lang=en_US;PHPSESSID=mospki67ovsnmkj1e4u4rpna44

I don't bypass any login form.

**Comment by Zapotek** [comment]
When you visit the page via your browser don't you get a prompt for HTTP authentication?

**Comment by janpapas** [comment]
No, I don't get any prompt about http authentication, but a login form.
The use of header aren't able to bypass the login form

**Comment by Zapotek** [comment]
That's strange, that check only runs when the page returns 401 or 403 HTTP status codes by default and its goal is to bypass HTTP auth not the login form.
If there was no HTTP auth it shouldn't have been run.

Can you please show me the output of:

    curl -vv http://myhost:81/index.php

**Comment by Zapotek** [comment]
Btw, 403 wouldn't present a login prompt, it'd just deny the request, but if it's bypassed then an issue should still be logged.

**Comment by janpapas** [comment]
I understand.
Now I don't have access anymore to that specific server, I have to try to another installation of FreePBX.
Thank you for explanation, it's clear the purpose of the plugin.

**Comment by janpapas** [comment]
Anyway the output of curl was:

HTTP/1.1 200 OK
< Date: Wed, 12 Jul 2017 14:16:20 GMT
< Server: Apache/2.2.15 (CentOS)
< X-Powered-By: PHP/5.3.28
< Set-Cookie: lang=en_US
< Set-Cookie: ARI=lnscrdo8rddvf1dko7pt3tmmb5; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Content-Length: 6568
< Connection: close
< Content-Type: text/html; charset=utf-8

**Comment by Zapotek** [comment]
Is this the same server or another installation? Did you get the FP on this installation too?

**Comment by Zapotek** [comment]
Closing due to lack of feedback, if you have a reproducible case please re-open.
