### ISSUE TITLE
127.0.0.1 IP disclosure

### ISSUE THREAD

**Issue by mfr-itr** [Arachni/arachni#903]
On a scan, Arachni opens a "Private IP address disclosure" issue because it finds `127.0.0.1` in a file. I wouldn't consider it important because every computer has `127.0.0.1`. Same for `::1`.

I'm on Arachni 1.5.1.

**Comment by Zapotek** [comment]
Importance depends on interpretation, Arachni just logs the issue.
The check info includes this warning:

>This finding typically requires manual verification to ensure the context is correct, as any private IP address within the HTML body will trigger it.

I do see your point, but it's good to log this just for the user to take a closer look at what's going on.
