### ISSUE TITLE
Only login page is crawling.

### ISSUE THREAD

**Issue by girishmsec** [Arachni/arachni#906]
Hi,
Am trying to scan java based web application, but tool crawls only login page. my application is protected with interceptor (Without login session object cant access other pages). can you plz guide me how to scan the application. 

Tried below mentioned commands, with this commands login is success but not crawling other pages.

-------
arachni.bat http://appurl --plugin=autologin:url=http://appurl/LOGIN_Page.htm,parameters="loginId=girish&password=Demo1234",check="." --audit-links --audit-forms --scope-exclude-pattern=Logout.htm

--------
arachni.bat http://appurl  --checks=* --scope-include-subdomains --plugin=login_script:script=login.js --session-check-url=http://appurl/Home.htm  --session-check-pattern='Logout' --output-debug 3> debug.log

**Comment by m6a-UdS** [comment]
I think it would be easier to debug using a login script ( `--plugin=login_script:browser=firefox,script=your_script.rb` ); You can test it "offline" with `watir-webdriver` and see if you can get through the login page. Then, use this script with Arachni :-)

**Comment by girishmsec** [comment]
Thank you for the response.. As you mentioned I have tried the login script with offline  watir-webdriver with chrome browser and login was success.  From tool again i tried, in console tool is printed login success and jsessionid but still only login page is scanning.

**Comment by m6a-UdS** [comment]
Can-we have an example of your login script? I know it took me a while to make mine work... Here is what mine looks like:
```
browser.goto 'https://mywebsite.com/'

form = browser.form( action: '/login/')
form.text_field(name: 'username').set('myuser')
form.text_field(name: 'password').set('mypassword')

form.submit

sleep 5

framework.options.session.check_url     = browser.url
framework.options.session.check_pattern = /logout/
```
Maybe you are missing `framework.options.session` variables?

**Comment by girishmsec** [comment]
Javascript script:
document.getElementById( 'loginId' ).value   = 'salipd';
 document.getElementById( 'password' ).value = 'Demo1234';
 document.getElementById( 'login' ).submit();

Ruby script:
browser.goto 'http://url'
 form = browser.form( :name=> 'form' )
form.text_field( :name=> 'loginId').set 'salipd'
 form.text_field( :name=> 'password').set 'salipd'
 form.submit

Tried with your script also but same issue.

**Comment by m6a-UdS** [comment]
Do you have a public URL we can try or reproduce?

**Comment by girishmsec** [comment]
No.. its a private URL.

**Comment by Zapotek** [comment]
@girishmsec I'm afraid I won't be able to tell what's going on without access to the webapp.
