### ISSUE TITLE
Private IP address disclosure: it's the IP from localhost (http://192.168.0.19/mysite)

### ISSUE THREAD

**Issue by alexlana** [Arachni/arachni#911]
Arachni says a link on page was private IP address disclosure, but it was the IP that I was testing (the access to site on local server are by IP, like http://192.168.0.19, because if it is http://localhost/ Arachni don't work).

The code containing the IP: `<link rel="canonical" href="http://192.168.0.19/mysite">`

**Comment by Zapotek** [comment]
As the issue description says:

> This finding typically requires manual verification to ensure the context is correct, as any private IP address within the HTML body will trigger it.

I don't want to alter this because you could be scanning your staging/dev environment (as you did) and in that case there's no impact from this issue, but you can't know whether or not the issue will persist when the code gets pushed to production.
