### ISSUE TITLE
Arachni Scan with Authendication

### ISSUE THREAD

**Issue by parimalazoho** [Arachni/arachni#913]
Hi,
     I am new to Arachni. I am trying to scan my service with authentication. But i am getting error continuously.
Getting error while trying autologin,
> bin/arachni http://testfire.net --plugin=autologin:url=http://testfire.net/bank/login.aspx,parameters="uid=jsmith&passw=Demo1234",check="Sign Off|MY ACCOUNT" --scope-exclude-pattern=logout

> error :  [*] Initializing...
 [*] Preparing plugins...
 [*] AutoLogin: Logging in, please wait.
 [-] [utilities#exception_jail:428] Session: [Net::ReadTimeout] Net::ReadTimeout
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
 [-] [utilities#exception_jail:428] Session: /home/local/ZOHOCORP/parimala-3988/APPSCAN/Arachni/arachni-1.5.1-0.5.12/system/usr/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
......
Now what can i do?......Please help me ASAP.... Thanks in Advance....

**Comment by Zapotek** [comment]
I can't reproduce it any no-one else is reporting any similar error, it seems like an env issue.
