### ISSUE TITLE
Audit Only the recorded Proxy URLs

### ISSUE THREAD

**Issue by hayageek** [Arachni/arachni#915]
How can we audit only the requests(All GET & POST requests) passed through proxy ?

I am running the scan using arachnni proxy plugin(Command-line). Arachni can audit all the forms,links,json,..etc.

But I want to restrict the audit only for the requests(POST,GET,...) passed through proxy. 
I don't want to audit all the forms located in the response.

For Example:
If the recorded requests are  1 GET, 1 POST(Form POST), 2 JSONs.
Then I want to audit only these 4 requests, I don't want to audit any other forms/links.

**Comment by Zapotek** [comment]
Try setting `--scope-page-limit=0` or `--scope-page-limit=`1`.
