### ISSUE TITLE
unable to install arachni w/ ruby v 2.3 & 2.4

### ISSUE THREAD

**Issue by zhaque44** [Arachni/arachni#916]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20170921-29838-eeyws1typhoeus-0.3.3/gems/typhoeus-0.3.3/ext/typhoeus
/home/linuxbrew/.linuxbrew/opt/ruby/bin/ruby -r ./siteconf20170921-29838-bqt62i.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2/bin/$(RUBY_BASE_NAME)
extconf.rb:9:in `<main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
               CONFIG

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20170921-29838-eeyws1typhoeus-0.3.3/gems/typhoeus-0.3.3 for inspection.
Results logged to /tmp/bundler20170921-29838-eeyws1typhoeus-0.3.3/extensions/x86_64-linux/2.4.0/typhoeus-0.3.3/gem_make.out

An error occurred while installing typhoeus (0.3.3), and Bundler cannot continue.
Make sure that `gem install typhoeus -v '0.3.3'` succeeds before bundling.

In Gemfile:
  arachni was resolved to 0.4.1.3, which depends on
    typhoeus

**Comment by Zapotek** [comment]
What version of Arachni are you trying to build? 0.4.1.3 is **ancient**.
