### ISSUE TITLE
Arachni scans subdomain

### ISSUE THREAD

**Issue by driiftkiing** [Arachni/arachni#918]
I did a scan on domain & arachni did scan also one of his subdomains.
Why did it scan it?

This was the command:

> http://example.com
> --http-user-agent='example'
> --scope-directory-depth-limit='5'
> --scope-dom-event-limit='100'
> --checks=common_directories,backup_directories,allowed_methods,htaccess_limit,insecure_client_access_policy,insecure_cross_domain_policy_access,directory_listing,xst,origin_spoof_access_restriction_bypass,backdoors,common_admin_interfaces,localstart_asp,insecure_cross_domain_policy_headers,unencrypted_password_forms,private_ip,cvs_svn_users,form_upload,emails,http_only_cookies,html_objects,password_autocomplete,hsts,cookie_set_for_parent_domain,insecure_cookies,x_frame_options,mixed_resource,ssn,insecure_cors_policy,captcha,credit_card,interesting_responses,common_files,http_put,backup_files,webdav,sql_injection,os_cmd_injection,no_sql_injection_differential,xss_dom_script_context,xss_dom,unvalidated_redirect_dom,no_sql_injection,response_splitting,unvalidated_redirect,sql_injection_timing,xpath_injection,xxe,path_traversal,sql_injection_differential,xss_path,xss_script_context,code_injection,xss_tag,source_code_disclosure,file_inclusion,session_fixation,ldap_injection,rfi,code_injection_timing,xss_event,csrf,code_injection_php_input_wrapper,xss,trainer,os_cmd_injection_timing

**Comment by Zapotek** [comment]
Please don't create [duplicates](http://support.arachni-scanner.com/discussions/questions/13709-arachni-scans-subdomain).
