### ISSUE TITLE
Maximum file size exceeded Error

### ISSUE THREAD

**Issue by brick713** [Arachni/arachni#926]
[2017-10-27 21:48:01 +0800] [HTTP: 200] https://www.*****.com/app/2296a8a768deb0713f15892c95ea17c4.mp4
[2017-10-27 21:48:01 +0800] [filesize_exceeded] Maximum file size exceeded

**Comment by Zapotek** [comment]
Don't worry about it, see: https://github.com/Arachni/arachni/wiki/Command-line-user-interface#http-response-max-size

Not downloading that file is what's supposed to happen, although you can't be sure so the error is logged for the user to see, just to be sure that the system isn't skipping important resources.

**Comment by brick713** [comment]
but i use it in web-ui not command-line-user-interface, how fix it?

**Comment by evil-alex** [comment]
so,do you fix it in web-ui?

**Comment by brick713** [comment]
no，i abandon。
