### ISSUE TITLE
Update Ruby

### ISSUE THREAD

**Issue by Joeyn414** [Arachni/arachni#928]
Hello,
I wanted to know when you are planning to update the ruby version. I see in the gemspec that you require version 2.2, however several critical vulnerabilities are present in this version, the last number I had was 12. The latest appears to be 2.4.2, would you be interested in having someone help you update to the newest version or do you already have this planned?

**Comment by Zapotek** [comment]
The gemspec says greater or equal to 2.2.0, it doesn't require version 2.2.0.
See: https://github.com/Arachni/arachni/blob/experimental/arachni.gemspec#L13
