### ISSUE TITLE
arachni_multi exits early when launched remotely

### ISSUE THREAD

**Issue by benm-stm** [Arachni/arachni#933]
When trying to launch arachni_multi over ssh it loses its context and exits early
with the following message

> Arachni - Web Application Security Scanner Framework v1.5.1
>    Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>
> 
>            (With the support of the community and the Arachni Team.)
> 
>    Website:       http://arachni-scanner.com
>    Documentation: http://arachni-scanner.com/wiki
> 
> 
> [2J[H[~] No element audit options were specified, will audit links, forms, cookies, JSONs and XMLs.
> I, [2017-11-24T09:31:58.854622 #159951]  INFO -- System: RPC Server started.
> I, [2017-11-24T09:31:58.854697 #159951]  INFO -- System: Listening on 127.0.0.1:47783
> I, [2017-11-24T09:31:59.077460 #159951]  INFO -- Call: service.alive? [127.0.0.1]
> I, [2017-11-24T09:31:59.099562 #159951]  INFO -- Call: service.scan [127.0.0.1]
> [-] [ui/cli/rpc/client/instance#run:81] [Errno::ENOTTY] Inappropriate ioctl for device
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `winsize'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `empty_screen'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:93:in `print_progress'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:75:in `run'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/local.rb:54:in `initialize'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/bin/arachni_multi:18:in `new'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/bin/arachni_multi:18:in `<top (required)>'
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/bin/../system/arachni-ui-web/bin/arachni_multi:17:in `load'
> 
> [H[*] Shutting down and retrieving the report, please wait...
> [-] [ui/cli/rpc/client/instance#run:81] /usr/local/arachni-1.5.1-0.5.12/bin/../system/arachni-ui-web/bin/arachni_multi:17:in `<main>'
> I, [2017-11-24T09:32:00.957379 #159955]  INFO -- System: RPC Server started.
> I, [2017-11-24T09:32:00.957450 #159955]  INFO -- System: Listening on 127.0.0.1:53260
> I, [2017-11-24T09:32:01.065104 #159955]  INFO -- Call: service.alive? [127.0.0.1]
> I, [2017-11-24T09:32:01.435892 #159955]  INFO -- Call: options.set [127.0.0.1]
> I, [2017-11-24T09:32:01.440095 #159955]  INFO -- Call: framework.set_master [127.0.0.1]
> I, [2017-11-24T09:32:01.492526 #159955]  INFO -- Call: service.scan [127.0.0.1]
> I, [2017-11-24T09:32:01.505162 #159955]  INFO -- Call: framework.progress [127.0.0.1]
> I, [2017-11-24T09:32:00.974928 #159964]  INFO -- System: RPC Server started.
> I, [2017-11-24T09:32:00.974997 #159964]  INFO -- System: Listening on 127.0.0.1:45986
> I, [2017-11-24T09:32:01.379820 #159964]  INFO -- Call: service.alive? [127.0.0.1]
> I, [2017-11-24T09:32:01.439229 #159964]  INFO -- Call: options.set [127.0.0.1]
> I, [2017-11-24T09:32:01.444365 #159964]  INFO -- Call: framework.set_master [127.0.0.1]
> I, [2017-11-24T09:32:01.496759 #159964]  INFO -- Call: service.scan [127.0.0.1]
> I, [2017-11-24T09:32:01.507246 #159964]  INFO -- Call: framework.progress [127.0.0.1]
> I, [2017-11-24T09:32:00.935715 #159961]  INFO -- System: RPC Server started.
> I, [2017-11-24T09:32:00.935783 #159961]  INFO -- System: Listening on 127.0.0.1:39396
> I, [2017-11-24T09:32:01.199484 #159961]  INFO -- Call: service.alive? [127.0.0.1]
> I, [2017-11-24T09:32:01.436424 #159961]  INFO -- Call: options.set [127.0.0.1]
> I, [2017-11-24T09:32:01.442103 #159961]  INFO -- Call: framework.set_master [127.0.0.1]
> I, [2017-11-24T09:32:01.496047 #159961]  INFO -- Call: service.scan [127.0.0.1]
> I, [2017-11-24T09:32:01.507880 #159961]  INFO -- Call: framework.progress [127.0.0.1]
> I, [2017-11-24T09:32:00.901016 #159958]  INFO -- System: RPC Server started.
> I, [2017-11-24T09:32:00.901084 #159958]  INFO -- System: Listening on 127.0.0.1:46225
> I, [2017-11-24T09:32:01.127751 #159958]  INFO -- Call: service.alive? [127.0.0.1]
> I, [2017-11-24T09:32:01.436158 #159958]  INFO -- Call: options.set [127.0.0.1]
> I, [2017-11-24T09:32:01.442211 #159958]  INFO -- Call: framework.set_master [127.0.0.1]
> I, [2017-11-24T09:32:01.518090 #159958]  INFO -- Call: service.scan [127.0.0.1]
> I, [2017-11-24T09:32:01.531000 #159958]  INFO -- Call: framework.progress [127.0.0.1]
> I, [2017-11-24T09:32:01.658974 #159958]  INFO -- Call: framework.clean_up [127.0.0.1]
> I, [2017-11-24T09:32:01.492167 #159951]  INFO -- Call: service.native_progress [127.0.0.1]
> I, [2017-11-24T09:32:01.555144 #159951]  INFO -- Call: service.native_abort_and_report [127.0.0.1]
> 

Is there any solution to launch the tool remotely
Waiting for a response and thanks in advance

**Comment by benm-stm** [comment]
i think i understand the problem it's related to the process who don't have an active shell i can see in the code lines like this one : 

>     def print_progress
>         empty_screen

or 

> print_info "('Ctrl+C' aborts the scan and retrieves the report)"

It shouldn't be dependent of the active shell

**Comment by Zapotek** [comment]
You should have been using a Dispatcher, they're remote agents meant to be used exactly for these use-cases.
Would that work for you?

**Comment by Zapotek** [comment]
Btw, `arachni_multi` has proven to not be reliable sometimes and will be removed in the future.

**Comment by benm-stm** [comment]
I was not using dispatchers, gonna try that.
but if you say that arachni_multi is not reliable ... is there another way to launch // pentests to reduce the execution time ?

Thanks for the response

**Comment by Zapotek** [comment]
Until the new engine comes out use your best judgment: http://support.arachni-scanner.com/kb/general-use/optimizing-for-faster-scans

**Comment by aiddroid** [comment]
Same issue, arachni cannot call in background with out TTY, error messages here:
```shell
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] [Errno::ENOTTY] Inappropriate ioctl for device
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `winsize'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/support/mixins/terminal.rb:45:in `empty_screen'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:93:in `print_progress'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/instance.rb:75:in `run'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/ui/cli/rpc/client/remote.rb:77:in `initialize'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_rpc:18:in `new'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/system/gems/gems/arachni-1.5.1/bin/arachni_rpc:18:in `<top (required)>'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_rpc:17:in `load'
[2018-05-23 10:33:37 +0800] [ui/cli/rpc/client/instance#run:81] /home/work/odp/webroot/arachni/bin/../system/arachni-ui-web/bin/arachni_rpc:17:in `<main>'
```
