### ISSUE TITLE
--http-cookie-string only sending first cookie

### ISSUE THREAD

**Issue by brandonprry** [Arachni/arachni#937]
Using experimental branch, setting --http-cookie-string="value1=fdsa;value2=rewq" results in only value1=fdsa being sent in the HTTP request to the web server.

I've confirmed this by running Arachni through burpsuite after setting the --http-cookie-string value.

```
$ git status
On branch experimental
Your branch is up to date with 'origin/experimental'.
```

**Comment by Zapotek** [comment]
```
      --http-cookie-string COOKIE
                              Cookie representation as a 'Set-Cookie' HTTP response header.
                                Example: my_cookie=my_value; Path=/, other_cookie=other_value; Path=/test
```

Needs a `Set-Cookie` format, you seem to using a `Cookie` request header format, which was supported a long time ago, but there was a bit of confusion going on and `Set-Cookie` is more versatile.

This should work:  

    --http-cookie-string="value1=fdsa,value2=rewq"

I probably need to update that option name for the new engine to something like `--http-set-cookie`.

**Comment by brandonprry** [comment]
So, I also tested with the value provided in the example. If I use that value exactly, then I also send my_cookie=my_value. other_cookie does not get sent. If I use the format you provided that doesn't contain semi-colons, then both values are sent.

Perhaps an update to the example would suffice.

**Comment by Zapotek** [comment]
You mean including attributes truncates subsequent cookies? If so then that's a bug.

**Comment by brandonprry** [comment]
My first inclination was the semi-colons causing the issue.

```
./arachni --checks sql* --http-cookie-string "my_cookie=my_value; Path=/, other_cookie=other_value; Path=/test"
```

This sends my_cookie, not other_cookie. Removing the path attributes so that the cookie is just `my_cookie=fdsa;other_cookie=rewq` also only results in my_cookie being sent, with other_cookie missing.

```
./arachni --checks sql* --http-cookie-string "my_cookie=my_value, other_cookie=other_value"
```
This results in both being sent correctly.
