### ISSUE TITLE
Arachni LoadError

### ISSUE THREAD

**Issue by arachni-user** [Arachni/arachni#941]
Hello can anybody help me out?
I got this error using gauntlt arachni

expected "Arachni - Web Application Security Scanner Framework v1.5.1\n Author: Tasos "Zapotek" Laskos <ta...ramework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/ui/cli/framework.rb:80:in block in run'\n" to include "0 issues were detected." Diff: @@ -1,2 +1,29 @@ -0 issues were detected. +Arachni - Web Application Security Scanner Framework v1.5.1 + Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com> + + (With the support of the community and the Arachni Team.) + + Website: http://arachni-scanner.com + Documentation: http://arachni-scanner.com/wiki + + +[~] No element audit options were specified, will audit links, forms, cookies, UI inputs, UI forms, JSONs and XMLs. + +[*] Initializing... +[*] Preparing plugins... +[*] ... done. +[-] [ui/cli/framework#run:129] [LoadError] cannot load such file -- selenium/webdriver/phantomjs +[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:inrequire'
+[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in rescue in require' +[-] [ui/cli/framework#run:129] /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:inrequire'
+[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/browser.rb:148:in executable' +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/browser.rb:142:inhas_executable?'
+[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:50:in host_has_browser?' +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:65:inuse_browsers?'
+[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/browser.rb:24:in browser_cluster' +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework/parts/audit.rb:173:inaudit'
+[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in block in run' +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/utilities.rb:425:inexception_jail'
+[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/lib/arachni/framework.rb:117:in run' +[-] [ui/cli/framework#run:129] /var/lib/gems/2.3.0/gems/arachni-1.5.1/ui/cli/framework.rb:80:inblock in run'
(RSpec::Expectations::ExpectationNotMetError)
arachni-xss.attack:10:in `Then the output should contain "0 issues were detected."'

Failing Scenarios:
cucumber arachni-xss.attack:4 # Scenario: Using the arachni, look for cross site scripting and verify no issues are found

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m1.953s

checked my arachni version
1.15.1

Gemfile content:

PATH
remote: .
specs:
gauntlt (1.0.12)
aruba (= 0.5.4)
cucumber (= 1.3.20)
nokogiri (> 1.6.5)
trollop (> 2.1.2)

GEM
remote: https://rubygems.org/
specs:
addressable (2.3.6)
arachni (1.4)
addressable (= 2.3.6)
arachni-rpc (= 0.2.1.3)
awesome_print
bundler
childprocess (= 0.5.3)
coderay (= 1.1.0)
concurrent-ruby (= 1.0.0)
concurrent-ruby-ext (= 1.0.0)
http_parser.rb
kramdown (= 1.4.1)
loofah (> 2.0.0)
msgpack (= 0.7.0)
nokogiri (= 1.6.8rc2)
oj (> 2.14.3)
oj_mimic_json
pony (= 1.8)
puma (= 2.14.0)
rack
rb-readline (= 0.5.1)
rubyzip (= 1.1.6)
sinatra (= 1.4.6)
sinatra-contrib (= 1.4.6)
terminal-table (= 1.4.5)
typhoeus (= 1.0.1)
watir-webdriver (= 0.8.0)
arachni-reactor (0.1.1)
arachni-rpc (0.2.1.3)
arachni-reactor (= 0.1.1)
aruba (0.5.4)
childprocess (>= 0.3.6)
cucumber (>= 1.1.1)
rspec-expectations (>= 2.7.0)
awesome_print (1.8.0)
background_process (1.3)
backports (3.10.3)
builder (3.2.3)
childprocess (0.5.3)
ffi (> 1.0, >= 1.0.11)
coderay (1.1.0)
concurrent-ruby (1.0.0)
concurrent-ruby-ext (1.0.0)
concurrent-ruby (> 1.0.0)
cucumber (1.3.20)
builder (>= 2.1.2)
diff-lcs (>= 1.1.3)
gherkin (> 2.12)
multi_json (>= 1.7.5, < 2.0)
multi_test (>= 0.1.2)
diff-lcs (1.3)
ethon (0.11.0)
ffi (>= 1.3.0)
ffi (1.9.18)
gherkin (2.12.2)
multi_json (> 1.3)
http_parser.rb (0.6.0)
kramdown (1.4.1)
loofah (2.0.3)
nokogiri (>= 1.5.9)
mail (2.7.0)
mini_mime (>= 0.1.1)
mini_mime (1.0.0)
mini_portile2 (2.1.0)
msgpack (0.7.0)
multi_json (1.12.2)
multi_test (0.1.2)
nokogiri (1.6.8.rc2)
mini_portile2 (> 2.1.0)
oj (2.14.6)
oj_mimic_json (1.0.1)
pony (1.8)
mail (>= 2.0)
puma (2.14.0)
rack (1.6.8)
rack-protection (1.5.3)
rack
rack-test (0.8.2)
rack (>= 1.0, < 3)
rake (11.0.1)
rb-readline (0.5.1)
rspec-expectations (3.7.0)
diff-lcs (>= 1.2.0, < 2.0)
rspec-support (> 3.7.0)
rspec-support (3.7.0)
rubyzip (1.1.6)
selenium-webdriver (3.8.0)
childprocess (> 0.5)
rubyzip (> 1.0)
service_manager (0.6.4)
background_process (>= 1.2)
tcpsocket-wait
sinatra (1.4.6)
rack (> 1.4)
rack-protection (> 1.4)
tilt (>= 1.3, < 3)
sinatra-contrib (1.4.6)
backports (>= 2.0)
multi_json
rack-protection
rack-test
sinatra (~> 1.4.0)
tilt (>= 1.3, < 3)
tcpsocket-wait (1.0.0)
terminal-table (1.4.5)
tilt (2.0.8)
trollop (2.1.2)
typhoeus (1.0.1)
ethon (>= 0.8.0)
watir-webdriver (0.8.0)
selenium-webdriver (>= 2.46.2)

PLATFORMS
ruby

DEPENDENCIES
arachni (= 1.4)
gauntlt!
rake (~> 11.0.1)
service_manager

BUNDLED WITH
1.15.1

**Comment by Lightman32** [comment]
I previously had many issues with arachni gem, could you please try using [official packages](http://www.arachni-scanner.com/download/).

**Comment by Zapotek** [comment]
@Lightman32 is right, you should be using the official packages, as for Gauntlt I've no idea, if you're having trouble with it you should contact them I think.

Cheers
