### ISSUE TITLE
arachni REST client error: `require': cannot load such file -- typhoeus (LoadError)

### ISSUE THREAD

**Issue by mgoins01** [Arachni/arachni#942]
Am seeking to run the example Ruby-based REST client listed on arachni GitHub here:  https://github.com/Arachni/arachni/wiki/REST-API, saving it as 'arachni-rest-client.rb'. 

I have pulled down the linux packages for both the 1.5.1 & 2.0dev versions.  Both exhibit similar symptoms.  Basically, am seeing failure to load 'typhoeus'.

[root@ip-10-1-0-152 arachni]# ./arachni-rest-client.rb
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- typhoeus (LoadError)
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./arachni-rest-client.rb:4:in `<main>'

Running find, i see several references to typhoeus, but am unsure how to ensure the proper modules are loaded at execution time.

[root@ip-10-1-0-152 arachni]# find / -name typhoeus -print
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-dfdc70df98a8/spec/arachni/typhoeus
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/typhoeus-1.0.2/spec/rack/typhoeus
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/typhoeus-1.0.2/spec/typhoeus
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/typhoeus-1.0.2/lib/rack/typhoeus
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/typhoeus-1.0.2/lib/typhoeus

/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/typhoeus-1.0.2/spec/rack/typhoeus
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/typhoeus-1.0.2/spec/typhoeus
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/typhoeus-1.0.2/lib/rack/typhoeus
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/typhoeus-1.0.2/lib/typhoeus
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/spec/arachni/typhoeus
[root@ip-10-1-0-152 arachni]# find / -name ethon -print
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/bundler/gems/arachni-dfdc70df98a8/lib/arachni/ethon
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.10.1/spec/ethon
/home/ec2-user/arachni-2.0dev-1.0dev/system/gems/gems/ethon-0.10.1/lib/ethon

/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/ethon-0.10.1/spec/ethon
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/ethon-0.10.1/lib/ethon
/home/ec2-user/arachni-1.5.1-0.5.12/system/gems/gems/arachni-1.5.1/lib/arachni/ethon
[root@ip-10-1-0-152 arachni]#

Appreciate the help!

**Comment by Zapotek** [comment]
The REST client (in this case `arachni-rest-client.rb`) has nothing to do with Arachni.
You just need to install the `typhoeus` gem, as it's being used in the example script as an HTTP client.
