### ISSUE TITLE
 Client: Request queue reached its maximum size, performing an emergency run.

### ISSUE THREAD

**Issue by kashenda** [Arachni/arachni#943]
Hello there,
I would like to get some help with the following Arachni CLI scanning error:
     [~] Client: Request queue reached its maximum size, performing an emergency run
when this error occur, arachni stops scanning and no report is generated despite of lunching the scan as follows:
\bin>arachni https://192.168.77.2:8443 --report-save-path=Report.afr

Thanks in advance

**Comment by Zapotek** [comment]
This isn't an error, it's normal operation, too many HTTP requests have been queued and they need to be performed immediately.
Nothing special happened, it will just take time for the requests to finish, depending on server responsiveness.
