### ISSUE TITLE
Getting this error code 0x007ff2a81fa818

### ISSUE THREAD

**Issue by sampathmende** [Arachni/arachni#946]
Hi,

I ran the arachni scanner to find vulnarabilities in my appliation.
the below is displayed
Running tasks in stage: wait
Running tasks in stage: mount
Running tasks in stage: file
Running tasks in stage: code
**code - Arachni - #Set:0x007ff2a81fa818**

can pls explain whats the code means??? Its not showing anything after that. Its not scanning also.

**Comment by Zapotek** [comment]
Not output from Arachni.
