### ISSUE TITLE
I am getting below issue and cant proceed further

### ISSUE THREAD

**Issue by sampathmende** [Arachni/arachni#947]
[-] [LoadError] cannot load such file -- selenium/webdriver/phantomjs
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in `require'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in `executable'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:126:in `has_executable?'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:50:in `host_has_browser?'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:65:in `use_browsers?'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:24:in `browser_cluster'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:167:in `audit'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `block in run'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in `exception_jail'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:in `run'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/framework.rb:62:in `block in run'
[-] [Errno::EINVAL] Invalid argument @ rb_io_seek - /tmp/arachni20180208-70-kjvacrafr
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in `seek'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in `block in load'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:in `open'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:in `load'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:40:in `run'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/reporter.rb:25:in `initialize'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:in `new'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/bin/arachni_reporter:12:in `<top (required)>'
[-] /root/.rbenv/versions/2.3.0/bin/arachni_reporter:23:in `load'

gemfile.lock
GIT
  remote: https://github.com/rweng/jquery-datatables-rails.git
  revision: d486b31b192a2924b1913e080ad23460e6b96d31
  specs:
    jquery-datatables-rails (3.4.0)
      actionpack (>= 3.1)
      jquery-rails
      railties (>= 3.1)
      sass-rails

GIT
  remote: https://github.com/sumoheavy/jira-ruby.git
  revision: 6406287b9abc823a4df4cda916fe04e9a62cd146
  specs:
    jira-ruby (1.4.3)
      activesupport
      multipart-post
      oauth (~> 0.5, >= 0.5.0)

GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.3.2)
    actionmailer (4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.7.1)
      actionview (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-action_caching (1.2.0)
      actionpack (>= 4.0.0, < 6)
    actionview (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.7.1)
      activesupport (= 4.2.7.1)
      globalid (>= 0.3.0)
    activemodel (4.2.7.1)
      activesupport (= 4.2.7.1)
      builder (~> 3.1)
    activerecord (4.2.7.1)
      activemodel (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      arel (~> 6.0)
    activerecord-session_store (1.1.0)
      actionpack (>= 4.0, < 5.2)
      activerecord (>= 4.0, < 5.2)
      multi_json (~> 1.11, >= 1.11.2)
      rack (>= 1.5.2, < 3)
      railties (>= 4.0, < 5.2)
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.6)
    aescrypt (1.0.0)
    arachni (1.3.2)
      addressable (= 2.3.6)
      arachni-rpc (= 0.2.1.2)
      awesome_print (~> 1.2.0)
      bundler
      childprocess (= 0.5.3)
      coderay (= 1.1.0)
      kramdown (= 1.4.1)
      loofah (~> 2.0.0)
      msgpack (= 0.5.8)
      nokogiri (~> 1.6.5)
      oj (~> 2.12.9)
      oj_mimic_json
      pony (= 1.8)
      rack
      rb-readline (= 0.5.1)
      rubyzip (= 1.1.6)
      terminal-table (= 1.4.5)
      typhoeus (= 0.6.9)
      watir-webdriver (= 0.6.9)
    arachni-reactor (0.1.0)
    arachni-rpc (0.2.1.2)
      arachni-reactor (= 0.1.0)
    arel (6.0.4)
    autoprefixer-rails (7.2.1)
      execjs
    awesome_print (1.2.0)
    bcrypt (3.1.11)
    bcrypt-ruby (3.1.5)
      bcrypt (>= 3.1.3)
    best_in_place (3.1.1)
      actionpack (>= 3.2)
      railties (>= 3.2)
    better_errors (2.4.0)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    binding_of_caller (0.7.3)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.7)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    bootstrap3-datetimepicker-rails (4.17.47)
      momentjs-rails (>= 2.8.1)
    brakeman (4.0.1)
    builder (3.2.3)
    bullet (5.7.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    bundler-audit (0.6.0)
      bundler (~> 1.2)
      thor (~> 0.18)
    byebug (9.1.0)
    cancancan (2.1.2)
    capybara (2.16.1)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    childprocess (0.5.3)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    chronic_duration (0.10.6)
      numerizer (~> 0.1.1)
    climate_control (0.2.0)
    cocaine (0.5.8)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    connection_pool (2.2.1)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    css_parser (1.6.0)
      addressable
    curb (0.9.4)
    cvss (0.99.0)
    data_mapper (1.2.0)
      dm-aggregates (~> 1.2.0)
      dm-constraints (~> 1.2.0)
      dm-core (~> 1.2.0)
      dm-migrations (~> 1.2.0)
      dm-serializer (~> 1.2.0)
      dm-timestamps (~> 1.2.0)
      dm-transactions (~> 1.2.0)
      dm-types (~> 1.2.0)
      dm-validations (~> 1.2.0)
    data_objects (0.10.17)
      addressable (~> 2.1)
    database_cleaner (1.6.2)
    dawnscanner (1.6.8)
      cvss
      data_mapper
      dm-sqlite-adapter
      haml
      justify
      logger-colors
      ptools
      ruby_parser
      sqlite3
      sys-uname
      terminal-table
    debug_inspector (0.0.3)
    devise (4.3.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.2)
      responders
      warden (~> 1.2.3)
    diff-lcs (1.3)
    dm-aggregates (1.2.0)
      dm-core (~> 1.2.0)
    dm-constraints (1.2.0)
      dm-core (~> 1.2.0)
    dm-core (1.2.1)
      addressable (~> 2.3)
    dm-do-adapter (1.2.0)
      data_objects (~> 0.10.6)
      dm-core (~> 1.2.0)
    dm-migrations (1.2.0)
      dm-core (~> 1.2.0)
    dm-serializer (1.2.2)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      json_pure (~> 1.6)
      multi_json (~> 1.0)
    dm-sqlite-adapter (1.2.0)
      dm-do-adapter (~> 1.2.0)
      do_sqlite3 (~> 0.10.6)
    dm-timestamps (1.2.0)
      dm-core (~> 1.2.0)
    dm-transactions (1.2.0)
      dm-core (~> 1.2.0)
    dm-types (1.2.2)
      bcrypt-ruby (~> 3.0)
      dm-core (~> 1.2.0)
      fastercsv (~> 1.5)
      json (~> 1.6)
      multi_json (~> 1.0)
      stringex (~> 1.4)
      uuidtools (~> 2.1)
    dm-validations (1.2.0)
      dm-core (~> 1.2.0)
    do_sqlite3 (0.10.17)
      data_objects (= 0.10.17)
    docile (1.1.5)
    erubi (1.7.0)
    erubis (2.7.0)
    et-orbi (1.0.8)
      tzinfo
    ethon (0.11.0)
      ffi (>= 1.3.0)
    execjs (2.7.0)
    factory_girl (4.9.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.9.0)
      factory_girl (~> 4.9.0)
      railties (>= 3.0.0)
    faker (1.8.5)
      i18n (~> 0.9.1)
    faraday (0.12.2)
      multipart-post (>= 1.2, < 3)
    fastercsv (1.5.5)
    ffi (1.9.18)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.7.0.2)
      railties (>= 3.2, < 5.2)
    foreman (0.84.0)
      thor (~> 0.19.1)
    gitlab (4.2.0)
      httparty
      terminal-table
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    god (0.13.7)
    haml (5.0.4)
      temple (>= 0.8.0)
      tilt
    hashdiff (0.3.7)
    hashie (3.5.6)
    highline (1.7.10)
    htmlentities (4.3.4)
    httparty (0.15.6)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jira4r (1.3.0)
      soap4r-ng (~> 2.0)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    jquery-validation-rails (1.16.0)
    json (1.8.6)
    json_pure (1.8.6)
    jsonpath (0.8.10)
      multi_json
    justify (1.0.2)
    jwt (1.5.6)
    kramdown (1.4.1)
    libv8 (3.16.14.19)
    local_time (2.0.0)
    logger-application (0.0.2)
    logger-colors (1.0.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mimemagic (0.3.2)
    mini_mime (1.0.0)
    mini_portile2 (2.1.0)
    minitest (5.10.3)
    momentjs-rails (2.17.1)
      railties (>= 3.1)
    msgpack (0.5.8)
    multi_json (1.12.2)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    mysql2 (0.4.10)
    nested_form (0.3.2)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    numerizer (0.1.1)
    oauth (0.5.3)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    octokit (4.7.0)
      sawyer (~> 0.8.0, >= 0.5.3)
    oj (2.12.14)
    oj_mimic_json (1.0.1)
    omniauth (1.7.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-github (1.3.0)
      omniauth (~> 1.5)
      omniauth-oauth2 (>= 1.4.0, < 2.0)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    orm_adapter (0.5.0)
    owasp-pipeline (0.8.7)
      brakeman (>= 3.0.5)
      bundler-audit (>= 0.3.1)
      curb (>= 0.8.8)
      dawnscanner (>= 1.6.0)
      fastercsv (>= 1.5)
      highline (>= 1.6.20)
      jsonpath (>= 0.5.7)
      multi_json (>= 1.2)
      nokogiri (>= 1.6.6.2)
      rake
      redcarpet
      terminal-table (>= 1.4)
    paperclip (5.0.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      cocaine (~> 0.5.5)
      mime-types
      mimemagic (~> 0.3.0)
    pony (1.8)
      mail (>= 2.0)
    premailer (1.11.1)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.10.1)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.5.1)
      byebug (~> 9.1)
      pry (~> 0.10)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    ptools (1.3.5)
    puma (3.11.0)
    rack (1.6.8)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.8)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-settings-cached (0.6.6)
      rails (>= 4.2.0)
    rails_autolink (1.1.6)
      rails (> 3.1)
    railties (4.2.7.1)
      actionpack (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rb-readline (0.5.1)
    rdoc (4.3.0)
    redcarpet (3.4.0)
    redis (3.3.5)
    redis-actionpack (5.0.2)
      actionpack (>= 4.0, < 6)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 2)
    redis-activesupport (5.0.4)
      activesupport (>= 3, < 6)
      redis-store (>= 1.3, < 2)
    redis-namespace (1.6.0)
      redis (>= 3.0.4)
    redis-rack (2.0.3)
      rack (>= 1.5, < 3)
      redis-store (>= 1.2, < 2)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.4.1)
      redis (>= 2.2, < 5)
    ref (2.0.0)
    remotipart (1.3.1)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rolify (5.1.0)
    rprogram (0.3.2)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.0)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)
    ruby-nmap (0.9.2)
      nokogiri (~> 1.3)
      rprogram (~> 0.3)
    ruby-progressbar (1.9.0)
    ruby_parser (3.10.1)
      sexp_processor (~> 4.9)
    rubyzip (1.1.6)
    rufus-scheduler (3.4.2)
      et-orbi (~> 1.0)
    safe_yaml (1.0.4)
    sass (3.5.3)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sawyer (0.8.1)
      addressable (>= 2.3.5, < 2.6)
      faraday (~> 0.8, < 1.0)
    sdoc (0.4.2)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    selenium-webdriver (3.8.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    sexp_processor (4.10.0)
    sidekiq (4.2.10)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (~> 3.2, >= 3.2.1)
    sidekiq-middleware (0.3.0)
      sidekiq (>= 2.12.4)
    sidekiq-retries (0.4.0)
      sidekiq (>= 3.2.4)
    sidekiq-scheduler (2.1.10)
      redis (>= 3, < 5)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    sidekiq-statistic (1.2.0)
      sidekiq (>= 3.3.4, < 5)
    sidekiq-status (0.7.0)
      chronic_duration
      sidekiq (>= 2.7)
    simplecov (0.15.1)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    sinatra (1.4.8)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    soap4r-ng (2.0.3)
      httpclient (~> 2.6)
      logger-application (~> 0.0.2)
    spinjs-rails (1.4)
      rails (>= 3.1)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    stringex (1.5.1)
    sys-uname (1.0.3)
      ffi (>= 1.0.0)
    tag-it-rails (2.0.0)
      jquery-ui-rails
      railties
    temple (0.8.0)
    terminal-table (1.4.5)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.8)
    toastr-rails (1.0.3)
      railties (>= 3.1.0)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.3)
    typhoeus (0.6.9)
      ethon (>= 0.7.1)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    uglifier (4.0.1)
      execjs (>= 0.3.0, < 3)
    uniform_notifier (1.10.0)
    uuidtools (2.1.5)
    warden (1.2.7)
      rack (>= 1.0)
    watir-webdriver (0.6.9)
      selenium-webdriver (>= 2.18.0)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    webmock (3.1.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    whenever (0.10.0)
      chronic (>= 0.6.3)
    will_paginate (3.1.6)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)
    xpath (2.1.0)
      nokogiri (~> 1.3)
    yajl-ruby (1.3.1)

PLATFORMS
  ruby

DEPENDENCIES
  RedCloth
  actionpack-action_caching
  activerecord-session_store
  addressable
  aescrypt
  arachni
  arachni-reactor
  best_in_place
  better_errors
  binding_of_caller
  bootstrap-sass
  bootstrap3-datetimepicker-rails (~> 4.17.42)
  bullet
  byebug
  cancancan
  capybara
  chronic
  coffee-rails
  crack
  database_cleaner
  devise
  execjs
  factory_girl_rails
  faker
  figaro
  font-awesome-rails
  foreman
  gitlab
  god
  jbuilder (~> 2.0)
  jira-ruby!
  jira4r
  jquery-datatables-rails!
  jquery-rails
  jquery-ui-rails
  jquery-validation-rails
  kramdown
  local_time
  loofah
  momentjs-rails (>= 2.9.0)
  mysql2 (>= 0.3.13, < 0.5)
  nested_form
  octokit
  omniauth
  omniauth-github
  owasp-pipeline (>= 0.8.7)
  paperclip (~> 5.0.0)
  premailer-rails
  pry-byebug
  pry-rails
  puma
  rails (= 4.2.7.1)
  rails-settings-cached
  rails_autolink
  redis-namespace
  redis-rails
  remotipart (~> 1.2)
  rolify
  rspec
  rspec-rails
  ruby-nmap
  ruby-progressbar
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  sidekiq
  sidekiq-middleware
  sidekiq-retries
  sidekiq-scheduler
  sidekiq-statistic
  sidekiq-status
  simplecov
  sinatra
  soap4r-ng (= 2.0.3)
  spinjs-rails
  spring
  spring-commands-rspec
  tag-it-rails
  terminal-table
  therubyracer
  toastr-rails
  turbolinks
  typhoeus
  uglifier (>= 1.3.0)
  web-console (~> 2.0)
  webmock (>= 1.17.2)
  whenever
  will_paginate
  will_paginate-bootstrap
  yajl-ruby

BUNDLED WITH
   1.16.0

**Comment by Zapotek** [comment]
Duplicate.
