### ISSUE TITLE
--session-check-url and --session-check-pattern does not work at all

### ISSUE THREAD

**Issue by luoluo1987** [Arachni/arachni#948]
I tried to give arachni a valid cookie and check if there is a valid session. But from the logs, it shows arachni was not able to use these two parameters. 

arachni --http-proxy=127.0.0.1:8080  --http-cookie-jar=cookies.txt --session-check-url=https://xxxxx/account/settings/profile --session-check-pattern=">Log out<" --scope-exclude-pattern=logout,png --scope-directory-depth-limit=10  --audit-forms --report-save-path=example.com.afr https://xxxx --output-debug=1
Arachni - Web Application Security Scanner Framework v1.5.1
   Author: Tasos "Zapotek" Laskos <tasos.laskos@arachni-scanner.com>

           (With the support of the community and the Arachni Team.)

   Website:       http://arachni-scanner.com
   Documentation: http://arachni-scanner.com/wiki

 [~] No checks were specified, loading all.
 [*] Initializing...
 [*] Preparing plugins...
 [*] ... done.
 [*] BrowserCluster: Initializing 6 browsers...

**Comment by Zapotek** [comment]
It should do that after the first page is audited but there's no point to do this from the jump, assuming the cookie is valid.

**Comment by Zapotek** [comment]
Nope, my bad, the check will never happen, there's no re-login capability so it's ignored.
