### ISSUE TITLE
cant load such file selenium/webdriver/phantomjs 

### ISSUE THREAD

**Issue by sampathmende** [Arachni/arachni#950]
LoadError] cannot load such file -- selenium/webdriver/phantomjs
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:in require' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:132:inexecutable'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/browser.rb:126:in has_executable?' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:50:inhost_has_browser?
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:65:in use_browsers?' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/browser.rb:24:inbrowser_cluster'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework/parts/audit.rb:167:in audit' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:inblock in run'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/utilities.rb:408:in exception_jail' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/framework.rb:120:inrun'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/ui/cli/framework.rb:62:in block in run' [-] [Errno::EINVAL] Invalid argument @ rb_io_seek - /tmp/arachni20180209-893-1sbkutgafr [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:inseek'
[-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:135:in block in load' [-] /root/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/arachni-1.3.2/lib/arachni/report.rb:134:inopen'

**Comment by Zapotek** [comment]
Please use the [official packages](http://www.arachni-scanner.com/download/).

**Comment by sampathmende** [comment]
I am getting same error after doing that like downloading from official packages

**Comment by Zapotek** [comment]
I don't think that's the case, the packages should just work.
Can you show me what command you are running when using the packages and the full error?
