### ISSUE TITLE
can't load such file.selenium/webdriver/phantomjs from arachni

### ISSUE THREAD

**Issue by sampathmende** [Arachni/arachni#951]
can't load such file.selenium/webdriver/phantomjs. while running web application scanning.
selenium-webdriver is a gem , any way selenium-webdriver is not included in our gemfile , you can verify from [**https://github.com/olacabs/jackhammer/blob/master/web/app/Gemfile**] We are depending on arachni gem for running web-scans and Arachni depend on selenium-webdriver
I verified it by unzipping the gem for contents. but not found phantomjs folder in .selenium/webdriver path

**Comment by Zapotek** [comment]
Can you please stop creating these issues?
These don't seem to be bugs in Arachni at all, the official packages work, you're trying to setup something on your own and running into env problems.

Download Arachni from here: http://www.arachni-scanner.com/download/

I **DO NOT** support anything else and have no affiliation whatsoever with the jackhammer project.
