### ISSUE TITLE
Arachni Scan Issues

### ISSUE THREAD

**Issue by kashenda** [Arachni/arachni#952]
Hello there,

Arachni has completed a benchmark scan with the attached issues.
May I get an insight of what these issues are and or how I can fix them. 
Thanks 
[Arachni_Scan_Issues.txt](https://github.com/Arachni/arachni/files/1742634/Arachni_Scan_Issues.txt)

**Comment by Zapotek** [comment]
Doesn't seem serious, a temp file was missing. If it's just that don't worry about it.
