### ISSUE TITLE
Problem when running Arachni on Ubuntu 16.04

### ISSUE THREAD

**Issue by AmandaBSobrinho** [Arachni/arachni#953]
Hello, I have an AWS instance running Ubuntu 16.04 and I'm trying to run Arachni on it. Since Arachni is no longer available to download from the Ubuntu repository (and I know from experience that the Arachni version available on the repository worked perfectly fine), I downloaded the self-contained package from Arachni's github (https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz), unzipped it and ran:

sudo /home/ubuntu/arachni/bin/arachni https://example.com 

However, when the script gets on the BrowserCluster part, it has over 300 pending jobs, and it takes a very long time to run. When it gets around the job number 209, it just hangs. Arachni has been running for over 4 hours and it is still stuck in this part. This is what is currently on the screen:

[*] Workload exhausted, waiting for new pages from the browser-cluster...
 [~] BrowserCluster: Pending jobs: 217
 [~] BrowserCluster: Pending jobs: 216
 [~] BrowserCluster: Pending jobs: 215
 [~] BrowserCluster: Pending jobs: 214
 [~] BrowserCluster: Pending jobs: 213
 [~] BrowserCluster: Pending jobs: 212
 [~] BrowserCluster: Pending jobs: 211
 [~] Worker: Retrying (1/6) due to time out: #<Arachni::BrowserCluster::Jobs::BrowserProvider:70168059034820 callback= time= timed_out=false>
 [~] BrowserCluster: Pending jobs: 210
 [~] Worker: Retrying (1/6) due to time out: #<Arachni::BrowserCluster::Jobs::BrowserProvider:70168398556340 callback= time= timed_out=false>
 [-] [browser_cluster/worker#run_job:121] Worker: Error while processing job: #<Arachni::BrowserCluster::Jobs::BrowserProvider:70168398556340 callback= time= timed_out=false>
 [-] [browser_cluster/worker#run_job:122] Worker: [Errno::ENOMEM] Cannot allocate memory - /home/ubuntu/arachni/system/usr/bin/ruby
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:209:in `spawn'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:209:in `spawn'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/processes/manager.rb:222:in `method_missing'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1251:in `block (2 levels) in spawn_phantomjs'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1195:in `call'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1195:in `block in with_timeout'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/usr/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/usr/lib/ruby/2.2.0/timeout.rb:32:in `catch'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/usr/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1194:in `with_timeout'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1245:in `block in spawn_phantomjs'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1234:in `times'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1234:in `spawn_phantomjs'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1217:in `spawn_browser'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1114:in `selenium'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser.rb:1337:in `start_webdriver'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser_cluster/worker.rb:268:in `browser_respawn'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser_cluster/worker.rb:101:in `rescue in run_job'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser_cluster/worker.rb:76:in `run_job'
 [-] [browser_cluster/worker#run_job:122] Worker: /home/ubuntu/arachni/system/gems/gems/arachni-1.5.1/lib/arachni/browser_cluster/worker.rb:244:in `block in start'
 [~] BrowserCluster: Pending jobs: 209

So, I have two questions:
1) Why is Arachni no longer available on Ubuntu Repository? Could you please put it back there? When I installed it from there, it worked just fine.

2) Is there a way of not running this BrowserCluster tests? I don't remember having this on the other Arachni version, and if it did exist there, it didn't take nearly this much time to run. I made a test analyzing the same website with the version on the repository and the version downloaded from GitHub: while the one from GitHub is taking over 4 hours to run (and I don't even know if it will end), the one from the repository ended in less than one hour.

Could you please help me? This scanner is really great, I would very much like to use it again.

**Comment by Zapotek** [comment]
1. Never was, don't know what you're talking about. Maybe it was something unofficial, in any case only the official packages are supported.
2. If the version you're talking about didn't have browser support it was ancient, you can't get decent coverage nowadays without it. Also, you're just running out of memory:

```
[-] [browser_cluster/worker#run_job:122] Worker: [Errno::ENOMEM] Cannot allocate memory - /home/ubuntu/arachni/system/usr/bin/ruby
```

**Comment by AmandaBSobrinho** [comment]
Hello Zapotek,

Thanks for answering the questions. I really was mistaken, Arachni is only available on Kali's repository, not Ubuntu. And I'm going to try running it in a better machine, with more memory, to see if it'll work.
