### ISSUE TITLE
CSRF Token not recognized using Razor  @Html.AntiForgeryToken() ASP MVC

### ISSUE THREAD

**Issue by turbutran** [Arachni/arachni#959]
Using Arachni 1.5.1 and web UI, when auditing an ASP MVC 5 application using native CSRF protection (razor + controller attribute), reports shows CSFR vulnerabilities detection despite token is there.

![image](https://user-images.githubusercontent.com/37378367/37416862-3a761ad8-27af-11e8-8075-b242cc51cb1f.png)

**Comment by Zapotek** [comment]
This should be fixed in the [nightlies](http://downloads.arachni-scanner.com/nightlies/), can you give them a try please?
