### ISSUE TITLE
Is there any roadmap?

### ISSUE THREAD

**Issue by q2dg** [Arachni/arachni#962]
Hello. Last commit was from one year ago. So it seems this project is pretty abandoned, isn't?
Thanks

**Comment by Zapotek** [comment]
It may look like that but I've been heavily focusing on the new engine[1], but it's private still.
There's no roadmap for it though, it's going to take as long as it takes.

http://www.arachni-scanner.com/blog/new-engine-sitrep/

**Comment by q2dg** [comment]
Thanks a lot. 
I'll close this issue if you don't mind, then.
