### ISSUE TITLE
--output-debug 4> ../report.log is not being filled with debug data

### ISSUE THREAD

**Issue by Aznariy** [Arachni/arachni#971]
arachni version: arachni-1.5.1-0.5.12-windows-x86_64
ruby version: 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]   
Writing over the debugging information only works between 1-2 values to the --output-debug parameter. 3 and 4 doesn't write anything to the file.

**Comment by kynx** [comment]
You sure that “4” isn’t being treated as a file descriptor by your shell?

**Comment by Aznariy** [comment]
@kynx what do you mean "treated as file descriptor" by the shell? **--output-debug 1> myreport.log** and **--output-debug 2> myreport.log** are writing the data normally, why would 3 and 4 won't write it? I think there is a bug in the framework.

**Comment by Zapotek** [comment]
Debugging output is written to STDERR, see: https://askubuntu.com/questions/625224/how-to-redirect-stderr-to-a-file
