### ISSUE TITLE
REST-SERVER SSL Certificates

### ISSUE THREAD

**Issue by ebakirmak** [Arachni/arachni#975]
Hi,

I want to use the REST-SERVER my ssl certificates but i have error `CA missing, peer verification has been disabled.` My command `./arachni_rest_server --addres=xxx --port=80|443 --authentication-username=xxx --authentication-password=1234 --ssl-certificate=mycertificate.pem --ssl-private-ley=mykey.pem `

what i should do?

**Comment by ebakirmak** [comment]
Also when i do the json request, i get an error  `#<Puma::MiniSSL:SSLError: OpenSSL errror: error:1407609C:SSL routines: SSL23_GET_CLIENT_HELLO:http request --336027804>`

**Comment by Zapotek** [comment]
`--ssl-private-ley` doesn't exist, try `--ssl-private-key`.
